### ISSUE TITLE
`isDarkTheme` deprecation from playground

### ISSUE THREAD

**Issue by bilobom** [facebook/docusaurus#7111] opened 2022-04-04 11:48 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The latest version `2.0.0-beta.18` shows the `isDarkTheme` deprecation error in development. The error occurs when you load the page at [https://new.docusaurus.io](https://new.docusaurus.io/.) or switching between color modes using the toggle button.

### Steps to reproduce

1.  open [https://new.docusaurus.io](https://new.docusaurus.io).
2.  See console logs.

### Expected behavior

No deprecation error when `isDarkTheme` is used

### Actual behavior

Deprecation error even though no `isDarkTheme` is used

### Your environment

- Public source code: https://new.docusaurus.io
- Public site URL: https://new.docusaurus.io
- Docusaurus version used: 2.0.0-beta.18
- Environment name and version : Version 100.0.4896.60 (Official Build) snap (64-bit)
- Operating system and version : Ubuntu 20.04.2 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-04-04 13:48
Hey, I can't seem to reproduce this:

![Test](https://user-images.githubusercontent.com/55398995/161558121-e242a675-4968-4a3a-ade3-e771d5bae5ce.gif)

Could you send a relevant screenshot/video/post a link?

**Comment by bilobom** [comment] 2022-04-04 21:14
Here is a recording done when using [https://new.docusaurus.io/](https://new.docusaurus.io/)

https://user-images.githubusercontent.com/19841175/161633120-9a7eec00-48ad-4d40-a8aa-9870b44f349f.mp4

**Comment by Josh-Cena** [comment] 2022-04-05 01:19
Hmmm, I still can't reproduce this in code sandbox. Could you make sure it's not a cache problem (e.g. try Incognito)?

**Comment by slorber** [comment] 2022-04-06 17:25
You were using different playgrounds

But can't reproduce either on https://docusaurus.sse.codesandbox.io/

Maybe it's a browser-specific bug?

**Comment by Josh-Cena** [comment] 2022-04-13 03:59
@bilobom Have you managed to narrow down the cause? We haven't had anyone else complaining. I'll close this if there's no follow-up in a week as it's unactionable at this stage.

**Comment by Josh-Cena** [comment] 2022-04-18 10:11
Closing because it seems no one else has been complaining about this. If we have someone who can clearly tell what's wrong (e.g. some DevTools) we can certainly re-open this. Probably make `isDarkTheme` non-enumerable. But at this stage I don't think action is needed.

**Closed by Josh-Cena** 2022-04-18 10:11 UTC
Labels: bug, status: needs more information

**Comment by bilobom** [comment] 2022-04-20 10:59
@Josh-Cena I haven't manage to narrow down the cause. When I open in incognito mode , the error disappears. Most probably cashing problem.

**Comment by Josh-Cena** [comment] 2022-04-20 11:01
Mmm, yeah, could be as well...

**Comment by jalalbmnf** [comment] 2023-10-24 09:40
I have same problem:

<img width="1743" alt="Screenshot 2023-10-24 at 13 40 00" src="https://github.com/facebook/docusaurus/assets/53921355/16c84503-ddc2-4085-a1e6-f3e5f63886fd">

**Comment by jalalbmnf** [comment] 2023-10-24 09:42
https://github.com/facebook/docusaurus/assets/53921355/3de851cc-ed63-4460-944a-641c6e501262
