### ISSUE TITLE
Eror ❌ 

### ISSUE THREAD

**Issue by bagussatoto** [facebook/docusaurus#7504] opened 2022-05-26 12:16 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

![image](https://user-images.githubusercontent.com/87259393/170485749-4027638a-ef49-439a-87fe-ab5c4576e526.png)

### Reproducible demo

https://docusaurus.io/ 

### Steps to reproduce

> ## 1. Visit https://docusaurus.io/
> ## 2. Click search and see the layout shift.

### Actual behavior

# N/A

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-05-26 12:18
There's no info to take any action. I suspect this is a duplicate of #7130. Closing.

**Closed as not planned by Josh-Cena** 2022-05-26 12:18 UTC
Labels: closed: duplicate
