### ISSUE TITLE
Markdown links inside comments shouldn't be resolved

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#6160] opened 2021-12-22 11:42 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When using HTML comments inside markdown files, and these comments contain markdown links, our system still tries to resolve those links.

See also https://github.com/facebook/docusaurus/pull/6159

> [WARNING] Docs markdown link couldn't be resolved: (./api/lifecycle-apis.md) in /Users/sebastienlorber/Desktop/projects/docusaurus/website/versioned_docs/version-2.0.0-beta.13/using-themes.md for version 2.0.0-beta.13

### Steps to reproduce

```md

# MyDoc

<!--

[bad markdown link](./does-not-exist.md)

-->
```

### Expected behavior

no warning

### Actual behavior

produces a warning

### Your environment

latest

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2021-12-22 11:44
Slightly related to https://github.com/facebook/docusaurus/issues/6108

**Comment by Josh-Cena** [comment] 2021-12-22 12:14
Duplicate of https://github.com/facebook/docusaurus/issues/5659 😄

**Comment by Josh-Cena** [comment] 2021-12-22 12:15
And that's why I started working on #5670

**Closed by Josh-Cena** 2021-12-22 12:14 UTC
Labels: bug

**Comment by slorber** [comment] 2021-12-22 13:15
😆 I was pretty sure this already came up
