### ISSUE TITLE
Docs sidebar layout issue when announcementBar is partially visible

### ISSUE THREAD

**Issue by guardsofmagog** [facebook/docusaurus#8374] opened 2022-11-25 12:44 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

![sidebar issue](https://user-images.githubusercontent.com/115551796/203984926-62ebaa22-38e9-45c5-8005-fda5e010534e.jpg)

When the announcementBar is partially visible, the docs sidebar is incorrectly sized vertically. This is particularly noticeable when the sidebar collapse button is visible. Note that the behaviour does not occur when the announcementBar is fully visible or fully invisible.

### Steps to reproduce

1. Navigate to [https://docusaurus.io/docs](https://docusaurus.io/docs)
2. Ensure announcementBar is visible (clear cache if required)
3. Resize browser window so scrollbar appears on sidebar
4. Scroll browser window so announcementBar is only partially visible

### Expected behavior

Scrollbar on sidebar does not overlap collapse button

### Actual behavior

Scrollbar on sidebar overlaps collapse button

### Your environment

- Docusaurus v2.2.0
- Chrome v107 or Safari v15.6.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-11-25 13:00
Duplicate of https://github.com/facebook/docusaurus/issues/8370?

**Comment by guardsofmagog** [comment] 2022-11-25 13:11
They are certainly related - I started looking into #8370 and it felt like that was more an issue around the sidebar ad when combined with the announcementBar (fully or partially visible). This is more specifically when the announcementBar is only partially visible - but I'm happy for the issues to be merged.

**Comment by guardsofmagog** [comment] 2022-11-25 13:21
It looks like `docusaurus-announcement-bar-height` is added to the bottom margin of the scrollable area of the sidebar - but only when the announcementBar is **fully** visible.

**Comment by Josh-Cena** [comment] 2022-11-25 13:26
Good catch! If you think you could make the situation better, feel free to propose it in this issue or directly send a PR.

**Comment by slorber** [comment] 2023-04-07 09:51
Going to close in favor of https://github.com/facebook/docusaurus/issues/8370

"announcement bar visible" vs "announcement bar partially visible" is almost the same thing. We'll try to solve all the announcement bar related layout issues at once

**Closed by slorber** 2023-04-07 09:51 UTC
Labels: bug
