### ISSUE TITLE
Single file with same name as folder is stripped from sidebar (Category index) - since 2.0.0-beta.19

### ISSUE THREAD

**Issue by ambroiseRabier** [facebook/docusaurus#7446] opened 2022-05-18 11:08 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Since 2.0.0-beta.19, a folder `docs/Same`  with a single file `docs/Same/Same.md` is not shown in sidebar. It work in 2.0.0-beta.18 as documented [here](https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention).

Observe `Same` folder being absent from the sidebar:

![image](https://user-images.githubusercontent.com/16115874/169024043-424b64c0-cfdf-4587-9d0d-fd53df7aead8.png)

![image](https://user-images.githubusercontent.com/16115874/169024403-ac41efc3-0fc4-4052-a7ae-f7fe9668a621.png)

### Reproducible demo

https://stackblitz.com/edit/github-vnuu5v?file=docs/Same/Same.md

### Steps to reproduce

1. Create a folder `docs/Same`.
2. Create a file `docs/Same/Same.md`
3. Observe the sidebar not displaying "Same" link item.

### Expected behavior

With a folder `docs/Same` containing a single file `docs/Same/Same.md`, the expected output as per https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention would be to have the Sidebar display `docs/Same` as a link, linking to `docs/Same/Same.md`.

### Actual behavior

A folder `docs/Same`  with a single file `docs/Same/Same.md` is not shown in sidebar. 

Note that if you rename the file to `docs/Same/Different.md`, or if add another file to `docs/Same` folder, it work as expected.

### Your environment

- Public source code: https://stackblitz.com/edit/github-vnuu5v?file=docs/Same/Same.md
- Public site URL: https://stackblitz.com/edit/github-vnuu5v?file=docs/Same/Same.md
- Docusaurus version used: 2.0.0-beta.19 and 2.0.0-beta.20
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-05-18 11:09
Duplicate of #7348

**Comment by Josh-Cena** [comment] 2022-05-18 11:10
You can try using [the canary version](https://docusaurus.io/community/canary)

**Closed by Josh-Cena** 2022-05-18 11:10 UTC
Labels: bug, closed: duplicate
