### ISSUE TITLE
Broken links in html when document from previous version is removed from next release

### ISSUE THREAD

**Issue by parthpp** [facebook/Docusaurus#1282] opened 2019-03-14 21:09 UTC
## 🐛 Bug Report

This bug is in association with #1271 and PR #1281. This bug exists in the Docusaurus 1.7.2 as well as it exists after the fix in PR #1281.

Let us say we have a markdown document `A` in version 1.0.0 and there are links to this document in another markdown file `B` in version 1.0.0. Now in the current or as we call it in Docusaurus the next version, we remove the document `A` and link to document `A` in document `B`. If we now start the website with `yarn run start` and go to document `B` in version 1.0.0, the link to document `A` is broken.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce
Please clone the repository at https://github.com/parthpp/Docusaurus-Broken-Links and follow the steps in the [ReadMe](https://github.com/parthpp/Docusaurus-Broken-Links/blob/master/README.md) file.

## Reproducible Demo

Please clone the repository at https://github.com/parthpp/Docusaurus-Broken-Links and follow the steps in the [ReadMe](https://github.com/parthpp/Docusaurus-Broken-Links/blob/master/README.md) file.

**Comment by parthpp** [comment] 2019-03-14 21:26
@endiliey After your fix in #1281 I have found another issue with markdown to html link conversion. Note that this bug happens in Docusaurus 1.7.2 as well as #1281. I think the basic problem is that [docs.mdToHtmlify](https://github.com/facebook/Docusaurus/blob/master/v1/lib/server/docs.js#L80) uses the `mdToHtml` to map `metadata.source` to html links. But `mdToHtml` never have `metadata.source` to html links mapping for the versioned documents due to `metadata.original_id` check in [`metadataUtils.mdToHtml`](https://github.com/facebook/Docusaurus/blob/master/v1/lib/server/metadataUtils.js#L73-L75). Thus, the logic will break down in the case of this bug because the relative link in the markdown of version 1.0.0  is for a document in version 1.0.0 and that document is absent from next version and `mdToHtml` does not have mapping for anything except next version.

**Comment by endiliey** [comment] 2019-03-15 03:46
Actually I am aware of this bug. This is duplicate of #845. Renaming or removing old versioned docs break links in next version. In fact this bug exists since 1.0.0 (way before I even helped to maintain this repo)

Sadly this is because the versioning mechanism of v1 expect that user shouldnt touch any of the versioned_docs file and it expects the previous version and next version of the docs is to be related (original_id).

if you’ve read our v2 blogpost, we are looking at a snapshot and different versionioning mechanism as the fix for this.

**Comment by endiliey** [comment] 2019-03-15 04:11
I am going to close this issue as a duplicate issue. This does not mean we are going to ignore this.

I suggest a workaround for you to just replace the broken links with the correct link. As far as I am aware, this bug is very rare and the workaround is super simple too

**Closed by endiliey** 2019-03-15 04:11 UTC
