### ISSUE TITLE
Swizzle does not work sometimes when using pnpm

### ISSUE THREAD

**Issue by Eliav2** [facebook/docusaurus#8698] opened 2023-02-23 01:16 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

It looks like pnpm selects wrong version for '@docusaurus/theme-common' when swizzling sometimes,  and i'm not sure if it's pnpm or docusaurus 'fault'.

let's pick `DocSidebar` for example, after swizzeling we get `Module not found: Error: Can't resolve '@docusaurus/theme-common'` error:

![image](https://user-images.githubusercontent.com/47307889/220795988-0d6e3edb-a018-40c0-879f-c41a6ba4a82b.png)

[stackblitz here](https://stackblitz.com/edit/github-djbcjh?file=README.md)

it's hard to understand what the problem is inside stackblitz because you don't have access to the node_modules problem but i could figure out the soruce of the problem on local project- it looks like there are 2 versions for '@docusaurus/theme-common' both v2.3.1 but with different hash(don't ask me how this is possible)

here we can see `jgxnvbe4faw3ohf4h6p42qq6oy` or `qy6u2m3twle75rldwm5f2xep3a`.
![image](https://user-images.githubusercontent.com/47307889/220796372-de14f6ff-2a33-45e4-9c70-065491861a32.png)

it is possible that `@docusaurus/theme-classic` searches for context provider from the same release version in '@docusaurus/theme-common' but can't find it becasue pnpm loads the wrong v2.3.1 package.

**actually deleting `node_modules/.pnpm/@docusaurus+theme-common@2.3.1_qy6u2m3twle75rldwm5f2xep3a` resulting in the swizzling working perfectly fine !** 

I did some digging, and by looking the pnpm-lock file it look like mixed dependencies between different versions, i'm not sure where exactly is the problem but it could probably be fixed by simple change to lock file. 

![image](https://user-images.githubusercontent.com/47307889/220799452-e544be02-eb7d-4324-be5d-158809c95d17.png)

### Reproducible demo

https://stackblitz.com/edit/github-djbcjh?file=README.md

### Steps to reproduce

to reprouduce:
1. `pnpx create-docusaurus@latest my-website facebook`
2. `cd my-website`
3. `pnpm install`
4. `pnpm run swizzle`
5. (select DocSidebar-Eject)
6. `pnpm run start`
7. navigate to docs

now you got error. to fix the error delete `node_modules/.pnpm/@docusaurus+theme-common@2.3.1_qy6u2m3twle75rldwm5f2xep3a` or bravely edit the `pnpm-lock.yaml` file, reinstall and restart. 

### Expected behavior

pnpm should pick the right appropriate versions from all @docusaurus packages and not mix them

### Actual behavior

asdxcaca

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4):  Edge latest
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-02-23 01:21
Duplicate of https://github.com/facebook/docusaurus/issues/7880

**Closed by Josh-Cena** 2023-02-23 01:21 UTC
Labels: bug, status: needs triage
