### ISSUE TITLE
Drafts not excluded from autogenerated sidebar

### ISSUE THREAD

**Issue by odsod** [facebook/docusaurus#7473] opened 2022-05-23 10:59 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The new `draft` feature of the docs plugin isn't taken into consideration in the [autogenerated sidebar](https://docusaurus.io/docs/sidebar/autogenerated#autogenerated-sidebar-metadata).

### Steps to reproduce

1. Mark one or more docs parents as `draft`
2. Use autogenerated sidebars

### Expected behavior

The draft pages and their children should not show up in the autogenerated sidebar.

### Actual behavior

The draft pages and their children *do* show up in the autogenerated sidebar.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-05-23 11:01
Please provide a detailed reproduction, including your file structure and which files are drafts.

**Comment by Josh-Cena** [comment] 2022-05-27 06:35
@odsod Do you have a reproduction? It's not really actionable at this stage and I'll probably close it next week.

**Comment by Josh-Cena** [comment] 2022-05-28 05:34
Closing because of lack of repro; there's a chance this has been fixed by beta.21, if it had been a problem at all.

**Closed by Josh-Cena** 2022-05-28 05:34 UTC
Labels: bug, status: needs more information
