### ISSUE TITLE
Markdown Headers from nested MDX should be included in table of contents

### ISSUE THREAD

**Issue by Noah-Silvera** [facebook/docusaurus#2463] opened 2020-03-24 21:59 UTC
## 🐛 Bug Report

Markdown headers from nested MDX are not included in the table of contents for a page. If you import another markdown file as a MDX component, any headers if defines do not show up for the table of contents in the page it's embedded in. This makes sharing content between documentation pages using snippets less useful, as you lose any table of contents navigation that comes with it. The anchor tags associated with the headers still work. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes.

## To Reproduce

1. Create an mdx document that embeds another mdx document with headers
2. Run docusaurus and open the parent document.

## Expected behavior

The markdown headers from both the parent document and the embedded document appear in the table of contents. This should be recursive, so embedded documents can embed documents with headers. 

## Actual Behavior

The markdown headers from the embedded document are **not** shown. Only the headers from the parent document are shown. 

![2020-03-24 14_59_46-Style Guide _ My Site](https://user-images.githubusercontent.com/8933450/77481079-263f3580-6de0-11ea-827e-2ccc2d79f1e3.png)

## Your Environment
- Docusaurus version used: 2.0.0-alpha.48
- Chrome  80.0.3987.149
- Windows Desktop

This occurs with both the development server and production build

## Reproducible Demo

https://github.com/Noah-Silvera/docusaurus-nested-headers-no-table-contents

**Comment by yangshun** [comment] 2020-06-05 11:01
This might not be trivial to fix :)

**Comment by marikaner** [comment] 2020-09-01 10:29
I encountered the same issue. Does anyone know a workaround for this?

**Comment by slorber** [comment] 2021-06-10 10:10
Duplicate of https://github.com/facebook/docusaurus/issues/3915

Definitively something I'd like to solve, not easy in practice

**Closed by slorber** 2021-06-10 10:10 UTC
Labels: bug, difficulty: advanced
