### ISSUE TITLE
URL behavior changes if markdown id is identical to folder

### ISSUE THREAD

**Issue by tony-b-4d** [facebook/docusaurus#7916] opened 2022-08-08 09:23 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, 

When the id of a markdown file is identical to the folder name (not case-sensitive), the URLs don't include the id.

For example, if I have a file Tags.md inside a Tags folder, and its id is `tags`
I should have http://localhost:3000/docs/Tags/tags as the URL of that page

Instead, Docusaurus builds the page with a URL that does not include the id: 
http://localhost:3000/docs/Tags/

The sidebar is not affected by this behavior, links are still correct

### Steps to reproduce

1. Install the latest version of Docusaurus
2. Create a folder in the docs (for example, Tags)
3. Inside that folder, create a markdown file, name it tags.md for example
4. Set the id of that file to the name of the folder (tags) 
5. (Optional) add that file and folder to the sidebar
6. Build your docusaurus website
7. Check the URL you get when you access the page

### Expected behavior

You should normally get theURL with the id of the markdown file
http://localhost:3000/docs/Tags/tags

### Actual behavior

the URL is cropped and stops at folder level
http://localhost:3000/docs/Tags/

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-08-08 09:26
Duplicate of https://github.com/facebook/docusaurus/issues/7725 —this is working as intended.

**Closed by Josh-Cena** 2022-08-08 09:26 UTC
Labels: bug, status: needs triage
