### ISSUE TITLE
Sidebar html divider does not display

### ISSUE THREAD

**Issue by shipswake** [facebook/docusaurus#9589] opened 2023-11-29 21:29 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I cannot display a divider in my sidebar using a:

```js
{
type: html, 
value: <hr/>.
}
```

I then created a new docusaurus site and added the code found in the GitHub repo test files and the divider does not display:

```js
{
          type: 'html',
          value:
            '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block; margin: 0.5rem 0 0.25rem 1rem;" />',
}, 
```

### Steps to reproduce

1.  Create a new Docusaurus site
2.  In the sidebar.ts file, turn off the autogenerated tutorialSidebar by commenting out the code
3.  In the sidebar.ts file, uncomment the code to create a manual sidebar 
4.  Insert the following code from your test files into the tutorialSidebar after the intro shortcut id:

```js
{
      type: 'html',
      value:
        '<span style="border-top: 1px solid var(--ifm-color-gray-500); display: block;margin: 0.5rem 0 0.25rem 1rem;" />',
    },
```

### Expected behavior

I expected a divider to display in my sidebar

### Actual behavior

Nothing happens

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 19.9
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-11-29 21:37
Duplicate of https://github.com/facebook/docusaurus/issues/9483

**Closed by Josh-Cena** 2023-11-29 21:37 UTC
Labels: bug, status: needs triage
