### ISSUE TITLE
RFC: Blog authors pages

### ISSUE THREAD

**Issue by OzakIOne** [facebook/docusaurus#10196] opened 2024-06-04 09:39 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

A page with a list of author names, grouped by letters (eg: [Author Geoff Graham — Smashing Magazine](https://www.smashingmagazine.com/author/geoff-graham/) / [Chris Coyier on CSS-Tricks - Archive](https://css-tricks.com/author/chriscoyier/) )
A view all authors page like : [View all tags `/blog/tags`](https://docusaurus.io/blog/tags)

Here is a visual for the view all author page: ![view all authors](https://github.com/facebook/docusaurus/assets/362732/14161677-cd91-4675-ace7-926166b4c549)

I'll try to mock a visual for the new design of `blog/authors/${name}` and the new design when viewing a blog post with the social icons

Here is a visual for `blog/authors/${name}`

![design 3](https://github.com/facebook/docusaurus/assets/29860391/fb686d8b-9f04-491d-b373-e6430a1a0359)

### Has this been requested on Canny?

https://docusaurus.io/feature-requests/p/blog-author-pages

### Motivation

It's a nice feature to have which other blogs have and it has already been implemented and asked by the community

@halildurmus
@shochdoerfer
@reda-jaifar
@ilg-ul
Have shown their interest in this feature

Perhaps you have ideas for the visuals, I've made some quick mockups if you have any preference or ideas tell me

### API design

recap from existing conversation about this feature : [docusaurus #9825](https://github.com/facebook/docusaurus/issues/9825#issuecomment-1933951802)

we should generate an author page for all `authors.yaml` authors by default, and have an option to opt-out.
`blog.generateAuthorsPage: boolean` (defaults: `true` if authors.yml exists)

The `author.url` should also be removed and replaced by `blog/authors/${name}` list url just like others blogs (smashingmagazine)

Maybe we might add a `blog.postsPerAuthorPage` just like the https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog#postsPerPage 

Then you can swizzle the author page and decide to sort, group, and display the posts of that author the way you want. You can order the post by date, event_date, last update time or whatever you want, implement your own layout, and group the posts by whatever attribute or custom front matter.

First introduce the ability to have "social icons" next to the author's name (asked [here](https://github.com/facebook/docusaurus/discussions/10136))
Which websites should we support for the logos ? Twitter github medium ? Should we not use logos at all ?

description will removed in favor of social icons unless there is none.
We'll still show the description in the `blog/authors/${name}`

The api and design for view all authors should be fairly similar to view all tags

### Have you tried building it?

Implemented by @ilg-ul in https://github.com/cronica-it/docusaurus-chronology/commit/746583324ad0655479b1199d52d9203d99508134 
The implementation adds a `NamedAuthor` type, similar to `Tag` and the code is basically a duplicate of the tag logic.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by ilg-ul** [comment] 2024-06-06 07:29
My code is indeed a duplicate of the tag logic, which is relatively complicated, perhaps you can do it better.

One major issue I encountered was the lack of a unique key in the Author definition, needed to generate the permalink.

I don't know now, but by the time I did that experimental implementation, the author name was neither mandatory, nor unique, thus the need to add a new definition `NamedAuthor` with a unique field, and an array of such objects, with the authors that have a name allowing to generate the unique field (see the `makePermalinkFromAuthorName()` function).

If needed, you can reuse any parts of my code, everything is licensed as MIT, so a short reference to the initial author is enough.

**Closed** 2024-08-01 15:30 UTC
Labels: feature
