### ISSUE TITLE
generated-index-page cards show MD comments

### ISSUE THREAD

**Issue by ArthurFlageul** [facebook/docusaurus#7472] opened 2022-05-23 10:25 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The [sidebar item of type `generated-index-page`](https://docusaurus.io/docs/sidebar/items#generated-index-page) created cards that automatically show the first line's 46ish characters of each given docs pages. 

The issue is that we display the first line, even when it's a comment leading to the following output:

<img width="396" alt="screenshot" src="https://user-images.githubusercontent.com/28596581/169798163-7cbaa86a-fc6e-4797-ab54-5e1ca4d71483.png">

### Steps to reproduce

1. Create MD file with a title, and make the first content line as a comment:
   ```markdown
   ---
   title: Hey
   ---

   <!-- my comment -->

   My first line. Real line.
   ```
1. Use this page in a generated-index-page items list.
   ```javascript
   {
     type: 'category',
     label: 'Test category',
     link: {
        type: 'generated-index',
        title: 'Test title',
        description:
          "Test",
         },
     items: [
       'myTestPage',
     ],
   },
   ```

### Expected behavior

Display the first line that is not an MDX import statement or HTML comment.

### Actual behavior

Displays the first line that is not a MDX import statement.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0.20
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-05-23 10:25
Duplicate of #6108

**Comment by Josh-Cena** [comment] 2022-05-23 10:26
This is because the generated cards use the description metadata. You can use the `description` front matter to assign a custom description text.

**Closed by Josh-Cena** 2022-05-23 10:26 UTC
Labels: bug, closed: duplicate
