### ISSUE TITLE
arrow up causing crashed when using @docusaurus/theme-search-algolia

### ISSUE THREAD

**Issue by vagusX** [facebook/docusaurus#5031] opened 2021-06-22 07:04 UTC
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

(A clear and concise description of what the bug is.)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Steps to reproduce

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Press `Cmd + K`
2. Press `↑` (arrow up)
3. Page is crashed

![image](https://user-images.githubusercontent.com/6828924/122878681-9b464580-d36a-11eb-8e9a-df9cd118e1c3.png)

## Expected behavior

No crashing

(Write what you thought would happen.)

## Actual behavior

(Write what happened. Add full console log messages and screenshots, if applicable.)

## Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

## Reproducible demo

https://docusaurus.io/docs/api/themes/@docusaurus/theme-search-algolia

**Comment by slorber** [comment] 2021-06-22 08:39
@vagusX I'm sorry but I can't reproduce on that page

https://docusaurus.io/docs/api/themes/@docusaurus/theme-search-algolia

![image](https://user-images.githubusercontent.com/749374/122892745-f285ef00-d345-11eb-81b1-0107c205a1e2.png)


As this issue has been reported first on the Ant design website (apparently), why are you reporting it to Docusaurus? Ant Design website is not using Docusaurus. I can reproduce it on the Ant design website, not on Docusaurus website.

@shortcuts is this issue known?

**Comment by shortcuts** [comment] 2021-06-22 11:14
Hi,

I'm not able to reproduce this issue in an up-to-date DocSearch v3 experience (with ant design index https://2ppfv.csb.app/)

@slorber do you have a link where I could see the issue on the Ant design website?

@vagusX if you can still reproduce on your side, could you please let me know which User Agents are sent with the query? They should contain the version of the DocSearch and Autocomplete library, which might gives a hint.

**Comment by slorber** [comment] 2021-06-22 12:54
I can reproduce it on the url reported here https://github.com/ant-design/ant-design/issues/31040: https://ant.design/

**Comment by vagusX** [comment] 2021-06-22 14:24
@slorber would you like to clean all recent items and try it again?

**Comment by vagusX** [comment] 2021-06-22 14:25
![image](https://user-images.githubusercontent.com/6828924/122942333-ba63c800-d3a8-11eb-8edd-66e77e77f765.png)

**Comment by shortcuts** [comment] 2021-06-22 14:51
Yep the repo of the underlying library is now https://github.com/algolia/autocomplete, thanks for pointing that out! The PR I've opened (https://github.com/algolia/autocomplete/pull/599) will also fix this issue.

**Comment by vagusX** [comment] 2021-06-22 15:02
> Yep the repo of the underlying library is now [algolia/autocomplete](https://github.com/algolia/autocomplete), thanks for pointing that out! The PR I've opened ([algolia/autocomplete#599](https://github.com/algolia/autocomplete/pull/599)) will also fix this issue.

Wow, just looking forward for this fix pr release.

**Comment by gearcoded** [comment] 2021-06-30 12:33
To reproduce the issue, you need to open the search popup and make sure that no entries are displayed. If there are previous search entries, you can remove them.
Then press the `Up` Arrow and the page will crash.

**Comment by shortcuts** [comment] 2021-07-07 16:34
Update: [this PR](https://github.com/algolia/autocomplete/pull/599) has been merged but didn't solved the DocSearch issue, I've found an other related issue which should solve it: https://github.com/algolia/autocomplete/pull/623

The DocSearch update will be released by the end of the week!

**Closed** 2021-07-09 15:52 UTC
Labels: bug, needs triage
