### ISSUE TITLE
Manual autogenerated sidebar category index showing as additional link

### ISSUE THREAD

**Issue by sam-bryant** [facebook/docusaurus#8588] opened 2023-01-26 22:41 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When I create a manual autogenerated sidebar, the category index is showing as an additional link in the left nav.

![category index link](https://user-images.githubusercontent.com/36208119/214966008-4fcf34eb-7cc3-49d8-97a1-0112c608224c.png)

### Reproducible demo

https://codesandbox.io/p/sandbox/nice-river-ybhub7?file=%2Fdocs%2Ftutorial-basics%2Ftutorial-basics.md&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A1%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D

### Steps to reproduce

1. New project
2. Delete the _category_.json file in the tutorial-basics folder
3. Create a tutorial-basics.md file in the tutorial-basics folder
4. Update docusaurus.config.js to add a top nav link:
```
          {
            type: "doc",
            docId: "tutorial-basics/tutorial-basics",
            position: "left",
            label: "Tutorial - Basics",
          },
```
5. Update sidebars.js replace tutorialSidebar with:
```
  tutorialBasicsSidebar: [
    {
      type: "category",
      label: "tutorial-basics",
      link: { type: "doc", id: "tutorial-basics/tutorial-basics" },
      items: [{ type: "autogenerated", dirName: "tutorial-basics" }],
    },
  ],
```

### Expected behavior

I expect the category link to navigate to the page and not have the extra link below the category.

### Actual behavior

An additional link is created below the category.  That category and the additional link navigate to the same page.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-01-27 17:59
Duplicate of https://github.com/facebook/docusaurus/issues/6127

**Closed by Josh-Cena** 2023-01-27 17:59 UTC
Labels: bug, status: needs triage
