### ISSUE TITLE
Unable to start docusaurus

### ISSUE THREAD

**Issue by sindhubb** [facebook/docusaurus#7869] opened 2022-08-01 06:57 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, 

I am trying out the [tutorial](https://docusaurus.io/docs/installation) but I get an error indicating I am missing some 'wait-for' plugin. I could not find any relevant google search results or any existing issues on docusaurus issue tracker. 

### Steps to reproduce

1. Go to https://docusaurus.io/docs/installation
2. Execute `npx create-docusaurus@latest my-website classic`
3. Results in the above error.

### Expected behavior

I expected Docusaurus server to start. 

### Actual behavior

I get this error in the terminal:

```
(base) ➜  my-website npx docusaurus --port 4000 start                   

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'wait-file'
Require stack:
- /Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js
- /Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/webpack/server.js
- /Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/commands/build.js
- /Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js',
    '/Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/webpack/server.js',
    '/Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/commands/build.js',
    '/Users/sindhus/code/bytebeam/test-docusaurus/my-website/node_modules/@docusaurus/core/lib/index.js'
  ]
}```

### Your environment

- node version: /Users/sindhus/.nvm/versions/node/v16.14.2/bin/node
- os: mac os ventura beta

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-08-01 07:00
Duplicate of https://github.com/facebook/docusaurus/issues/7868

**Comment by Josh-Cena** [comment] 2022-08-01 07:00
We are working on it right now

**Closed by Josh-Cena** 2022-08-01 07:00 UTC
Labels: bug, status: needs triage

**Comment by sindhus-in** [comment] 2022-08-01 07:02
> We are working on it right now

Thank you, appreciated!
