### ISSUE TITLE
the website is horizontally scrollable

### ISSUE THREAD

**Issue by gurrrung** [facebook/docusaurus#4228] opened 2021-02-16 15:02 UTC
## What is the current behavior?

Website is being scrollable horizontally for pages like:
https://v2.docusaurus.io/docs/api/themes/configuration
https://v2.docusaurus.io/docs/markdown-features

![Screenshot from 2021-02-16 20-10-38](https://user-images.githubusercontent.com/30543444/108080543-ff43bf00-7095-11eb-8a45-2a7221ea65f4.png)

## What is the expected behavior?

It should not be horizontally scrollable.

**Comment by sarthakkundra** [comment] 2021-02-16 17:04
@gurrrung I can't recreate this. What's the OS and browser you're using? Also if you can provide your screen dimenstions, that'd be great

**Comment by slorber** [comment] 2021-02-16 18:38
Yes it's a bug thanks, duplicate of https://github.com/facebook/docusaurus/issues/3870

**Closed by slorber** 2021-02-16 18:38 UTC
Labels: bug, needs triage
