### ISSUE TITLE
Unreadable font color of code within link within admonition

### ISSUE THREAD

**Issue by hsheth2** [facebook/docusaurus#4781] opened 2021-05-12 21:38 UTC
## 🐛 Bug Report + Repro Steps

Repro example: https://codesandbox.io/s/mutable-firefly-lrpoy?file=/docs/intro.md

Using something like this:
```
:::tip

test `normal` and [`link` text](https://google.com).

:::
```

Looks like this:
![image](https://user-images.githubusercontent.com/12566801/118047256-5d97db00-b32f-11eb-95dd-f3673e1bb09a.png)

I would have expected the word "link" to be in the black font so that it's readable.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by HonkingGoose** [comment] 2021-05-13 08:21
@hsheth2 The Infima team are working on a admonition redesign, see https://github.com/facebookincubator/infima/issues/55.
You can add your image and post to the issue, so that it can be taken into account with the redesign.

**Comment by slorber** [comment] 2021-05-13 10:07
Looks like a potential regression of https://github.com/facebookincubator/infima/pull/113

**Comment by slorber** [comment] 2021-05-18 10:37
will be fixed by https://github.com/facebookincubator/infima/pull/120

**Closed** 2021-05-28 07:58 UTC
Labels: bug, needs triage
