### ISSUE TITLE
problems with main.css during npm run build since 1.0.12

### ISSUE THREAD

**Issue by dgracehmh** [facebook/Docusaurus#602] opened 2018-04-25 08:34 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### Environment

(Docusaurus version via `npm outdated docusaurus` or `yarn outdated docusaurus`, OS, Node, npm, yarn)
Package     Current  Wanted  Latest  Location
docusaurus   1.0.12  1.0.12  1.0.14

OS : Mac High Sierra
Node : v8.4.0
npm : 5.6.0
yarn : 1.5.1

### Steps to Reproduce

1. Update to version 1.0.12 or beyond
2. Run ```npm install``` followed by ```npm run build``` to generate the build
3. Since this PR - https://github.com/facebook/Docusaurus/pull/569 - When I build and deploy my site I have css issues.
4. When I deploy my site it does not display correctly, css is broken. In Chrome devtools console I see ```Resource interpreted as Stylesheet but transferred with MIME type test/plain: "https://www.www.www/doc-site/css/main.css"

### Expected Behavior

After update to 1.0.12 and later css would work correctly.

### Actual Behavior

When I deploy my site it does not display correctly, css is broken. In Chrome devtools console I see ```Resource interpreted as Stylesheet but transferred with MIME type test/plain: "https://www.www.www/doc-site/css/main.css"

### Reproducible Demo
To demo this..
1. init and build the demo site. Have a look at the generated css file.
2. Deploy the build directory. You will see that css us broken.

**Comment by dgracehmh** [comment] 2018-04-25 10:06
![screen shot 2018-04-25 at 09 21 09](https://user-images.githubusercontent.com/24386227/39239409-b030743c-4878-11e8-876f-e298975dfe09.png)

**Comment by dgracehmh** [comment] 2018-04-25 10:07
![screen shot 2018-04-25 at 09 21 24](https://user-images.githubusercontent.com/24386227/39239419-c42240d8-4878-11e8-95d0-d6b6a1feeef1.png)

**Comment by yangshun** [comment] 2018-04-25 20:19
@dgracehmh It could be something to do with your web server's settings. Docusaurus has been using the latest version and there aren't issues with it. 

It would help if you could answer the following questions:

1. What web server are you using for serving the CSS? Docusaurus uses GitHub pages hosting
1. Try to run the website locally on localhost:3000. Does the warning still show and does the CSS work fine? Inspect the network tab and see the `content-type` of the HTTP request on your web server vs local server.
1. Is your website or code online for us to reproduce?

I have a suspicion it is not due to the cssnano change but due to the addition of `<!DOCTEXT html>` in #566, which makes the browser warn about non-standard practices.

My recommendation would be to check your web server configuration that it is serving the CSS files correctly. I had to make this change to the local web server to get it to work - https://github.com/facebook/Docusaurus/pull/566/files#diff-fe37ce87a7b7b83106303bf9233b49fbR508

**Comment by dgracehmh** [comment] 2018-04-26 16:13
@yangshun 

1. I am using nginx to serve the site on an internal cloud via docker container.
2. Running locally is fine.
3. Sorry, my docs are not online. I've been deploying using exact same config (nginx + docker + Docusaurus) but when I update to 1.0.12 or beyond on the exact same config the css is broken. 

I'm trying to dig in to figure out what changed since 1.0.11 to break my setup.

**Comment by yangshun** [comment] 2018-04-26 16:15
The change was that we added doctype to the top of each html file, and that
makes browsers less forgiving about non-standard practices. Please check
the content type of the CSS file being served. It shouldn't be anything to
do with cssnano

**Comment by yangshun** [comment] 2018-04-27 04:29
@darren128 Please check that your webserver is serving the CSS files using the correct HTTP `content-type` header - `text/css` and not `text/plain`.

Closing for now. Please reopen if you find that it is indeed a bug.

**Closed by yangshun** 2018-04-27 04:29 UTC
Labels: bug

**Comment by darren128** [comment] 2018-04-27 13:28
@yangshun Wrong person :)

**Comment by JoelMarcey** [comment] 2018-04-27 13:30
Oops. Sorry 😄 

@dgracehmh ^^

**Comment by dgracehmh** [comment] 2018-04-27 13:49
Thanks for the pointers @yangshun  : I changed my nginx configuration (content-type header - text/css) and got it working again. I guess it's handy to have a record of it here in case someone else comes up against the something similar.

**Comment by JoelMarcey** [comment] 2018-04-27 13:52
@dgracehmh  Or if you think there is a place in the docs we should add something, a doc update PR might be a good thing too.

**Comment by dgracehmh** [comment] 2018-04-27 14:28
Done @JoelMarcey , hopefully it's ok - https://github.com/facebook/Docusaurus/pull/611

**Comment by erikh** [comment] 2019-03-02 22:08
so fwiw S3 doesn't seem to set these mime types by default either. can't the link tag be adjusted?
