### ISSUE TITLE
Auto-generated title incorrect when not using Unix newline encoding (LF)

### ISSUE THREAD

**Issue by andgeno** [facebook/docusaurus#7156] opened 2022-04-12 05:12 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

Page titles will be rendered incorrectly depending on which newline format has been chosen.

✔ Linux (LF): Works as expected. Text of the first Markdown header is displayed.
❌ Windows (CRLF): Original filename and text of the first Markdown header is displayed.
❌ macOS (CR): Original filename is displayed. It's also missing the "Hello" text.

Here is a repro repository:

https://github.com/andgeno/docusaurus-repro-newline-encoding-bug

See the second commit for the actual demo files involved.

Some screenshots:

![image](https://user-images.githubusercontent.com/2432608/162884828-bcc37fcb-4f3f-4476-88d7-07ed5d422759.png)

![image](https://user-images.githubusercontent.com/2432608/162884869-ac5c0c69-f4cb-454f-a97c-1b4eb22441d9.png)

![image](https://user-images.githubusercontent.com/2432608/162884919-b453d3df-b556-44ac-b789-45e7349c1cb3.png)

![image](https://user-images.githubusercontent.com/2432608/162885042-316b2156-8da7-40b3-8285-a647ffbf8259.png)

### Reproducible demo

https://github.com/andgeno/docusaurus-repro-newline-encoding-bug

### Steps to reproduce

- Create a new file and encode it Windows or macOS newline format.
- Add a Markdown header to make the title look different / nicer than just the raw filename.
- Visit page of that new file.
- Page title will be rendered incorrectly.

### Expected behavior

Titles should render the same in all cases.

### Actual behavior

Titles render wrong depending on chosen newline format.

### Your environment

- Docusaurus version used: 2.0.0-beta.18

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-04-12 05:17
Duplicate of #7044

**Closed by Josh-Cena** 2022-04-12 05:17 UTC
Labels: bug, status: needs triage

**Comment by Josh-Cena** [comment] 2022-04-12 05:18
Also, I've never seen a text editor, macOS (unless you use a super old one) or anywhere else, that uses only CR for line breaks. TBF, you should always normalize line endings to LF.
