### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by luhc228** [facebook/docusaurus#9460] opened 2023-10-27 03:18 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

docusaurus 2.x build error:
<img width="1143" alt="image" src="https://github.com/facebook/docusaurus/assets/44047106/6aec3089-e81e-430e-9daf-7a6b2188d2a9">

### Steps to reproduce

1. `npx create-docusaurus@latest my-website classic`
2. `npm start`

### Expected behavior

build successfully.

### Actual behavior

Build error

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-10-27 03:21
Duplicate of https://github.com/facebook/docusaurus/issues/9459

**Closed by Josh-Cena** 2023-10-27 03:21 UTC
Labels: bug, status: needs triage
