### ISSUE TITLE
Some Mermaid diagrams are not rendering text

### ISSUE THREAD

**Issue by rhuanbarreto** [facebook/docusaurus#10524] opened 2024-09-27 09:22 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Demo Available on https://codesandbox.io/p/devbox/cocky-napier-6kqqkk

### Reproducible demo

https://6kqqkk-3000.csb.app/docs/mermaid-test

### Steps to reproduce

1. Install Docusarus (Latest Version)
2. Install the mermaid theme
3. Try to put a simple graph:
```
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
\```
```

### Expected behavior

To have the graph showing correctly

### Actual behavior

Graphs are not displaying text. This affects many different types of mermaid diagrams. In the link shared I made one smoke test page.

### Your environment

- Public source code: https://codesandbox.io/p/devbox/cocky-napier-6kqqkk
- Public site URL: https://6kqqkk-3000.csb.app/docs/mermaid-test
- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-09-27 15:57
Duplicate of https://github.com/facebook/docusaurus/issues/10526

**Closed by slorber** 2024-09-27 15:57 UTC
Labels: bug, status: needs triage
