### ISSUE TITLE
Doc sidebar flickers when scrolling quickly with mouse

### ISSUE THREAD

**Issue by Kimi-Gao** [facebook/docusaurus#4854] opened 2021-05-26 14:23 UTC
## 🐛 Bug Report

The sidebar on the left of page will shake if you scroll page quickly using mouse. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.) Yes

## To Reproduce

go to https://docusaurus.io/docs/sidebar,  scrolls quickly using mouse

## Expected behavior

scroll smoothly

## Actual Behavior

the sidebar on the left of the page will shake as following (please try it more times if it doesn't occur):

https://user-images.githubusercontent.com/12554487/119675512-af804b00-be6f-11eb-9421-4efead0be843.mov

**Comment by lex111** [comment] 2021-05-26 15:35
I was only able to reproduce this issue with very fast scrolling. As I understand it, this is a browser problem due to the fact that we are using sticky positioning. Does this really make you uncomfortable? This is the first time I see someone report about such a flicker.

**Comment by Kimi-Gao** [comment] 2021-05-26 18:28
@lex111 Thanks for finding out the root cause. It should be caused by sticky positioning. [Here](https://ob02v.csb.app/) you can see more example. It often occurs on my website when scrolling fast especially on the long pages using mouse. Is there any quick solution to avoid this flicker?

**Comment by lex111** [comment] 2021-05-27 03:56
You can try using fixed positioning, this will require more code and effort, I'm not sure if we need to refuse sticky position, sooner or later this bug will be fixed in the browser vendors.

**Comment by Kimi-Gao** [comment] 2021-05-29 03:02
@lex111 Thanks, looking forward to the bugfix in the browser vendors.

**Comment by Neilblaze** [comment] 2021-06-01 07:51
@Kimi-Gao I tried this on two different browsers, Chrome & Firefox on Windows 10, but haven't got any glitch like yours. I'm sharing my preview below.


https://user-images.githubusercontent.com/48355572/120286654-1ff9f280-c2dc-11eb-8ad5-c2b3c7fd9ddc.mp4

Can you please tell me which browser/OS you used?

**Comment by Kimi-Gao** [comment] 2021-06-02 17:42
@Neilblaze FYI
OS: macOS 11.3.1
Chrome: Version 90.0.4430.212 (Official Build) (x86_64)

[This website](https://thinkbucket.cn/docs/typescript/2.types/basic-types) is built using docusaurus which is easy to reproduce this issue with mouse scrolling.

https://user-images.githubusercontent.com/12554487/120527233-af062800-c40c-11eb-9500-5422b7537b67.mov

**Comment by Neilblaze** [comment] 2021-06-02 18:42
@Kimi-Gao I went through the [link](https://thinkbucket.cn/docs/typescript/2.types/basic-types/) that you gave, but did not found the issue. I think maybe the issue is device dependant 🤔

**Comment by Kimi-Gao** [comment] 2021-06-03 02:36
@Neilblaze My another device has the same issue, FYI:
![image](https://user-images.githubusercontent.com/12554487/120576901-172d2c00-c456-11eb-8155-d2985a1e0a02.png)
![image](https://user-images.githubusercontent.com/12554487/120576937-2613de80-c456-11eb-8f2e-a108d6db5ca5.png)

both run in chrome: Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by slorber** [comment] 2023-09-25 17:09
Old issue, can't reproduce anymore

Let me know if in 2023+ you can still reproduce this issue, and post a new video + your config

**Closed by slorber** 2023-09-25 17:09 UTC
Labels: bug, domain: theme
