### ISSUE TITLE
Allow to define `"items": []` in `_category_.json`

### ISSUE THREAD

**Issue by softmarshmallow** [facebook/docusaurus#6149] opened 2021-12-21 17:52 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

we can easily customize sidebar hierarchy via sidebars.js, but sometimes using `_category_.json` under direct directory is more effecient.

The problem is we cannot define which documents to show withing `_category_.json`

### Motivation

more usecases with only using `_category_.json`

### API design

Where in documents under /docs/layouts has item from one.md, two.md, three.md ~ ten.md

We can define items to be shown with this directory’s category when autogenerated.
```json
{
  "label": "Layouts",
  "items": ["one", "two", "three"]
}
```

This is useful to ignore files on main/master branch that are incomplete for production.

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment] 2021-12-21 23:11
Sorry, duplicate of #5689. That issue wasn't finalized so let's move the discussion there and see what would be good for us.

**Closed by Josh-Cena** 2021-12-21 23:11 UTC
Labels: feature, status: needs triage
