### ISSUE TITLE
Cannot find module 'wait-file'

### ISSUE THREAD

**Issue by allenli178** [facebook/docusaurus#7892] opened 2022-08-03 09:40 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

`Cannot find module 'wait-file'`

### Steps to reproduce

1. modify all docusaurus lib version to 2.0.0 in `package.json`
2. execute `npm i`
3. when I execute `npm run start`,site couldn't be started。

### Expected behavior

![image](https://user-images.githubusercontent.com/53218750/182576935-79adfc79-ee5a-4fd0-b66b-0bc1db0bef1e.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/53218750/182576975-aeca45a3-fc61-4972-b698-31456eb48daf.png)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-08-03 09:42
Duplicate of #7868

**Closed by Josh-Cena** 2022-08-03 09:42 UTC
Labels: bug, status: needs triage
