### ISSUE TITLE
Theme toggle :hover contrast issue while navbar style: 'dark'

### ISSUE THREAD

**Issue by dewanshDT** [facebook/docusaurus#8587] opened 2023-01-26 22:01 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

while hovering on the theme toggle it still shows light background with light foreground color. this is a design flaw and leads to poor accessibility of the application. 
fixing this will improve the viewability of the button by more users and improve the accessibility of the application.

check the expected and current behaviors of the button below:

### Step 1
set the navbar style to 'dark' in `docusaurus.config.js` file
```
navbar: {
        title: "My Site",
        style: "dark",
```

### Step 2
while in light mode hover on the theme toggle

### Expected behavior

![docusaurauscorrect](https://user-images.githubusercontent.com/71703033/214959061-d5d88d53-0e28-4424-978e-22cce744a7bf.png)

### Actual behavior

![docusauraus](https://user-images.githubusercontent.com/71703033/214959120-948eb651-68e0-4917-aafa-118f3e4704f8.png)

### Your environment

- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chorme 89
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-01-27 18:02
Can't reproduce this on https://docusaurus.io/ using Windows 7 and Chrome 89. Can you see the same behavior on our site, or does it only happen with your site?

**Comment by Josh-Cena** [comment] 2023-01-27 18:04
> while navbar style: 'dark'

Oh I see. Thanks for reporting!

**Comment by dewanshDT** [comment] 2023-01-27 18:49
hey can I work on this?

**Comment by slorber** [comment] 2023-02-01 18:19
Yes, you don't need to ask for such issues, first good PR will be merged @dewanshDT

**Comment by dewanshDT** [comment] 2023-02-01 21:56
hey @slorber @Josh-Cena I've fixed this problem and created a PR 😁

**Closed** 2023-02-23 18:24 UTC
Labels: bug, domain: theme
