### ISSUE TITLE
Translating the auto-generated sidebar labels for categories.

### ISSUE THREAD

**Issue by Rigel772** [facebook/docusaurus#10707] opened 2024-11-21 12:59 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The labels for documents work fine - the problem is with labels for catgories (folders)
Not sure how to tag this. It is either "Bug", "Feature request" or "Documentation"
In documentation I am not able to find how to translate the labels for auto-generated sidebar documentation menu.

### Steps to reproduce

1. configure i18n as per documentation
2.  copy docs to i18n folder
3.  translate documents
4.  translate category labels in `_category_.yml` files
```
position: 3
label: "translated label"
```
5. run `npm run start -- --locale fr `

### Expected behavior

Expect in sidebar to see the translated labels from _category_.yml files from i18n folder

### Actual behavior

The displayed category labels are from original (not translated) docs folder

Searching through the Discord conversations I have found advice to run 
`npm run write-translations -- --locale`
and place the translations in generated `json` file but searching through a file with thousands  of lines seems to bit crazy, hard to believe that it is the recommended way

### Your environment

- Docusaurus version used: 3.6.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-12-10 10:03
It's a current limitation we have.

Duplicate of https://github.com/facebook/docusaurus/issues/8996

**Closed by slorber** 2024-12-10 10:03 UTC
Labels: bug
