### ISSUE TITLE
Hashlinks from inside docusaurus only work a second time

### ISSUE THREAD

**Issue by Repulser** [facebook/docusaurus#3081] opened 2020-07-20 09:11 UTC
## 🐛 Bug Report

Hashlinks only work a second time on big documents when linked from inside docusaurus

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a document with a lot of headers in it
2. Create a document that hyperlinks somewhere around the bottom of the document
3. Click the hyperlink

## Expected behavior

Hashlink works as expected and puts you at the right header

## Actual Behavior

Hashlink puts you half a page above the right header

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.58
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome, production environment (hashlinks don't work in dev) built with Node.js v12.18.2
- Operating system and version (desktop or mobile): Windows 10 desktop

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)
https://github.com/Repulser/Rythm-documentation (should `npm run build` and serve that since hashlinks don't work in dev, the big document here is `/faq` and is linked from `/settings#blacklist`)

**Comment by slorber** [comment] 2020-07-20 10:04
Hi,

Do you have your site hosted somewhere so that it can be easily checked? (you can drag@drop your build folder to Netlify for example)

Do you see this happening on other sites as well? (like D2 documentation?)

**Comment by Repulser** [comment] 2020-07-20 11:29
Hey @slorber 
Please check out - https://staging.rythm.online/misc_help
If you click the "Support Server" hyperlink the issue should reproduce.

**Comment by slorber** [comment] 2020-07-20 13:17
Thanks, definitively a bug.

Could also be related to 
- https://github.com/facebook/docusaurus/issues/2907 
- https://github.com/facebook/docusaurus/issues/2901

**Comment by Drewbi** [comment] 2020-07-23 08:10
I had a look into this and I believe it has to do with when the element.scrollIntoView() method is called. I think in the case where you load in for the first time and then navigate to the hash link, it scrolls to the correct location before images have loaded, when they do load the page content is pushed down leaving the scroll location in the incorrect position. 
As for the other cases where the offset is the height of the navbar i believe it may be the same issue of when the method is called.
If anyone has any possible fixes or areas I should look into in order to solve this I'd be very interested to hear your opinions.

**Comment by Repulser** [comment] 2020-08-20 11:52
Hey! Anything new on this issue?

**Comment by slorber** [comment] 2020-08-20 13:05
Not from me and unfortunately can't dedicate time on this until versioning and i18n have progressed.

Help from the community is welcome for now.

**Comment by lex111** [comment] 2020-11-11 17:02
> Please check out - https://staging.rythm.online/misc_help
If you click the "Support Server" hyperlink the issue should reproduce.

But this is correct behavior, since the header is placed at the bottom of page, so when we click on the anchor link to it ("What is Rythm's Discord Server used for?"), we reach the end of page. In other words, we cannot scroll further directly to this heading in this case.

![image](https://user-images.githubusercontent.com/4408379/98839580-c07ae900-2456-11eb-930a-91850153a18b.png)

It is possible for you to add header highlighting if it was navigating by an anchor link, something like this http://jsfiddle.net/g5QDp/4/
FYI, in current implementation of header, it will not work just to use the `target` CSS selector, need to apply custom JS for achieve this.

**Comment by Repulser** [comment] 2020-11-11 17:12
I believe in this case you haven't reproduced the issue correctly. The docs have moved from staging to https://rythmbot.co/docs/
If I click the "Support Server" hyperlink on https://rythmbot.co/docs/misc_help I get here, without the information in sight:
![image](https://user-images.githubusercontent.com/23503317/98841996-94a93480-2451-11eb-8d36-0f74e1f42fd5.png)

Note that this only happens if you haven't loaded the FAQ page prior.

**Comment by lex111** [comment] 2020-11-11 18:35
Yes, thanks, now I see what the issue is. Indeed, this is related to the loading of images, rather we need to somehow detect that resources was loaded, and only then scroll to the header.

**Comment by slorber** [comment] 2020-11-12 11:35
Hopefully, soon we might use Suspense to load images, and delay navigation until images are all loaded (not sure it's a good idea but could solve the problem).

Something I noticed also, is that the TOC item is not "visible", maybe we should call "scrollIntoView" on highlighted TOC item?

**Comment by Repulser** [comment] 2020-12-20 13:33
Hey! Any update on this issue?

**Comment by TomPeirs** [comment] 2022-01-14 10:01
Hi,
It can be reproduced on this link too: https://docs.boc-group.com/adonis/en/docs/13.0/administration_manual/lbm-000000/#libcs-L0000
Furhtermore, @Josh-Cena  recommended to adding the width & height to the image during processing the image in markdown.
![image](https://user-images.githubusercontent.com/68061801/149496977-079ec0ff-f03f-49dc-912e-a0e6d9bead20.png)

**Comment by TomPeirs** [comment] 2022-01-14 10:05
> Something I noticed also, is that the TOC item is not "visible", maybe we should call "scrollIntoView" on highlighted TOC item?

@slorber  This I believe is fixed with https://github.com/facebook/docusaurus/issues/6058

**Comment by Josh-Cena** [comment] 2022-01-14 10:07
Yes, I'm spinning up a quick fix for this. We should probably read the image's width & height when processing them

**Closed** 2022-01-19 11:45 UTC
Labels: bug, help wanted, mlh
