### ISSUE TITLE
Front Matter to override docs lastUpdate date/author

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#7263] opened 2022-04-29 09:37 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Suggested in https://github.com/facebook/docusaurus/discussions/7229#discussioncomment-2658878

We should allow docs frontMatter that permits to override the "last updated" data that we generally read from Git.

Git is not always available at build time, but users should still be able to manually fill those data

```yaml
lastUpdate:
  at: 1539502055
  by: "Author"
```

Front matter validation could accept the date as timestamp (seconds or millies?), or ISO/parseable string? (+ JS Date because Yaml may automatically do the conversion)

This is a relatively simple issue, good for external contributors

### Self-service

- [ ] I'd be willing to do some initial work on this proposal myself.

**Comment by Josh-Cena** [comment] 2022-04-29 09:38
Duplicate of #5691

**Comment by Josh-Cena** [comment] 2022-04-29 09:39
Let's discuss it there instead. The API is slightly different, but not a big deal

**Closed by Josh-Cena** 2022-04-29 09:39 UTC
Labels: closed: duplicate, feature
