### ISSUE TITLE
My screen getting blank when i use mdx live editor.

### ISSUE THREAD

**Issue by fiqryq** [facebook/docusaurus#5555] opened 2021-09-11 15:52 UTC
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

I try to use MDX using livecodeblock , everything is okay until I try to delete all code on the live editor and when i press delete one more time my screen getting blank and my console give me this code :  Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Expected behavior

i can delete my code on the live editor.

## Actual behavior

console code :  Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

<img width="1440" alt="Screen Shot 2021-09-11 at 22 48 27" src="https://user-images.githubusercontent.com/25787603/132953583-032408e6-ea7a-4493-aa96-90c666e8663b.png">

## Your environment

- Public source code: https://github.com/fiqryq/fiqrychoerudin
- Public site URL: localhost / https://fiqrychoerudin.vercel.app/
- Docusaurus version used: 2.0.0-beta.6
- Environment name and version (chrome Version 93.0.4577.63 (Official Build) (x86_64) , Node.js 14.17.6 LTS):
- Operating system and version (Mac OS Big Sur 11.5.2):

## Reproducible demo

Use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by lex111** [comment] 2021-09-11 16:22
Could you please provide reproducible code or video? For example, I don't see an error if I delete code from [the section on docs website](http://localhost:3000/docs/markdown-features/code-blocks#interactive-code-editor).

![image](https://user-images.githubusercontent.com/4408379/132954481-7bf98751-0ecf-4a1d-ac20-5f27cdcb9bfc.png)

**Comment by ChristopherHButler** [comment] 2021-09-11 18:55
I'm having the same or similar issue. I tried following the instructions at [https://docusaurus.io/docs/markdown-features/code-blocks#interactive-code-editor](https://docusaurus.io/docs/markdown-features/code-blocks#interactive-code-editor) to add a live code editor and when I add the `live` tag to the meta string my app basically crashes. I have also attached a screenshot with console output. As soon as I remove the `live` tag everything works fine again.

![Screenshot 2021-09-11 at 20 50 53](https://user-images.githubusercontent.com/29358086/132958382-fd05cefb-1254-433d-a011-ae74c677c6b3.png)

docusaurus.config.js:
```
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');


// With JSDoc @type annotations, IDEs can provide config autocompletion
/** @type {import('@docusaurus/types').DocusaurusConfig} */
(module.exports = {
  title: 'Deez Docs',
  tagline: 'Take a look at deez docs',
  url: 'https://deez-docs.vercel.app/',
  baseUrl: '/',
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'ChristopherHButler',
  projectName: 'docs',

  presets: [
    [
      '@docusaurus/preset-classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: 'docs',
          path: 'docs',
          sidebarPath: require.resolve('./sidebars.js'),
          lastVersion: 'current',
          onlyIncludeVersions: ['current'],
          editUrl: 'https://github.com/ChristopherHButler/docs',
        },
        // blog: {
        //   showReadingTime: true,
        //   // Please change this to your repo.
        //   editUrl:
        //     'https://github.com/ChristopherHButler/docs/blog/',
        // },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'development',
        path: 'docz/engineering/development',
        routeBasePath: 'docz/engineering/development',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'design',
        path: 'docz/engineering/design',
        routeBasePath: 'docz/engineering/design',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'architecture',
        path: 'docz/engineering/architecture',
        routeBasePath: 'docz/engineering/architecture',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'javascript',
        path: 'docz/engineering/javascript',
        routeBasePath: 'docz/engineering/javascript',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'typescript',
        path: 'docz/engineering/typescript',
        routeBasePath: 'docz/engineering/typescript',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'react',
        path: 'docz/engineering/react',
        routeBasePath: 'docz/engineering/react',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'react-typescript',
        path: 'docz/engineering/react-typescript',
        routeBasePath: 'docz/engineering/react-typescript',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'reactnative',
        path: 'docz/engineering/react-native',
        routeBasePath: 'docz/engineering/react-native',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'preact',
        path: 'docz/engineering/preact',
        routeBasePath: 'docz/engineering/preact',
        sidebarPath: require.resolve('./sidebars.js'),
      }, 
    ],
  ],

  themes: ['@docusaurus/theme-live-codeblock'],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: 'Docs',
        logo: {
          alt: 'Docs Logo',
          src: 'img/logo.svg',
        },
        items: [
          {
            label: 'Dev',
            type: 'dropdown',
            position: 'left',
            items: [
              {
                label: 'JavaScript',
                to: '/docz/engineering/javascript/index',
                activeBaseRegex: `/javascript/`,
              },
              {
                label: 'TypeScript',
                to: 'docz/engineering/typescript/index',
                activeBaseRegex: `/typescript/`,
              },
              {
                label: 'React',
                to: 'docz/engineering/react/intro',
                activeBaseRegex: `/react/`,
              },
              {
                label: 'React + TypeScript',
                to: 'docz/engineering/react-typescript/index',
                activeBaseRegex: `/ts-react/`,
              },
              {
                label: 'React Native',
                to: 'docz/engineering/react-native/index',
                activeBaseRegex: `/react-native/`,
              },
              {
                label: 'Preact',
                to: 'docz/engineering/preact/index',
                activeBaseRegex: `/preact/`,
              },
            ],
          },
          {
            label: 'Management',
            type: 'dropdown',
            docId: 'intro',
            position: 'left',
            items: [
              {
                label: 'Coming Soon',
                type: 'doc',
                docId: 'intro',
              }
              // {
              //   label: 'Leadership',
              //   to: '/management/leadership/intro',
              //   activeBaseRegex: `/management/leadership/`,
              // },
              // {
              //   label: 'Strategy',
              //   type: 'doc',
              //   docId: 'intro',
              // },
              // {
              //   label: 'Marketing',
              //   type: 'doc',
              //   docId: 'intro',
              // },
            ],
          },
          {
            label: 'UX Design',
            type: 'dropdown',
            position: 'left',
            items: [
              {
                label: 'Coming Soon',
                type: 'doc',
                docId: 'intro',
              }
              // {
              //   label: 'Information Architecture',
              //   type: 'doc',
              //   docId: 'intro',
              // },
              // {
              //   label: 'Interaction Design',
              //   type: 'doc',
              //   docId: 'intro',
              // },
              // {
              //   label: 'User Research',
              //   type: 'doc',
              //   docId: 'intro',
              // },
            ],
          },
          // {to: '/blog', label: 'Blog', position: 'left'},
          {
            href: 'https://github.com/ChristopherHButler/docs',
            position: 'right',
            className: 'header-github-link',
            'aria-label': 'GitHub repository',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              {
                label: 'Software Engineering',
                to: '/docs/engr',
              },
              {
                label: 'Engineering Management',
                to: '/docs/management',
              },
              {
                label: 'UX Design',
                to: '/docs/design',
              },
            ],
          },
          {
            title: 'Social',
            items: [
              {
                label: 'LinkedIn',
                href: 'https://www.linkedin.com/in/christopherharoldbutler/',
              },
              {
                label: 'GitHub',
                href: 'https://github.com/ChristopherHButler',
              },
            ],
          },
          // {
          //   title: 'More',
          //   items: [
          //     {
          //       label: 'Blog',
          //       to: '/blog',
          //     },
          //     {
          //       label: 'GitHub',
          //       href: 'https://github.com/facebook/docusaurus',
          //     },
          //   ],
          // },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Deez Docs.`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
});
```

my package.json:
```
{
  "name": "docs",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.6",
    "@docusaurus/plugin-content-docs": "^2.0.0-beta.6",
    "@docusaurus/preset-classic": "2.0.0-beta.6",
    "@docusaurus/theme-live-codeblock": "^2.0.0-beta.6",
    "@mdx-js/react": "^1.6.21",
    "@svgr/webpack": "^5.5.0",
    "clsx": "^1.1.1",
    "file-loader": "^6.2.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "styled-components": "^5.3.1",
    "url-loader": "^4.1.1"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}


```

**Comment by lex111** [comment] 2021-09-11 19:07
@ChristopherHButler I need reproducible repo, could you provide it?

**Comment by ChristopherHButler** [comment] 2021-09-11 19:29
@lex111 sure thing. Here is my repo: [https://github.com/ChristopherHButler/docs](https://github.com/ChristopherHButler/docs).

I do not have my docs in the `docs` folder. You can find the example of the broken live codeblock under docz > engineering > typescript > 1-basics > 00-introduction.md. I just copied in the example from the docusaurus site at line 11.

Let me know if you need anything else

**Comment by lex111** [comment] 2021-09-11 21:10
@ChristopherHButler thanks, but in your case, the problem with React version mismatch (you use v17, but the latest minor version react-live 2.3.0 rewritten on hooks uses v16). yarn can resolve this automatically, but npm you use doesn't.

A workaround would be to downgrade React to v16. But it would be better if we just use the previous version react-live 2.2.0. I created PR for this #5556.

**Comment by ChristopherHButler** [comment] 2021-09-11 21:38
Thanks @lex111 I'll downgrade for now and maybe keep an eye out for that PR.

**Comment by fiqryq** [comment] 2021-09-12 02:27
@lex111 this my video , 
https://user-images.githubusercontent.com/25787603/132969316-970782af-d9c4-4d61-88a4-a27d66ab504c.mov

docusaurus.config.js

```js
const lightCodeTheme = require("prism-react-renderer/themes/github");
const darkCodeTheme = require("prism-react-renderer/themes/dracula");

/** @type {import('@docusaurus/types').DocusaurusConfig} */
module.exports = {
  title: "fiqryq",
  tagline: "Membanteng",
  url: "https://fiqryq.github.io",
  baseUrl: "/",
  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",
  favicon: "/img/favicon.ico",
  organizationName: "fiqryq",
  projectName: "porfolio",
  themes: ["@docusaurus/theme-live-codeblock"],
  themeConfig: {
    navbar: {
      title: "Hi there 👋",
      logo: {
        alt: "My Site Logo",
        src: "img/icon.svg",
      },
      items: [
        { to: "/", label: "Blog", position: "left" },
        {
          type: "doc",
          docId: "index",
          position: "left",
          label: "About me",
        },
        {
          href: "https://github.com/fiqryq",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Support me",
          items: [
            {
              label: "Saweria",
              href: "https://saweria.co/fiqryq",
            },
          ],
        },
        {
          title: "Social Media",
          items: [
            {
              label: "Twitter",
              href: "https://twitter.com/fiqryq",
            },
            {
              label: "Instagam",
              href: "https://instagram.com/fiqryq",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Fiqry choerudin.`,
    },
    prism: {
      theme: lightCodeTheme,
      darkTheme: darkCodeTheme,
    },
  },
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
          // Please change this to your repo.
          // editUrl:
          //   "https://github.com/facebook/docusaurus/edit/master/website/",
        },
        blog: {
          showReadingTime: true,
          routeBasePath: "/",
          // Please change this to your repo.
          // editUrl:
          //   "https://github.com/facebook/docusaurus/edit/master/website/blog/",
        },
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      },
    ],
  ],
};

```

package.json

```json
{
  "name": "portfolio",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "dependencies": {
    "@docusaurus/core": "^2.0.0-beta.6",
    "@docusaurus/preset-classic": "^2.0.0-beta.6",
    "@docusaurus/theme-live-codeblock": "^2.0.0-beta.6",
    "@mdx-js/react": "^1.6.21",
    "@svgr/webpack": "^5.5.0",
    "clsx": "^1.1.1",
    "file-loader": "^6.2.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "url-loader": "^4.1.1"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by lex111** [comment] 2021-09-12 06:50
@fiqryq your video is not available, could you provide reproducible repo with broken live code block?

![image](https://user-images.githubusercontent.com/4408379/132976760-545ce200-efaf-4eb8-acd9-ab7ffc838c9f.png)

**Comment by fiqryq** [comment] 2021-09-12 07:07
> @fiqryq your video is not available, could you provide reproducible repo with broken live code block?
> 
> ![image](https://user-images.githubusercontent.com/4408379/132976760-545ce200-efaf-4eb8-acd9-ab7ffc838c9f.png)

sorry my bad i set private video on my youtube , here my video :

https://user-images.githubusercontent.com/25787603/132977208-bf490fd0-b979-4354-a041-eeee9d6ab28b.mp4

**Comment by Josh-Cena** [comment] 2021-09-12 08:14
I was discussing with someone on Discord about this as well, it's specific to the case where an invalid React child (e.g. an object like `console`) is passed to the live scope without being wrapped by a function. Seems this is caused by a bad error boundary

**Comment by lex111** [comment] 2021-09-12 08:57
The bug is reproduced on react-live playground https://react-live.netlify.app/, so the issue related with this dependency.

**Comment by slorber** [comment] 2021-09-22 07:57
Hey

Merged https://github.com/facebook/docusaurus/pull/5556 so please test and let us know if canary doesn't fix the problems

**Closed by slorber** 2021-09-22 07:57 UTC
Labels: bug, needs triage
