### ISSUE TITLE
Headers in pasted URLs (external links) do not load the page at the specified header

### ISSUE THREAD

**Issue by bgree052** [facebook/docusaurus#4802] opened 2021-05-17 09:07 UTC
Posted about this before but the issue was closed immediately after someone said to update (which did not solve the issue).
I did ask for it to be reopened 4 days ago, but it has not been so I am making another.

## 🐛 Bug Report

When trying to load a page at a specific header via an external link or pasting in a URL with a # header argument, the page instead loads at the beginning rather than at the header specified. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce
1. Paste in this link in your browser and hit enter (https://docs.lunalabs.io/docs/playable/getting-started/step-by-step#2-create-your-playable-scene-in-unity)
2. Notice that the URL removes the header argument and instead loads at the beginning of the page

## Expected behaviour

I expected the page to load with # header still in the URL and at that specified header location on the page. 
**Note:** Links that are on pages that link to headers (both for headers on the same page, and to headers on other pages) work fine. 

## Actual Behaviour

The page instead loads at the beginning rather than at the header specified, and you can see the URL change before the page loads to remove the # header argument from it. 

A gif of this happening
![alt-text](https://i.imgur.com/1p5RF56.gif)

(A gif of the full page view of the problem occurring if you click [here](https://i.imgur.com/jnbM6Eq.gif))

## Your Environment

- Public source code: Not available publicly
- Public site url: https://docs.lunalabs.io/
- Docusaurus version used: 2.0.0-beta.0
- Environment name and version: Chrome 90.0.4430.212, Babel 7.10.4, Node 14.0.19
- Operating system and version: Windows 10 Pro, Version 20H2

**Comment by slorber** [comment] 2021-05-18 08:25
Thanks for upgrading.

I didn't re-open just because I don't work on weekends :) 

Also was pretty sure this issue was a duplicate of something else. Just found it again, so let's close this one: https://github.com/facebook/docusaurus/issues/3081

**Comment by slorber** [comment] 2021-05-18 08:26
hmmm not 100% sure it's the same bug, but looks related, so re-opening

**Comment by bgree052** [comment] 2021-05-18 13:24
Yeah there issue seems to be links that are within their docs, whereas for us it is external links or pasted in URLs that don't function properly.

**Comment by bgree052** [comment] 2021-05-25 11:00
Just following up on this, do you have any suggestions for a workaround?
Or if this has turned out to be a known bug or not?

**Comment by lex111** [comment] 2021-05-25 19:23
It seems to be related to hosting provider of your site, for some reason it makes a redirect, which is why hash in URL seems to be lost after redirection. Are you using GitHub Pages?

**Comment by bgree052** [comment] 2021-05-26 11:38
We are indeed using GitHub Pages

**Comment by lex111** [comment] 2021-05-26 11:53
And this is strange since I have deployed demo site on GitHub Pages and I cannot reproduce this issue. Perhaps you added redirects or something like that?

**Comment by bgree052** [comment] 2021-05-27 17:05
Turns out we had a script that we made a while back that fixed a similar problem previously, but had stopped working. 
An adjustment was made and things work fine now 

![image](https://user-images.githubusercontent.com/22733684/119867753-24a65b80-bf16-11eb-9ee8-331ba730189e.png)

**Closed** 2021-05-27 17:05 UTC
Labels: bug, needs triage
