### ISSUE TITLE
Build warnings about unresolved MDX components don't fail build

### ISSUE THREAD

**Issue by ianschmitz** [facebook/docusaurus#2448] opened 2020-03-23 16:37 UTC
## 🐛 Bug Report

Build system warnings don't cause a build failure in CI, even when `CI` env variable is set to `true`. 

For example:
![image](https://user-images.githubusercontent.com/6355370/77339546-2ad4f280-6ce9-11ea-85a4-6f608ae0907b.png)

IMO this should cause the build to fail as the component wasn't imported in the `.mdx` file correctly.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

:+1: 

## To Reproduce

1. Import a component in a `.mdx` file and purposely mis-spell the imported member
1. Use the component in the `.mdx` file with the correct spelling (not the misspelled name)
1. `yarn build`
1. Notice the warning, but process exits with `0` exit code

## Expected behavior

In this case i feel it should always fail, but alternatively you could follow the same approach we've used in CRA which is to treat as a warning, and if there are any warnings and `CI=true`, then exit with non-zero exit code.

## Actual Behavior

Build succeeds

## Your Environment

- Docusaurus version used: 2.0.0-alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): node 12.13.0
- Operating system and version (desktop or mobile): Ubuntu 19.10

**Comment by Josh-Cena** [comment] 2022-01-08 09:47
This for sure can be reproduced, but since it's logged directly from the MDX component creator, I'm not sure if we can intercept that. Probably this has to be done in userland with log parsing.

**Comment by Josh-Cena** [comment] 2022-01-29 15:48
I'll be closing this, because it's not fixable on our side. Will be automatically fixed in the attempt to migrate to MDX v2 (#4029), which will probably be in Docusaurus v3.

**Closed by Josh-Cena** 2022-01-29 15:48 UTC
Labels: bug, closed: wontfix
