### ISSUE TITLE
Yarn is showing a `npx` command

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [facebook/docusaurus#8070] opened 2022-09-08 19:06 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

![image](https://user-images.githubusercontent.com/7463564/189205516-8e1f38df-fb66-49fd-89b7-9af0f8218e75.png)

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment] 2022-09-08 19:08
Duplicate of https://github.com/facebook/docusaurus/issues/7908

**Comment by Josh-Cena** [comment] 2022-09-08 19:09
This is very much working as intended (as in, even if we control the conversion process, we don't be able to change it). We have been constantly banging our heads on this about what the best way to denote execution of remote packages is, and ultimately we only found `npx`.

**Closed by Josh-Cena** 2022-09-08 19:09 UTC
Labels: closed: duplicate, external
