### ISSUE TITLE
Add baseUrl to the link suggested by the dev server on start

### ISSUE THREAD

**Issue by maksnester** [facebook/docusaurus#3275] opened 2020-08-13 10:35 UTC
## 🚀 Feature

When baseUrl is used, dev server should suggest opening the URL with that baseUrl. It should be `localhost:port/baseUrl` But now it suggests opening just `localhost:port`. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yeah. 

## Motivation

It would be more convenient. Now you click on the suggested link and see the 404-page every time you start the dev server.

```
  Compiled successfully in 9.48s

ℹ ｢wds｣: Project is running at http://localhost:3000/
```

## Pitch

See Motivation. 
This feature request is actually more like a bug report. Wasn't sure which one I should pick.

**Comment by Ako92** [comment] 2020-08-14 12:11
I will handle it.

**Comment by Ako92** [comment] 2020-08-14 12:12
Please Just give me a little information about how to do that?

**Comment by slorber** [comment] 2020-08-14 12:29
@Ako92 I have no idea, maybe it's something out of our control inside Webpack :) Please investigate and tell us what you think

**Comment by anshulrgoyal** [comment] 2020-08-14 16:40
> Please Just give me a little information about how to do that?

I think changing webpack-dev-server config should work.
@Ako92 this should work https://webpack.js.org/configuration/dev-server/#devserveropenpage

**Comment by Ako92** [comment] 2020-08-15 19:11
dev server auto open browser is fine
when you change baseUrl in docusaurus.config.js and start the project it show browser with new baseUrl. Thats fine


The problem is that i should change this url 
![image](https://user-images.githubusercontent.com/24778140/90319759-423ea180-df50-11ea-97b6-ca6148a0da93.png)

**Comment by imskr** [comment] 2020-09-13 15:43
@slorber This is open?

**Comment by slorber** [comment] 2020-09-29 17:53
@imskr I'll merge the first PR that solves this problem so if you find a solution let me know as it seems @Ako92 didn't

**Comment by utkarsh867** [comment] 2020-10-03 18:36
@slorber Is this issue still open?

@sarthakkundra and I would like to take this up as a good first issue.

We think that we may have a workaround for the issue to fulfil the motivation. It looks like the lines starting with `wds` are actually from weback-dev-server. So modifying those would be out of scope. As per the motivation, a simple solution would be to add an output with the website's correct URL such that:

![image](https://user-images.githubusercontent.com/19630580/94999183-4c912980-05ea-11eb-8443-8820659f6db5.png)

**Comment by slorber** [comment] 2020-10-05 11:06
Thanks @utkarsh867 you can take this issue.

Your solution can be a workaround if it's not possible to modify the URL displayed by WDS

**Comment by utkarsh867** [comment] 2020-10-05 16:00
@slorber From what I understand after reading up about WDS, the URL displayed in the console makes sense because it indicates that the WDS is running at the specific port.

**Comment by slorber** [comment] 2020-10-05 17:17
@utkarsh867 yes it makes sense for WDS and I'm not sure we can do anything about it anyway. If we don't change anything it's not a big deal.

Maybe just showing "docusaurus website is running at http://localhost:8000/baseUrl" is good enough?

I'll let @maksnester tell you why he thinks it's important. For me now having the baseUrl printed by WDS has never been a big deal, but I may lack the perspective of a junior dev or something that is not used to frontend dev at all.

**Closed** 2020-10-06 11:19 UTC
Labels: difficulty: starter, feature, good first issue, help wanted, mlh

**Comment by slorber** [comment] 2020-10-06 11:20
Thanks @utkarsh867  the new output is

![image](https://user-images.githubusercontent.com/749374/95195286-9fc7cf80-07d6-11eb-83fe-955954bb2333.png)


WDS log does not include the baseurl but I think it's good enough so that we can close this issue. 
If you feel it's not enough please open a PR with an implementation proposition.
