### ISSUE TITLE
Cannot use SVG in img element

### ISSUE THREAD

**Issue by matevz** [facebook/docusaurus#8398] opened 2022-11-30 06:16 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Following https://docusaurus.io/docs/markdown-features/assets#images I can use markdown syntax for PNG, JPG and SVG images fine:

```
![Example banner](./assets/docusaurus-asset-example-banner-in-svg.svg)
```

However, I cannot seem to use CommonJS or Import statement for SVG images:

```
<img
  src={require('./assets/docusaurus-asset-example-banner-in-svg.svg').default}
  alt="Example banner"
/>
```

In this case an `<img />` tag is generated in HTML without having `src` attribute defined. Using the same syntax for PNGs and JPGs works fine. Using [inline SVGs](https://docusaurus.io/docs/markdown-features/assets#inline-svgs) again works fine, but I'd like to keep SVG file as an asset.

### Steps to reproduce

1. Follow https://docusaurus.io/docs/markdown-features/assets#images
2. Use CommonJS or Import statement for SVG image.

### Expected behavior

`<img src="path-to-my-svg-file-with-some-hash-behind.svg" />` produced in HTML.

### Actual behavior

`<img />` produced in HTML.

### Your environment

- Public source code: https://github.com/oasisprotocol/docs/blob/matevz/docs/km-diagrams/docs/dapp/sapphire/guide.mdx?plain=1
- Public site URL: https://deploy-preview-310--trusting-archimedes-14c863.netlify.app/dapp/sapphire/guide/#transactions--calls
- Docusaurus version used: 2.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.17.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 22.04

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-11-30 06:19
You need to use `require('!!url-loader!./assets/docusaurus-asset-example-banner-in-svg.svg').default`, because otherwise `svg-loader` kicks in. This is working as intended.

**Comment by slorber** [comment] 2022-11-30 11:32
We decided that all md/mdx/js/ts files will convert SVG to REact components automatically.

This is also what permits to support this:

```js
import DocusaurusSvg from './docusaurus.svg';

<DocusaurusSvg />;
```

We can't support your behavior without removing the behavior above, so indeed this works as intended and is not really a bug and I'm closing.

If you don't agree with our opinions you can use a plugin that modifies the svgr config using the `configureWebpack` hook.

It's also possible to override on a case-by-case basis with Webpack inline loaders, as @Josh-Cena suggested:
https://webpack.js.org/concepts/loaders/#inline

**Closed by slorber** 2022-11-30 11:32 UTC
Labels: bug, status: needs triage
