### ISSUE TITLE
Hash link jumping not working when opening a new tab

### ISSUE THREAD

**Issue by oriooctopus** [facebook/docusaurus#3109] opened 2020-07-23 18:23 UTC
By hash link jumping I am referring to the behavior of, at a link such as [https://v2.docusaurus.io/docs/installation#problems](https://v2.docusaurus.io/docs/installation#problems), the page should automatically scroll to the hashed section when right clicking on a link and opening to a new tab

This can be reproduced by right clicking on any hash link that appears right next to the headers. **This works on v2.docusaurus.io but does not seem to work when generating a new docusaurus site**. Steps to reproduce:
1. npx @docusaurus/init@next init my-website facebook (my version is the latest, .58-alpha)
2. Yarn start
3. Go to the style guide doc page (it is the default doc page) 
4. Right click on any of the hash links on that page and open a new tab. The expected behavior would be for that tab to automatically be at the hashed section, but instead the location is at the top of the page.

-Also, refreshing a page on a hash link, such as [https://v2.docusaurus.io/docs/design-principles#how-docusaurus-works](https://v2.docusaurus.io/docs/design-principles#how-docusaurus-works), does not take you to the hashed section but instead keeps you were you were. This to me makes sense, but I still wanted to note it

**Comment by svict4** [comment] 2020-07-24 06:59
Can confirm that appears to be an issue, but when running the dev server. The hash links work as expected when serving a build.

**Comment by bendtherules** [comment] 2020-10-26 15:27
Yes, this is a issue with local dev server, but works correctly on prod build. Many users might be confused with this and spend countless hours trying to "fix" it.

**Comment by slorber** [comment] 2020-10-26 17:17
I can't reproduce on the examples given in production build, so yeah that might be a dev only issue, which is a bit different from production due to rendering on the client and having hot module reloading wired etc...

I'm not sure we can do anything about it, but if you have any suggestion for a fix, or how to document this behavior, don't hesitate to submit a PR

**Comment by bendtherules** [comment] 2020-10-27 06:10
Can someone point to which file handles this section link scrolling logic?

**Comment by slorber** [comment] 2020-10-27 08:59
@bendtherules I don't know well this part so you'll have to look in the codebase to find it. But also consider that anchor linking is native to browsers so it's not even sure we wrote any code for that.

**Comment by bendtherules** [comment] 2020-10-27 10:14
Cool, i will try will out and see.

**Comment by lex111** [comment] 2020-11-10 15:02
In fact, we documented it a long time ago that some functionality might not work in the dev server. So I'm closing this issue, but If you have suggestions for improving this docs, please create a PR.

![image](https://user-images.githubusercontent.com/4408379/98690940-8dfdbd00-237e-11eb-8f63-47c894c48b5b.png)

**Closed by lex111** 2020-11-10 15:02 UTC
Labels: bug, needs triage
