### ISSUE TITLE
Broken Markdown link detection should also work for internal links

### ISSUE THREAD

**Issue by Zamiell** [facebook/docusaurus#4180] opened 2021-02-05 01:52 UTC
One fantastic feature of Docusaurus 2 is that it warns me if I have a broken link in one of my Markdown files:

```
warn Docs markdown link couldn't be resolved: (non_existent_page.md) in C:\Repositories\my-repo\docs\main.md for version current
```

This feature is really helpful and a huge time saver!

However, this feature does not work with internal links on the page.

For example, consider the following Markdown file:

```
### Section 1

This is section 1. By the way, you might want to also check out [section 2](#section-3).
<!-- Oops, I made a typo at the end of the previous line, and the link is now broken! -->

### Section 2

This is section 2.
```

Docusaurus won't warn me about the bug in this file, which is a real bummer. =(
Is this something that can be added?

**Comment by slorber** [comment] 2021-02-05 15:05
Yes, we definitively want this feature, duplicate of https://github.com/facebook/docusaurus/issues/3321

**Closed by slorber** 2021-02-05 15:05 UTC
Labels: feature, needs triage
