### ISSUE TITLE
Algolia DocSearchPage doesn't inherit searchParameters 

### ISSUE THREAD

**Issue by csestito** [facebook/docusaurus#4221] opened 2021-02-12 21:59 UTC
## 🐛 Bug Report

The search parameters e.g. facets passed into searchParameters are used for the SearchBar, but don't carry over to the DocSearchPage. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes 

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

1. Add a facet to searchParameters to algolia in docusaurus config'
2. Search in Search Bar
3. Click view all
4. See filter is not run on the search page
5. 
## Expected behavior

any searchParameters specified in the config would carry over to the DocSearchPage 

## Actual Behavior

No searchParameters were used on the DocSearchPage

## Your Environment

- Public source code/URL https://codesandbox.io/s/magical-mclaren-byg9e?file=/docusaurus.config.js
- Docusaurus version used: 70

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

https://codesandbox.io/s/magical-mclaren-byg9e?file=/docusaurus.config.js

**Comment by slorber** [comment] 2021-02-15 17:13
Yes you are right

Duplicate of https://github.com/facebook/docusaurus/issues/3805

**Closed by slorber** 2021-02-15 17:13 UTC
Labels: bug, needs triage
