### ISSUE TITLE
TOC shows comments in headings

### ISSUE THREAD

**Issue by plocket** [facebook/docusaurus#10018] opened 2024-04-04 18:37 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

The table of contents menu shows the comments in the heading, well as the text of the other nodes.

There is probably an issue for this already, but I couldn't find it.

### Reproducible demo

https://codesandbox.io/p/devbox/intelligent-franklin-s3vldx

### Steps to reproduce

1. Make a heading
2. Add either a MDX comment or an html comment
3. See that the comments are correctly invisible in the heading
4. See that the text is visible in the table of contents

### Expected behavior

I thought the text of the comment that I put in the heading would be invisible in the table of contents.

### Actual behavior

The text of the comments was visible in the table of contents.

### Your environment

- Public source code: https://codesandbox.io/p/devbox/intelligent-franklin-s3vldx
- Public site URL: https://codesandbox.io/p/devbox/intelligent-franklin-s3vldx
- Docusaurus version used: 3.2.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 123.0.6312.87, devbox
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): OSX 12.6.6

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Abdullah-03** [comment] 2024-04-05 22:08
I've figured it out.
```js
const tree = fromMarkdown('## Comments {/* are visible */} <!-- in --> the TOC')
visit(tree, 'heading', (headingNode) => {
    console.log(headingNode)
}
```
This piece of code in docusaurus-mdx-loader/src/remark/headings/index.ts produces the following output:
```
{
  type: 'heading',
  depth: 2,
  children: [
    {
      type: 'text',
      value: 'Comments {/* are visible */} ',
      position: [Object]
    },
    { type: 'html', value: '<!-- in -->', position: [Object] },
    { type: 'text', value: ' the TOC', position: [Object] }
...
```

Notice that while the html comment is detected as a non text (hence not part of the heading) type, the comment prior is not separated. Hence the reason that part is visible in TOC but not the html comment.

Solution: The most obvious approach seems to be the write in extra parsing logic to handle this edge case and test it out that it doesn't have any extraneous effect.

If this sounds good, this issue can be assigned to me and I'll fix it this weekend.

**Comment by Abdullah-03** [comment] 2024-04-07 16:31
TOC in docusaurus-mdx-loader currently does not parse JSX. Not just comments but any expression is simply just converted to string i.e.
```js
{5 + 5}
```
becomes "5 + 5".

In the code a comment actually states this as a todo
```
// TODO This is really a workaround, and not super reliable
// For now we only support serializing tagName, className and content
// Can we implement the TOC with real JSX nodes instead of html strings later?
```

I tried implementing it but wasn't able to without making the code insecure (eval). If a maintainer can point out how that is achieved for headings within the document I could work towards porting it for the TOC. I wasn't able to find that implementation by myself.

**Comment by Josh-Cena** [comment] 2024-04-08 14:13
Calling it a duplicate of https://github.com/facebook/docusaurus/issues/9772

**Closed by Josh-Cena** 2024-04-08 14:13 UTC
Labels: bug, status: needs triage
