### ISSUE TITLE
Imported SVGs incorrectly share the same fill definitions

### ISSUE THREAD

**Issue by ArthurFlag** [facebook/docusaurus#10357] opened 2024-07-31 08:20 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I've imported 3 SVGs, and it would appear the fill color definition is used **across** the SVGs, if that fill has the same id, even though the svg files themselves don't share the same id.

### Reproducible demo

[See demo](https://codesandbox.io/p/devbox/exciting-bartik-g8zy55?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxessktk00083b6jexlayd6a%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxessktk00033b6j92kr96ix%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxessktk00053b6juped4sy2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxessktk00073b6jvu4mavz2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxessktk00033b6j92kr96ix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxessktk00023b6jzmen8oxr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxessktk00033b6j92kr96ix%2522%252C%2522activeTabId%2522%253A%2522clxessktk00023b6jzmen8oxr%2522%257D%252C%2522clxessktk00073b6jvu4mavz2%2522%253A%257B%2522id%2522%253A%2522clxessktk00073b6jvu4mavz2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxessktk00063b6j9fp5refe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fdocs%252Fintro%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxessktk00063b6j9fp5refe%2522%257D%252C%2522clxessktk00053b6juped4sy2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxessktk00043b6j385j2djs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxessktk00053b6juped4sy2%2522%252C%2522activeTabId%2522%253A%2522clxessktk00043b6j385j2djs%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. See the [reproducible](https://codesandbox.io/p/devbox/exciting-bartik-g8zy55?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxessktk00083b6jexlayd6a%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxessktk00033b6j92kr96ix%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxessktk00053b6juped4sy2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxessktk00073b6jvu4mavz2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxessktk00033b6j92kr96ix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxessktk00023b6jzmen8oxr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxessktk00033b6j92kr96ix%2522%252C%2522activeTabId%2522%253A%2522clxessktk00023b6jzmen8oxr%2522%257D%252C%2522clxessktk00073b6jvu4mavz2%2522%253A%257B%2522id%2522%253A%2522clxessktk00073b6jvu4mavz2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxessktk00063b6j9fp5refe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fdocs%252Fintro%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxessktk00063b6j9fp5refe%2522%257D%252C%2522clxessktk00053b6juped4sy2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxessktk00043b6j385j2djs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxessktk00053b6juped4sy2%2522%252C%2522activeTabId%2522%253A%2522clxessktk00043b6j385j2djs%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). Notice the 3 SVGs have the same color. 
2. Open the SVG files themselves in your browser, notice they actually don't have the same color.
3. Change the order of the SVG on the md page and notice how they will all use the color of the first SVG used on the page.

It appears that they all get a fill defined as `fill="url(#a)"`, even though this is not the name of the fill in the original svg in the img folder. Maybe that's the reason? That id is then shared by all components on the page?

### Expected behavior

They shouldn't share colors.

### Actual behavior

The fill used across SVGs is the fill of the first SVG used on the page.

### Your environment

- Docusaurus version used: ^3.4.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2024-07-31 15:48
Duplicate of https://github.com/facebook/docusaurus/issues/8297

**Closed by Josh-Cena** 2024-07-31 15:48 UTC
Labels: bug, status: needs triage
