### ISSUE TITLE
Brand new project fails to compile - throws errors

### ISSUE THREAD

**Issue by fuzing** [facebook/docusaurus#8689] opened 2023-02-20 19:19 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Brand new project installed using nodejs v18.7.

Installation and subsequent commands:
```
npx create-docusaurus@latest <project-name> --typescript
cd <project-name>
npm start
```

Results in the following errors:
```
TypeError: /home/Projects/some-project/node_modules/@docusaurus/theme-common/lib/components/Details/index.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
TypeError: /home/Projects/some-project/node_modules/@docusaurus/theme-common/lib/index.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
TypeError: /home/Projects/some-project/node_modules/@docusaurus/theme-common/lib/internal.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
TypeError: /home/Projects/fsome-project/node_modules/@docusaurus/utils-common/lib/index.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
client (webpack 5.75.0) compiled with 4 errors

```

### Steps to reproduce

```
npx create-docusaurus@latest <project-name> --typescript
cd <project-name>
npm start
```

### Expected behavior

Per installation/getting started docs, this should work

### Actual behavior

Throws errors:

```
TypeError: /home/Projects/some-project/node_modules/@docusaurus/theme-common/lib/components/Details/index.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
TypeError: /home/Projects/some-project/node_modules/@docusaurus/theme-common/lib/index.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
TypeError: /home/Projects/some-project/node_modules/@docusaurus/theme-common/lib/internal.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
TypeError: /home/Projects/fsome-project/node_modules/@docusaurus/utils-common/lib/index.js: Cannot read properties of undefined (reading '0')
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
client (webpack 5.75.0) compiled with 4 errors

```

### Your environment

- Public source code: development/private right now
- Public site URL:  development/private right now
- Docusaurus version used: 2.3.1 (latest)
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):  Ubuntu 22.04 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by andysm1th** [comment] 2023-02-20 19:26
I am also experiencing this same problem

**Comment by andysm1th** [comment] 2023-02-20 19:38
This also happens when not using Typescript, so:

`npx create-docusaurus@latest docusaurus-test classic`

I am using Node v18.14.0

I've also tried with the pnpm and yarn package managers, they return the same error as posted above by fuzing.

**Comment by zph** [comment] 2023-02-20 20:12
I'm seeing the same outcome in the following new scenarios:
1. node v19.6.0
2. node v18.14.0
3. Installation failed in same way using `npx create-docusaurus@latest my-website classic` (after the desired project name failed to work), with and without the typescript flag

**Comment by Tandashi** [comment] 2023-02-20 20:33
For Reference / Duplicate of #8688 
Also describes a workaround for the meantime

> Using the `yarn.lock` [of the codesandbox (https://codesandbox.io/p/sandbox/github/facebook/docusaurus/tree/main/examples/classic?file=%2Fyarn.lock)] and installing with `yarn install --force --pure-lockfile` works. Looks like a dependency issue

**Comment by Josh-Cena** [comment] 2023-02-20 20:36
I'm going to close this as a duplicate of https://github.com/facebook/docusaurus/issues/8688

**Closed by Josh-Cena** 2023-02-20 20:36 UTC
Labels: bug, status: needs triage
