### ISSUE TITLE
CSS: [data-theme='dark'] not affects after build

### ISSUE THREAD

**Issue by baur** [facebook/docusaurus#10261] opened 2024-07-03 06:42 UTC
### Description

This CSS works as expected in development mode but does not take effect after building the project:

```css
[data-theme='dark'] {
  .speedSelector {
      background-color: #333; /* Dark theme background color */
      color: #fff; /* Dark theme text color */
      border-color: #666; /* Dark theme border color */
  }

  .speedSelector option:checked {
      background-color: #555; /* Dark theme selected background color */
  }
}
```

Additionally, the following warnings are shown during the build process::

```js
[WARNING] {"file":"assets/css/styles.fa9d63bb.css","message":"assets/css/styles.fa9d63bb.css from Css Minimizer plugin\nUnexpected '}' at assets/css/styles.fa9d63bb.css:25:41240.","compilerPath":"client"}
[WARNING] {"file":"assets/css/styles.fa9d63bb.css","message":"assets/css/styles.fa9d63bb.css from Css Minimizer plugin\nInvalid property name '.speedSelector_lVk0{background-color' at assets/css/styles.fa9d63bb.css:25:41112. Ignoring.","compilerPath":"client"}
[WARNING] {"file":"assets/css/styles.fa9d63bb.css","message":"assets/css/styles.fa9d63bb.css from Css Minimizer plugin\nInvalid selector '}.playerContainer_JoZp' at assets/css/styles.fa9d63bb.css:25:41240. Ignoring.","compilerPath":"client"}
```
### Your environment

- Docusaurus version used: 3.4 
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome, Node v20
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Win10

DEV:

![image](https://github.com/facebook/docusaurus/assets/2898361/3b8fa5cc-dd31-4d45-b0fe-e6ecc49d487c)

![image](https://github.com/facebook/docusaurus/assets/2898361/afd86918-0e15-4568-8db9-2f8ad1311732)

PRD:

![image](https://github.com/facebook/docusaurus/assets/2898361/c4416218-0cc1-4fa6-a7ee-d499eba90b40)

![image](https://github.com/facebook/docusaurus/assets/2898361/6a59832c-1591-4654-9c5e-cc01cc55e633)

**Comment by Josh-Cena** [comment] 2024-07-03 22:56
Duplicate of https://github.com/facebook/docusaurus/issues/9303

**Closed by Josh-Cena** 2024-07-03 22:56 UTC
Labels: bug, status: needs triage
