### ISSUE TITLE
[GitHub Pages Deployment] Client bundle compiled with errors therefore further build is impossible.

### ISSUE THREAD

**Issue by ohitsjudd** [facebook/docusaurus#8148] opened 2022-09-30 06:48 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When deploying to github pages all of a sudden build is failing.
When build started failing it was after pulling in a PR for just 1 .md page
Removed said page and still failed.

Was using yarn, switched to pnpm to see if that would change anything but get the same error

`[INFO] [en] Creating an optimized production build...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
[success] [webpackbar] Client: Compiled with some errors in 25.46s

Error:  Client bundle compiled with errors therefore further build is impossible.
assets/css/styles.c[9](https://github.com/IT-Handbook/kb/actions/runs/3156573210/jobs/5136424105#step:8:10)92ff75.css from Css Minimizer plugin
Error: Call retries were exceeded
assets/css/styles.e0e51a1a.css from Css Minimizer plugin
Error: Call retries were exceeded
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.`

### Steps to reproduce

commit to github pages

### Expected behavior

should build successfully

### Actual behavior

build fails

### Your environment

- Public source code: https://github.com/IT-Handbook/kb
- Public site URL: https://ithandbook.net/
- Docusaurus version used: latest

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by surishubham** [comment] 2022-09-30 07:02
I have added a temporary solution by changing build command

"build": "docusaurus build --no-minify",

but it might effect on page performance

**Comment by ohitsjudd** [comment] 2022-09-30 07:07
> This issue coming from last few hours before that everything was working fine.
> 
> For the time I have added a temporary solution by changing build command
> 
> "build": "docusaurus build --no-minify",
> 
> but it might effect on page performance

Can confirm doing this does build successful now

**Comment by surishubham** [comment] 2022-09-30 07:25
yes, can build without minimize JS/CSS

https://docusaurus.io/docs/cli#options

**Comment by slorber** [comment] 2022-09-30 09:47
Duplicate of https://github.com/facebook/docusaurus/issues/8147

Original issue in third-party dependency: https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/198

Temporary workaround is to pin the dependency to ensure it uses 4.1.0 instead of 4.2.0 (or use --no-minify but not so great)

**Closed** 2022-09-30 09:47 UTC
Labels: bug, status: needs triage
