### ISSUE TITLE
More TOC options (to integrate in-page TOC into the global TOC & make global TOC's top-level items link to article)

### ISSUE THREAD

**Issue by tomchen** [facebook/docusaurus#3815] opened 2020-11-25 11:03 UTC
## 🚀 Features

Options to add:

1. Could there be an option to control whether in-page headings TOC on the right is integrated into the global TOC on the left? [VuePress](https://vuepress.vuejs.org/guide/), [Docsify](https://docsify.js.org/#/quickstart) and [vuejs.org/v2/guide](https://vuejs.org/v2/guide/) put the two TOC together as one.
2. In the global TOC on the left of the page, could we be able to make top-level links (or any parent items) real article links? I mean, for example, on [v2.docusaurus.io/docs](https://v2.docusaurus.io/docs/), visitor clicks "Docusaurus", "Getting Started", "Guides" and "Advanced Guides", the collapsable sublist will show or hide, but the page will not change. However, there could be a scenario where we want to make "Docusaurus", "Getting Started" real article links so that the visitors clicking them will go to another article page. It's just like [gatsbyjs.com/docs](https://www.gatsbyjs.com/docs/).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation, pitch and other comment
These options allow more customization, so users who want to have similar TOC as in those documentation sites and generators I mentioned could do it.

I was about to mention 4 TOC-related options in this proposal/request. Then I found two of them (which I think more crucial than the other two I mentioned above) have already been posted in #2700 and #2220 (both are open).

I think an ideal design is that my proposals 1 and 2 could work together with #2700, #2220 and other existing TOC options, so user could fully control what to include in TOC and where to put them.

For example, my option 1 proposed could make the headache in #2220 less painful. (#2220: in V2, no way to view the in-page headings TOC in mobile screen. There are already a hamburg button for top menu and another hamburg button for global TOC, should we add a third for in-page headings TOC? If we are able to integrate in-page headings TOC into the global TOC (which is my option 1), there will be at most two hamburg buttons. And to add my option 1, it looks like my option 2 will have to be enabled)

Yes, these features will require some work but just put them into the (long-term) to do list maybe.

**Comment by slorber** [comment] 2020-12-29 15:20
Going to close as duplicate of existing issues you mentionned.

Please open issues to discuss a specific problem, and if issues already exist, then add your contribution to the existing issue.

Until we have a better mobile experience, you can use the new inline TOC component to make the TOC available on mobile.

https://v2.docusaurus.io/docs/markdown-features/#inline-table-of-contents

(you can decide yourself if you want to hide it for certain screen widths)

**Closed by slorber** 2020-12-29 15:20 UTC
Labels: feature, needs triage

**Comment by slorber** [comment] 2020-12-29 15:22
Also, you may be looking for sidebar categories as document links, for which there is also a issue: https://github.com/facebook/docusaurus/issues/2643
