### ISSUE TITLE
Usage of polyfill configuration throws error

### ISSUE THREAD

**Issue by jeluard** [facebook/docusaurus#10010] opened 2024-04-03 20:38 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When writing mdx components using external dependencies, it might be necessary to use polyfills. One way to do that is to create a docusaurus plugin leveraging `node-polyfill-webpack-plugin`.
After migrating to docusaurus 3.2 an exception is thrown when building the final website.

Note: it's not clear to me if this is the recommended approach to polyfill node.

### Reproducible demo

https://github.com/jeluard/lodestar/commit/41289518460a460810bf1f04efb76db782705f93

### Steps to reproduce

1. `cd docs` 
2. Run `yarn`
3. Run `yarn build`

### Expected behavior

Compilation should finish and node specifics should be polyfilled.

### Actual behavior

The following error is thrown:

```js
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:53:19)
    at async /Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:64:9
    at async mapAsyncSequential (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
  [cause]: Error: Docusaurus static site generation failed for 1 paths:
  - "/lodestar/"
      at generateStaticFiles (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/ssg.js:85:15)
      at async executeSSG (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:146:23)
      ... 4 lines matching cause stack trace ...
      at async Command.build (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
    [cause]: AggregateError
        at generateStaticFiles (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/ssg.js:86:20)
        at async executeSSG (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:146:23)
        at async buildLocale (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:126:31)
        at async tryToBuildLocale (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:46:13)
        at async /Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:64:9
        at async mapAsyncSequential (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
        at async Command.build (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
      [errors]: [
        Error: Can't render static file for pathname "/lodestar/"
            at generateStaticFile (/Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/@docusaurus/core/lib/ssg.js:119:15)
            at processTicksAndRejections (node:internal/process/task_queues:95:5)
            at runNextTicks (node:internal/process/task_queues:64:3)
            at process.processImmediate (node:internal/timers:449:9)
            at async /Users/julien/Documents/Projects/jeluard/lodestar/docs/node_modules/p-map/index.js:57:22 {
          [cause]: TypeError: Cannot read properties of undefined (reading 'id')
              at DocItem (server.bundle.js:20550:89)
              at Uc (server.bundle.js:32879:44)
              at Xc (server.bundle.js:32881:253)
              at Z (server.bundle.js:32887:89)
              at Xc (server.bundle.js:32885:231)
              at Z (server.bundle.js:32887:89)
              at Xc (server.bundle.js:32881:481)
              at Z (server.bundle.js:32887:89)
              at Vc (server.bundle.js:32879:473)
              at Xc (server.bundle.js:32881:210)
        }
      ]
    }
  }
}
```

Note that with docusaurus `3.1` a different error is [thrown](https://github.com/jeluard/lodestar/actions/runs/8537178685/job/23387215954#step:12:33).

### Your environment

- Public source code: https://github.com/jeluard/lodestar/
- Docusaurus version used: 3.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node 20
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): OSX

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-04-04 09:36
Hi

> When writing mdx components using external dependencies, it might be necessary to use polyfills. 

I'm not sure to follow, why exactly? How is this different from using external dependencies in React page components? How are external dependencies requiring a node polyfill different from first-party code you write that requires the exact same polyfill?

> After migrating to docusaurus 3.2 an exception is thrown when building the final website.

> Note that with docusaurus 3.1 a different error is [thrown](https://github.com/jeluard/lodestar/actions/runs/8537178685/job/23387215954#step:12:33).

It's not clear from which version you are upgrading exactly. If it didn't work before, then how can we consider the new v3.2 breaks things?

---

> [jeluard/lodestar@jeluard/docusaurus-lc](https://github.com/jeluard/lodestar/tree/jeluard/docusaurus-lc?rgh-link-date=2024-04-03T20%3A38%3A49Z)

This repro is not very actionable from my perspective. I can't investigate your monorepo in its entirety to look for problems because it's not minimal and many things on it could be the source of problems (for example, a dependency/hoisting problem related to the package manager)

Please create a **minimal** repro using https://docusaurus.new/stackblitz

I need to see a minimal project that works on a specific version before the upgrade, despite including a lib requiring polyfill. And I need to see it failing after the upgrade.

**Comment by jeluard** [comment] 2024-04-04 10:04
> I'm not sure to follow, why exactly? How is this different from using external dependencies in React page components? How are external dependencies requiring a node polyfill different from first-party code you write that requires the exact same polyfill?

What is different is the way things are configured in docusaurus. How can I tweak webpack's configuration in docusaurus? 

> I need to see a minimal project that works on a specific version before the upgrade, despite including a lib requiring polyfill. And I need to see it failing after the upgrade.

I can look at providing a minimal reproducing issue definitely. What is the recommended approach to hook polyfill, if any? 
If I don't provide any polyfill, an error very similar to [this one](https://stackoverflow.com/questions/66255566/webpack-5-receiving-a-polyfill-error-my-javascript-react-project-is-receivin) is thrown by webpack.

Note that in dev mode (i.e. `docusaurus start`), everything works as expected with my current approach. It only fail when building (via `docusaurus build`).

**Comment by slorber** [comment] 2024-04-04 11:11
> > I'm not sure to follow, why exactly? How is this different from using external dependencies in React page components? How are external dependencies requiring a node polyfill different from first-party code you write that requires the exact same polyfill?
> 
> What is different is the way things are configured in docusaurus. How can I tweak webpack's configuration in docusaurus?

https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#configureWebpack

> 
> > I need to see a minimal project that works on a specific version before the upgrade, despite including a lib requiring polyfill. And I need to see it failing after the upgrade.
> 
> I can look at providing a minimal reproducing issue definitely. 

That would help me help you 👍 

> What is the recommended approach to hook polyfill, if any? If I don't provide any polyfill, an error very similar to [this one](https://stackoverflow.com/questions/66255566/webpack-5-receiving-a-polyfill-error-my-javascript-react-project-is-receivin) is thrown by webpack.

"very similar" does not help. If you have an error, please share it exactly as is.

We don't have a recommended approach for now, because most sites don't need it and this is not different from any other Webpack app. If you can make it work outside Docusaurus, you can probably make it work similarly inside. 


I still don't even know what contains your code to require such polyfill.

None of the 2 reported errors in this issue (v3.1 or v3.2) look related to polyfills.


> Note that in dev mode (i.e. `docusaurus start`), everything works as expected with my current approach. It only fail when building (via `docusaurus build`).

Probably because the problem is due to using browser APIs in Node.js, which is likely not a polyfill issue. I will only be able to help if I see a minimal repro.

**Comment by jeluard** [comment] 2024-04-04 12:01
You can find a minimal repository [here](https://github.com/jeluard/docusaurus-polyfills). First commit just uses the lib w/o polyfill, then the second adds a polyfill.

> https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#configureWebpack

This is what I did [here](https://github.com/jeluard/lodestar/commit/41289518460a460810bf1f04efb76db782705f93#diff-c10fe356f270a677c210ad5b37cbc382ff475adf37a365616160a383d42b5d02) by providing a plugin, so I would assume that this is the right approach.

> I still don't even know what contains your code to require such polyfill.

Some libraries relies on node code (e.g. `path`, `Buffer` or `crypto`) and expect polyfills to run in a browser.

> Probably because the problem is due to using browser APIs in Node.js, which is likely not a polyfill issue. I will only be able to help if I see a minimal repro.

That's the other way around, those libs use node APIs e.f. [crypto](https://nodejs.org/api/crypto.html) or [path](https://nodejs.org/api/path.html). Historically [browserify](https://github.com/browserify/path-browserify) or [others](https://github.com/feross/buffer) have been used to address that.

I've seen a number of workaround in the wild, so looks like others people have those needs:

* https://gist.github.com/sibelius/24f63eef7f43b15dc73c4a0be11bbef8
* https://gist.github.com/rohit-gohri/59d0e6a9b4f51d1dd39f5e8894050f74
* https://github.com/JayaKrishnaNamburu/docusaurus-node-polyfills

**Comment by slorber** [comment] 2024-04-04 18:14
You are using this component inside your homepage:

`<LatestOptimisticHeader>`

```ts
import {useEffect, useState} from "react";
import {getClient} from "@lodestar/api";
import {createChainForkConfig} from "@lodestar/config";
import {networksChainConfig} from "@lodestar/config/networks";

import {Lightclient, LightclientEvent} from "@lodestar/light-client";
import {LightClientRestTransport} from "@lodestar/light-client/transport";
import {getFinalizedSyncCheckpoint, getGenesisData, getLcLoggerConsole} from "@lodestar/light-client/utils";

const config = createChainForkConfig(networksChainConfig.mainnet);
const logger = getLcLoggerConsole({logDebug: true});
const api = getClient({urls: ["https://lodestar-mainnet.chainsafe.io"]}, {config});

const lightclient = await Lightclient.initializeFromCheckpointRoot({
  config,
  logger,
  transport: new LightClientRestTransport(api),
  genesisData: await getGenesisData(api),
  checkpointRoot: await getFinalizedSyncCheckpoint(api),
  opts: {
    allowForcedUpdates: true,
    updateHeadersOnForcedUpdate: true,
  },
});

await lightclient.start();

export function LatestOptimisticHeader(): React.JSX.Element {
  const [head, setHead] = useState<string | undefined>();
  const [updated, setUpdated] = useState<boolean>(false);
  useEffect(() => {
    lightclient.emitter.on(LightclientEvent.lightClientOptimisticHeader, (optimisticUpdate) => {
      setHead(optimisticUpdate.beacon.slot.toString());
      setUpdated(true);
      setTimeout(() => setUpdated(false), 1000);
    });
  }, []);
  return (
    <span>
      Latest optimistic header: <span className={updated ? "highlight" : ""}>{head}</span>
    </span>
  );
}
```

Again, this is not minimal at all. You are expecting me to retro-engineer your code.

This has never worked in Docusaurus, not in v3.2 or any previous versions, simply because we don't support ESM and top-level await.

I'm closing because I doubt there is a bug in Docusaurus. We'll re-open when a truly minimal repro is provided, not involving the complexity of your custom dependencies and the code above which can't work.

**Closed by slorber** 2024-04-04 18:14 UTC
Labels: bug
