### ISSUE TITLE
Python syntax highlighting in a code block is inconsistent (again)

### ISSUE THREAD

**Issue by omry** [facebook/docusaurus#3004] opened 2020-06-27 02:03 UTC
## 🐛 Bug Report

Python syntax highlighting in a code block is inconsistent.
If this looks familiar, it's because it's just like #2655 (regression).

## To Reproduce
Add this block:
```python
@dataclass
class MySQLConfig:
    host: str = "localhost"
    port: int = 3306

@dataclass
class Config:
    db: MySQLConfig = MySQLConfig()
    verbose: bool = True

cfg_store = ConfigStore.instance()
cfg_store.store(name="config", node=MyConfig)

@hydra.main(config_name="config")
def my_app(cfg: MyConfig) -> None:
    # Python knows that the type of cfg.db is MySQLConfig without any additional hints
    print(f"Host: {cfg.db.host}, port: {cfg.db.port}")

if __name__ == "__main__":
    my_app()
```

## Expected behavior
Syntax highlighting is applied consistently.

## Actual Behavior
See screen shot, only the first @dataclass annotation is highlighted.

![image](https://user-images.githubusercontent.com/376455/85912193-92667680-b7df-11ea-80b8-798792836d28.png)

## Your Environment
Ubuntu 18.

- Docusaurus version used:
[package.json](http://paste.ubuntu.com/p/8wx6cdPMF9/)

**Comment by slorber** [comment] 2020-06-29 12:53
Hi,

Unfortunately, this is a bug in an underlying library (prism / react-prism-renderer), not really Docusaurus itself. 

We don't really work on syntax highlighting in this repo, and can't ensure that underlying libs are able to highlight correctly all the existing languages correctly. These kind of bugs should rather be isolated and reported https://github.com/FormidableLabs/prism-react-renderer instead

But on Docusaurus 2 website / master (alpha 58), I'm able to get this output, so I can't reproduce:

![image](https://user-images.githubusercontent.com/749374/86007516-ccba5880-ba17-11ea-84ea-9a18f673f3a1.png)

If you share a repro, it might be easier to see if we can do something.

**Comment by slorber** [comment] 2020-06-29 12:56
according to the PR:

> After that, Python decorator highlighting works fine (although this is not supported by all themes), and then Palenight theme now has diff syntax support.

Have you tried using the default theme?

**Comment by omry** [comment] 2020-06-29 16:13
@slorber  : 
It's a bug in a dependency. the previous issue I was linking too had the same issue and it was resolved (see the comments there).

Your screen shot is does not highlight the @dataclass decorator, so while consistent it shows a different bug.

I am using the default theme, where did you get the comment about Palenight (never heard of it before).

**Comment by omry** [comment] 2020-06-29 16:26
I tried 58, but it blows up when I start:
I checked the release notes and did not see anything about sidebar changes in the breaking list.
```
$ docusaurus start
Starting the development server...
TypeError: sidebarItems is not iterable
    at getFirstDocLinkOfSidebar (/home/omry/dev/hydra/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:42:29)
    at Object.contentLoaded (/home/omry/dev/hydra/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:298:23)
    at /home/omry/dev/hydra/website/node_modules/@docusaurus/core/lib/server/plugins/index.js:74:22
    at Array.map (<anonymous>)
    at Object.loadPlugins (/home/omry/dev/hydra/website/node_modules/@docusaurus/core/lib/server/plugins/index.js:60:31)
    at async Object.load (/home/omry/dev/hydra/website/node_modules/@docusaurus/core/lib/server/index.js:57:46)
    at async start (/home/omry/dev/hydra/website/node_modules/@docusaurus/core/lib/commands/start.js:45:19)

```

**Comment by omry** [comment] 2020-06-29 16:29
You can repro by checking out https://github.com/facebookresearch/hydra and running the website.

Example with inconsistent highlight:
https://hydra.cc/docs/next/tutorials/structured_config/nesting

Example with no highlight:
https://hydra.cc/docs/next/tutorials/structured_config/minimal_example

**Comment by slorber** [comment] 2020-06-29 16:51
@omry the quote about theme palenight is actually from the pr you linked :)

The D2 website is using:

```
    prism: {
      theme: require('prism-react-renderer/themes/github'),
      darkTheme: require('prism-react-renderer/themes/dracula'),
    },
```

What I can see is that the classes on the decorator tokens are set correctly, it's just that D2 themes do not style decorators in a decent color.

![image](https://user-images.githubusercontent.com/749374/86033572-6e05d680-ba39-11ea-84a0-77ab2a916f4c.png)

![image](https://user-images.githubusercontent.com/749374/86033595-7827d500-ba39-11ea-8e5b-02d6d1b1875a.png)

--- 

Will try to see why you can't upgrade, this error is related to new code added recently so it might have a bug.

**Comment by omry** [comment] 2020-06-29 17:03
Thanks for the info.
I linked to an issue, and I can't find penlight there. I am using the standard theme in my website.

Please let me know if there is anything I should do on my end to fix the decorators issue or if I should just wait for a future version.

**Comment by slorber** [comment] 2020-06-29 17:49
I've made a PR to your repo: https://github.com/facebookresearch/hydra/pull/730

And opened an issue on prism-react-render, not sure what's happening exactly: https://github.com/FormidableLabs/prism-react-renderer/issues/87

**Comment by lex111** [comment] 2021-06-10 09:47
It seems that this is no longer relevant, so I'm closing this issue.

**Closed by lex111** 2021-06-10 09:47 UTC
Labels: bug, needs triage
