### ISSUE TITLE
need hot reload md

### ISSUE THREAD

**Issue by wulucxy** [facebook/Docusaurus#367] opened 2018-01-03 03:36 UTC
### Is this a bug report?

no

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

yes

### Environment

(OS, Node, npm, yarn)

### Steps to Reproduce

(Write your steps here:)

1. when I edit the md docs，I have to reload the page to see what i have changed, it is not very pleasant experience。so hmr can help a lot。
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots, if applicable.)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by JoelMarcey** [comment] 2018-02-27 03:38
@wulucxy Hi. So this is different than having to restart the local server (which in some cases you have to do) -- you just want the page to refresh itself periodically without having to press `cmd-R` or equivalent. We could do some time-based polling maybe.

**Comment by JoelMarcey** [comment] 2018-02-28 22:28
This is a duplicate of #234, so let's use that as the canonical issue.

**Closed by JoelMarcey** 2018-02-28 22:28 UTC
Labels: difficulty: advanced, feature request, mentorship
