### ISSUE TITLE
"author_image_url" must be a valid uri

### ISSUE THREAD

**Issue by SebDanielsson** [facebook/docusaurus#5011] opened 2021-06-18 20:27 UTC
After upgrading to beta 1 I get the following message:
```
22:24:03.735 | {
22:24:03.735 | "slug": "nitmod-2.3.4-b4",
22:24:03.735 | "title": "N!tmod 2.3.4 Beta 4",
22:24:03.735 | "author": "N!trox*",
22:24:03.735 | "author_title": "Founder",
22:24:03.735 | "author_image_url": "/img/nitmod-square.webp",
22:24:03.735 | "tags": [
22:24:03.735 | "nitmod",
22:24:03.735 | "release",
22:24:03.736 | "beta",
22:24:03.736 | "changelog"
22:24:03.736 | ]
22:24:03.736 | }
22:24:03.736 | contains invalid values for field(s): author_image_url.
22:24:03.736 | - "author_image_url" must be a valid uri
22:24:03.736 | Processing of blog source file failed for path "2021-06-12-nitmod-2.3.4-b4.md"
22:24:03.736 | Unable to build website for locale "en".
22:24:03.736 | ValidationError: "author_image_url" must be a valid uri
```

Worked perfectly in the beta 0 and the image showed up properly.

**Comment by slorber** [comment] 2021-06-21 17:23
Thanks, we'll fix asap.

Closing as duplicate of https://github.com/facebook/docusaurus/issues/5012

**Closed by slorber** 2021-06-21 17:23 UTC
Labels: bug, needs triage
