### ISSUE TITLE
Unable to add icons to the navbar

### ISSUE THREAD

**Issue by PatelN123** [facebook/docusaurus#6418] opened 2022-01-20 09:04 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Adding svg's to the Navbar does not work, if I input it using the character svg method, that works. 

You may see here: https://github.com/PatelN123/Digital-Support-Notes/pull/102
The first commit is with the .svg and second with the .png

Both times, it failed in some way

 @Josh-Cena Requested I open a bug report for this, not sure how to better explain it. 

### Steps to reproduce

1. Clone the repo: https://github.com/PatelN123/Digital-Support-Notes
2. Try to add an image to the navbar
3. yarn build

### Expected behavior

Add the icon to the navbar

### Actual behavior

A white space shows, with no image. 

### Your environment

- Public source code: https://notes.nayanpatel.net/
- Public site URL:  https://github.com/PatelN123/Digital-Support-Notes
- Docusaurus version used: Canary

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-01-20 09:06
Duplicate of #6408. I have told you on Discord...

**Closed by Josh-Cena** 2022-01-20 09:06 UTC
Labels: bug, status: needs triage
