### ISSUE TITLE
Support Relative Path

### ISSUE THREAD

**Issue by huchenme** [facebook/docusaurus#448] opened 2018-02-13 05:05 UTC
Docusaurus expect `baseUrl` to be absolute path, to use relative path, I have tried to put `baseUrl=''` and it does not work for `docs` link and generated build.

It will be nice that Docusaurus support relative mode as well

**Comment by JoelMarcey** [comment] 2018-02-27 00:32
@huchenme Hi. What error do you get when you use `baseUrl = ''`? Do you get the same thing if you use `baseUrl='/'`?

**Comment by huchenme** [comment] 2018-02-27 07:36
@JoelMarcey after running `build` command, css path and docs path not working

**Comment by JoelMarcey** [comment] 2018-02-28 05:27
@huchenme Hi. Do you have a repo I can look at to see your `siteConfig.js`? Thanks!

**Comment by huchenme** [comment] 2018-02-28 13:59
Hi @JoelMarcey , I have just created this repo https://github.com/huchenme/docusaurus-demo

It is generated from `docusaurus-init` and changed the baseUrl to "", you could cd into website and try

```
yarn start
```

and click [Docs header](http://localhost:3000/docs/doc1.html), you should able to see the error.

and then try run `docusaurus build` and open generated index.html, click the Docs header again, the css is not rendered correctly

**Comment by jacarma** [comment] 2018-04-16 12:00
I think this is the same feature request: "Make the built site work without a web server"
Acceptance criteria:
`yarn build`
open `file://{PATH}/website/build/{projectName}/index.html` in a browser

Expected behaviour: You can navigate through pages and docs and links work

**Comment by stoffeastrom** [comment] 2018-04-22 19:43
It would be really nice if this was supported. I just save my build artifacts on circle ci but the site will not work since it doesn't handle relative `baseUrl` e.g `./`

Problems seem to be that in the generated html files css and images are referenced as 

`./css/main.css`
`./img/some-image.png`

when it should have been

`../css/main.css`
`../img/some-image.png`

since they are relative to their html file.

Using the `./css/main.css` will be relative to web server root

**Comment by kevinbarabash** [comment] 2018-07-29 17:57
The problem I ran into was I want to deploy to docs to both `khan.github.io/KaTeX` (for production) as well as `katex.netlify.com` (for testing).

**Comment by lwasylow** [comment] 2018-08-06 12:24
Would be great feature as its quite painful to review build on local machine

**Comment by olafurpg** [comment] 2018-09-03 08:57
This would be a nice feature addition. It would enable users to download an offline zip of the website, open `index.html` and everything works without a server. Another use-case is that it becomes possible to serve the same generated site from different base URLs.

For example, I'm using docusaurus for documenting Scala projects https://olafurpg.github.io/sbt-docusaurus/ I also release the documentation as a zip file to Maven Central (similar to npm) and it's possible to browse those docs and download offline archives via https://www.javadoc.io/. Currently, the css/js/html artifact links return 404s when browsing sbt-docusaurus docs on https://static.javadoc.io/com.geirsson/sbt-docusaurus-docs_2.12/0.1.1/sbt-docusaurus/docs/installation.html I could work around this problem by generating the site with baseUrl `com.geirsson/sbt-docusaurus-docs_2.12/0.1.1/sbt-docusaurus/` but then the site would not work anywhere else.

**Comment by olafurpg** [comment] 2018-09-08 22:27
A workaround for this issue is to post-process the anchor links in the html files generated by `yarn run build`. I wrote a simple transformation in Scala using Jsoup that does a few things (actual [code](https://github.com/olafurpg/sbt-docusaurus/blob/0130fe2ee4918b3bdd90944f6fa767c37d3035f1/plugin/src/main/scala/sbtdocusaurus/internal/Relativize.scala) and [test suite](https://github.com/olafurpg/sbt-docusaurus/blob/0130fe2ee4918b3bdd90944f6fa767c37d3035f1/plugin/src/test/scala/tests/RelativizeSuite.scala))

- convert `/absolute/path/page.html` links to `../relative/page.html` links
- process `<a href`, `<img src` and `<link href` (I'm probably missing some other cases, but this was enough on my small sample)
- prefix `//example.com` with `https:` to prevent such links from resolving as `file://example.com` when browsing plain html files without a server
- append `/index.html` to directory links

None of these transformations are Docusaurus-specific, they can be applied to any static site. I would not be surprised if there already exists a JavaScript library that can do this (more robustly than me 😅 ). The benefit of relative links is that
- the site can be browsed by opening `index.html` without a file server, which is especially handy if you distribute zip archives of the site for offline browsing.
- the site can hosted at any base url such as on static.javadoc.io for Java/Scala libraries https://static.javadoc.io/com.geirsson/sbt-docusaurus-docs_2.12/0.3.1/sbt-docusaurus/index.html

**Comment by tibdex** [comment] 2018-12-07 22:48
It would be great to support relative paths in a future release.

In the meantime, here's how you can transform absolute links to relative ones in a postbuild script:

```js
// utils.js
const fs = require('fs-extra');

const baseUrlPattern = '/_baseUrlPattern_/';
const baseUrlRegExp = new RegExp(baseUrlPattern, 'g');

const relativify = (content, filePath) =>
  content.replace(baseUrlRegExp, () => {
    const result = `${path.relative(`${path.dirname(filePath)}`, '')
      // Normalize Windows path to Unix ones
      .replace(/\\/g, '/')}/`;
    return result === '/' ? '' : result;
  });

const websiteTextualFileExtensions = ['.css', '.js', '.html', '.xml'];

const isNotWebsiteTextualFile = (filePath, stats) =>
  !(stats.isDirectory() || websiteFileTextualExtensions.includes(path.extname(filePath))));

const postProcess = async () => {
  const buildPath = path.join(__dirname, 'build');
  const tmpPath = await fs.mkdtemp(path.join(os.tmpdir(), 'docs-'));
  await fs.copy(buildPath, tmpPath);
  const filePaths = await recursiveReaddir(tmpPath, [isNotWebsiteTextualFile]);
  await Promise.all(
    filePaths.map(async filePath => {
      const content = await fs.readFile(filePath);
      const relativePath = path.relative(tmpPath, filePath);
      await fs.writeFile(filePath, relativify(String(content), relativePath));
    })
  );
  await fs.copy(tmpPath, buildPath);
};

module.exports = {
  baseUrlPattern,
  postProcess,
};
```

```js
// siteConfig.js
const {baseUrlPattern} = require('./utils');

const isBuilding = process.env.npm_lifecycle_script
  && process.env.npm_lifecycle_script === 'docusaurus-build'; 

const siteConfig = {
  // Keep `/` in watch mode.
  baseUrl: isBuilding ? baseUrlPattern : '/',
  // ...
};

module.exports = siteConfig;
```

```js
// postprocess.js
'use strict';

require('loud-rejection/register');

const {postProcess} = require('./utils');

postProcess();
```

```json
// package.json
{
  "devDependencies": {
    "docusaurus": "1.6.2"
  },
  "scripts": {
    "build": "docusaurus-build",
    "postbuild": "node postprocess"
  }
}
```

**Comment by amimas** [comment] 2019-02-11 16:16
Any update available on this item? This would allow me to have a review site deployed very easily. I can deploy the site in a different path other than what's mentioned in `baseUrl` but all the generated links are set to absolute path.

**Comment by amimas** [comment] 2019-02-11 19:46
@JoelMarcey @yangshun - Would you be able to provide some feedback? If I can I'd love to look into implementing this and submit a PR for it.

**Comment by yangshun** [comment] 2019-02-12 03:17
@amimas Sure, go ahead 😄

**Comment by amimas** [comment] 2019-02-12 18:22
Any guidance available? I'm new to this and not really sure where to begin.

**Comment by endiliey** [comment] 2019-07-18 05:27
I think at this point our architecture relies a lot on baseUrl and supporting this will be quite a huge refactor. I personally feel the effort is better spent elsewhere

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2019-07-18 05:27 UTC
Labels: feature request, wontfix

**Comment by divinekiatan** [comment] 2019-12-10 08:39
Any updates on this? I am trying to open the files without hosting.

**Comment by endiliey** [comment] 2019-12-10 10:39
Just for the sake of people who revisit this issue in the future requesting “build artifacts without a web server”, here is my opinion.

I dont think its a good idea to support serving files without a webserver. At least from my point of view it causes lot more problems than bringing benefit. 

It got to do with the protocol used to access the files. When you request anything over the web you're using http, and the server level security is enough to ensure you can only access files you're meant to. But when you drag a file in it's loaded via the local file system (technically file://) and that is massively restricted, for obvious reasons. Under file:// there's no concept of domains, no server level security, just a raw file system.

Ask yourself this: do you really want JavaScript to have the ability to load files from anywhere on your local file system?
Your immediate answer should of course be "not in a million years!". If JavaScript had free reign while operating under file:// there would be nothing stopping it loading pretty much any file, and sending it off who knows where.

Your site is going to need to load resources: images, JSON data, maybe other JavaScript files. And in order to do this it needs to run unhindered by the browser security shackles. It needs http:// access to the files. And for that we need a web server.

I remember https://blog.chromium.org/2008/12/security-in-depth-local-web-pages.html?m=1. explained this security loophole really well

**Comment by jacarma** [comment] 2020-04-16 09:09
I agree with you @endiliey, I wanted to provide an easy way to check the requirement is complete, it's not that I use it with file://  

We generate the documentation site as an artifact on the CI and it stores and serves it for us. The builds have auto-generated ids so we don't know the final url in advance.
It's a nice feature for us to be able to check the docs in past versions and it would be great to publish them too for our users to check what's supported on each version.
We can do that by knowing the final url in advance and changing the baseurl as part of the build, but we can't make the built site to work both in the CI and the public site.

Of course you know where to put the effort, thanks a lot for the great work :D

**Comment by olafurpg** [comment] 2020-04-16 13:12
To echo @jacarma 's comment, our primary use-case is also to host Docusaurus sites at URLs we don't know in advance. For example, here is a 3rdparty service that is hosting our Docusaurus documentation for every published version of a library we maintain https://www.javadoc.io/doc/org.scalameta/munit-docs_2.12/0.4.3/index.html

**Comment by atilkan** [comment] 2020-04-16 18:00
@endiliey That is your view based on 12 years old article and a couple false information.

**Comment by tiptronic** [comment] 2020-04-16 23:37
@endiliey Sorry - the whole security in a browser is about running a browser safely on a local machine AND on the web. This is how browsers worked since they were invented. 
And since Flash is dead, there's no risk at all to run under the file:// protocol... that's why browser-security is there. 
For the link, I agree with @atilkan

**Comment by JoelMarcey** [comment] 2020-04-17 02:15
All - I find it surreal that I was looking at this closed issue less than 24 hours ago and all of a sudden it started gaining traction with comments again.

That said, I just want you to be aware, in case you didn't know, that @endiliey passed away this past early this year after a long battle with cancer. https://docusaurus.io/blog/2020/01/07/tribute-to-endi

**Comment by tiptronic** [comment] 2020-04-17 07:03
@JoelMarcey That's *really, really* sad to read... :(

**Comment by atilkan** [comment] 2020-04-17 09:04
RIP.

**Comment by jacarma** [comment] 2020-04-23 05:01
My most sincere condolences

**Comment by roguexz** [comment] 2021-06-15 23:04
My condolences to Endi's family and friends.

Given that this is still a very valuable feature, do the new maintainers have any plans for it?

**Comment by roguexz** [comment] 2021-06-15 23:07
@tibdex - Your solution is quite elegant and works for the most part of it. However the webpack script in `runtime~main` goes for a toss. Any ideas?

**Comment by ohkimur** [comment] 2021-08-30 23:29
I improved @tibdex approach by resolving all nested paths in a single `postprocess` script. Also, this approach is more generic, so it captures the majority of cases (tested on production 😎).

@roguexz I think this approach should also work fine with Webpack too, but I didn't manage to test it yet. ✌️

```js
// postprocess.js

'use strict';

const fs = require('fs-extra');
const path = require('path');
const recursiveReaddir = require('recursive-readdir');

const buildDirectory = path.join(__dirname, 'build');
const absoluteUrlRegExp = /(href|src)="(?!http[s]|ftp?:\/\/)([^"|#]+)"/g;

const isDirectory = dirPath => path.extname(dirPath) === '';

const convertAbsolutePathsToRelative = (content, filePath) =>
  content.replace(absoluteUrlRegExp, (_absoluteUrl, $1, $2) => {
    const currentDirPath = path.dirname(filePath);
    const relativeDirPath = currentDirPath === '.' ? '.' : path.relative(currentDirPath, '');

    let relativePath = path.join(relativeDirPath, $2);
    if (isDirectory(relativePath)) {
      relativePath = path.join(relativePath, 'index.html');
    }

    return `${$1}="${relativePath}"`;
  });

const websiteTextualFileExtensions = ['.css', '.js', '.html', '.xml'];
const isNotWebsiteTextualFile = (filePath, stats) =>
  !(stats.isDirectory() || websiteTextualFileExtensions.includes(path.extname(filePath)));

const postProcess = async () => {
  const filePaths = await recursiveReaddir(buildDirectory, [isNotWebsiteTextualFile]);
  await Promise.all(
    filePaths.map(async filePath => {
      const content = await fs.readFile(filePath);
      const relativePath = path.relative(buildDirectory, filePath);
      await fs.writeFile(filePath, convertAbsolutePathsToRelative(String(content), relativePath));
    })
  );
};

postProcess();
```

```json
// package.json
{
  "scripts": {
    "build": "docusaurus build",
    "postbuild": "node postprocess"
  },
  "devDependencies": {
    "@docusaurus/core": "^2.0.0-beta.5"
  }
}
```

**Comment by slorber** [comment] 2021-08-31 08:28
Everyone, this is a quite old issue that was first opened for Docusaurus v1.

For deploying Docusaurus v2 site to multiple environments with different baseUrls, please use `baseUrl: process.env.BASE_URL` and provide the appropriate baseUrl as an explicit environment variable.

For deploying a Docusaurus v2 site without a server, using the `file://` protocol, let's track this here: https://github.com/facebook/docusaurus/issues/3825

**Comment by pavelloz** [comment] 2021-11-01 01:40
Since we are slowly approaching the holy grail I will add my 2 cents.
It would be great to have possibility of setting baseUrl (the part that is used in javascript) during runtime just like [webpack does it](https://webpack.js.org/guides/public-path/#on-the-fly). 
It helps a lot people that use CDNs (ie. website is https://example.com and stores assets on CF @ sha.cloudfront.net)  

Its possible that it would require splitting it into two variables (one for site url, one for assets url), but from my experience with static site generators, cdns, documentations, it is a great feature that makes docs developers life easier.

**Comment by larissa-n** [comment] 2022-01-05 12:14
@ohkimur: Thanks for the plugin! Script references stilll need adjusted, those may require `./` vs. `/` for relative paths (script references remain absolute with the [plugin](https://github.com/ohkimur/docusaurus-plugin-relative-paths) as it is).

@slorber: Where would you enter `process.env.BASE_URL`? If you tried in docusaurus.config.js, build fails with `Error: "baseUrl" is required`.

**Comment by slorber** [comment] 2022-01-05 12:55
You have to set it as an env variable outside of docusaurus, in your CI/CD config, in your bashrc or when running CLI commands like `BASE_UTL=xyz yarn start`

**Comment by larissa-n** [comment] 2022-01-05 13:28
Thank you, that makes sense. So this approach would not fill in the final filesystem location once the build is deployed, but it can be used if the final destination is known in advance.

When a build needs to be deployed locally, I could see the compiled files reference a location variable like window.location (or, in the case of electron, a process variable) that's unique to each machine and fill in baseUrl that way. But those won't be defined during the compilation step, so they would somewhat have to be added (and tested) separately.

**Comment by ohkimur** [comment] 2022-01-06 15:23
@larissa-n @slorber I know about this issue. It's quite clear for me at the moment how to replace the paths in scrips in an elegant way, that's why I didn't fixed this problem yet. If you have any suggestions I am open.

**Comment by anthonyborell** [comment] 2022-01-20 06:11
@ohkimur Thank you for posting your example code, helped me out greatly. Real shame docusaurus isn't focused on issues like this one. Seems to be a really common feature people are after.

**Comment by ColinLondon** [comment] 2024-02-16 13:52
> I improved @tibdex approach by resolving all nested paths in a single `postprocess` script. Also, this approach is more generic, so it captures the majority of cases (tested in production 😎).
> 
> @roguexz I think this approach should also work fine with Webpack too, but I didn't manage to test it yet. ✌️
> 
> ```js
> // postprocess.js
> 
> 'use strict';
> 
> const fs = require('fs-extra');
> const path = require('path');
> const recursiveReaddir = require('recursive-readdir');
> 
> const buildDirectory = path.join(__dirname, 'build');
> const absoluteUrlRegExp = /(href|src)="(?!http[s]|ftp?:\/\/)([^"|#]+)"/g;
> 
> const isDirectory = dirPath => path.extname(dirPath) === '';
> 
> const convertAbsolutePathsToRelative = (content, filePath) =>
>   content.replace(absoluteUrlRegExp, (_absoluteUrl, $1, $2) => {
>     const currentDirPath = path.dirname(filePath);
>     const relativeDirPath = currentDirPath === '.' ? '.' : path.relative(currentDirPath, '');
> 
>     let relativePath = path.join(relativeDirPath, $2);
>     if (isDirectory(relativePath)) {
>       relativePath = path.join(relativePath, 'index.html');
>     }
> 
>     return `${$1}="${relativePath}"`;
>   });
> 
> const websiteTextualFileExtensions = ['.css', '.js', '.html', '.xml'];
> const isNotWebsiteTextualFile = (filePath, stats) =>
>   !(stats.isDirectory() || websiteTextualFileExtensions.includes(path.extname(filePath)));
> 
> const postProcess = async () => {
>   const filePaths = await recursiveReaddir(buildDirectory, [isNotWebsiteTextualFile]);
>   await Promise.all(
>     filePaths.map(async filePath => {
>       const content = await fs.readFile(filePath);
>       const relativePath = path.relative(buildDirectory, filePath);
>       await fs.writeFile(filePath, convertAbsolutePathsToRelative(String(content), relativePath));
>     })
>   );
> };
> 
> postProcess();
> ```
> 
> ```json
> // package.json
> {
>   "scripts": {
>     "build": "docusaurus build",
>     "postbuild": "node postprocess"
>   },
>   "devDependencies": {
>     "@docusaurus/core": "^2.0.0-beta.5"
>   }
> }
> ```

This works superbly, but for one thing. It doesn't support mode switching (I get the disabled icon). But if I copy the build to a test server, mode switching works.

Cheers.

**Comment by slorber** [comment] 2024-02-19 13:57
Please note this issue was initilly opened for Docusaurus v1 in 2018. Since then, Docusaurus v2 has been released. It's a full rewrite and has nothing to do with the v1 codebase.

Mixing comments for Docusauru v1 and Docusaurus v2 here is confusing so I'm going to lock this issue. 

There are other Docusaurus v2+ issues to comment on now, like this one: https://github.com/facebook/docusaurus/issues/3825

If being able to browser a Docusaurus v2 site offline with the  `file://` protocol is not related to your use case, please open a brand new issue explaining your use case.

---

> This works superbly, but for one thing. It doesn't support mode switching (I get the disabled icon). But if I copy the build to a test server, mode switching works.

@ColinLondon this probably doesn't work as well as you think.

If the theme switch is disabled it likely means React couldn't hydrate on your page, and thus all interactive elements will not work. 

These things are all likely to be broken:
- Mobile drawer button
- Category collapsible button
- Search
- Theme switch
- Tabs
- All the interactive React components you embed in your MDX docs

So... no this is not a good solution, unless you are ok with the tradeoffs of having all these elements not working...
