### ISSUE TITLE
Broken link found where it should not on relative (same folder) link

### ISSUE THREAD

**Issue by axel7083** [facebook/docusaurus#9876] opened 2024-02-21 15:37 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

## Error message got

```
  Exhaustive list of all broken links found:
  - Broken link on source page path = /api/interfaces/EndpointSettings:
     -> linking to EndpointIPAMConfig.md (resolved as: /api/interfaces/EndpointIPAMConfig.md)
```

Let's break it down. On page `/api/interfaces/EndpointSettings` specifically, let's find the link to the `EndpointIPAMConfig.md` file.
- Here is the _broken link_ : `[EndpointIPAMConfig](EndpointIPAMConfig.md)`

> It is using relative link, and have the `.md` suffix. (just like many other links in the same folder)

- [x] EndpointIPAMConfig.md and EndpointIPAMConfig.md are in the same folders.

## Debugging the issue.

Let's run the debugger for the building process. I added some breakpoints in the `handleBrokenLinks`.

Inside the `isPathBrokenLink` we got the following, when we reached `linkPath === {
  "pathname": "/api/interfaces/EndpointIPAMConfig.md"
}`

<img width="1099" alt="image" src="https://github.com/facebook/docusaurus/assets/42176370/e7fc48a4-4b9c-40cc-be7a-bfde8bdf0802">

Let's evaluate the `validPathnames` (used for optimizations)

| with `.md` | without |
| --- | --- |
| <img width="438" alt="image" src="https://github.com/facebook/docusaurus/assets/42176370/9e66dc82-9af2-4b02-a8af-a7fe6c001c6d"> | <img width="436" alt="image" src="https://github.com/facebook/docusaurus/assets/42176370/6d2bae75-16a5-47c7-ba96-674a71e4f172"> |

Since the file with the `.md` suffix is not included in the validPathnames, we result in calling the `react-router-config` method `matchRoutes`.

However it __has not any chance of success__ since this are the provided arguments

<img width="1040" alt="image" src="https://github.com/facebook/docusaurus/assets/42176370/9784dd47-fd95-48ec-9ad2-8b7054b5f8c0">

Resulting in the link being added to the brokens list

<img width="1066" alt="image" src="https://github.com/facebook/docusaurus/assets/42176370/7d38e5c5-a7dc-40da-bcd8-e0f22f5d4940">

### Steps to reproduce

(1) git clone https://github.com/axel7083/docusaurus-reproductible-broken-link
(2) npm install
(3) npm run build

Wait and see

### Expected behavior

Not detecting a broken links as it is not one

### Actual behavior

Broken link detected

### Your environment

- Public source code: https://github.com/axel7083/podman-desktop/tree/24f217519eb2e19f143b34007de3b7def390b266
- Public site URL: https://podman-desktop.io/
- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome latest
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by axel7083** [comment] 2024-02-21 17:42
I added a minimal reproductible example here https://github.com/axel7083/docusaurus-reproductible-broken-link

**Comment by axel7083** [comment] 2024-02-21 17:44
cc @slorber

**Comment by slorber** [comment] 2024-02-22 10:57
The problem is not in the broken link checker. Markdown relative file links should be resolved before reaching the broken link checker, and not end with `.md`.

The problem is in our legacy `replaceMarkdownLinks` function and how it handles fenced code blocks with hacky regexes.

A minimal repro:

````md
```something```

[test](test.md)
````


It's not clear to me why you use "inline triple backticks" instead of regular inline code blocks, but you can probably fix the problem by migrating to regular inline code blocks.

The solution should be https://github.com/facebook/docusaurus/issues/9048, so I'm closing this issue as a duplicate.

**Closed by slorber** 2024-02-22 10:57 UTC
Labels: bug, status: needs triage

**Comment by axel7083** [comment] 2024-02-22 11:23
> The problem is not in the broken link checker. Markdown relative file links should be resolved before reaching the broken link checker, and not end with `.md`.
> 
> The problem is in our legacy `replaceMarkdownLinks` function and how it handles fenced code blocks with hacky regexes.
> 
> A minimal repro:
> 
> ```
> ```something```
> 
> [test](test.md)
> ```
> 
> It's not clear to me why you use "inline triple backticks" instead of regular inline code blocks, but you can probably fix the problem by migrating to regular inline code blocks.
> 
> The solution should be #9048, so I'm closing this issue as a duplicate.

The markdown is generated by https://github.com/tgreyuk/typedoc-plugin-markdown

**Comment by slorber** [comment] 2024-02-22 11:37
I see thanks, will track the issue to see what the author has to say.

**Comment by melroy89** [comment] 2024-04-28 07:26
This is a very nasty bug and hard to debug! Please support triple backticks!
