### ISSUE TITLE
Can't render markdown formatting in mermaid

### ISSUE THREAD

**Issue by Penggeor** [facebook/docusaurus#9296] opened 2023-09-10 23:13 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Mermaid flowchat is support markdown formatting: [http://mermaid.js.org/syntax/flowchart.html#markdown-formatting](http://mermaid.js.org/syntax/flowchart.html#markdown-formatting)

But docusaurus can't render markdown formatting:

<img width="1006" alt="image" src="https://github.com/facebook/docusaurus/assets/68799055/3ad8ce9d-20b7-48bc-9d9d-494b2d490c2b">

<img width="1512" alt="image" src="https://github.com/facebook/docusaurus/assets/68799055/185948c1-c874-4d8f-aeea-6f4b530596d2">

### Reproducible demo

https://codesandbox.io/p/sandbox/aged-waterfall-d69rkt

### Steps to reproduce

1. enter the repo
2. enter /tutorial/intro page
3. you will see the marmaid

### Expected behavior

Render markdown formatting correctly in mermaid.

### Actual behavior

No render

### Your environment

Same as the example repo.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2023-09-11 16:46
As far as I understand this was added in Mermaid 10.1 in https://github.com/mermaid-js/mermaid/pull/4271

Docusaurus v2 uses Mermaid 9.x so it is not a bug, but a feature request.

We'll upgrade to Mermaid v10.latest in https://github.com/facebook/docusaurus/issues/9032 for Docusaurus v3, so closing this as a duplicate

**Closed by slorber** 2023-09-11 16:46 UTC
Labels: bug
