### ISSUE TITLE
npm run build fails when nmetadata are missing

### ISSUE THREAD

**Issue by wagnbeu0** [facebook/docusaurus#10069] opened 2024-04-23 12:54 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi, I have a git repository as source for my webpage. with docusaurus 3.1 I get a warning:

[WARNING] Error: Failed to retrieve the git history for file "/opt/ARTOPS_DOKU/docs/tutorial-extras/translate-your-site.md" with exit code 128: fatal: not a git repository (or any parent up to mount point /opt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Now I updates to 3.2.1 and the build os now aborting:

[INFO] [en] Creating an optimized production build...
[ERROR] Loading of version failed for version current

[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/opt/ARTOPS_DOKU/node_modules/@docusaurus/core/lib/commands/build.js:53:19)
    at async /opt/ARTOPS_DOKU/node_modules/@docusaurus/core/lib/commands/build.js:64:9
    at async mapAsyncSequential (/opt/ARTOPS_DOKU/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/opt/ARTOPS_DOKU/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
 ...
      [cause]: Error: Failed to retrieve the git history for file "/opt/ARTOPS_DOKU/docs/tutorial-extras/translate-your-site.md" with exit code 128: Schwerwiegend: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
    
...

What can I do to enable the build again? I think problem is caused by the following parameters:

          showLastUpdateAuthor: true,
          showLastUpdateTime: true,

### Steps to reproduce

Docusaurus is installed under /opt/ARTOPS_DOKU. A git Repo is cloned to /opt/ARTOPS_DOKU/docu/Doku. In /opt/ARTOPS_DOKU/docu the efault files from docusaurus are located.
When running npm run build docusaurus 3.2.1 is aborting.

### Expected behavior

Behaviour from all version up to 3.1.1:
All files are searched for last modified user and last modified time. Then the webpages are created. If a file has not git information, a warning is reported, but the webpage is build.

### Actual behavior

New behaviour since 3.2.1:
All files are searched for last modified user and last modified time. But the webpages are created, If a file has not git information, because a warning is reported and the buold is aborted.

### Your environment

- Public source code: no
- Public site URL: internal
- Docusaurus version used: 3.2.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): nodejs16
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): RedHat 8

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment] 2024-04-23 16:41
Indeed this is caused by the two options, I'm not sure if we changed the internal behavior in version 3.2.1

```
      showLastUpdateAuthor: true,
      showLastUpdateTime: true,
```

> Docusaurus is installed under /opt/ARTOPS_DOKU. A git Repo is cloned to /opt/ARTOPS_DOKU/docu/Doku

I'm not sure to understand correctly what you mean by Docusaurus is installed in ARTOPS_DOKU and then a git repo is cloned to ARTOPS_DOKU/docu/Doku

Meanwhile you can disable the two options

**Comment by wagnbeu0** [comment] 2024-04-24 05:54
Hi, I installed Docusaurus there:

```
cd /opt/
npx create-docusaurus@latest ARTOPS_DOKU classic
```

Later I cloned my documentation repo into a subfolder:
```
mkdir /opt/ARTOPS_DOKU/docs/Docu
git clone https://my-git-servert/reponame /opt/ARTOPS_DOKU/docs/Docu
```

**Comment by slorber** [comment] 2024-04-25 09:35
These options require Git indeed. 

![CleanShot 2024-04-25 at 11 34 13](https://github.com/facebook/docusaurus/assets/749374/23c95609-7cae-4f6b-94d3-26fdae49bccb)

If you don't use Git you should turn them off. If you use Git, double-check your setup because we run `git log` on your docs files.

Also closing because we need a repro to troubleshoot problems, and no repro was provided

**Closed by slorber** 2024-04-25 09:35 UTC
Labels: bug, status: needs triage

**Comment by sibelius** [comment] 2024-10-13 11:39
we are getting this error when using `git`

```
[INFO] [en] Creating an optimized production build...
[ERROR] Loading of version failed for version current

[ERROR] Error: Unable to build website for locale en.
at tryToBuildLocale (dev-docs/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async dev-docs/node_modules/@docusaurus/core/lib/commands/build.js:65:9
at async mapAsyncSequential (dev-docs/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
at async Command.build (dev-docs/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
[cause]: Error: Can't process doc metadata for doc at path path=dev-docs/docs/charge/charge-intent/credit/how-to/charge-credit-how-to-pay.md in version name=current
at processDocMetadata (dev-docs/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:151:15)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async Promise.all (index 2222)
... 3 lines matching cause stack trace ...
at async Object.loadContent (dev-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:171:33)
at async dev-docs/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:39:23
at async Promise.all (index 0)
at async dev-docs/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:140:25 {
[cause]: Error: An error occurred when trying to get the last update date
at getGitLastUpdate (dev-docs/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:46:19)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async readLastUpdateData (dev-docs/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:78:33)
... 5 lines matching cause stack trace ...
at async Promise.all (index 0)
at async Object.loadContent (dev-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:171:33) {
[cause]: Error: Failed to retrieve the git history for file "dev-docs/docs/charge/charge-intent/credit/how-to/charge-credit-how-to-pay.md" with exit code EAGAIN:
at getFileCommitDate (dev-docs/node_modules/@docusaurus/utils/lib/gitUtils.js:56:15)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async getGitLastUpdate (dev-docs/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:26:24)
at async readLastUpdateData (dev-docs/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:78:33)
at async doProcessDocMetadata (dev-docs/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:53:24)
at async processDocMetadata (dev-docs/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:148:16)
at async Promise.all (index 2222)
at async doLoadVersion (dev-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:122:34)
at async loadVersion (dev-docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:163:28)
at async Promise.all (index 0)
}
}
}
```

**Comment by slorber** [comment] 2024-10-14 12:57
@sibelius are you able to run `git log` on the file? 

Are you manipulating it through other processes at the same time?

Can you try to apply a patch like this locally and see if it solves the problem?
https://github.com/facebook/docusaurus/pull/10354

**Comment by sibelius** [comment] 2024-10-14 13:57
```
[cause]: Error: Failed to retrieve the git history for file "dev-docs/docs/charge/analytics/updates/2023/dec-2023/charge-analytics-updates-dec-15-2023.md" with exit code EAGAIN: 
```

git log works well

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/48e2c9e8-778d-4d54-9120-88cc0fb7a0c9">

**Comment by lanegoolsby** [comment] 2025-01-31 17:27
@slorber I am running into a very similar issue right now. Was something like this ever implemented?

For context, we are migrating a ton of content from an old system to an existing Docusaurus site. The site in question has been around for a few years with over 1500 .md files. I am adding around 4500 new files that are a mix of markdown and PNG files. 

When I try to build the site I get the following error for random files under `/docs`, not just the files that I am trying to migrate.

```
[INFO] [en] Creating an optimized production build...
[ERROR] Loading of version failed for version current

[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/path/to/my/repo/node_modules/@docusaurus/core/lib/commands/build/build.js:78:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /path/to/my/repo/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
    at async mapAsyncSequential (/path/to/my/repo/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/path/to/my/repo/node_modules/@docusaurus/core/lib/commands/build/build.js:33:5) {
  [cause]: Error: Can't process doc metadata for doc at path path=/path/to/my/repo/docs/stack-backup/questions/4148.md in version name=current
      at processDocMetadata (/path/to/my/repo/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:151:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 2384)
      ... 3 lines matching cause stack trace ...
      at async Object.loadContent (/path/to/my/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:201:33)
      at async /path/to/my/repo/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:39:23
      at async Promise.all (index 0)
      at async /path/to/my/repo/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:140:25 {
    [cause]: Error: An error occurred when trying to get the last update date
        at getGitLastUpdate (/path/to/my/repo/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:46:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async readLastUpdateData (/path/to/my/repo/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:78:33)
        ... 5 lines matching cause stack trace ...
        at async Promise.all (index 0)
        at async Object.loadContent (/path/to/my/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:201:33) {
      [cause]: Error: Failed to retrieve the git history for file "/path/to/my/repo/docs/stack-backup/questions/4148.md" with exit code EAGAIN: 
          at getFileCommitDate (/path/to/my/repo/node_modules/@docusaurus/utils/lib/gitUtils.js:56:15)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async getGitLastUpdate (/path/to/my/repo/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:26:24)
          at async readLastUpdateData (/path/to/my/repo/node_modules/@docusaurus/utils/lib/lastUpdateUtils.js:78:33)
          at async doProcessDocMetadata (/path/to/my/repo/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:53:24)
          at async processDocMetadata (/path/to/my/repo/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:148:16)
          at async Promise.all (index 2384)
          at async doLoadVersion (/path/to/my/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:152:34)
          at async loadVersion (/path/to/my/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:193:28)
          at async Promise.all (index 0)
    }
  }
}
```

I've also noticed that when that:

1. When the error happens none of the console output is written to the terminal
2. The build finishes after a few seconds but the CPU is maxed out for a minute or two after the build reports as 'done'
3. I ran `git config --global http.postBuffer 1048576000` to increase the buffer Git uses to no effect
4. Committing the files so they're in the log doesn't seem to have an effect

If I remove `showLastUpdateAuthor` and `showLastUpdateTime` from the config file the build seems to work and I do not see the massive CPU spike. 

Any suggestions for how to tell DS to be kinder to Git?
