### ISSUE TITLE
Proposal: option to drop data-theme in favor of prefers-color-scheme

### ISSUE THREAD

**Issue by SethFalco** [facebook/docusaurus#9579] opened 2023-11-24 11:14 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

It would be valuable for Docusaurus to provide an option that disables `data-theme` entirely, and drops all attributes and JavaScript for it, in favor of solely using the `prefers-color-scheme` property.

### Has this been requested on Canny?

N/A

### Motivation

In the following scenario, it's best to drop `data-theme` altogether:

* the website uses `prefers-color-scheme`
* does not provide an on-site toggle
* light mode and dark mode are the only color schemes available

Some developers, such as myself, don't provide an on-site toggle for changing theme. Instead, we guide users to their browser or operating system settings if it's supported.

* This also improves theming when JavaScript is disabled, whereas currently Docusaurus and similar tool chains are locked into light mode when JavaScript is disabled.
* In the scenario described initially, this minimally reduces the network transfer when serving pages and parsed/executed JavaScript.
* Avoids any messiness or disputes regarding if the ePrivacy Directive applies to this use of localStorage to store theming preferences.

This option would introduce a tradeoff that developers would have to consider:

* current behavior, clients with JavaScript disabled can't access dark mode
* proposed option, clients on old software can't access dark mode

### API design

I think the best way to do this is to perform the action implicitly based on the current config, no API change is necessary.

In the [color mode config](https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode), if `disableSwitch: true` and `respectPrefersColorScheme: true` are configured, then implicitly perform this behavior, where all styling is applied through `prefers-color-scheme`, not `[data-theme=dark]`.

```
export default {
  themeConfig: {
    colorMode: {
      disableSwitch: true,
      respectPrefersColorScheme: true,
    }
  }
};
```

### Have you tried building it?

I have reviewed the Docusaurus repo. Skipping the script that adds the theming script at the top of the `<body>` is easy.

The part I'm not sure of is how to approach selectors for `[data-theme='dark']` in the code. I'm thinking this would be easiest as a post step with PostCSS or webpack to convert them to `@media (prefers-color-scheme: dark)`, but I have not done this yet.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment] 2023-11-24 23:28
That seems a bit complicated for limited usefulness.

Who disables JS these days? I mean it can fail to load ok (but in our case it's inlined) but if you disable it on purpose you can expect 99.9% of the internet to not work as good as if it were enabled 😅 

Who has a concrete use-case for this, apart theorically? Do you browse internet using a very old browser (which we don't support) or with JS disabled?

**Comment by SethFalco** [comment] 2023-11-24 23:54
> Who disables JS these days?

Not many people, admittedly. However, as a participant in privacy spaces, I have encountered users who browse with JavaScript disabled by default (i.e. with uBlock Origin rather than the browser setting) and only enable it again for sites they trust.

> Who has a concrete use-case for this

The only group I can think of, and a reference to the above, are individuals who are protective around privacy/tracking.

> Do you browse internet using a very old browser (which we don't support) or with JS disabled?

I, personally, do not disable JavaScript myself.

I have considered it, but as you've said, some sites don't work as well, and many don't work whatsoever. However, this can also explain why I'd value building a better JavaScript-less experience in web apps, since I'd like to see the web run better without JavaScript.

---

In general, I agree it's niche and might be more work than it's worth. If you aren't into it, I'm happy to look externally to get this done.

I thought it would be great to have this baked into Docusaurus because it already has a (mostly) good JavaScript-less experience, so I assumed it was one of the goals. It's actually one of the reasons I tried it out.

If JavaScript-less browsing hasn't been a focus, I'm actually surprised and impressed with how well it works. ^-^'

**Comment by slorber** [comment] 2023-11-25 15:08
Thanks for the explanations.

Yes working without JS has been a focus for most features (notably navigation), and we kept the hardest cases for later.

I guess we can close as duplicate of the existing "no js support" issue: https://github.com/facebook/docusaurus/issues/3030

**Closed by slorber** 2023-11-25 15:08 UTC
Labels: feature
