### ISSUE TITLE
Alpha v75 causes Markdown imports to exponentially increase compilation time, rendering my website impossible to compile

### ISSUE THREAD

**Issue by Zamiell** [facebook/docusaurus#4713] opened 2021-05-02 23:47 UTC
## 🐛 Bug Report

In my Docusaurus website, I have import statements at the top of my Markdown files for the purposes of showing diagrams as React components. When upgrading to Docusaurus v75, these import statements make the development server impossible to start, as it hangs forever.

My website works completely fine on the previous version of 70.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Install Python 3 (e.g. `apt install python3`)
1. `pip install svgwrite`
1. `git clone git@github.com:hanabi/hanabi.github.io.git`
1. `cd hanabi.github.io.git`
1. `git checkout -b doc-bug`
1. `npm install`
1. `npm run start`
1. Observe that compilation takes around 6.5 seconds.
1. Open the "beginner.md" file. Move a single import statement on line 17 up a line so that it is no longer commented out. Save the file.
1. `npm run start`
1. Observe that compilation takes around 22 seconds.
1. Open the "beginner.md" file. Move another import statement up so that it is no longer commented out. Save the file.
1. `npm run start`
1. Observe that compilation never completes.

## Expected behavior

I expect my website to compile like it has been doing on previous versions of this software. On v70, it compiles in around 20 seconds with hundreds of import statements in around 30 different Markdown files.

## Actual Behavior

The website does not compile.

**Comment by RDIL** [comment] 2021-05-03 15:24
Hey, webpack 5 dude here.  Sorry to hear this is happening!  I'll take a look for you.

**Comment by RDIL** [comment] 2021-05-03 15:35
Can confirm, will be working to figure out why exactly this is.  Sorry about that!

**Comment by slorber** [comment] 2021-05-03 18:04
running "npm ci" fails for me 

![image](https://user-images.githubusercontent.com/749374/116914234-c0f87d80-ac4a-11eb-94e2-b1a0f423089e.png)


also, can't run after "npm install":

![image](https://user-images.githubusercontent.com/749374/116914273-ceae0300-ac4a-11eb-8b79-3be19a71fab1.png)

**Comment by Zamiell** [comment] 2021-05-03 18:44
@slorber As the error message implies, you have to first run `pip install svgwrite`. I guess that needs to be included in the above instructions.

**Comment by Zamiell** [comment] 2021-05-04 05:35
@RDIL Thanks for looking, did you find anything?

**Comment by slorber** [comment] 2021-05-04 09:50
@Zamiell please don't assume I know anything about Python because I don't 😅 

I had not planned to learn about how to to make python 3 the default on macos or how to handle a `requirements.txt` file (because obviously "pip install yaml" does not work")

Now it seems to work, but it was quite time-consuming to get there 😓 

---

It seems your site builds, but there are a lot of broken links reported at the end, is this normal?

**Comment by Zamiell** [comment] 2021-05-04 13:11
Hey Slorber, thanks for taking a look. On MacOS, you simply use brew (i.e. `brew install python`).

> It seems your site builds, but there are a lot of broken links reported at the end, is this normal?

Yes, it is normal because in order to find the problem, I had to "comment out" (i.e. remove) the entire docs folder, and then just re-introduce one file, beginner.md.

**Comment by slorber** [comment] 2021-05-04 13:15
`brew install python` did not change the `python --version`, had to alias python to python3.

So, you upgraded from alpha 70 to alpha 75. The problem is also there on alpha74 (using Webpack 4), and it's not a Webpack 5 bug.

I found out we have a very slow regex trying to extract a top-level doc markdown title, ignoring the mdx exports above it.

Reported another bug report here for clarity: https://github.com/facebook/docusaurus/issues/4726

Going to close this one.

A workaround to solve this regex problem is to add a md title above the MDX imports, or to not use MDX imports at the very top of the file.

```
---
id: beginner
title: Beginner's Guide
---

# Beginner's Guide

import CardLayout1 from '@site/image-generator/yml/beginner/card-layout-1.yml';
import CardLayout2 from '@site/image-generator/yml/beginner/card-layout-2.yml';
import Chop1 from '@site/image-generator/yml/beginner/chop-1.yml';
import Chop2 from '@site/image-generator/yml/beginner/chop-2.yml';
import BasicClue from '@site/image-generator/yml/beginner/basic-clue.yml';
```

This is useless title duplication, but fixes the perf problem for me.

About your custom plugin, I suggest not importing our getFileLoader() utils and write your own svgr loader, as we are likely to change this: it is internal Docusaurus code, not public API.

**Closed by slorber** 2021-05-04 13:15 UTC
Labels: bug, needs triage

**Comment by Zamiell** [comment] 2021-05-04 14:12
Awesome, thanks again for looking into this so quickly.

**Comment by DarthGandalf** [comment] 2021-05-04 14:17
> About your custom plugin, I suggest not importing our getFileLoader() utils and write your own svgr loader

That was me. I just wanted to avoid code duplication, since the svgr loader options in Docusaurus worked fine.

**Comment by slorber** [comment] 2021-05-04 14:23
Thanks for reporting this, was not easy to find the issue 😅 

About the plugin, it's not a big deal but you'd rather duplicate a few lines rather than being subject to internal changes of Docusaurus. It's likely that this will change again

**Comment by DarthGandalf** [comment] 2021-05-04 14:31
Ideally, I'd query webpack itself for the options used to load svg files, except that I didn't find such API.

Sure, we'll just instantiate svgr without calling into your internals, thanks for advice!
