### ISSUE TITLE
Mermaid not displaying correctly in mdx

### ISSUE THREAD

**Issue by asalwaysimani** [facebook/docusaurus#9891] opened 2024-02-25 23:36 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When using the Dynamic Mermaid Component diagram for mermaid, the display on the mdx page is either blank (other than the page title ) or does not render with the theme. It only shows the code block with what should be in the Mermaid chart.

### Steps to reproduce

1.  Enable the @docusaurus/theme-mermaid plugin.
2. Set markdown.mermaid to true in your docusaurus.config.js
3. Create a new mdx file, set title.
4. Add in any type of applicable mermaid diagram such as 
`mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;`
6. Save the page.
7. Build the site (yarn build).

### Expected behavior

It should display a flow chart

![Screenshot 2024-02-25 151852](https://github.com/facebook/docusaurus/assets/30423669/20369ab3-8244-4728-aa4a-2f5a9e519251)

### Actual behavior

The display of the Dynamic Mermaid Component on the mdx page is either blank  or it does not render with the theme instead of showing the code block.

![Screenshot 2024-02-25 151741](https://github.com/facebook/docusaurus/assets/30423669/b798b16b-659b-4d28-941a-74a88684ba02)
![Screenshot 2024-02-25 151541](https://github.com/facebook/docusaurus/assets/30423669/8d96fe8c-32db-41d4-9744-91677fd286e8)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-02-26 09:38
No repro provided so I'm closing. 

It works on our site, so it's likely a mistake on your side (unless you prove me wrong with a repro)

**Closed by slorber** 2024-02-26 09:38 UTC
Labels: bug, status: needs triage, closed: can't repro

**Comment by quinn-p-mchugh** [comment] 2024-04-19 00:15
@asalwaysimani
I ran into this issue (Mermaid diagrams not rendering). Not clear if my issue was caused by the same thing, however.

To solve, I upgraded `@mdx-js/react` to the latest version using `npm install @mdx-js/react@latest`. It seems I neglected to do this when upgrading from Docusaurus v2 to v3.

[It's called out in the "Upgrading to Docusaurus v3" instructions here](https://docusaurus.io/docs/migration/v3#:~:text=%2D%20%20%20%20%22%40mdx%2Djs/react%22%3A%20%22%5E1.6.22%22%2C%0A%2B%20%20%20%20%22%40mdx%2Djs/react%22%3A%20%22%5E3.0.0%22%2C).

Hope this helps someone!
