### ISSUE TITLE
html sidebar item should be translatable

### ISSUE THREAD

**Issue by fgalz** [facebook/docusaurus#9575] opened 2023-11-22 16:28 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Docusaurus offers the possibility to add a "sidebar-title" using the HTML type. However, there is currently no option for a simple translation. 

```
{
type: 'html',
className: 'sidebar-title',
value: 'Placeholder',
defaultStyle: true,
},
```

The function itself works again with the latest Canary version, but it can only be used in one language and is limited if you offer docs in several languages. 

### Steps to reproduce

Add the sidebar-title, build it and check it. It's only available in the hardcoded language or rather the value that is set. 

### Expected behavior

The sidebar-title should be available in other languages as well, so there should be some sort of support for this. 

### Actual behavior

The sidebar-title (value) is hardcoded and therefore the same for all languages. 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: Canary
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2023-11-26 14:23
I'll consider it as a duplicate of https://github.com/facebook/docusaurus/issues/4542

Suggested workaround, not an ideal api but will work to translate html navbar items: https://github.com/facebook/docusaurus/issues/4542#issuecomment-1434839071

**Closed by slorber** 2023-11-26 14:23 UTC
Labels: feature, domain: i18n

**Comment by slorber** [comment] 2023-11-30 14:15
This works on our own website:

![CleanShot 2023-11-30 at 15 14 27@2x](https://github.com/facebook/docusaurus/assets/749374/9b36d45b-bbda-40ca-bf65-9315e4aabc5c)

<img width="994" alt="CleanShot 2023-11-30 at 15 14 56@2x" src="https://github.com/facebook/docusaurus/assets/749374/f551996b-ed3e-48b3-92a4-b9d84172a651">

I just ran `yarn start:website --locale de`

If it doesn't work for you please create a runnable repro including the command you use to start in `de` lang

**Comment by slorber** [comment] 2023-12-07 14:09
Runnable proof that it does: https://stackblitz.com/edit/github-zcvn3b?file=sidebars.js,docusaurus.config.js

Please create a minimal repro next time

![CleanShot 2023-12-07 at 15 08 39@2x](https://github.com/facebook/docusaurus/assets/749374/11ffebb4-567d-4004-882f-3a3ccc7e5928)

**Comment by Blumlaut** [comment] 2024-01-02 09:31
Thank you, it seems our issue was that instead of `export default sidebars;` we still had `module.exports = sidebars;` at the end of the sidebars config, updating this has indeed resulted in the expected behaviour.
