### ISSUE TITLE
Mermaid graphs missing node labels

### ISSUE THREAD

**Issue by ei-grad** [facebook/docusaurus#10538] opened 2024-09-30 07:18 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Following the official Docusaurus documentation for integrating Mermaid graphs, I'm experiencing an issue where the node labels in embedded Mermaid graphs within blog posts do not display. The nodes appear as empty blocks without any text labels. Reproduced this behavior with site built in docker to isolate possible problems with my environment. Checked in latest Firefox and Chromium browsers.

### Reproducible demo

new.docusaurus.io doesn't allow to add modules

### Steps to reproduce

1. **Initialize a new Docusaurus site:**

   ```bash
   npx create-docusaurus@latest my-website classic
   cd my-website
   ```

2. **Install the Mermaid theme:**

   ```bash
   npm install @docusaurus/theme-mermaid
   ```

3. **Update `docusaurus.config.js` (or `docusaurus.config.ts`):**

   Add the following lines to enable the Mermaid theme and plugin:

   ```javascript
   themes: ['@docusaurus/theme-mermaid'],
   markdown: {
     mermaid: true,
   },
   ```
   
4. **Add a Mermaid graph to the first blog post:**

   Append the graph to `blog/2019-05-28-first-blog-post.md`:

    ~~~bash
    cat >> blog/2019-05-28-first-blog-post.md << "EOF"
    ```mermaid
    graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
    ```
    EOF
    ~~~

5. **Start the development server:**

   ```bash
   npm start
   ```

6. **Navigate to the first blog post:**

   Open `http://localhost:3000/blog/first-blog-post` in your browser.

### Expected behavior

The Mermaid graph should display correctly with all node labels (A, B, C, D) visible.

### Actual behavior

The graph is rendered, but the node labels are missing. Nodes appear as empty blocks without any text.

### Your environment

```
    "@docusaurus/core": "3.5.2",
    "@docusaurus/preset-classic": "3.5.2",
    "@docusaurus/theme-mermaid": "^3.5.2",
    "@mdx-js/react": "^3.0.0",
    "clsx": "^2.0.0",
    "prism-react-renderer": "^2.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
```

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-09-30 08:16
Duplicate of https://github.com/facebook/docusaurus/issues/10526

**Closed by slorber** 2024-09-30 08:16 UTC
Labels: bug, status: needs triage
