### ISSUE TITLE
index.md not behaving correctly with autogenerated sidebar slices.

### ISSUE THREAD

**Issue by Zenahr** [facebook/docusaurus#8659] opened 2023-02-13 12:07 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I've been debugging an issue with autogenerated sidebar slices not working correctly with the index.md/README.md index file convention described here: https://docusaurus.io/docs/sidebar/autogenerated#category-index-convention

Here's my setup:

docs/Tutorials/index.md
docs/Tutorials/some-other-file.md

sidebars.js
```js
...
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Tutorials',
        }
      ],
    },
...
```

### Steps to reproduce

1. Create a sidebars file with

```js
...
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Tutorials',
        }
      ],
    },
...
```

As part of it.

2. Add some files so that your docs directory looks like this:

docs/Tutorials/index.md
docs/Tutorials/some-other-file.md

3. Click on "Tutorials" in the sidebar and observe the behavior

### Expected behavior

sidebar shows "Tutorials" label. Clicking on it automatically opens the index.md file.

### Actual behavior

clicking on "Tutorials" unfolds the category and shows `index` as its own document (not desired). Clicking there also doesn't open the index.md file automatically.

### Your environment

- Docusaurus version used: 2.3.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node v18.12.1.
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Zenahr** [comment] 2023-02-13 12:18
The only way I've gotten indices to work as per usual is like so:

```js
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'Tutorials/index',
      },
      items: [
        'Tutorials/basic free-charging setup',
      ],
    },
```

But somehow it's not possible to keep this configuration and replace the `items` with an autogenerated slice. Is this not intended? I'd like to simply use autogenerated sidebars while respecting the index.md convention. I don't see reason to have index.md files behave differently based on manual or autogenerative sidebars.

**Comment by Josh-Cena** [comment] 2023-02-15 16:44
Duplicate of https://github.com/facebook/docusaurus/issues/8588

**Closed** 2023-02-16 17:53 UTC
Labels: closed: duplicate
