### ISSUE TITLE
Defining default image/icon for standalone pages and categories

### ISSUE THREAD

**Issue by dbrrt** [facebook/docusaurus#7904] opened 2022-08-06 12:06 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Docusaurus offers the ability to loop over sidebar items to generate a list of cards corresponding to folders and pages (final nodes), this feature is reading the markdown content to display more insights in the cards.

It'd be nice to define in the markdown specs an image to replace the default one for folders and pages. 

### Has this been requested on Canny?

https://docusaurus.io/feature-requests/p/defining-default-imageicon-lightdark-for-standalone-pages-and-categories

### Motivation

Better user experience navigating through a list of cardified pages with icons rather than the standard page image

### API design

```md
---
id: "page-id"
sidebar_label: "Sidebar label"
title: ""
img_light: "<img-src-light>"
img_dark: "<img-src-dark>"
---
```

### Self-service

- [ ] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment] 2022-08-06 12:09
Duplicate of https://github.com/facebook/docusaurus/issues/7844. We want to defer these kinds of very-hard-to-generalize APIs to userland design because it's trivially implementable (and we would make the same implementation anyway) with swizzling.

**Closed by Josh-Cena** 2022-08-06 12:09 UTC
Labels: feature, status: needs triage
