### ISSUE TITLE
Change nav bars for docs multi instance

### ISSUE THREAD

**Issue by NathanHennigh** [facebook/docusaurus#9182] opened 2023-07-27 23:01 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Im in the process of creating a community and developer docs site but I want to switch up the nav bars based on the route the user is on. I don't see any clear way to do this besides using docsVersionDropdown which doesn't seem very applicable in this case. Would appreciate any guidance or docs revision.

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment] 2023-07-28 09:39
Duplicate of https://github.com/facebook/docusaurus/issues/4389

**Closed by slorber** 2023-07-28 09:39 UTC
Labels: closed: duplicate, documentation
