### ISSUE TITLE
Code block highlighting of script tag in html syntax is invalid

### ISSUE THREAD

**Issue by JOU-amjs** [facebook/docusaurus#9517] opened 2023-11-08 13:24 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When I upgrade from v2 to v3. I found the html code block not recognize the js code in `<script>` any more,  which is normal before upgrading.

The following is snapshot.
<img width="569" alt="image" src="https://github.com/facebook/docusaurus/assets/29848971/5a6e7991-e678-40cc-b25a-e607cfd4b23a">

And I also found that class names of js code is recognized as plain text like this.
<img width="314" alt="image" src="https://github.com/facebook/docusaurus/assets/29848971/604c96e2-769c-418c-97b6-83d0fa7eabd9">

### Reproducible demo

https://codesandbox.io/p/sandbox/charming-torvalds-h9spkl?file=%2Fsrc%2Fpages%2Fmarkdown-page.md&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clops0uop000d3b6k3a41myzq%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clops0uoo00043b6kjjat6mdy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clops0uop000b3b6k19zjjaix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clops0uop000c3b6ke2qbkxpg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clops0uoo00043b6kjjat6mdy%2522%253A%257B%2522id%2522%253A%2522clops0uoo00043b6kjjat6mdy%2522%252C%2522activeTabId%2522%253A%2522clops3pq900qm3b6kzgep5qvz%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Fmarkdown-page.md%2522%252C%2522id%2522%253A%2522clops3pq900qm3b6kzgep5qvz%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clops0uop000c3b6ke2qbkxpg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clops0uop000c3b6ke2qbkxpg%2522%257D%252C%2522clops0uop000b3b6k19zjjaix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clops0uop00053b6koulfpl6j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522docusaurus%2522%257D%252C%257B%2522id%2522%253A%2522clops0uop00063b6kpy8f9oq1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clops0uop00073b6kxqpgr96l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clops0uop00083b6ki1hh0et7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522clear%2522%257D%252C%257B%2522id%2522%253A%2522clops0uop00093b6ka6tt9orb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522write-heading-ids%2522%257D%252C%257B%2522id%2522%253A%2522clops0uop000a3b6kd6gt7mvo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clops0uop000b3b6k19zjjaix%2522%252C%2522activeTabId%2522%253A%2522clops0uop00053b6koulfpl6j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A23.888888888888886%257D

### Steps to reproduce

1. open the `src/pages/markdown-page.md`.
2. run the project.

### Expected behavior

Highlight valid in html code block.

### Actual behavior

and you can find the invalid effect
```html
<div>aaa</div>
<script>
const a = 1;
console.log(a);
</script>
```

### Your environment

- Docusaurus version used: v3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 119, Node.js 18.8.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows/Mac

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-11-08 14:02
Hi, could you try https://github.com/facebook/docusaurus/discussions/9506#discussioncomment-7506183?

**Comment by JOU-amjs** [comment] 2023-11-08 14:58
> Hi, could you try [#9506 (comment)](https://github.com/facebook/docusaurus/discussions/9506#discussioncomment-7506183)?

Wow... it works. THANKS SO MUCH!

**Comment by Josh-Cena** [comment] 2023-11-08 15:31
Going to reopen until it gets fixed on prism-react-renderer's end. I'm going to send a issue if no one else has

**Comment by slorber** [comment] 2023-11-10 17:30
cc @carloskelly13 any idea what's happening here? 

Looks like languages are now loaded in the wrong order? (cf https://github.com/facebook/docusaurus/discussions/9506#discussioncomment-7506183)

**Comment by carloskelly13** [comment] 2023-11-11 00:57
@slorber Yeah, good find. The problem is the `html` (https://github.com/FormidableLabs/prism-react-renderer/blob/master/packages/generate-prism-languages/index.ts#L23) language preset does not highlight script tags. I've fixed this locally with reverting back to top-level markup and will get a patch published here.

Here is an example of the fix doing what I think we want → 

<img width="1063" alt="Screenshot 2023-11-10 at 4 55 26 PM" src="https://github.com/facebook/docusaurus/assets/1738349/11fe082f-b076-4ce6-b915-bfc2798f98a4">

**Comment by slorber** [comment] 2023-11-11 16:02
Thanks @carloskelly13! 
Let me know when it's on npm so that I can test it.

**Comment by carloskelly13** [comment] 2023-11-11 18:50
@slorber [`prism-react-renderer@2.2.0`](https://github.com/FormidableLabs/prism-react-renderer/releases/tag/prism-react-renderer%402.2.0) is published. Let me know if this fixes it! Thanks!

**Closed** 2023-11-15 23:27 UTC
Labels: bug, external

**Comment by slorber** [comment] 2023-11-16 22:56
Thanks @carloskelly13 👍  I'll test it soon

**Comment by slorber** [comment] 2023-11-21 11:39
@carloskelly13 some impacts our visual regression testing tool detected.

(by the way I should have been more careful because when upgrading it reported the regressions 😅 )

It also improves inline style:

![CleanShot 2023-11-21 at 12 33 05@2x](https://github.com/facebook/docusaurus/assets/749374/db87f0a6-9d19-4c65-82f9-32c3e9bdabc8)

It fixes this 

![CleanShot 2023-11-21 at 12 35 07@2x](https://github.com/facebook/docusaurus/assets/749374/5aad3ea1-2569-4d74-953c-7bfe2c8edf08)

But for some reason this one lose its highlighting when upgradng to v2.2

<img width="1028" alt="CleanShot 2023-11-21 at 12 36 26@2x" src="https://github.com/facebook/docusaurus/assets/749374/391ef1b0-e3f2-4cea-a79c-6f8b41f7e6b5">

Both cases on page https://docusaurus.io/docs/seo

Not a big deal though, because it was already the case before under v1. I just thought you might like to know about this edge case.
