### ISSUE TITLE
Document to document links don't work with sub directories

### ISSUE THREAD

**Issue by SimeonRoss** [facebook/Docusaurus#1094] opened 2018-11-06 20:23 UTC
## 🐛 Bug Report

I'm trying to use docusaurus with my docs in sub directories as we have a lot of files and want to keep things organised. I'm having trouble getting markdown links to work correct. When I'm linking to another markdown file in the same directory I've found you can only use a relative path. So, dirA/file1.md can like to dirA/file2.md by doing [text](dirA/file2.md) (incidently my IDE warns me that the file doesn't exist)

```
docs/
├── assets
│   └── images
│       └── image1.png
├── dirA
│   └── file1.md
└── dirB
    └── file2.md
```

However, if I have dirA/file1.md referencing dirB/file2.md [text](dirB/file2.md) then I end up with the link dirA/dirB/file2.md. I've tried absolute links and different ways of putting it together but i cannot get this to work at all.

I've also had issues with trying to reference the images from sub directories. file1.md references image1.png, which i've had to do with /docs/assets/images/image1.png which my IDE tells me is invalid

**Comment by respinoza** [comment] 2018-11-08 05:29
I think this is related, if not let me know and I will open a new issue.
With this structure:

```
docs/
└── index.md
        └── user
                └── index.md
                └── another.md
```

Have a file in `docs/index.md`

```
[users](user/index.md)
```

Now your `user/index.md` has this

```
[Another file](another.md)
```

When I build everything, the link `[Another file](another.md)` won't link to the HTML version, it still tries to open it with the `.md` extension and as expected, it breaks. If I switch that `.md` to `.html`, it opens the right file as expected.
The documentation is clear on this and it says it replaces the `.md` and it does for the root directory but not for subdirs.

**Comment by endiliey** [comment] 2018-11-11 14:42
Could be a regression. Do any of you happen to have a reproducible repo? That will be nice because I wasn't able to reproduce it >.<

**Comment by endiliey** [comment] 2018-11-23 07:49
> @respinoza  When I build everything, the link [Another file](another.md) won't link to the HTML version

You should refer it as `[Another file](user/another.md)`

--- 
So I managed to spend some time and came up with a test case

docs/index.md
```
---
id: index
title: Index
---

Testing all links

# Test me
[ecosystem/bar](ecosystem/bar.md)

# Test me
[index](index.md)

# Test me
[hydra/bar](hydra/bar.md)
```

docs/hydra/bar.md
```
---
id: bar
title: Security Architecture
---

Testing all links

# Test me
[ecosystem/bar](ecosystem/bar.md)

# Test me
[index](index.md)

# Test me
[hydra/bar](hydra/bar.md)
```

docs/ecosystem/bar.md
```
---
id: bar
title: Cloud Native Architecture
---

Testing all links

# Test me
[ecosystem/bar](ecosystem/bar.md)

# Test me
[index](index.md)

# Test me
[hydra/bar](hydra/bar.md)
````

And it all worked perfectly.

![no-error](https://user-images.githubusercontent.com/17883920/48932482-20f58080-ef37-11e8-9ce0-83e7e7088977.gif)

## I'm going to close this issue. 
## Please send a reproducible repo for bug report

**Closed by endiliey** 2018-11-23 07:49 UTC
Labels: bug

**Comment by respinoza** [comment] 2018-11-23 15:20
Did you try without the IDs at the top of the files? I believe that's when it breaks.

We opted to have everything in one level and avoid the issue.

**Comment by endiliey** [comment] 2018-11-23 15:31
Yep, I did.

If bug persists. Please re-open a new issue with a reproducible demo 😊

**Comment by alexsierro** [comment] 2020-04-16 08:52
I had same issue with a link... Finally filename was just mistyped the path. ;-)

**Comment by alexsierro** [comment] 2020-04-16 08:52
I had same issue with a link... Finally filename was just mistyped. ;-)
