### ISSUE TITLE
Add `showLastUpdateTime` and `showLastUpdateAuthor` to blogs

### ISSUE THREAD

**Issue by ilg-ul** [facebook/docusaurus#9826] opened 2024-02-06 16:01 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Keep track of the last update time & author for blog posts, similarly to documentation pages.

### Has this been requested on Canny?

No.

### Motivation

Posts with historical data are often updated at a later time, as new data is discovered.

The last update time can also be used to reorder posts to move recently updated posts at the top of the list, both in the web and the feeds.

### API design

The features are enabled by `showLastUpdateTime` and `showLastUpdateAuthor` added to hte blog plugin configuration.

When enabled, the last update time is displayed below the post and also used when sorting the posts in the feed files.

![last-updated](https://github.com/facebook/docusaurus/assets/362732/1b3c90e8-f99d-48bb-b6c5-b27bf968ee19)

### Have you tried building it?

The functionality is implemented in https://github.com/cronica-it/docusaurus-chronology/commit/83e5293121aeb8c9b419be0fc0857cd56a5f72cc.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment] 2024-02-08 15:31
Closing as a duplicate of an already existing feature request: https://github.com/facebook/docusaurus/issues/8657

I'd suggest adding your comments here, other persons of the community might be interested to provide feedback on the feature design.

**Closed by slorber** 2024-02-08 15:31 UTC
Labels: feature
