### ISSUE TITLE
Nested folder named "static" inside static files folder causes build error

### ISSUE THREAD

**Issue by vonagam** [facebook/Docusaurus#525] opened 2018-04-02 02:20 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Steps to Reproduce

1. Have a folder named "static" inside "website/static" folder.
2. Run `docusaurus-build` command.
3. Get error from `fs.js` about not permitted operation.

### Cause

The problem lies in code lines like this: [1](https://github.com/facebook/Docusaurus/blob/1a674885aeff1a3c9523d16a72a34e4ba0ce8019/lib/server/generate.js#L324), [2](https://github.com/facebook/Docusaurus/blob/1a674885aeff1a3c9523d16a72a34e4ba0ce8019/lib/server/generate.js#L405), [3](https://github.com/facebook/Docusaurus/blob/1a674885aeff1a3c9523d16a72a34e4ba0ce8019/lib/server/generate.js#L424)

`path.split('static')` assumes that there is only one folder named static in a path.

[Here](https://github.com/vonagam/Docusaurus/commit/fdb38575ccdca61c811608035c5f072600ebe961) is how i think it can be fixed. 

Have not opened a pull request because do not have a "test plan" and there not much tests currently... But on my local setup it did fix the problem.

**Comment by yangshun** [comment] 2018-05-04 03:10
Hey @vonagam , could you help us understand why there is another folder called `static` within `static`? Doesn't seem like a common thing to do.

**Comment by vonagam** [comment] 2018-05-04 08:55
In my case i wanted to place output of [storybook](https://github.com/storybooks/storybook) [static build](https://storybook.js.org/basics/exporting-storybook/) into docusaurus. And it has folder named "static" in [build](https://github.com/storybooks/storybook/blob/323c523d1875d925e81d2903d8ee14d059b0f858/app/react/src/server/config/webpack.config.prod.js#L28).

**Comment by ericnakagawa** [comment] 2018-05-16 19:19
I've looked into this. The fix will require changing how we glob for files in a "static" directory.

**Comment by JoelMarcey** [comment] 2018-05-17 00:01
I will assign this one to you Eric. Thanks!

**Comment by vaibhavsingh97** [comment] 2018-06-14 08:27
@ericnakagawa Are you still working on this issue? I am interested to fix this issue 😄

**Comment by JoelMarcey** [comment] 2018-06-14 14:29
@vaibhavsingh97 I believe @ericnakagawa would not mind at all if you work on this. 😄

**Comment by vaibhavsingh97** [comment] 2018-06-18 11:40
@JoelMarcey @vonagam I am not able to reproduce the issue 😞

**Comment by endiliey** [comment] 2018-08-28 17:53
Couldn't reproduce as well. Feel free to reopen

**Closed by endiliey** 2018-08-28 17:53 UTC
Labels: bug, good first issue, issue: claimed
