### ISSUE TITLE
Unresolved link inside HTML comment

### ISSUE THREAD

**Issue by KyrietS** [facebook/docusaurus#5659] opened 2021-10-07 18:52 UTC
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

I get an error when I build the website:
```
Docs markdown link couldn't be resolved: (somepage.md) in {path}/mypage.md for version current
```
**mypage.md** looks like this:

```markdown
# title
<!-- [some page](somepage.md) -->
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

Add to any markdown page:
```markdown
<!-- [some text](nonexistentpage.md) -->
```

## Expected behavior

Dummy links in HTML comments should not produce any warning / error during build.

## Actual behavior

Docusaurus thinks that markdown link cannot be resolved even though it's inside the HTML comment. Error is printed and build fails.

## Your environment

not relevant

## Reproducible demo

https://stackblitz.com/edit/github-qhwl7g?file=docs/intro.md

**Comment by slorber** [comment] 2024-05-23 15:08
Duplicate of https://github.com/facebook/docusaurus/issues/9048

**Closed by slorber** 2024-05-23 15:08 UTC
Labels: bug, help wanted, difficulty: intermediate, domain: markdown
