### ISSUE TITLE
Bug: Cyrillic title with icon 

### ISSUE THREAD

**Issue by baur** [facebook/docusaurus#8725] opened 2023-03-02 16:49 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Cyrillic title with icon

<img width="682" alt="image" src="https://user-images.githubusercontent.com/2898361/222495246-f044d49d-ecc6-4179-a050-983e4b5c9d1d.png">

Latin title with icon

<img width="634" alt="image" src="https://user-images.githubusercontent.com/2898361/222495649-c634a5df-f963-4f7d-87d4-53e89496cc76.png">

### Steps to reproduce

just type:

```
## topic

### 1️⃣ Первый
### 2️⃣ Второй
### 3️⃣ Третий
```

### Expected behavior

normal text

### Actual behavior

...

### Your environment

- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-03-02 22:16
@baur I can't reproduce this.

<img width="193" alt="image" src="https://user-images.githubusercontent.com/55398995/222571467-59febab9-5e07-4ef2-8f55-1cb3f36f0a5d.png">

I suspect it's a font issue.

**Comment by baur** [comment] 2023-03-03 02:53
reproduced via [docusaurus.new](https://docusaurus.new/) StackBlitz

https://stackblitz.com/github/facebook/docusaurus/tree/starter?file=docs/tutorial-basics/congratulations.md

![image](https://user-images.githubusercontent.com/2898361/222619543-00e981cf-0a65-4676-8aa8-c61b684dad9c.png)

**Comment by baur** [comment] 2023-03-03 02:59
```md
## topic

### 2️⃣ Второй
### 1️⃣ First
### 3️⃣ Третий
### 1️⃣ Digit One
```

![image](https://user-images.githubusercontent.com/2898361/222620294-4b6dd45c-9105-418b-a613-e4e8414e8045.png)

**Comment by Josh-Cena** [comment] 2023-03-03 03:24
<img width="193" alt="image" src="https://user-images.githubusercontent.com/55398995/222623518-39f5ce82-b047-4fdf-a54b-18d63bfaa022.png">

As you can tell from my screenshot, I'm using Mac, and on Mac, emojis always use a uniform font. I suspect there's something going on with Windows fonts, but lacking a Windows machine, I cannot debug this.

**Comment by hrumhurum** [comment] 2023-05-14 22:48
This must be a font issue. I cannot repro it neither on Windows nor on Mac.

**Comment by Josh-Cena** [comment] 2023-05-22 16:08
Going to close this because it looks platform-specific. I would encourage you to tweak your CSS and use a different font face or font weight.

**Closed by Josh-Cena** 2023-05-22 16:08 UTC
Labels: bug, status: needs more information
