### ISSUE TITLE
Markdown relative links are treated URL paths if split over multiple lines

### ISSUE THREAD

**Issue by ahmetb** [facebook/docusaurus#10183] opened 2024-05-31 05:51 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

If a relative markdown link's text is split over multiple lines, the link value ending  in `.md` is treated as absolute URL and ends up in the generated `a.href`.

### Steps to reproduce

1. Create a.md and b.md in different directories under `docs/`
2. In `b.md` try referencing `a.md` with a link that splits over multiple lines.

        To learn how access to nodes is granted, see [Node Access
        Control](../a.md).

3. Observe generated link is `<a href="[...]/a.md">`, hence broken

4. Change the link text to appear on one line.

        To learn how access to nodes is granted, see
        [Node Access Control](../a.md).

3. Observe generated link is `<a href="[...]/a">` which is correct.

### Expected behavior

URL behavior (relative file vs URL) should not be impacted whether the markdown link text is split over multiple lines.

### Actual behavior

When markdown link is split over multiple lines, relative `.md` references are treated as absolute URLs.

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 3.3.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): v18.17.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 14.5 (23F79)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-05-31 07:45
Duplicate of https://github.com/facebook/docusaurus/issues/9048

Will be released as v3.4 probably today

**Closed by slorber** 2024-05-31 07:45 UTC
Labels: bug
