### ISSUE TITLE
Change code highlight module to Shiki

### ISSUE THREAD

**Issue by SuperManito** [facebook/docusaurus#9834] opened 2024-02-08 11:24 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Prism performance is not good enough

### Motivation

[Shiki](https://shiki.style) is a syntax highlighter based on Microsoft VSCode TextMate grammar. TextMate grammar is very powerful.

### Self-service

- [x] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by slorber** [comment] 2024-02-08 11:57
Duplicate of https://github.com/facebook/docusaurus/issues/9122

It doesn't have to live in the Docusaurus repo and can remain a third-party plugin

See also:
- https://github.com/shikijs/twoslash/tree/main/packages/docusaurus-preset-shiki-twoslash
- https://github.com/shikijs/twoslash/tree/main/packages/remark-shiki-twoslash

**Closed by slorber** 2024-02-08 11:57 UTC
Labels: feature
