### ISSUE TITLE
[v2] Server build fails after updating to 2.0.0-alpha.66

### ISSUE THREAD

**Issue by the-spyke** [facebook/docusaurus#3614] opened 2020-10-20 16:04 UTC
## 🐛 Bug Report

`start` command work fine. `build` command succeeds with the client, but fails on server throwing an error. Looks like some Webpack configuration goes wrong.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. clone https://github.com/the-spyke/undercut
1. `cd website`
1. `yarn`
1. `yarn build`

## Expected behavior

Finishes successfully.

## Actual Behavior

Fails with an error:

```
TypeError: Cannot read property 'replace' of undefined
    at String.replace (<anonymous>)TypeError: Cannot read property 'replace' of undefined
    at String.replace (<anonymous>)
(undefined) TypeError: Cannot read property 'replace' of undefined
    at Object.options.minifyJS (main:22934:28)
    at Object.chars (main:23422:24)
    at main:52510:19
    at String.replace (<anonymous>)
    at new HTMLParser (main:52502:19)
    at minify (main:23208:3)
    at module.exports.exports.minify (main:23569:16)
    at serverEntry_render (main:100079:38)
Error: Failed to compile with errors.
    at /home/spyke/Projects/undercut/node_modules/@docusaurus/core/lib/webpack/utils.js:164:24
    at finalCallback (/home/spyke/Projects/undercut/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /home/spyke/Projects/undercut/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/home/spyke/Projects/undercut/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/home/spyke/Projects/undercut/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /home/spyke/Projects/undercut/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /home/spyke/Projects/undercut/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/home/spyke/Projects/undercut/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/spyke/Projects/undercut/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/spyke/Projects/undercut/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/home/spyke/Projects/undercut/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/spyke/Projects/undercut/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/spyke/Projects/undercut/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/spyke/Projects/undercut/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/spyke/Projects/undercut/node_modules/tapable/lib/Hook.js:154:20)
    at /home/spyke/Projects/undercut/node_modules/webpack/lib/Compiler.js:678:31
error Command failed with exit code 1.
```

## Your Environment

- Docusaurus version used: 2.0.0-alpha.66
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): v14.14.0
- Operating system and version (desktop or mobile): Ubuntu 20.04 x64

## Reproducible Demo

https://github.com/the-spyke/undercut

`website` directory

**Comment by slorber** [comment] 2020-10-20 17:41
Hi,

This looks like a duplicate of this one:
https://github.com/facebook/docusaurus/issues/3515

This looks to me more like a yarn monorepo resolution bug or something that lead to the wrong version of a package being loaded at runtime.

There is a workaround that should work, and not sure what else we can do apart from waiting for our dependency to upgrade to Terser v5 (https://github.com/terser/html-minifier-terser/issues/46)

**Closed by slorber** 2020-10-20 17:41 UTC
Labels: bug, needs triage
