### ISSUE TITLE
docusaurus.config.js not found when running "docusaurus build --no-minify=true"

### ISSUE THREAD

**Issue by ggalli** [facebook/docusaurus#2999] opened 2020-06-26 14:05 UTC
## 🐛 Bug Report

I need to build the project with --no-minify=true

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes.

## To Reproduce

1. start a new docusaurus project with `npx @docusaurus/init@next init my-website classic`
2. run `yarn build --no-minify=true`

## Expected behavior

I expected to build without minify files.

## Actual Behavior

```
Error: docusaurus.config.js not found
    at Object.loadConfig (c:\works\teste\node_modules\@docusaurus\core\lib\server\config.js:43:15)
    at loadContext (c:\works\teste\node_modules\@docusaurus\core\lib\server\index.js:24:33)
    at Object.load (c:\works\teste\node_modules\@docusaurus\core\lib\server\index.js:52:21)
    at build (c:\works\teste\node_modules\@docusaurus\core\lib\commands\build.js:59:34)
    at args (c:\works\teste\node_modules\@docusaurus\core\bin\docusaurus.js:29:5)
    at Command.cli.command.description.option.option.option.action (c:\works\teste\node_modules\@docusaurus\core\bin\docusaurus.js:53:23)
    at Command.listener (c:\works\teste\node_modules\commander\index.js:370:29)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (c:\works\teste\node_modules\commander\index.js:892:12)
    at Command.parse (c:\works\teste\node_modules\commander\index.js:642:21)
    at Object.<anonymous> (c:\works\teste\node_modules\@docusaurus\core\bin\docusaurus.js:120:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Your Environment

- Docusaurus version used: 2.0.0-alpha.58
- Environment name and version: Node.js 10.20.1

**Comment by slorber** [comment] 2020-06-26 14:38
Hi,

did you cd in the created folder? did you use yarn build without the option to see if it works better?

The code is so simple that I doubt there's a bug due to the option:


```js
  const configPath = path.resolve(siteDir, CONFIG_FILE_NAME);

  if (!fs.existsSync(configPath)) {
    throw new Error(`${CONFIG_FILE_NAME} not found`);
  }
```

So you likely are in the wrong folder

**Comment by ggalli** [comment] 2020-06-26 16:36
Hi,
I'm sure I'm in the correct folder. Without the option it works nice and because of that I opened this issue.
I just created a new docusaurus project, cd in it and run `yarn build --no-minify=true`.
There's no secret to reproduce.

**Comment by slorber** [comment] 2020-06-26 18:26
yes I can reproduce on a freshly initialized project, this is weird :/

**Comment by rpajay** [comment] 2020-08-06 16:53
Facing the same issue on running 
```
ajay@ajay:~/code/my-website$ npm start run
> my-website@0.0.0 start /home/ajay/code/my-website
> docusaurus start "run"

Starting the development server...
Error: docusaurus.config.js not found
    at Object.loadConfig [as default] (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/server/config.js:20:15)
    at loadContext (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/server/index.js:46:40)
    at Object.load (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/server/index.js:74:21)
    at start (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/commands/start.js:44:34)
    at /home/ajay/code/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:73:5
    at Command.<anonymous> (/home/ajay/code/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:150:23)
    at Command.listener (/home/ajay/code/my-website/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/home/ajay/code/my-website/node_modules/commander/index.js:892:12)
    at Command.parse (/home/ajay/code/my-website/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/home/ajay/code/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:202:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-website@0.0.0 start: `docusaurus start "run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-website@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ajay/.npm/_logs/2020-08-06T16_45_19_773Z-debug.log
```
and 
```
ajay@ajay:~/code/my-website$ yarn build --no-minify=true
yarn run v1.21.1
$ docusaurus build --no-minify=true
Creating an optimized production build...
Error: docusaurus.config.js not found
    at Object.loadConfig [as default] (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/server/config.js:20:15)
    at loadContext (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/server/index.js:46:40)
    at Object.load (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/server/index.js:74:21)
    at build (/home/ajay/code/my-website/node_modules/@docusaurus/core/lib/commands/build.js:30:34)
    at /home/ajay/code/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:73:5
    at Command.<anonymous> (/home/ajay/code/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:97:23)
    at Command.listener (/home/ajay/code/my-website/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/home/ajay/code/my-website/node_modules/commander/index.js:892:12)
    at Command.parse (/home/ajay/code/my-website/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/home/ajay/code/my-website/node_modules/@docusaurus/core/bin/docusaurus.js:202:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by slorber** [comment] 2020-08-08 14:28
npm run start, not npm start run :) 


![image](https://user-images.githubusercontent.com/749374/89712913-3cffb680-d994-11ea-88d9-cbe38f689cea.png)

**Comment by lex111** [comment] 2020-11-10 15:20
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.

**Closed by lex111** 2020-11-10 15:20 UTC
Labels: bug, needs triage

**Comment by naim5am** [comment] 2021-04-25 16:11
I was facing the same issue. Running with clean  **node -v => v14.16.1** and **yarn --version => 1.22.10**
I had to **npm install @babel/core --save** to get going

**Comment by Korede-TA** [comment] 2023-03-15 20:49
Facing the same issue when i run docusaurus with `--out-dir` argument, adding the `--config` argument has the same issue
variations tried include:
```sh
# all these fail
docusaurus build --config docusaurus.config.js --out-dir ./build-staging
docusaurus build --config ./docusaurus.config.js
docusaurus build --out-dir ./build-staging

# only this works, but doesn't let me customize output directory
docusaurus build
```

made sure i created the `./build-staging` directory first. running node 16.7.0, and npm 8.15.0

---
UPDATE: tried defining the arguments as `--arg=val` instead of `--arg val` and it seems to work now!

**Comment by drwelby** [comment] 2023-06-20 17:14
Running into similar weirdness with the `--config` option:

`npm run start --config ./configs/draft/docusaurus.config.js` errors:

```
[INFO] Starting the development server...
[ERROR] No config file found.
[INFO] Expected one of:
- docusaurus.config.js
- docusaurus.config.cjs
You can provide a custom config path with the `--config` option.
```

Following the above post:

`npm run start --config=./configs/draft/docusaurus.config.js` runs, but it uses the default location instead of the path I provided.

and with a nonexistent file it also starts with the default config file:

`npm run docusaurus start --config=./foo/bar`

**Comment by Josh-Cena** [comment] 2023-06-20 17:21
@drwelby Have you tried `npm run start -- --config ./configs/draft/docusaurus.config.js`?

**Comment by drwelby** [comment] 2023-06-20 17:26
The extra `--` got it working, thanks!
