### ISSUE TITLE
Anchor links are not scrolled to automatically

### ISSUE THREAD

**Issue by Domiii** [facebook/docusaurus#6176] opened 2021-12-23 13:38 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Anchor links do not scroll to their position on the page (in fact, no scrolling happens).

### Steps to reproduce

I tried reproducing on https://codesandbox.io/s/docusaurus, but they ignore links entirely.

Locally:

1. Go to some page and copy some heading anchor link (e.g. http://localhost:3000/dbux/advanced/terminology#cgr).
2. Go to some other page.
3. Paste and go to the copied link.

I end up on the right page, but it does not scroll down to the correct heading.

I tried the same on the official page (e.g. https://docusaurus.io/docs/configuration#site-metadata), and there it works correctly.

### Expected behavior

When going to an anchor (hash) link of some sub heading on a page, it should scroll to the sub heading right away.

### Actual behavior

The link take you the correct page, but there is no scrolling.

### Your environment

- Public source code: https://github.com/Domiii/dbux/tree/master/docs
- Public site URL: (not public yet)
- Docusaurus version used: `2.0.0-beta.14` and `2.0.0-beta.13`
- Environment:
  `Node.js@16.13.0`
  Google Chrome | 96.0.4664.110 (Official Build) (64-bit) (cohort: Stable)
  Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664
  OS | Windows 10 Version 20H2 (Build 19042.1415)

### Reproducible demo

(cannot reproduce since direct links don't work at all on codepen)

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2021-12-23 13:41
Duplicate of https://github.com/facebook/docusaurus/issues/5272. We also have a notice here: https://docusaurus.io/docs/cli#docusaurus-start-sitedir

> Please note that some functionality (for example, anchor links) will not work in development. The functionality will work as expected in production.

**Closed by Josh-Cena** 2021-12-23 13:41 UTC
Labels: bug, verdict: duplicate
