### ISSUE TITLE
Version 2.0.0-beta.14 fails type check for typecsript

### ISSUE THREAD

**Issue by tonyneel923** [facebook/docusaurus#6262] opened 2022-01-05 00:18 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

Latest version of docusaurus fails typescript tsc with error `Cannot find module '@theme/BlogSidebar' or its corresponding type declarations.`

### Steps to reproduce

Init a new folder, and add packages and tsconfig as outlined here https://docusaurus.io/docs/typescript-support#setup

Then add a new command to your package.json `"typecheck": "tsc --noEmit"`

Finally run yarn typecheck

### Expected behavior

Fresh install has no errors.

### Actual behavior

There are fiver errors. `Cannot find module '@theme/BlogSidebar' or its corresponding type declarations.`

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.14
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome Version 96.0.4664.110, Node v16.3.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac Big sur 11.6.1

### Reproducible demo

Could not get terminal to work in code sandbox but this is very minimal to setup

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-01-05 04:27
Hi, I can't reproduce this. Our CI test also runs `tsc` on our website. We do have some type setup problems which I will fix in #6175 and subsequent PRs, but I haven't observed any problems so far unless you are using Yarn PnP. Could you try again with `create-docusaurus --typescript`? Do you have public source code?

**Comment by tonyneel923** [comment] 2022-01-05 15:56
Hello @Josh-Cena  if you add 
`,
  "include": [
    "src/"
  ]`

to your tsconfig you will get the errors as listed above.

**Comment by tonyneel923** [comment] 2022-01-05 15:58
Also I did just try again fresh install for a second time using --typescript and same issue. In the typescript support page it shows a tsconfig with an include but in the auto generated one it does not have the include attribute this is probably why you did not catch it in CI pipeline

**Comment by Josh-Cena** [comment] 2022-01-05 23:12
Oops! Can reproduce. Thanks for reporting😄

**Comment by tonyneel923** [comment] 2022-01-06 17:42
I do not think this should be closed. The above pr only fixes the documentation. In my project I need to add the include because of some other typescript scripts that I compile.

**Comment by Josh-Cena** [comment] 2022-01-06 23:12
If you have other scripts, you should use multiple tsconfigs. Since this one should not be used to emit code at all, it can be as wide as possible.

**Comment by tonyneel923** [comment] 2022-01-07 15:56
You are trying to say I should not have a tsconfig in the root of my app? This is a bug.

**Comment by Josh-Cena** [comment] 2022-01-08 05:29
You should have a `tsconfig.json` without any `includes` (i.e. including everything in the website folder) which is only used for typechecking, and another `tsconfig.build.json` which only includes the files you want to build. This is a pretty common pattern.

**Comment by Josh-Cena** [comment] 2022-01-10 06:28
Hi, after thinking it over, I do think this error has something to do with our toxic TS setup. Will investigate

**Comment by tonyneel923** [comment] 2022-01-31 16:57
Any update on this?

**Comment by slorber** [comment] 2022-02-02 10:44
@tonyneel923 is this issue annoying you in a concrete use-case for which you don't have a good-enough workaround?

If that's the case, please provide a repro where we can see the problem in practice, this will help us get it fixed sooner

**Comment by Josh-Cena** [comment] 2022-02-07 12:14
@tonyneel923 I'll be closing this in #6629. It has a possibility of fixing your issue since the `BlogSidebar` def is moved to `theme-classic`. However, I still do believe that removing the `include` option and including everything in your typechecking `tsconfig.json` is the right approach. If you are compiling something else, just use another tsconfig. It's impossible to be able to include all the types while only _compiling_ a subset.

**Closed** 2022-02-07 12:17 UTC
Labels: bug, status: needs more information
