### ISSUE TITLE
Only h2 and h3 will be in the toc

### ISSUE THREAD

**Issue by frank-lam** [facebook/docusaurus#2914] opened 2020-06-10 06:45 UTC
I am want to display the h2 - h6 toc in my right bar? Is there any config to display it ???

**Comment by yangshun** [comment] 2020-06-10 06:55
Not at the moment. Duplicate of https://github.com/facebook/docusaurus/issues/2700, please follow that one instead.

**Closed by yangshun** 2020-06-10 06:55 UTC
Labels: feature
