### ISSUE TITLE
CSS minification bug: File encoding is wrong on Windows

### ISSUE THREAD

**Issue by jp2masa** [facebook/docusaurus#10515] opened 2024-09-21 19:33 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

CSS minification produces an invalid css file, encoded as Windows 1252, on Windows. This breaks the paginator arrows, "«" and "»", and probably other strings.

### Reproducible demo

Not easy to create a demo as it would have to run on Windows.

### Steps to reproduce

1. Create a docusaurus project with docs (template should work)
2. Run `yarn build`
3. Open `build\assets\css\styles.{hash}.css`
4. Observe the encoding is wrong
    - e.g. previous arrow in docs paginator, matched by `.pagination-nav__link--prev .pagination-nav__label::before`, whose content should be `'« '`

Repeating the process with `yarn build --no-minify` works correctly.

~~**EDIT:** Setting `USE_SIMPLE_CSS_MINIFIER=true` works correctly as well.~~

**EDIT 2:** Apparently some caches affect the result (mainly the `.docusaurus` folder, I think). It seems to be a problem with CSS minification that does not depend on the used `cssnano` preset (the previous edit was wrong).

### Expected behavior

CSS minification produces a css file encoded as UTF-8 on all OSes.

### Actual behavior

CSS minification produces a css file encoded as Windows 1252 on Windows.

### Your environment

- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Any browser, Node.js v22.7.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 23H2 (22631.4169)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2024-09-21 20:24
Duplicate of https://github.com/facebook/docusaurus/issues/10465

**Closed by Josh-Cena** 2024-09-21 20:24 UTC
Labels: bug, status: needs triage
