### ISSUE TITLE
Browser runtime `require` error when user within ESM package

### ISSUE THREAD

**Issue by xobotyi** [facebook/docusaurus#9653] opened 2023-12-20 23:44 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

If to switch example docusaurus package type to module - following runtime error will be emitted within browser.
```
runtime~main.js:39 Uncaught ReferenceError: require is not defined
    at eval (client-modules.js:1:1)
    at ./.docusaurus/client-modules.js (main.js:1708:1)
    at __webpack_require__ (runtime~main.js:36:33)
    at fn (runtime~main.js:341:21)
    at eval (App.js:7:83)
    at ./node_modules/@docusaurus/core/lib/client/App.js (main.js:23:1)
    at __webpack_require__ (runtime~main.js:36:33)
    at fn (runtime~main.js:341:21)
    at eval (clientEntry.js:8:62)
    at ./node_modules/@docusaurus/core/lib/client/clientEntry.js (main.js:79:1)
eval @ client-modules.js:1
./.docusaurus/client-modules.js @ main.js:1708
__webpack_require__ @ runtime~main.js:36
fn @ runtime~main.js:341
eval @ App.js:7
./node_modules/@docusaurus/core/lib/client/App.js @ main.js:23
__webpack_require__ @ runtime~main.js:36
fn @ runtime~main.js:341
eval @ clientEntry.js:8
./node_modules/@docusaurus/core/lib/client/clientEntry.js @ main.js:79
__webpack_require__ @ runtime~main.js:36
__webpack_exec__ @ main.js:1786
(anonymous) @ main.js:1787
__webpack_require__.O @ runtime~main.js:83
(anonymous) @ main.js:1788
webpackJsonpCallback @ runtime~main.js:1336
(anonymous) @ main.js:9
```

### Steps to reproduce

1. Initialize docusaurus
2. Change type to module
3. Rename `babel.config.js` to `babel.config.cjs`
4. `docusaurus start` will succesfully start but runtime error will be emitted within browser

### Expected behavior

Site works

### Actual behavior

Runtime error

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome latest
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2023-12-21 11:00
We don't support ESM so I'd recommand to not use type module in the first place for now.

Duplicate of https://github.com/facebook/docusaurus/issues/6520

**Closed by slorber** 2023-12-21 11:00 UTC
Labels: bug

**Comment by xobotyi** [comment] 2023-12-21 11:36
😓 recomendations are good, but we have some packages that forces to change type to module.
okay, yet have to suspend documentation updates

**Comment by slorber** [comment] 2023-12-21 11:44
Which packages forces you to change to type module and why?

You can load ESM-only packages by using dynamic imports, or use the `.mjs` extension

**Comment by Josh-Cena** [comment] 2023-12-22 01:55
This is a weirdity of Webpack: it doesn't treat the absence of `type ` as `type: commonjs`. Rather, "no type", `type: module` and `type: commonjs` are three distinct entities and once you have an explicit `type` at the project root, you cannot go back to the "unspecified" state in a subpackage!

I would recommend setting up your website outside of the influence of your main project's package.json...

**Comment by mihajloS** [comment] 2025-02-10 09:10
Has this went past this point or it is sitll in "not-planned" status?

My project is using ESM and current docusaurus version is 3.9.

Console message is exactly the same even after introducing webpack plugin, babel reconfiguration and loader to try to affect `client-modules.js` format. If you alter `client-modules.js` to use import, manually next file in line has "require error " and so on.

**Comment by mihajloS** [comment] 2025-02-10 12:39
> Docusaurus v3.9 doesn't exist yet so I wonder how you could use it 😅
Sorry error in my time-machine 😅 I meant 3.7.

Thank you for the update!
