### ISSUE TITLE
Large CSS file import causes compilation error

### ISSUE THREAD

**Issue by waveflip** [facebook/docusaurus#8705] opened 2023-02-23 20:37 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm trying to import a large CSS file (~6000 lines) that is part of an SVG icon library. When I run ```npm run start``` I get a call stack size exceeded error and the compilation fails.

Reproducible demo:
https://stackblitz.com/edit/github-s2hpzp?file=src/components/HomepageFeatures/styles.module.css

### Reproducible demo

https://stackblitz.com/edit/github-s2hpzp?file=src/components/HomepageFeatures/styles.module.css

### Steps to reproduce

1. Import a css file with 6000 lines of code (i.e. an icon library stylesheet) into a component
2. Run ```npm run start```

### Expected behavior

Docusaurus compilation is successful.

### Actual behavior

Compiled with problems:

ERROR in ./src/components/HomepageFeatures/styles.module.css (./src/components/HomepageFeatures/styles.module.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].use[2]!./src/components/HomepageFeatures/styles.module.css)

Module parse failed: too much recursion
File was processed with these loaders:
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by advitiya7** [comment] 2023-07-15 07:40
@slorber can we send the css files using streams in node.js? as the streams sends the data in form of chunks

**Comment by slorber** [comment] 2023-07-20 12:16
@advitiya7 I know what streaming is but don't know how exactly you want docusaurus to use streams. If you have an idea on how this can be solved please submit a PR.

**Comment by advitiya7** [comment] 2023-07-20 12:21
@slorber i also don't have the exact idea but like while sending the files on the server using node js or express we can use streams at it divides the data in the form of chunks for the easy loading of the file.

**Comment by prathamVaidya** [comment] 2023-11-27 10:03
Assign it to me. I'll fix this.

**Comment by OzakIOne** [comment] 2023-11-27 13:53
Docusaurus maintainers don't assign issues to anyone @prathamVaidya , if you want to fix this just send a PR directly with your work

**Comment by prathamVaidya** [comment] 2023-11-30 12:17
@waveflip I am unable to reproduce the issue, maybe this was fixed by `css-loader` module itself. Can you confirm this? Even your web container is working without errors.

**Comment by slorber** [comment] 2023-11-30 20:27
Awesome news 😄

**Closed** 2023-11-30 20:27 UTC
Labels: bug
