### ISSUE TITLE
Wrong CSS for link in a comment `` inside :::info 

### ISSUE THREAD

**Issue by joseantgv** [facebook/docusaurus#5028] opened 2021-06-21 14:38 UTC
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io
- [ ] I have read the console error message carefully (if applicable)

### Description

This code generates a CSS issue:

```
:::info
Example [CSS `error`](https://www.google.com)
:::
```

![image](https://user-images.githubusercontent.com/5071263/122779764-7be9e280-d2ae-11eb-8c4e-e1faf3be83b3.png)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

https://codesandbox.io/s/sweet-greider-j7gsp?file=/docs/intro.md:29-86

## Expected behavior

It should not be `#FFFFFF` font color with `#F6F7F8` background color.

**Comment by Josh-Cena** [comment] 2021-06-21 15:20
Looks like a duplicate of #4781 but this is supposed to be fixed... 🤔

**Comment by Josh-Cena** [comment] 2021-06-21 23:46
This is a `beta-0` bug, and is fixed in `beta-1`. Consider updating docusaurus and see if it's fixed.

**Comment by slorber** [comment] 2021-06-22 08:46
Yes, this is supposed to be fixed, and you are probably not using beta.1 (so you are not using the latest version in practice)

**Closed by slorber** 2021-06-22 08:46 UTC
Labels: bug, needs triage

**Comment by joseantgv** [comment] 2021-06-22 15:55
After updating docusarurus with `npm i @docusaurus/core@latest @docusaurus/preset-classic@latest` to version `2.0.0-beta.1` the issue is fixed.
