### ISSUE TITLE
Empty md link make unworking site

### ISSUE THREAD

**Issue by lobanov4real** [facebook/docusaurus#8358] opened 2022-11-21 12:11 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

If I use in doc.md empty link my site of docusaurus is not working properly.

### Steps to reproduce

1. I create doc: general.md at doc section.
2. In this doc I write an empty link like this: ``[google]()`` and save doc.
3. I reload site and nothing work on site.

### Expected behavior

No site freezing.

### Actual behavior

No log errors, just site is freeze.

### Your environment

- Public source code: https://github.com/awesometic/docker-docusaurus
- Public site URL:
- Docusaurus version used: latest
- Chrome 107.0.5304.107, Node.js 18.12.1
-  Ubuntu 22.04.1 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by skirianov** [comment] 2022-11-21 22:28
I run the latest build and tried to reproduce it, but the error handler is taking care of that. Can you provide more data/screenshots?

This is the test file I used 

```
## TEST

Empty link - [google]()
Non empty link - [google.com](https://google.com)
```

**Path:** /docs/general.md

On save I've got the following error, the same error is displayed on the build 
`Error: Markdown link URL is mandatory in "docs/general.md" file (title: google.com, line: 3).`

**Comment by lobanov4real** [comment] 2022-11-22 07:54
I create an empty link and save doc:
![image](https://user-images.githubusercontent.com/110660329/203255333-96087e1b-888d-49a7-a824-5a991079f2f6.png)
When I open site and all links not working:
https://www.awesomescreenshot.com/video/12684273?key=2d0029e30057bf0b88a6b445a6e56cce
When I delete an empty link:
![image](https://user-images.githubusercontent.com/110660329/203256311-af522fd5-88f4-46d2-9b31-2a9e45620b20.png)
And site working correctly:
https://www.awesomescreenshot.com/video/12684335?key=a2e6f96302df07e9edb3c30a48e68e13

I use [docker image](https://github.com/awesometic/docker-docusaurus) for Docusaurus.

**Comment by slorber** [comment] 2022-11-23 17:14
Please create a smaller stackblitz repro, not using Docker

**Comment by Josh-Cena** [comment] 2022-12-03 00:43
I'm going to close this as can't repro, because as @skirianov pointed out, you are likely getting an error from using an empty link. Maybe the error message is not propagated to your terminal, or you didn't check your terminal for the error.

**Closed by Josh-Cena** 2022-12-03 00:43 UTC
Labels: bug, status: needs triage

**Comment by lobanov4real** [comment] 2022-12-03 08:57
Ok, sorry, I have no time to try @slorber variant. Maybe on next week I try and leave comment here.
