### ISSUE TITLE
announcementBar height and sidebar conflicts.

### ISSUE THREAD

**Issue by azeek21** [facebook/docusaurus#8789] opened 2023-03-17 18:27 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io.
- [x] I have read the console error message carefully (if applicable).

### Description

AnnouncementBar has fixed height which cuts content inside itself.

I guess they kept the height fixed so that it'll not mess up sidebar bottom which heavily depends on fixed annoucementBar height with it's `margin-bottom: var(--docusaurus-announcement-bar-height)` property. 

### Steps to reproduce

1. Open browser and visit Docusarus official website.
2. Inspect the page and set `--docusaurus-announcement-bar-height` to `auto`
3. Check bottom of sidebar with full content inside.

### Expected behavior

Shouldn't be fixed height or at least must respect content inside itself.

### Actual behavior

Stays 30px no matter how much content it has.

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2023-04-07 10:00
Duplicate of https://github.com/facebook/docusaurus/issues/8370 and https://github.com/facebook/docusaurus/issues/7815

**Closed by slorber** 2023-04-07 10:00 UTC
Labels: bug, status: needs triage
