### ISSUE TITLE
Responsibility issue

### ISSUE THREAD

**Issue by massoudmaboudi** [facebook/docusaurus#3958] opened 2020-12-28 09:06 UTC
## 🐛 Bug Report

I tried the main website and also I built a new website using v2.docusaurus and I noticed when the responsibility issue (horizontal scrollbar) in my system which is MacBook Pro 13 inches.
Also, the navbar has a save issue with a different screen width which described below.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

Visit the below page:
[https://v2.docusaurus.io/docs/markdown-features](https://v2.docusaurus.io/docs/markdown-features
)
## Expected behavior

1. It should not have a horizontal scrollbar on that page in Macbook Pro 13 inches. (13.3-inch (2560 × 1600))
2. The Navbar row should perform better in the below the range of width: (997px < screen width < 1425px)

(Write what you thought would happen.)

## Actual Behavior

1. It shows a horizontal scrollbar. (13.3-inch (2560 × 1600))
2. Navbar should show 2 rows properly in width: (997px < screen width < 1425px)

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used: 2.0.0-alpha.71
- Environment name and version: Chrome 87.0.4280.88 (Official Build) (arm64)
- Operating system and version (desktop or mobile): MacBook Pro 13 Inches (13.3-inch (2560 × 1600))

## Reproducible Demo

<img width="721" alt="1425px" src="https://user-images.githubusercontent.com/18216265/103202993-ea1ca080-492e-11eb-8b50-40e3eb3f9b06.png">
<img width="495" alt="997px" src="https://user-images.githubusercontent.com/18216265/103203005-f0128180-492e-11eb-8a54-be3ba7919d95.png">
<img width="572" alt="1143px" src="https://user-images.githubusercontent.com/18216265/103203006-f143ae80-492e-11eb-8b02-1c679abf789d.png">

**Comment by slorber** [comment] 2020-12-28 09:33
Hi,

I've mitigated this issue by replacing the "unreleased" label with a construction icon

![image](https://user-images.githubusercontent.com/749374/103204256-2e8c4a00-48f7-11eb-8114-816bf587ac05.png)

But we should find a solution. 
The problem is that the breakpoint really depends on the site navbar content. Some sites will work with 1 line with 997px width.

Closing because:
- Responsive navbar is duplicate of https://github.com/facebook/docusaurus/issues/3820 
- Scrollbar issue is duplicate of https://github.com/facebook/docusaurus/issues/3870

**Closed by slorber** 2020-12-28 09:33 UTC
Labels: bug, needs triage

**Comment by massoudmaboudi** [comment] 2020-12-29 00:31
@slorber 
I noticed the problem with the scrollbar is because of the CodeBlock. There is no issue for me in pages without a code block.
Also, When I set the width equal to a fixed size, it will remove the scrollbar. But When I set it to a percentage, still the problem persists.
