### ISSUE TITLE
Unable to use zenuml from mermaid

### ISSUE THREAD

**Issue by davidolrik** [facebook/docusaurus#9559] opened 2023-11-16 07:48 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

On a brand new installation of Docusaurus I wanted to create a sequence diagram using `zenuml`, which is part of mermaid since 10.2.3.

In order to add support for `zenuml` you have to install the support package `@mermaid-js/mermaid-zenuml` but unfortunately this package has conflicting dependencies with Docusaurus as seen here:

```
$ npm install --save @mermaid-js/mermaid-zenuml
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: flux@4.0.4
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peerOptional react@">= 16.8.0 < 19.0.0" from @docsearch/react@3.5.2
npm WARN   node_modules/@docsearch/react
npm WARN     @docsearch/react@"^3.5.2" from @docusaurus/theme-search-algolia@3.0.0
npm WARN     node_modules/@docusaurus/theme-search-algolia
npm WARN   32 more (@docusaurus/core, @docusaurus/mdx-loader, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
npm WARN node_modules/@microlink/react-json-view/node_modules/flux
npm WARN   flux@"~4.0.1" from @microlink/react-json-view@1.23.0
npm WARN   node_modules/@microlink/react-json-view
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^15.0.2 || ^16.0.0 || ^17.0.0" from flux@4.0.4
npm WARN   node_modules/@microlink/react-json-view/node_modules/flux
npm WARN     flux@"~4.0.1" from @microlink/react-json-view@1.23.0
npm WARN     node_modules/@microlink/react-json-view
```

### Steps to reproduce

1. `npx create-docusaurus@latest docusaurus classic`
2. `cd docusaurus`
3. `npm install --save @docusaurus/theme-mermaid`
4. `npm install --save @mermaid-js/mermaid-zenuml`

### Expected behavior

`@mermaid-js/mermaid-zenuml` would install cleanly, so mermaid markdown blocks with `zenuml` would render.

### Actual behavior

Unable to install `@mermaid-js/mermaid-zenuml`

### Your environment

Docusaurus 3.0.0
Node.js v20.9.0
macOS 14.1 (23B74)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by davidolrik** [comment] 2023-11-16 08:51
It seems that the culprit is `@docusaurus/plugin-debug` which dependes on `@microlink/react-json-view` which has this dependency `"flux": "~4.0.1"` defined that does not support React 18.

**Comment by davidolrik** [comment] 2023-11-16 08:58
More info here: https://github.com/mac-s-g/react-json-view/issues/403

**Comment by Josh-Cena** [comment] 2023-11-16 16:05
Duplicate of https://github.com/facebook/docusaurus/issues/9486. The error does not mention zenuml, so it surely comes from somewhere else!

**Closed by Josh-Cena** 2023-11-16 16:05 UTC
Labels: bug, status: needs triage
