### ISSUE TITLE
v2) Ability to associate content with a category

### ISSUE THREAD

**Issue by chrisdostert** [facebook/docusaurus#3686] opened 2020-11-04 19:53 UTC
## 🚀 Feature
Allow categories to have content i.e. be doc pages themselves.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

It's often the case you want the behavior that clicking on a category actually shows a page (index page) for that category.

You then of course can have sub categories or docs too.

## Pitch

Please see kubernetes "concepts" docs which observe this behavior. For example concepts/containers opens a page even though it's a category https://kubernetes.io/docs/concepts/containers/

**Comment by slorber** [comment] 2020-11-05 11:47
Duplicate of https://github.com/facebook/docusaurus/issues/2643

Note: Kubernete category is not collapsable. What's your suggestion for having a collapsible category that is also a link? What's the action on click?

**Closed by slorber** 2020-11-05 11:47 UTC
Labels: feature, needs triage

**Comment by chrisdostert** [comment] 2020-11-09 18:20
@slorber thanks for pointing me at that existing ticket. Re: action on click) i'd expect if you click on a category it will show the index of that category as well as showing any sub categories (i.e. expand that category) in the nav. I don't know the value of collapsing docs you're currently reading so additional clicks on the same category i'd expect to do nothing, clicks on other categories (whether sub categories, siblings, or parents) i'd expect to all just do the same.

**Comment by slorber** [comment] 2020-11-10 10:19
I thunk this could be confusing,  can you find an example online reproducing this behavior?

Also it's better to move the discussions to the opened issue

**Comment by chrisdostert** [comment] 2020-11-10 15:17
@slorber re: example online) yes it's exactly how the k8s docs linked above work

**Comment by slorber** [comment] 2020-11-12 14:11
@chrisdostert the K8s doc is not an SPA and does not really have collapsible sidebars. 
The sidebar remains static over the lifetime of the page, there is no arrow that will rotate, you just click a link and goes to another page with a different sidebar in a different state.

But this is a mode we could support in Docusaurus: remove the arrow, navigate on click, and only expand the sidebar when we navigate inside the sidebar category (including category-associated doc)
