### ISSUE TITLE
Page scroll on search (Website)

### ISSUE THREAD

**Issue by kalinpatel** [facebook/docusaurus#4088] opened 2021-01-22 16:24 UTC
## 📚 Documentation

When on the documentation website, pressing search, then clicking escape or clicking away from the search scrolls the page to the bottom. This is unexpected, as I would assume to be in the same place that I left off at.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

**Comment by slorber** [comment] 2021-01-27 15:58
Hi,

I can't reproduce this behavior on Docusaurus 2 website, so I'm closing.

Feel free to provide much more details on how to reproduce exactly, and I'll re-open.

**Comment by kalinpatel** [comment] 2021-01-27 20:18
This seems to be on Safari only. Here is a quick recording of what occurred for me. (the first time was via clicking on the search field, the second time was by pressing CMD+K)

https://user-images.githubusercontent.com/52113248/106048459-89f25900-60aa-11eb-8902-97a5b2c2b87a.mov

**Comment by slorber** [comment] 2021-01-28 15:30
Thanks, I can reproduce that on safari 😓

**Comment by slorber** [comment] 2021-01-28 15:38
@shipow @francoischalifour afaik the scroll lock/restore is managed by DocSearch. Do you know about this scroll problem on Safari? Does it affect other DocSearch v3 deployments or it's just a Docusaurus problem?

**Closed** 2021-02-08 14:57 UTC
Labels: documentation, needs triage
