### ISSUE TITLE
front matter validation does not print a good error message

### ISSUE THREAD

**Issue by wenerme** [facebook/docusaurus#8230] opened 2022-10-20 05:30 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

```
ValidationError: "title" must be a string
```

without context, I don't know where to look at

https://github.com/wenerme/wener/actions/runs/3286799524/jobs/5415286638

### Steps to reproduce

```bash
git clone git@github.com:wenerme/wener.git
cd wener/site

pnpm install
make build
```

### Expected behavior

Works as before

### Actual behavior

```
[ERROR] The following front matter:
---
title: null
---
contains invalid values for field(s): `title`.

- "title" must be a string

[ERROR] Loading of version failed for version current
[ERROR] Unable to build website for locale en.
[ERROR] ValidationError: "title" must be a string
```

### Your environment

- Public source code: https://github.com/wenerme/wener
- Public site URL: https://wener.me
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2022-10-20 08:11
Hey,

You have a markdown file that has `title: null` frontmtter that is not allowed by validation. This is the intended behavior.

> without context, I don't know where to look at

I can agree that we don't make it easy to find the original md file that has the problem, so I'll consider it as a bug: we should at least print the file path in the error message

> Works as before

What does it even mean? How did it work before exactly? What did you change that led to this new failure?

**Comment by slorber** [comment] 2022-10-20 08:45
Added a local try/catch in our code and was able to print the problematic doc:

```js
Inject custom docs filter
[ERROR] The following front matter:
---
title: null
---
contains invalid values for field(s): `title`.

- "title" must be a string

failed to process doc {
  source: 'web/framework/uniapp.md',
  content: '---\n' +
    'title:\n' +
    '---\n' +
    '\n' +
    '# uniapp\n' +
    '\n' +
    '- [dcloudio/uni-app](https://github.com/dcloudio/uni-app)\n' +
    '  - Apache-2.0, Vue\n',
  contentPath: '/home/wenerme/wener/notes',
  filePath: '/home/wenerme/wener/notes/web/framework/uniapp.md'
}
[ERROR] The following front matter:
---
title: null
---
contains invalid values for field(s): `title`.

- "title" must be a string

[ERROR] Loading of version failed for version current
[ERROR] ValidationError: "title" must be a string
[INFO] Docusaurus version: 2.1.0
Node version: v16.14.2
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by slorber** [comment] 2022-10-20 08:49
We are supposed to print a better error message, unfortunately the failure is swallowed because we don't await the returned promise:

```js
export function processDocMetadata(args: {
  docFile: DocFile;
  versionMetadata: VersionMetadata;
  context: LoadContext;
  options: MetadataOptions;
  env: DocEnv;
}): Promise<DocMetadataBase> {
  try {
    return doProcessDocMetadata(args);
  } catch (err) {
    logger.error`Can't process doc metadata for doc at path path=${args.docFile.filePath} in version name=${args.versionMetadata.versionName}`;
    throw err;
  }
}
```

Also a good opportunity to replace this code with the new Error Cause system (our Node.js version supports it)

---

A good first issue to solve for external contributors. 

Please sent a PR directly if you can handle it (don't ask to claim it).

**Comment by shermanhui** [comment] 2022-10-21 03:29
@slorber I'm looking to get more involved in larger open-source projects - this looks like a great first opportunity.

> Also a good opportunity to replace this code with the new Error Cause system (our Node.js version supports it

Could you point me to where I can find more info about the Error Cause system you mentioned and how I can leverage that to resolve this issue?

In the meantime, I'll try to take a look at this on my own - thanks!

**Comment by slorber** [comment] 2022-10-21 07:40
@shermanhui as mentioned above, if you want to contribute you can directly open a PR. If I have to spend time explaining things to you, it will be faster for me to solve the bug myself. Error Cause is a standard EcmaScript feature, you will find everything on Google or in the spec

@shanpriyan opened a PR already so it is too late now for this issue, but you can open a PR to another one if you want

**Comment by wenerme** [comment] 2022-10-21 10:43
I don't know is this related or not, but the katex error is also masked

https://github.com/wenerme/wener/actions/runs/3296716113/jobs/5436697247

```
Error: Cannot handle unknown node `inlineMath`
```

Have no idea which file(maybe this https://github.com/wenerme/wener/blob/master/notes/algorithm/ml/cs221-reflex.md), which line cause the error.

**Comment by Jaya-sys** [comment] 2022-10-23 22:17
Hey, can you assign this issue to me?

**Comment by slorber** [comment] 2022-10-26 12:26
@Jaya-sys we won't assign any issue to someone not willing to even read previous comments on the issue claimed. Please be responsible

**Comment by slorber** [comment] 2022-10-26 12:26
> cause is founded but the problem is missing file context

@wenerme that's a different problem, I suggest opening another issue for it

**Closed** 2022-10-26 12:48 UTC
Labels: bug, good first issue, hacktoberfest
