### ISSUE TITLE
Navbar doc link versions support

### ISSUE THREAD

**Issue by fantua** [facebook/docusaurus#4972] opened 2021-06-15 10:47 UTC
## 🚀 Feature

We have few navbar items as a doc links: 
```js
{
  label: 'Server',
  position: 'left',
  to: 'docs/server/getting-started',
},
```
When navigating in previous version docs click on `Server` switches to the latest docs. As a result, we lose the "version context". 
An option could be [navbar doc link](https://docusaurus.io/docs/next/api/themes/configuration#navbar-doc-link) usage, but it doesn't work with versioned docs:
```js
{
  type: 'doc',
  label: 'Server',
  position: 'left',
  docId: 'server/getting-started',
},
```
this will work for version 5 and 4 (cause both of them have this doc), but for version 3 there will be an error:

> Uncaught Error: DocNavbarItem: couldn't find any doc with id=server/getting-started in version 3.x.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

✅ 

## Motivation

It could be very useful to support versioned doc links in Navbar.

## Possible solution

Add a fallback logic (activeVersion -> preferredVersion -> latestVersion) in `DocNavbarItem` could be a way to go:
https://github.com/facebook/docusaurus/blob/073fdeae8eea3cf13e27fcc7f0a9fe5265fad84c/packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx#L22-L35

or new navbar item `type` with similar logic

**Comment by slorber** [comment] 2021-06-15 12:42
Having a better fallback makes sense.

Maybe we could expect `latestVersion` to contain that doc id in most cases, as you generally want to target recent/latest docs from your navbar (ie in your case 5.x). 

Eventually, add a way to provide a custom link (we need to + label here)

**Comment by fantua** [comment] 2021-06-15 13:26
> Maybe we could expect latestVersion to contain that doc id in most cases, as you generally want to target recent/latest docs from your navbar (ie in your case 5.x).

👍

**Comment by slorber** [comment] 2021-06-16 10:57
Will be fixed in https://github.com/facebook/docusaurus/pull/4985

Please test the latest `@canary` npm dist tag release as soon as it is merged to be sure it fixes your issue

**Closed** 2021-06-16 11:18 UTC
Labels: feature, needs triage

**Comment by fantua** [comment] 2021-06-16 14:12
@slorber works as expected, thanks!

now we have another issue 😄 
[Navbar dropdown](https://docusaurus.io/docs/next/api/themes/configuration#navbar-dropdown) items doesn't support `type` prop. We have a dropdown and I would like to use `type='doc'` there as well

Possible solution will be to use [getNavbarItemComponent](https://github.com/facebook/docusaurus/blob/073fdeae8eea3cf13e27fcc7f0a9fe5265fad84c/packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx#L32) here:
https://github.com/facebook/docusaurus/blob/073fdeae8eea3cf13e27fcc7f0a9fe5265fad84c/packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx#L122-L129

**Comment by slorber** [comment] 2021-06-16 14:41
> We have a dropdown and I would like to use type='doc' there as well

Not sure what you mean here. It is either the default navbar item, or the docs navbar item, it can't be both at the same time. 

Please show me the exact config you want to use and the behavior you expect

**Comment by fantua** [comment] 2021-06-16 15:15
> @slorber works as expected, thanks!

actually it doesn't work with production build 

```
main.6ec3c0e3.js:2 TypeError: Cannot read property 'id' of undefined
    at 1808.842f0660.js:1
    at Array.find (<anonymous>)
```

error on this line:
https://github.com/facebook/docusaurus/blob/59f78f9084e1d19485ea97b1178499775a48cbdc/packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx#L25

> Please show me the exact config you want to use and the behavior you expect

```js
items: [
  {
    type: 'docsVersionDropdown',
    position: 'right',
  },
  {
    type: 'doc',
    label: 'Docs',
    position: 'left',
    docId: 'welcome',
  },
  {
    label: 'Flows',
    position: 'left',
    items: [
      {
        // works:
        label: 'Library Flow',
        to: 'docs/library-flow/overview'
      },
      {
        // doesn't work:
        type: 'doc',
        label: 'App Flow',
        position: 'left',
        docId: 'app-flow',
      },
    ],
  },
```

**Comment by slorber** [comment] 2021-06-16 17:39
> actually it doesn't work with production build

It works for me, I'll need a GitHub repo repro to debug this

> Please show me the exact config you want to use and the behavior you expect

```
  {
    label: 'Flows',
    position: 'left',
    items: [
      {
        // works:
        label: 'Library Flow',
        to: 'docs/library-flow/overview'
      },
      {
        // doesn't work:
        type: 'doc',
        label: 'App Flow',
        position: 'left',
        docId: 'app-flow',
      },
    ],
```

Yes, having a type for subitems is not something we support currently. 

Thinking about it, it wouldn't make sense either to nest a version dropdown inside a regular dropdown (or we would have to support multi-level dropdowns somehow). 

I guess supporting a few types like "doc" for subitems can make sense, but it's worth opening a totally separate issue for that, as it's a new feature.

**Comment by fantua** [comment] 2021-06-17 14:39
> It works for me, I'll need a GitHub repo repro to debug this

https://github.com/fantua/docusaurus 

let me know if you need anything else

**Comment by slorber** [comment] 2021-06-18 09:21
found the cause, for some reason my array deduplication logic is transpiled in a wrong way. Will open a PR and fix this for beta.1

```
// Source:
[...new Set([{}, {}])]
// => [{},{}]

// prod build
[].concat(new Set([{},{}]))                        
// => [Set(2)]
```

**Comment by slorber** [comment] 2021-06-18 09:44
Fixed in https://github.com/facebook/docusaurus/pull/5000
