### ISSUE TITLE
[V2] viewing Docusaurus V2 site through Google Translate causes 'page not found'

### ISSUE THREAD

**Issue by goransle** [facebook/docusaurus#1927] opened 2019-11-01 09:15 UTC
## 🐛 Bug Report

When viewing a Docusaurs (V2) site via Google Translate it ultimately routes to 'page not found' after a brief flash of translated page. [Example using the Docusaurus v2 docs](https://translate.google.com/translate?hl=no&sl=en&tl=no&u=https%3A%2F%2Fv2.docusaurus.io%2Fdocs%2Flifecycle-apis)

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

1. Open a web browser
2. Go to https://translate.google.com/translate?hl=no&sl=en&tl=no&u=https%3A%2F%2Fv2.docusaurus.io%2Fdocs%2Flifecycle-apis

## Expected behavior

Should not route to 'page not found'

## Actual Behavior

Routes to 'page not found' after a brief glimpse of the actual page.

## Reproducible Demo

N/A

**Comment by yangshun** [comment] 2019-11-03 23:53
Related to https://github.com/gatsbyjs/gatsby/issues/6300 as mentioned by @lex111

**Comment by endiliey** [comment] 2019-11-04 04:44
iirc gatsby also had this problem, technically all app that uses client side routing had this problem.

Reactjs.org also had it ：（
https://github.com/reactjs/reactjs.org/issues/467

**Comment by lex111** [comment] 2019-11-04 13:35
The problem is relevant for all of them now. I wonder if it’s possible to simply turn off client routing when viewing with Google Translate?

**Comment by endiliey** [comment] 2019-11-06 11:41
Well actually there's also a bug in Google Translate for React. See https://bugs.chromium.org/p/chromium/issues/detail?id=872770

I am thinking that maybe the right fix/ workaround for ours is to check if we're in an iframe, and don't React.hydrate if that's the case. Just let everything be static site.

This shouldn't be hard in our case
https://github.com/facebook/docusaurus/blob/ff83e6f8bc2b8fb0cee58cab2e05ccb781a9661e/packages/docusaurus/src/client/clientEntry.js#L17-L31

**Comment by lex111** [comment] 2021-02-27 22:47
Accidentally noticed that now this problem does not cause when trying to translate a Docusaurus site via Google Translate. I think we can close the issue for now.

**Closed by lex111** 2021-02-27 22:47 UTC
Labels: bug, help wanted, v2
