### ISSUE TITLE
ClassicTheme ColorModeToggle shows both icons in Firefox

### ISSUE THREAD

**Issue by mattcorner** [facebook/docusaurus#9582] opened 2023-11-24 16:24 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When a Docusaurus 3 site using the classic theme is built, in Firefox, the toggle colour mode button shows both icons rather than the single icon for the current mode.

This works fine in other browsers, and works fine in Firefox when using `npm run start`. 

The issue on occurs when running `npm run build && npm run serve`

### Reproducible demo

https://codesandbox.io/p/sandbox/divine-sky-wcnrpr

### Steps to reproduce

1. `npx create-docusaurus@latest doc classic --typescript`
2. `npm run build && npm run serve`

### Expected behavior

Expect the button to be either:

![image](https://github.com/facebook/docusaurus/assets/27866636/25d4551b-904d-4b7c-aff3-fe341f230ec1)
![image](https://github.com/facebook/docusaurus/assets/27866636/ecd4a391-8050-41e7-a549-711fa08c35cc)

### Actual behavior

Actually seeing this:

![image](https://github.com/facebook/docusaurus/assets/27866636/6df50c36-ecec-4001-a7c0-d62367a0a2f5)
![image](https://github.com/facebook/docusaurus/assets/27866636/72742097-731a-41cc-a4cb-927b8c5b1a75)

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 120.0 (64-bit)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Seen on MacOS and Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-11-24 17:01
Duplicate of https://github.com/facebook/docusaurus/issues/9493

**Closed by Josh-Cena** 2023-11-24 17:02 UTC
Labels: bug, status: needs triage
