### ISSUE TITLE
Cant use subdirectories for sidebar subcategory

### ISSUE THREAD

**Issue by BrendanThompson** [facebook/Docusaurus#1446] opened 2019-05-10 09:26 UTC
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Add a `subcategory` to the sidebar for a subdirectory

```
{
  "products": {
    "Products": [
        "products/cool-app",
        {
            "type": "subcategory",
            "label": "My Example Subcategory",
            "ids": [
              "products/cool-app/architecture"
            ]
        },
        "products/derp"
    ]
  }
```

## Expected behavior

There would be a subcategory present with the links to the subdirectory as declared.

## Actual Behavior

No links were shown, the subcategory didn't show up at all.

## Reproducible Demo

Whilst I cannot paste the entire thing here or link to it, in the above it outlines the `sidebars.json` segment which is in question. Happy to provide other information if required and possible.

**Comment by endiliey** [comment] 2019-05-10 09:53
What version of Docusaurus are you using ?
Have u tried restarting your server ?
Do you include "products/cool-app/architecture" in any other sidebar ?

Please create a reproducible demo. A repo that we can clone and run locally.

I could not reproduce it. It works fine in our Docusaurus v1

![image](https://user-images.githubusercontent.com/17883920/57518798-7a6a3400-734c-11e9-8ef7-e5fb45b1ede7.png)


```json
// sidebars.json
{
  "docs": {
    "Getting Started": [
      "installation",
      {
        "type": "subcategory",
        "label": "My Example Subcategory",
        "ids": [
          "test/hello"
        ]
      },
      "site-creation",
      "publishing",
      "docker"
    ],
    "Guides": [
      "adding-blog",
      "custom-pages",
      "search",
      "navigation",
      "translation",
      "versioning"
    ],
    "API": [
      "commands",
      "doc-markdown",
      "api-pages",
      "site-config"
    ]
  },
  "tutorial": {
    "Tutorial": [
      "tutorial-setup",
      "tutorial-create-new-site",
      "tutorial-create-pages",
      "tutorial-publish-site",
      "tutorial-version"
    ]
  }
}

```

**Comment by amimas** [comment] 2019-05-11 01:22
I am currenrly using v1 with subdirectories in subcatergory.

Make sure you have your doc file in "docs/products/cool-app/" and the `id` of the front matter is set to "architecture".

**Comment by endiliey** [comment] 2019-05-11 07:59
I am going to close this out. @amimas has helped to confirm that this is not a bug too.

Chat us on discord for faster help -> https://discordapp.com/invite/docusaurus

**Closed by endiliey** 2019-05-11 07:59 UTC
Labels: needs more information

**Comment by BrendanThompson** [comment] 2019-05-13 00:19
It looks as though its because I reference the same page in another `SideBar`. Thats a bit of a pain!

**Comment by amimas** [comment] 2019-05-13 08:05
Interesting. Maybe this can be a new feature request (using same page in multiple sidebars)
