### ISSUE TITLE
Azure AD Login implementation for authorizing user to see private documents

### ISSUE THREAD

**Issue by vkrishnak-hexaware** [facebook/docusaurus#7837] opened 2022-07-27 05:51 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

I am trying to implement azure ad login where user is authorized to see the documentation site. Is there a way to implement this? Any suggestions and comments can help. Thanks!

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment] 2022-07-27 05:53
Duplicate of https://github.com/facebook/docusaurus/issues/6890.

Please don't use the issue tracker as a support forum. Please ask in discussions instead—and give more details about how the authentication system is expected to be interacted with. Remember, Docusaurus is just a React app, so you implement any API calls the same way as normal React app.

**Closed by Josh-Cena** 2022-07-27 05:53 UTC
Labels: documentation, status: needs triage
