### ISSUE TITLE
Admonitions broken in .mdx files as of v2.0 alpha.50

### ISSUE THREAD

**Issue by markerikson** [facebook/docusaurus#2551] opened 2020-04-05 19:38 UTC
## 🐛 Bug Report

Docusaurus is no longer correctly parsing admonition blocks in files with a `.mdx` extension as of alpha.50.  They worked correctly in alpha.48 .

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a project using v2 alpha.48
2. Create a `.mdx` file and add an admonition, like:

```
:::note
The content and title *can* include markdown.
:::
```

3. Start the dev server and note that the admonition appears correctly in the page
4. Update the project to alpha.50
5. Restart the dev server and note that the admonition is no longer rendered correctly - instead, the plain text is inserted, indicating it wasn't parsed at all:

![image](https://user-images.githubusercontent.com/1128784/78508192-f20a3400-7752-11ea-8d2f-bfe21509a9cc.png)

6. Still on alpha.50, rename the file to `.md`.  The page should now render correctly (exact appearance dependent on project styling):

![image](https://user-images.githubusercontent.com/1128784/78508224-182fd400-7753-11ea-8067-379b70f05bd3.png)

## Expected behavior

The admonition should have continued rendering correctly when used in a `.mdx` file.

## Actual Behavior

Had to rename to `.md` to get the admonitions to show up.

## Your Environment

Went from alpha.48 to alpha.50 in the Redux repo while working on https://github.com/reduxjs/redux/pull/3740

## Reproducible Demo

https://github.com/reduxjs/redux/tree/c7ed4c64e48763226f5710416feb100068a0cc34 as the starting point using alpha.48 .  Update to `alpha.50` and you should see this behavior.

**Comment by yangshun** [comment] 2020-04-05 19:53
Instead of 

```
:::note
The content and title *can* include markdown.
:::
```

try 

```
:::note

The content and title *can* include markdown.

:::
```

with the empty lines around the content. See if it helps.

**Comment by markerikson** [comment] 2020-04-05 19:58
Was doing that already:

```
# Quick Start, Part 1: Redux Concepts and Structure

:::tip What You'll Learn

- What Redux is and why you might want to use it
- Key Redux terms and concepts
- The structure of a typical React + Redux app

:::
```

**Comment by lex111** [comment] 2020-04-09 06:50
I could not reproduce it locally, it works for me correctly:

```bash
git clone git@github.com:reduxjs/redux.git
cd redux
git checkout docs/create-quick-start-take-2
cd website
# bump vers to .50
yarn
yarn start
# navigate to http://localhost:3000/tutorials/quick-start/quick-start-part-1
```

Result:

![image](https://user-images.githubusercontent.com/4408379/78866003-4eb56980-7a47-11ea-81b4-f27a653bcc67.png)

Try removing `node_modules` dir and reinstalling deps.

**Comment by lex111** [comment] 2020-04-21 21:45
@markerikson can I close this issue? It is rather related to deps, because I could not reproduce it.

**Comment by markerikson** [comment] 2020-04-21 22:24
Let me try it again this evening.

**Comment by lex111** [comment] 2020-04-27 19:22
In order to reduce staled issues, I am closing this issue, but feel free to open it again if you run into this again.

**Closed by lex111** 2020-04-27 19:22 UTC
Labels: bug, difficulty: intermediate, help wanted

**Comment by markerikson** [comment] 2020-04-27 19:25
Yeah, I've been otherwise occupied.  I'll let you know when I have a chance to look at it.

**Comment by markerikson** [comment] 2020-05-03 19:57
Just tried this on alpha.54 and it appears to be working fine.  Thanks!
