### ISSUE TITLE
Docs layout issue: content container does not grow to take all the available space

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#8369] opened 2022-11-24 13:55 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The docs layout looks particularly weird when sidebar/content is smaller than viewport, which is likely to be the case on small pages + vertical screen

![CleanShot 2022-11-24 at 14 51 42](https://user-images.githubusercontent.com/749374/203800613-86aa6e2f-3ed5-460f-9f58-95cc93cfa469.png)

Follow-up of bug discussed in:
- https://github.com/facebook/docusaurus/pull/8328#issuecomment-1326466597
- https://github.com/facebook/docusaurus/issues/4415

### Steps to reproduce

https://docusaurus.io/tests/docs/doc-with-another-sidebar

### Expected behavior

The content container (sidebar + main) should grow

### Actual behavior

The content container does not expand

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by RavenColEvol** [comment] 2022-12-03 13:41
Can someone close this Issue if it's completed?

**Comment by 0916dhkim** [comment] 2022-12-03 19:12
It's not completed yet. The issue is still there.

**Comment by Djunnni** [comment] 2022-12-19 17:49
if this #8463 PR is finish, i will do some of work for #8370

**Closed** 2022-12-22 18:20 UTC
Labels: bug, help wanted, good first issue

**Comment by Briffou** [comment] 2023-02-11 17:58
I feel like I still have this issue on a fresh docusaurus 2.3.1 install, where I simply added
```
      docs: {
         sidebar: {
            hideable: true,
         },
      },
```
inside docusaurus.config.js
![capture](https://user-images.githubusercontent.com/18452695/218273375-e4ec324e-641c-4a0d-90f8-0f9b1344750c.png)

**Comment by Tandashi** [comment] 2023-02-21 17:25
In case someone finds this and still has the same issue. I added the following to my custom css file:
```css
/* Full Size Sidebar */
.main-wrapper > div {
  flex: 1 0
}
```

**Comment by slorber** [comment] 2023-02-22 17:23
Will look into it, indeed it seems we have a little flex problem.

Not related to the hideable sidebar, can also be seen here:

https://tutorial.docusaurus.io/docs/tutorial-basics/congratulations/

![CleanShot 2023-02-22 at 18 22 46](https://user-images.githubusercontent.com/749374/220706869-ec906374-c2c9-4347-a288-2df9c111aed1.png)


@Tandashi do you want to send a PR?

**Comment by Tandashi** [comment] 2023-02-22 17:38
@slorber Sure, will try my best

**Comment by Tandashi** [comment] 2023-02-22 18:48
@slorber Looks like it's already fixed in the `3.0.0-alpha.0` version. At least the tutorial page (`examples/classic`) renders as it should.

**Comment by slorber** [comment] 2023-02-24 13:36
Thanks, looks like you are right and it's fixed already! See prod URL: https://docusaurus.io/tests/docs/more-test

Looks like this issue has been fixed in https://github.com/facebook/docusaurus/pull/7966 and it's a breaking change pr and not backported to 2.x

Will do a quick fix for docusaurus-v2 branch

**Comment by slorber** [comment] 2023-02-24 13:49
should be fixed in https://github.com/facebook/docusaurus/pull/8707
