### ISSUE TITLE
Cannot install if user folder contain spaces on Windows.

### ISSUE THREAD

**Issue by Xarkam** [facebook/Docusaurus#1217] opened 2019-02-01 15:58 UTC
## 🐛 Bug Report
In accordance with documentation, `npx docusaurus-init` cannot install in my windows user folder because, I have spaces in name.

I discovered this after analyzing installation log.

```
info using npm@6.4.1
info using node@v10.14.0
silly fetchPackageMetaData error for file:Xarkam\AppData\Roaming\npm-cache\_npx\8596 Could not install from "Xarkam\AppData\Roaming\npm-cache\_npx\8596" as it does not contain a package.json file.
verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "docusaurus-init@latest" "--global" "--prefix" "C:\\Users\\Xarkam" "Xarkam\\AppData\\Roaming\\npm-cache\\_npx\\8596" "--loglevel" "error" "--json"
error Could not install from "Xarkam\AppData\Roaming\npm-cache\_npx\8596" as it does not contain a package.json file.
```

The correct path is `"C:\\Users\\Xarkam Xarkam\\AppData\\Roaming\\npm-cache\\_npx\\8596"` but the cli cut into two argments because of the space.

**Comment by endiliey** [comment] 2019-03-28 12:34
I use window myself and was not able to reproduce this

![image](https://user-images.githubusercontent.com/17883920/55157913-98167c00-5198-11e9-98a1-9e3ca3a2cf3c.png)

Furthermore, the cli for docusaurus-init does not take any argument. It installs in the current folder. As you can see in above screenshot, my folder name is even `spaces spaces spaces` and it still works. 

Do you mind to send in screenshots or videos and report it if it still persists ? Thank you

**Comment by Xarkam** [comment] 2019-03-28 15:14
Hello and thank you for your answer.

Are you serious?

I give you an example in powershell/Dos and you answer me with ubuntu for windows.

If it's something linux only, please update your documentation.

**Comment by JoelMarcey** [comment] 2019-03-28 15:27
@Xarkam I don’t think questioning @endiliey’s seriousness of his response is helpful or called for. He took the time to provide a thoughtful answer and asked for more information if you had it. In no way was he condescending to you, and I would hope for the same level of respect in return. Thank you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by endiliey** [comment] 2019-03-28 15:27
My bad. I wasn't aware that it was on powershell/dos. There is no mention on it. 

I wasn't able to reproduce it even with command prompt though.

![image](https://user-images.githubusercontent.com/17883920/55169801-5b567f00-51b0-11e9-9c5f-20ae5afd5a05.png)

**Comment by endiliey** [comment] 2019-03-28 15:35
I'm really sorry. I still couldn't reproduce it.

![image](https://user-images.githubusercontent.com/17883920/55170629-d9675580-51b1-11e9-9043-67142ff3f8af.png)

If you don't mind, you can send us a screenshot/video to better describe the situation. 
I'll be happy to do my best to help and *maybe we can fix it*. 😉

**Comment by Xarkam** [comment] 2019-03-28 15:51
@endiliey thank you for response as part of my problem.
@JoelMarcey do you think that the first answer is in the context of my problem? I do not think so.

@endiliey I will take some time tomorrow to redo the procedure as indicated in the documentation.
It may be that in the meantime an update will fix the problem. Otherwise, it will be necessary to understand it cuts the path in two parts on my system

**Comment by JoelMarcey** [comment] 2019-03-28 16:40
> @JoelMarcey do you think that the first answer is in the context of my problem? I do not think so.

@Xarkam That's actually not the point. Whether the initial response answered your question, there are more appropriate and respectful ways to make your disagreement known than "Are you serious?".

```
s/Are you serious?/Thank you for taking the time to try to provide an answer, but I don't think it fully captures the issue.

s/Are you serious?/I see you tried that using Ubuntu via Powershell. Could you please try using Windows directly?

s/Are you serious?/I believe you may not have captured the essence of my question because you were using Ubuntu and not Windows.
```

@endiliey is one of our most active and prolific Docusaurus contributors who is really trying to help improve Docusaurus. In no way was he purposely not trying to answer your question. 

It is quite clear the essence of your response was disparaging. Maybe it wasn't on purpose, I hope not.

Anyway, I appreciate you filing a bug report and it looks like there may be a path forward to continue to try to resolve this issue. I am going to consider this ancillary matter closed so that we can continue down the technical discussion path.

Thanks.

**Comment by JoelMarcey** [comment] 2019-03-28 16:54
Also, for now I will reopen this issue since it sounds like there may be some continued work towards a resolution here.

**Comment by Xarkam** [comment] 2019-03-29 07:38
Hello, I just testing this morning.
![image](https://user-images.githubusercontent.com/331816/55216346-c8900180-51fc-11e9-9761-05abbc0a4d45.png)
![image](https://user-images.githubusercontent.com/331816/55216357-d0e83c80-51fc-11e9-9c45-29ce2736d90d.png)
Run install in normal user mode
![image](https://user-images.githubusercontent.com/331816/55216377-df365880-51fc-11e9-84ca-28db306d01c4.png)
Run install in admin user mode
![image](https://user-images.githubusercontent.com/331816/55216391-e8bfc080-51fc-11e9-9603-2806d1de09e1.png)
User folder:
![image](https://user-images.githubusercontent.com/331816/55216484-245a8a80-51fd-11e9-861b-63c74c377eac.png)
Logs:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'docusaurus-init@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\Benjamin',
1 verbose cli   'Nolmans\\AppData\\Roaming\\npm-cache\\_npx\\9576',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json' ]
2 info using npm@6.4.1
3 info using node@v10.14.0
4 verbose npm-session dd168d0c4e355131
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for file:Nolmans\AppData\Roaming\npm-cache\_npx\9576 Could not install from "Nolmans\AppData\Roaming\npm-cache\_npx\9576" as it does not contain a package.json file.
8 http fetch GET 304 https://registry.npmjs.org/docusaurus-init 936ms (from cache)
9 silly pacote tag manifest for docusaurus-init@latest fetched in 958ms
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 1243ms
12 verbose stack Error: ENOENT: no such file or directory, open 'C:\Developpement\docu\Nolmans\AppData\Roaming\npm-cache\_npx\9576\package.json'
13 verbose cwd C:\Developpement\docu
14 verbose Windows_NT 10.0.17763
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "docusaurus-init@latest" "--global" "--prefix" "C:\\Users\\Benjamin" "Nolmans\\AppData\\Roaming\\npm-cache\\_npx\\9576" "--loglevel" "error" "--json"
16 verbose node v10.14.0
17 verbose npm  v6.4.1
18 error code ENOLOCAL
19 error Could not install from "Nolmans\AppData\Roaming\npm-cache\_npx\9576" as it does not contain a package.json file.
20 verbose exit [ 1, true ]
```
**### Look this line in logs:**
```
verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "docusaurus-init@latest" "--global" "--prefix" "C:\\Users\\Benjamin" "Nolmans\\AppData\\Roaming\\npm-cache\\_npx\\9576" "--loglevel" "error" "--json"
```
The path is separate in two arguments:
first: `"C:\\Users\\Benjamin"`
second: `"Nolmans\\AppData\\Roaming\\npm-cache\\_npx\\9576"`
**The normal path is** : `"C:\\Users\\Benjamin Nolmans\\AppData\\Roaming\\npm-cache\\_npx\\9576"`
![image](https://user-images.githubusercontent.com/331816/55216812-093c4a80-51fe-11e9-97ce-2a611a584a83.png)

So, why my path is cut on space ?

**Comment by endiliey** [comment] 2019-03-29 08:19
Looking at your log, it seems to be not related to docusaurus. But 'npx' package itself. You might want to file an issue at https://github.com/zkat/npx

However, I took my time to investigate and find that this issue you are facing is in fact happening with many other cli app too. See below, the log is very identical to your log.

# Running install in user mode
# https://github.com/zkat/npx/issues/100

# Run install in admin user mode
# https://github.com/zkat/npx/issues/146

Conclusion: **this bug is caused by npx and not docusaurus itself.
---

There are various solutions shown in that issue, you might want to look at that.

If it still doesn't, did you try the alternative commands to install docusaurus that we have written in our documentation ?
See https://docusaurus.io/docs/en/installation

```bash
yarn global add docusaurus-init
docusaurus-init
```

I believe this is worth closing. Thank you for the time 😉

**Closed by endiliey** 2019-03-29 08:19 UTC
Labels: bug, needs more information

**Comment by Xarkam** [comment] 2019-03-29 08:39
Thanks @endiliey.

If this problem is recurrent with npx, why no adding a note in getting started documentation about this ?
This would allow people who also encounter this problem to know what to do.

I did not follow the procedure with yarn because I thought that it did not concern me since I use node 10.

**Comment by JoelMarcey** [comment] 2019-03-29 15:18
@Xarkam - we encourage those that feel the documentation could use improvement to send a pull request to update it. We are generally very accommodating to such changes, assuming they provide value to those that use or are starting to use Docusaurus.
