### ISSUE TITLE
Google Crawler Breadcrumb Structured Data Error

### ISSUE THREAD

**Issue by elucidsoft** [facebook/docusaurus#7375] opened 2022-05-08 13:49 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

This issue occurs only when Google Search Crawls your Docusaurus site.  It will warn you that breadcrumb structured data was detected but it is invalid with the following error:

```Invalid URL in field "id" (in "itemListElement.item")```

Perhaps this is a change to Googles Own Search Criteria, I am not 100% clear but I did not see this error until I upgraded my Docusaurus to the latest version last week.  

### Steps to reproduce

1. Use Docusaurus Docs with Nested Content
2. Submit to Google
3. Wait for Google to finish crawling and do a validation check.
4. Observe validation errors reported by Google Search Console

### Expected behavior

Breadcrumb Structured Data to be valid.

### Actual behavior

Breadcrumb Structured Data is invalid.

### Your environment

- Public source code: https://github.com/cloudlayerio/docs
- Public site URL: https://docs.cloudlayer.io
- Docusaurus version used: 2.0.0-beta.18
- Environment name and version (e.g. Chrome 89, Node.js 16.4): n/a
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): n/a

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-05-08 13:51
Duplicate of #7303

**Comment by Josh-Cena** [comment] 2022-05-08 13:52
This has been fixed by #7304 and released in beta.19

**Closed by Josh-Cena** 2022-05-08 13:52 UTC
Labels: closed: duplicate
