### ISSUE TITLE
Could not find a declaration file for module 'react' for PNPM setup

### ISSUE THREAD

**Issue by sparanoid** [facebook/docusaurus#9580] opened 2023-11-24 12:44 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

The initial project created by `create-docusaurus` with PNPM will not resolve TypeScript hinting for `react` package

### Steps to reproduce

Follow https://docusaurus.io/docs/typescript-support to create a new repo:

1. `pnpx create-docusaurus@latest my-website classic --typescript`
2. Open the project
3. Create a component with `import React from 'react';`

### Expected behavior

React resolves correctly (The result in this screenshot is created by `npx`):

<img width="785" alt="image" src="https://github.com/facebook/docusaurus/assets/96356/f6313b45-0fca-47ce-a313-aa7f129ba618">

### Actual behavior

<img width="963" alt="image" src="https://github.com/facebook/docusaurus/assets/96356/9a8977f6-7c52-4574-884c-2ec119df080d">

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 21.2.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 14.1.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-11-24 18:53
Duplicate of https://github.com/facebook/docusaurus/issues/9080

**Closed by Josh-Cena** 2023-11-24 18:53 UTC
Labels: bug, status: needs triage
