### ISSUE TITLE
magicComments invalid

### ISSUE THREAD

**Issue by dshvv** [facebook/docusaurus#7470] opened 2022-05-23 08:45 UTC
### Description
```
prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
        defaultLanguage: "javascript",
        magicComments: [
          {
            className: 'theme-code-block-highlighted-line',
            line: 'highlight-next-line',
            block: {start: 'highlight-start', end: 'highlight-end'},
          },
          {
            className: 'code-error',
            line: 'error-next-line',
            block: {start: 'error-start', end: 'error-end'},
          },
        ]
      }
```

```javascript title="utils.js"
const add = (x, y) => {
// highlight-next-line
const res = x + y;
// error-next-line
return res;
};
```

just `highlight-next-line` take effect

**Comment by Josh-Cena** [comment] 2022-05-23 08:51
Hi, I can't reproduce this.

![Uploading image.png…]()

Try re-starting your dev server.

**Comment by Josh-Cena** [comment] 2022-05-23 08:54
I have a suspicion that you didn't have the right CSS accompanying it. I'll be pre-emptively closing this as a question because apparently the lack of reproduction disqualifies it as a bug report. Please don't use the GitHub issue tracker as a support forum.

**Closed by Josh-Cena** 2022-05-23 08:54 UTC
Labels: closed: question

**Comment by dshvv** [comment] 2022-05-23 11:58
> I have a suspicion that you didn't have the right CSS accompanying it. I'll be pre-emptively closing this as a question because apparently the lack of reproduction disqualifies it as a bug report. Please don't use the GitHub issue tracker as a support forum.
> 
> We can re-open once we get more information needed.

sorry is my fault, the reasoun is docusaurus version . my version is [beta.18], but custom code style need [beta.20]

**Comment by Josh-Cena** [comment] 2022-05-23 12:00
I see 👍
