### ISSUE TITLE
Inline SVGs not rendering and break page

### ISSUE THREAD

**Issue by oriooctopus** [facebook/docusaurus#3179] opened 2020-07-31 16:13 UTC
## 🐛 Bug Report

This may be user error, as I feel like this is core enough that it would have already been reported, so I apologize if I waste anyone's time.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. npx @docusaurus/init@next init my-website classic
2. Add the following to the top of mdx.md:

```
import Mountain from '@site/static/img/undraw_docusaurus_mountain.svg';

A mountain:
<Mountain />
```

3. Go to http://localhost:3000/docs/mdx The page should be broken and the following error should be in the developer panel: 
`
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/assetsundraw_docusaurus_mountain-b480421ae597bc5783ec62d605645b24.svg') is not a valid name.
`

I want to add that I also tried including the svg in an external component file with the same results

## Your Environment

This was done with the most recent version of docusaurus

## Reproducible Demo

I'm not including a link because the steps to reproduce from scratch are so quick. Hopefully that's ok!

**Comment by teikjun** [comment] 2020-07-31 16:46
Hi, you can include svgs (and images) like this:

```
<img src='../static/img/undraw_docusaurus_mountain.svg' />
```
Or like this:
```
![img](../static/img/undraw_docusaurus_mountain.svg)
```

You can also choose to create a React component for the svg in another file. Then import it in your documentation. In this case, your doc file needs to end with `.mdx`.

**Comment by oriooctopus** [comment] 2020-07-31 18:15
Hi @teikjun thanks for your response. Unfortunately, even when the file is named mdx.mdx, the same error occurs

**Comment by slorber** [comment] 2020-07-31 18:30
Hi,

```
import Mountain from '@site/static/img/undraw_docusaurus_mountain.svg';

A mountain:
<Mountain />
```

This is not std javascript to import a svg, this is Webpack specific, and there's no unique way to handle a svg file import:
- we could get the SVG as a react component
- we could get the SVG as 
- we could get a URL for downloading a svg source file...

This is not a bug to me, but a feature request, and Docusaurus user may want different behaviors according to their own usecases 

---



In the meantime, you should be able to solve your problem by using "inline" Webpack loaders, directly in your import expression, and using a loader like: https://github.com/jhamlet/svg-react-loader

Add the dependency, and then:

```
# Some markdown title 

import Icon from 'svg-react-loader?name=Mountain!@site/static/img/undraw_docusaurus_mountain.svg';

A mountain:
<Mountain />
```

I'm closing, but open to discuss a feature request for this.

**Comment by oriooctopus** [comment] 2020-07-31 19:02
Hi @slorber  the thing is that in the docs https://v2.docusaurus.io/docs/static-assets#jsx-example states that inline svgs are an option.
I should also add I tried putting the svg import in an extrernal component and then importing that into the mdx file, with the same error

**Comment by slorber** [comment] 2020-07-31 19:12
Hmmmm, I didn't know we had that!

Need to check this next week, but I can confirm I see this webpack loader:

```
        {
          test: /\.svg$/,
          use: '@svgr/webpack?-prettier-svgo,+titleProp,+ref![path]',
        },
```

**Comment by oriooctopus** [comment] 2020-07-31 20:02
Awesome! Thank you!

**Comment by anshulrgoyal** [comment] 2020-08-03 13:44
I will take this.

**Comment by anshulrgoyal** [comment] 2020-08-03 14:12
I checked the code and the problem is that there are conflicting webpack-loaders for `.svg` files. Both `url-loader` and `@svgr/webpack` try to load svg. If we disable `url-loader` for `.svg` it works fine. @slorber what should we do?

**Comment by anshulrgoyal** [comment] 2020-08-03 14:15
We can use something like this.
```
{
  test: /\.svg$/,
  use: ['@svgr/webpack', 'url-loader'],
}

```
then it won't break existing websites.
```js
import starUrl, { ReactComponent as Star } from './star.svg'
 
const App = () => (
  <div>
    <img src={starUrl} alt="star" />
    <Star />
  </div>
)
```

**Comment by slorber** [comment] 2020-08-03 14:46
I think in the image loader of webpack:

```
    images: (): RuleSetRule => {
      return {
        use: [loaders.url({folder: 'images'})],
        test: /\.(ico|svg|jpg|jpeg|png|gif|webp)(\?.*)?$/,
      };
    },
```

we can just remove the svg from here, as:
- Using imports/requires, we expect to get a React comp
- Using md images, we already force the file-loader


Can you find a way to dogfood this feature somewhere by rendering an svg as both a md image + a mdx react component? That would help us not break this feature again in the future.

**Comment by anshulrgoyal** [comment] 2020-08-03 14:55
But if we remove `svg` from url-loader it might break pages for some users in the next release.

**Comment by slorber** [comment] 2020-08-03 15:01
This is a new feature, I don't think it has been used by users in this small amount of time, and also, this feature is actually in contraction with our existing svg to React conversion in the first place, so I'd rather revert to the correct behavior we had before alpha 59, even if it's a breaking change.

**Closed** 2020-08-05 17:19 UTC
Labels: bug, difficulty: starter, good first issue, help wanted, mlh

**Comment by oriooctopus** [comment] 2020-08-05 19:11
Thank you @slorber !

**Comment by slorber** [comment] 2020-08-05 19:15
thank @anshulrgoyal  :)
