### ISSUE TITLE
build fails on Windows when using a plugin to `addRoute` that uses a url-param like `path/:id`

### ISSUE THREAD

**Issue by vhvb1989** [facebook/docusaurus#10564] opened 2024-10-07 19:02 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When trying to build a website with a plug-in to add routes in Windows, the build process fails at the end with:

```
 my-website@0.0.0 build
> docusaurus build

[INFO] [en] Creating an optimized production build...

✔ Client
  Compiled successfully in 27.72s

✔ Server



● Client █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

✔ Server



[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:54:19)
    at async C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:65:9
    at async mapAsyncSequential (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\utils\lib\jsUtils.js:21:24)
    at async Command.build (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:63:5) {
  [cause]: Error: Docusaurus static site generation failed for 1 paths:
  - "/path/:id"
      at generateStaticFiles (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\ssg.js:86:15)
      at async executeSSG (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:174:23)
      ... 4 lines matching cause stack trace ...
      at async Command.build (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:63:5) {
    [cause]: AggregateError
        at generateStaticFiles (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\ssg.js:87:20)
        at async executeSSG (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:174:23)
        at async buildLocale (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:134:31)
        at async tryToBuildLocale (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:47:13)
        at async C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:65:9
        at async mapAsyncSequential (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\utils\lib\jsUtils.js:21:24)
        at async Command.build (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\commands\build.js:63:5) {
      [errors]: [
        Error: Can't render static file for pathname "/path/:id"
            at generateStaticFile (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\ssg.js:119:15)
            at processTicksAndRejections (node:internal/process/task_queues:95:5)
            ... 2 lines matching cause stack trace ...
            at async C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\p-map\index.js:57:22 {
          [cause]: Error: Path contains invalid characters: C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\build\path\:id
              at checkPath (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\fs-extra\lib\mkdirs\utils.js:16:21)
              at module.exports.makeDir (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\fs-extra\lib\mkdirs\make-dir.js:12:3)
              at Object.<anonymous> (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\universalify\index.js:18:45)
              at writeStaticFile (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\ssg.js:152:30)
              at generateStaticFile (C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\@docusaurus\core\lib\ssg.js:108:15)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at runNextTicks (node:internal/process/task_queues:64:3)
              at process.processImmediate (node:internal/timers:449:9)
              at async C:\Users\vivazqu\workspace\repro-docusaurus-issue\my-website\node_modules\p-map\index.js:57:22 {
            code: 'EINVAL'
          }
        }
      ]
    }
  }
}
[INFO] Docusaurus version: 3.5.2
Node version: v20.11.1
```

The error complains about the plugin is using a syntax like `path/:id`, which is for the `react-router-dom`.

I created a new docusaurus  with `npx create-docusaurus@latest my-website classic --typescript` to validate this issue.

The issue does not occur in Linux/Mac

Looking at the stack-trace, the issue leads to a function from `universalify` which applies only to `win32`:

![image](https://github.com/user-attachments/assets/ec8b720f-2377-45fd-b4bf-312d848319f2)

I couldn't find a workaround to tell docusaurus to exclude the plug-in folder/file or anything.

### Reproducible demo

https://github.com/vhvb1989/repro-docusaurus-issue

### Steps to reproduce

clone the repo with Windows and run 
- npm install
- npm build

Steps for creating everything from scratch:

- run `npx create-docusaurus@latest my-website classic --typescript`
- Add a new plug-in using this code:

```ts
import { LoadContext, Plugin } from '@docusaurus/types';

export default function dynamicRouter(context: LoadContext, options: {}): Plugin<void> {
  return {
    name: 'dynamic-router-plugin',
    async contentLoaded({ actions }) {
      const { addRoute } = actions;
      addRoute({
        path: '/path/:id',
        component: '@site/src/components/Foo',
        exact: true,
      });
    },
  };
}
``` 

- Add a component in `src/components/` called `Foo` and use this:

```tsx
import React from 'react';
import { useParams } from 'react-router-dom';

const Foo: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  return <div>Repo ID: {id}</div>;
};

export default Foo;
```

- Add plug-in to docusaurus config
- Run `npm build`

### Expected behavior

website builds correctly.

### Actual behavior

Error during build. stacktrace provided in details

### Your environment

- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

Only reproduces in Windows

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-10-08 09:16
@vhvb1989 we don't have first-class support for such dynamic paths routes. 

I'll consider this as a duplicate of https://github.com/facebook/docusaurus/issues/4710

I don't think it's related to Windows although technically maybe your site is able to build under other OS I doubt it behaves as you think it does.



---

## Let me explain

Docusaurus is a static site generator. I try to generate all pages as static `.html` files and do not have a server runtime to serve dynamic requests.

The problem when using `/path/:id` is that we don't know what all the `:id` path params will be, so we technically can't generate all the possible `/path/id1.html` and `/path/id2.html` as static files.

The only thing Docusaurus can do at this point with a dedicated API (https://github.com/facebook/docusaurus/issues/4710) is to try to emit a `/path/:id.html` file (or `/path/:id/index.html`, which apparently is not a valid file path on Windows.

Even if we did generate such static file, it still wouldn't solve your problem properly. When browsing an URL such as `/path/id1`, your CDN/host will probably serve a 404 response with the `/404.html` content. This is because your CDN doesn't have any file to serve at `/path/id1.html`: this file doesn't exist because Docusaurus can't generate it.


## Solving your problem

You can still achieve dynamic routing in Docusaurus, but it requires understanding the limitations. Your dynamic routes will be client-only, and won't generate static pages because we don't have a way for Docusaurus to know the exhaustive list of all `/path/:id` to generate.


The way to achieve this is to use `/path/` with `exact: false`

```ts
import { LoadContext, Plugin } from '@docusaurus/types';

export default function dynamicRouter(context: LoadContext, options: {}): Plugin<void> {
  return {
    name: 'dynamic-router-plugin',
    async contentLoaded({ actions }) {
      actions.addRoute({
        path: '/path/',
        component: '@site/src/components/Foo',
        exact: false,
      });
    },
  };
}
```

This will lead Docusaurus to generate:
- a parent route `/path/` that will also match `/path/id1`.
- a static file at `/path/index.html`

Inside your `Foo` component, it's possible to use React Router v5 features: https://v5.reactrouter.com/web/guides/quick-start

```ts
<Switch>
  <Route path="/path/:id"/>
</Switch>
```

But you'd better wrap this in a [`<BrowserOnly>`](https://docusaurus.io/docs/docusaurus-core#browseronly) component, because at SSG/SSR time, Docusaurus will generate the static page with no param. If you want to use `useParams()`, you need to put it down the tree, on code that only executes client-side, because there's no params known at build time. And you'll probably want to show some kind of spinner in the static page so that user knows something dynamic is loading and will be presented client-side after React hydrates.

You'll also need to configure your host to support those dynamic params. Remember that Docusaurus only generated a `/path/index.html` static file. Now you don't want users browsing `/path/id1` to be served a 404 page, which your CDN/host will probably do by default. To ensure it serves the static `/path/index.html` instead of `/404.html`. A CDN like Netlify/Cloudflare/Vercel will allow you do so.



## Full example

Our feature-request page is an example of dynamic routing integrated into Docusaurus: 
https://docusaurus.io/feature-requests
https://docusaurus.io/feature-requests/p/update-mermaid-version-in-theme-mermaid

As you can see, it first loads a skeleton

![CleanShot 2024-10-08 at 11 12 17](https://github.com/user-attachments/assets/dea775b0-b8da-4436-9eb3-87cb8dee9f85)


And then the content gets loaded client-side:

![CleanShot 2024-10-08 at 11 12 33](https://github.com/user-attachments/assets/2883776a-b9af-4afb-aa56-831b6a2ed8e1)


It's a bit different though, because it's using a third-party lib instead of React Router to manage the dynamic routes, but the rest is the same.




The code is here: https://github.com/facebook/docusaurus/tree/main/website/src/plugins/featureRequests

We also have the following Netlify `_redirects` file to ensure `/feature-requests/XYZ` gets served the `/feature-requests/index.html` static file that contains the static loading skeleton:

```
# Feature requests redirects
/feature-requests/*         /feature-requests                  200
/fr/feature-requests/*      /fr/feature-requests               200
```


---

I hope all this makes sense. Unfortunately, shoehorning dynamic content into a static site is more challenging than it seems, but it is a constraint we currently have.

**Closed by slorber** 2024-10-08 09:16 UTC
Labels: bug, closed: duplicate

**Comment by vhvb1989** [comment] 2024-10-08 19:38
thank you @slorber .  That's a very good explanation.

I updated my project and changed the dynamic-routes from using parameter-id (like `:id`) to, instead, use a json file with the list of all the valid routes and call `addRoute` for each one.

This approach still uses the `contentLoaded` plugin.

Do you know if I can use the same JSON files to generate all the static pages (one for each entry in the JSON) using the same tsx component for all of them?
The tsx component is reading the URL and loading the content on client-side.

**Comment by slorber** [comment] 2024-10-09 07:08
If you have a predefined list of routes then yes creating one static route for each is the way to go 👍 

I'm not sure to understand your question

You can choose to inject data statically at built time by using:
- `route.modules.myModule = await actions.createData(myPath,myData)` (same module can be shared between multiple routes)
-`route.props = myData` (simpler but still undocumented)

Or you can read the URL in a shared TSX component and fetch the data from a remote source. Just keep in mind that at build time the app will be rendered only with the static route pathnames you provided, and there will be no query-string available.
