### ISSUE TITLE
Automatic Updates without reload

### ISSUE THREAD

**Issue by JPeer264** [facebook/docusaurus#7722] opened 2022-07-04 11:41 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

**Prefetching sidebar items:** Docusaurus prefetches pages when opening sidebar items, which works perfectly fine.
**Prefetching pages on hover:** When the content has changed and the user did not yet reload the docusaurus page the user receives a 404 in the network tab and docusaurus automatically fetches the newer version of the content, which also works fine.

The thing is that both of these concepts work perfectly fine on their own. A problem we encountered is that a combination of both (I guess it is the combination somehow) will break the behavior and the user ends up in a never ending loading state (unless the user manually reloads the page).

### Reproducible demo

https://github.com/JPeer264/docusaurus-cache

### Steps to reproduce

The reproduction is written inside the docusaurus home. But to complete it here I will copy it here as well:

# Reproduction

1. Build and run the docker image

    ```sh
    $ docker build -t docusaurus .
    $ docker run -p 3000:80 --rm docusaurus
    ```

1. Open http://localhost:3000/ in your browser and open up all pages.

1. In your browser return to the sidebar item **Reproduction** and reload the page (leave the cache as is)

1. In your editor change the header `/pages/subfolder/another-subfolder/modifyMe.md` to something else

1. Rebuild everything as described in point 1. (remember to not reload the page)

1. In the browser, and without reloading, open **Subfolder** and try to open **Some important heading**

1. 💥

# Video 

[Kapture 2022-07-04 at 13.26.38.webm](https://user-images.githubusercontent.com/10677263/177147488-7d272cd1-c096-49af-9601-175a4a9f3946.webm)

### Expected behavior

I would expect that the page **Some important heading** will load without reloading as this page was not affected by anything.

### Actual behavior

The page **Some important heading** does not load as the refetch was pointing to a 404.

### Your environment

- Public source code: https://github.com/JPeer264/docusaurus-cache
- Public site URL: -
- Docusaurus version used: 2.0.0-beta.21
- Environment name and version (e.g. Chrome 89, Node.js 16.4): NodeJS 16.14.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Natively macOS 11.6.7 (20G630), Docker env: linux/amd64 based on [the nginx image](https://hub.docker.com/layers/nginx/library/nginx/1.20.1/images/sha256-ee2970c234800c5b5841d20d04b7ddc2a08f8653ce6d3376782c8a48eb61428b?context=explore)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-07-04 11:43
Hey, this is a duplicate of #7599 and fixed in the next version (expect a release this week). Try the [canary release](https://docusaurus.io/community/canary) for now.

**Closed by Josh-Cena** 2022-07-04 11:43 UTC
Labels: bug, status: needs triage

**Comment by JPeer264** [comment] 2022-07-04 11:46
Thanks a lot! I was searching for the correct issue. Seems that my search skills need to improve ;)

**Comment by Josh-Cena** [comment] 2022-07-04 11:51
Yeah, I wouldn't have arrived at that either if I'm searching this myself :/ Accidentally creating duplicate issues is not a problem at all!
