### ISSUE TITLE
[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by MartinMuzatko** [facebook/docusaurus#10200] opened 2024-06-05 09:56 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

when using `npm start` I get the following error message:

```
[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at Object.pluginContentBlog [as plugin] (/Users/martin/dev/gitlab/scisp-api-docs/node_modules/@docusaurus/plugin-content-blog/lib/index.js:51:37)
    at initializePlugin (/Users/martin/dev/gitlab/scisp-api-docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:83:61)
    at async Promise.all (index 1)
    at async initPlugins (/Users/martin/dev/gitlab/scisp-api-docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:91:21)
    at async /Users/martin/dev/gitlab/scisp-api-docs/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:136:36
    at async loadSite (/Users/martin/dev/gitlab/scisp-api-docs/node_modules/@docusaurus/core/lib/server/site.js:135:45)
    at async createReloadableSite (/Users/martin/dev/gitlab/scisp-api-docs/node_modules/@docusaurus/core/lib/commands/start/utils.js:50:16) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

### Steps to reproduce

```

npx create-docusaurus@latest my-website classic
cd my-website
npm start

```

### Expected behavior

It should run

### Actual behavior

It does not run

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

Perhaps what's important to note, is that I try to develop on a Macbook. (MacOS Sonoma 14.5)

I can't reproduce this in the codesandbox unfortunately.. It's a freshly downloaded project (using `npx create-docusaurus@latest my-website classic`)

Docusaurus version: 3.4.0
Node version: v18.20.3
npm: 10.7.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment] 2024-06-05 10:01
Closing duplicate of : https://github.com/facebook/docusaurus/issues/10199

Solution is here : https://github.com/facebook/docusaurus/issues/10199#issuecomment-2149368485

**Comment by MartinMuzatko** [comment] 2024-06-05 10:01
Thank you! For some reason I couldn't find the other issue.

**Closed by OzakIOne** 2024-06-05 10:01 UTC
Labels: bug, closed: duplicate
