### ISSUE TITLE
Non-English Tutorial Section Images Render Markup

### ISSUE THREAD

**Issue by scottilee** [facebook/docusaurus#2206] opened 2020-01-11 17:50 UTC
## 🐛 Bug Report

Images in the tutorial section of https://docusaurus.io display larger and with markup `{.docImage}` if viewed in any language other than English.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

(Write your steps here:)

1. Navigate to https://docusaurus.io/docs/en/tutorial-setup
1. Click "English" in the top navigation and switch to any non-English language
1. When the page reloads images will be larger and there will be `{.docImage}` markup below the image

## Expected behavior

When viewing the tutorial section in any non-English language there should be no `{.docImage}` markup below images and images should not change size.

## Actual Behavior

When viewing the tutorial section in any non-English language there is `{.docImage}` markup below images and images change size.

## Reproducible Demo

(a) what it looks like for English and should look like for any language
<img width="905" alt="Screen Shot 2020-01-11 at 12 35 34 AM" src="https://user-images.githubusercontent.com/7443383/72208418-283b5e80-3457-11ea-8510-6de9947c0dff.png">

(b) what it looks like for non-English
<img width="905" alt="Screen Shot 2020-01-11 at 12 36 41 AM" src="https://user-images.githubusercontent.com/7443383/72208417-283b5e80-3457-11ea-9cac-3b7b5eb74c32.png">

**Comment by Tarektouati** [comment] 2020-01-13 12:25
Can I work on this?

**Comment by scottilee** [comment] 2020-01-14 08:26
@Tarektouati Of course, just assign it to yourself and provide updates here.

**Comment by yangshun** [comment] 2020-01-14 09:24
@Tarektouati go ahead

**Comment by Tarektouati** [comment] 2020-02-04 20:23
@yangshun  Hey! I have been trying to reproduce the same bug as in the issue with multiple translations.
Sadly, I couldn't reproduce it, if not maybe it's the crowdin translated files could be buggy. 
Thanks

**Comment by yangshun** [comment] 2020-06-05 09:29
I can reproduce it by going to https://docusaurus.io/docs/fr/tutorial-setup. Almost definitely a Crowdin issue.

**Comment by slorber** [comment] 2021-01-15 18:22
It's indeed a crrowdin issue:

![image](https://user-images.githubusercontent.com/749374/104763932-f1cda900-5766-11eb-861e-eb92d465179b.png)

![image](https://user-images.githubusercontent.com/749374/104763969-feea9800-5766-11eb-840a-ef7c63b12780.png)

Not sure we'll be able to do anything about it without somehow resetting the doc on crowdin side.

Closing

**Closed by slorber** 2021-01-15 18:22 UTC
Labels: bug, difficulty: intermediate, help wanted, v1
