### ISSUE TITLE
Failed to deploy: Reference error self is not defined

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/docusaurus#2494] opened 2020-04-01 18:00 UTC
## 🐛 Bug Report

I get a ReferenceError in Webpack while running `yarn build` to deploy the Hermes website.

I _think_ it's due to `monaco-editor-webpack-plugin` but I'm not sure.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce
Note: I setup a branch that has the required hermes.js files we're only adding to the gh-pages branch during deploys.

- Clone my branch here: https://github.com/rickhanlonii/hermes/tree/rh-deploy-hermes
- `cd website`
- `yarn build`
- Observe error

## Expected behavior

- Build completes, site deploys

## Actual Behavior

<img width="1363" alt="Screen Shot 2020-04-01 at 12 53 56 PM" src="https://user-images.githubusercontent.com/2440089/78170464-fe278600-7420-11ea-987f-e260d827c72c.png">

## Your Environment

- Docusaurus version used: 2.0.0-alpha.43
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 12.9.1
- Operating system and version (desktop or mobile): macOS

## Reproducible Demo

https://github.com/rickhanlonii/hermes/tree/rh-deploy-hermes

**Comment by lex111** [comment] 2020-04-01 18:09
@rickhanlonii could you please upgrade D2 to the latest version (2.0.0-alpha.49)?

**Comment by rickhanlonii** [comment] 2020-04-01 21:42
@lex111 I did try it with the latest alpha as well, sorry I left that out of the description. I also reverted back to 2.0.0-alpha.19 (the last version that we deployed with successfully) but that failed for a different reason.

**Comment by lex111** [comment] 2020-04-01 23:44
@rickhanlonii this is not really a D2 bug. This bug is related to what we do prerendering (something like SSR). But I fix it, you can see my commit here https://github.com/lex111/hermes/commit/b8a3e14c111697114321b06eeedcbd2b5b11806c

**Comment by rickhanlonii** [comment] 2020-04-02 00:19
Thanks @lex111, I verified that that fixed the issue and deployed the site. PR is here https://github.com/facebook/hermes/pull/204

For D2, is there a way we can surface these errors with an explanation of how to fix? If I got an error that told me the issue was that I broke server side rendering I may have been able to fix this myself.

**Comment by lex111** [comment] 2020-04-02 00:27
@rickhanlonii I don't think there's that easy way to find out that the issue is related with SSR.

**Comment by yangshun** [comment] 2020-04-02 02:42
I agree it's hard for us to determine if the issues are caused by SSR. One rule of thumb I use is if a component has highly complex interactions (e.g. videos, playgrounds), chances are it relies on browser APIs.

I think this issue is common enough and we can start an FAQ page and document these down. To get around them you can use [`<BrowserOnly>`](https://v2.docusaurus.io/docs/docusaurus-core/#browseronly) or [`ExecutionEnvironment`](https://v2.docusaurus.io/docs/docusaurus-core/#executionenvironment) (similar to the one we have internally at FB).

**Comment by Gtosta96** [comment] 2020-04-09 21:52
@lex111 I'm having troubles importing `<BrowserOnly> into my project.
`Cannot find module '@docusaurus/BrowserOnly'`. I'm using `@docusaurus/core": "2.0.0-alpha.50` installed. Could you help me? =(

**Comment by Gtosta96** [comment] 2020-04-13 14:27
Can I use ExecutionEnvironment outside .mdx files?
I'm facing the following issue when importing ExecutionEnvironment inside .tsx files.

`Cannot find module '@docusaurus/ExecutionEnvironment'.`

**Comment by dotansimha** [comment] 2020-04-16 15:21
I'm having the same issue, but with `navigator`. 
The error is:
```
ReferenceError: navigator is not defined
(undefined) ReferenceError: navigator is not defined
    at main:12649:19
    at main:12643:28
    at Object.<anonymous> (main:12645:2)
    at __webpack_require__ (main:21:30)
    at Module.<anonymous> (main:105212:18)
    at __webpack_require__ (main:21:30)
    at main:169369:12707

```

`start` works fine, it only happens with `build`. I guess one of the deps in not compatible with SSR? but the error is not helpful :(

**Comment by mharsat** [comment] 2020-04-22 21:06
Also having the same issue with components in a mdx file. Only happening with `build`.
```bash
ReferenceError: Buffer is not defined
(undefined) ReferenceError: Buffer is not defined
    at Object.<anonymous> (main:119548:13)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:119188:11)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:54000:26)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:119149:30)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:79590:23)
    at __webpack_require__ (main:27:30)
```

Any solution for mdx files yet?

**Comment by yangshun** [comment] 2020-04-23 02:13
The solution is the same. What are you importing in your MDX files?

**Comment by mharsat** [comment] 2020-04-23 07:16
I am importing a

**Comment by mharsat** [comment] 2020-04-23 07:20
```jsx
import { RichContentWrapper } from "wix-rich-content-wrapper";
import { RichContentEditor } from "wix-rich-content-editor";
import { pluginDivider } from "wix-rich-content-plugin-divider";
import { pluginVideo } from "wix-rich-content-plugin-video";
```

I am importing a few libraries, one of them has a dependency using `scss` files. So I installed the `docusaurus-plugin-sass` plugin, and then stopped getting the error for unrecognized `scss`. Now `start` works but `build` fails with the above   `ReferenceError`. What do you suggest? Is this really SSR related?

**Comment by dotansimha** [comment] 2020-04-23 15:45
@mharsat It's usually happen because of SSR related issues. You can bypass that by loading those only for client side. 

I did something like that:
https://github.com/dotansimha/graphql-code-generator/blob/master/website/src/components/live-demo/Editor.js#L1-L4

**Comment by mharsat** [comment] 2020-04-23 21:26
> @mharsat It's usually happen because of SSR related issues. You can bypass that by loading those only for client side.
> 
> I did something like that:
> [dotansimha/graphql-code-generator:website/src/components/live-demo/Editor.js@`master`#L1-L4](https://github.com/dotansimha/graphql-code-generator/blob/master/website/src/components/live-demo/Editor.js#L1-L4) [](/dotansimha/graphql-code-generator/blob/HEAD@{2020-04-23T15:45:00Z}/website/src/components/live-demo/Editor.js#L1-L4)

Thanks @dotansimha that helped

**Comment by jonnynabors** [comment] 2020-04-30 22:10
I have a similar issue when importing the Redoc React Component (https://github.com/Redocly/redoc#usage-as-a-react-component). The error only occurs when I'm actually importing the component. I've tried to use the `ExecutionEnvironment.canUseDOM` in a parent component to conditionally render a child component with the import statement, but the error persists. 

Is there any way to disable the SSR build step? Or is there another idea worth exploring?

**Comment by yangshun** [comment] 2020-05-05 08:38
@jonnynabors the workaround is along the lines of what I would recommend. Refer to https://github.com/facebook/hermes/pull/204/files for the recommended solution of using `<Suspense>` and `React.lazy` to lazily import the modules.

> That said, is there any way to bypass or disable the SSR bundle

Nope. But we could consider adding that although we rather try to solve the problems that emerge along the way.

**Comment by mtooke** [comment] 2020-05-14 21:55
@jonnynabors would you mind posting your entire page code? I'm trying to make redoc work and am running into the same problem (when building only). I'm not a react dev.

For instance, where do I put that bit? Where does the ReactStandalone component go? Do I need the import statement, etc. 

Thanks!

**Comment by lex111** [comment] 2020-11-10 15:12
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.

**Closed by lex111** 2020-11-10 15:12 UTC
Labels: documentation, faq, good first issue, help wanted

**Comment by sibelius** [comment] 2020-12-02 20:14
can we improve the message for non SSR components?

**Comment by slorber** [comment] 2020-12-03 09:57
@sibelius what kind of message you have and what should be the improvement?
I added recently the page path that is failing to render on node, that might help find the cause of the issue.

Should we link to a guide page or something when we detect a potential issue?
How can we be sure the error is related to this issue? (I guess if it's a "ReferenceError" it's quite likely to be related?)

**Comment by sibelius** [comment] 2020-12-03 12:06
I've got the same on https://github.com/facebook/docusaurus/issues/2494#issuecomment-622143023

```jsx
ReferenceError: Buffer is not defined
(undefined) ReferenceError: Buffer is not defined
    at Object.<anonymous> (main:119548:13)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:119188:11)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:54000:26)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:119149:30)
    at __webpack_require__ (main:27:30)
    at Object.<anonymous> (main:79590:23)
    at __webpack_require__ (main:27:30)
```

it would be cool to show the component that throw this

**Comment by zerkms** [comment] 2021-03-03 00:14
@yangshun <Suspense> and React.lazy fail to build

```
Docusaurus Node/SSR could not render static page with path=/api because of error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.


Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

> ReactDOMServer does not yet support Suspense

**Comment by sibelius** [comment] 2021-03-03 01:10
We should be using BrowserOnly component

Is BrowserOnly documented somewhere?

**Comment by zerkms** [comment] 2021-03-03 01:17
https://v2.docusaurus.io/docs/docusaurus-core#browseronly

**Comment by alex88** [comment] 2021-03-29 05:22
I've tried BrowserOnly around the RedocStandalone component but that didn't help, same Buffer error

**Comment by slorber** [comment] 2021-03-29 14:46
It's not always enough to wrap in `<BrowserOnly>`, you might also use a "lazy require" and ensure that the lib is not initialized eagerly. 

See  a possible solution here: https://github.com/mac-s-g/react-json-view/issues/121#issuecomment-670431408

![image](https://user-images.githubusercontent.com/749374/112854619-5170fa80-90ae-11eb-8e01-f0ab26d1beb2.png)
