### ISSUE TITLE
@docusaurus/utils fails to install with PNPM and Webpack v4

### ISSUE THREAD

**Issue by kaiyoma** [facebook/docusaurus#6102] opened 2021-12-13 19:38 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Starting with 2.0.0-beta.10, @docusaurus/utils has a peer dependency of `"webpack": "5.x"`. Is this correct? We're using webpack 4 and things seem to work fine. The new peer dependency is causing pnpm to fail to install packages:

```
 ERR_PNPM_INVALID_PEER_DEPENDENCY  ..\..\packages\cloudvision-docs > @easyops-cn/docusaurus-search-local: @docusaurus/utils@2.0.0-beta.13 requires a peer of webpack@5.x but version 4.46.0 was installed.
```

### Steps to reproduce

Install docusaurus packages with pnpm while using webpack 4.

### Expected behavior

Packages should install.

### Actual behavior

Packages failed to install.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2021-12-13 23:06
Why would you want to use Webpack 4? You shouldn't care about what Webpack version Docusaurus uses under the hood: it shouldn't even be in your deps list.

**Comment by kaiyoma** [comment] 2021-12-13 23:16
@Josh-Cena I'm being forced to specify a webpack version because `@docusaurus/utils` requires it here:

https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-utils/package.json#L52

If I don't specify a webpack version at all, I get a similar error when trying to install packages:

```
 ERR_PNPM_MISSING_PEER_DEPENDENCY  ..\..\packages\cloudvision-docs > @docusaurus/preset-classic > @docusaurus/plugin-debug > @docusaurus/utils: file-loader@6.2.0 requires a peer of webpack@^4.0.0 || ^5.0.0 but none was installed.
```

**Comment by Josh-Cena** [comment] 2021-12-13 23:32
I see. I suggest you specify Webpack 5 since that's what Docusaurus uses anyways. Not very familiar with PNPM myself—does this error need additional configuration to reproduce? We have recently added a PNPM E2E test and it's passing

**Comment by kaiyoma** [comment] 2021-12-14 00:48
I can confirm that updating our webpack dependency to version 5 fixes the issue here. A caveat for anyone else stumbling upon this: if you're using Rush.js (and pnpm) to implement a monorepo, you'll probably have to upgrade to webpack 5 in all your other packages too.

**Comment by Josh-Cena** [comment] 2021-12-14 00:51
@kaiyoma I believe PNPM is smart enough to figure out which WP version to use in each package? You can use WP 5 for the website and WP4 for the rest.

**Comment by kaiyoma** [comment] 2021-12-14 07:41
> @kaiyoma I believe PNPM is smart enough to figure out which WP version to use in each package? You can use WP 5 for the website and WP4 for the rest.

Rush.js will throw an error if it detects mis-matched dependency versions among packages.

**Comment by Josh-Cena** [comment] 2021-12-14 08:40
I don't think it's fair to expect that utils would work with WP v4 considering it's designed for the core which uses WP v5. It seems that the misconfiguration is coming from a third-party dep as well—if I understand correctly, removing the external plugin will also remove the error? If that's the case, can I safely close this without any fixes?

**Comment by kaiyoma** [comment] 2021-12-14 18:09
Yes, I think you can close this. Hopefully the discussion here will help someone else if they run into the same thing.

**Closed** 2021-12-14 23:03 UTC
Labels: bug

**Comment by slorber** [comment] 2021-12-15 10:44
You should definitively use multiple versions of Webpack in a single monorepo. 

For example you should be able to have an app using Webpack 4, alongside a Docusaurus site using Webpack 5. Monorepos can be huge, contain a lot of apps with different lifecycles. If your monorepo tooling does not allow this, it's not really Docusaurus fault 😅

**Comment by kaiyoma** [comment] 2021-12-15 17:44
> You should definitively use multiple versions of Webpack in a single monorepo.
> 
> For example you should be able to have an app using Webpack 4, alongside a Docusaurus site using Webpack 5. Monorepos can be huge, contain a lot of apps with different lifecycles. If your monorepo tooling does not allow this, it's not really Docusaurus fault 😅

Rush allows this via its `allowedAlternativeVersions` mechanism. I agree that webpack is probably the one exception to the rule of keeping all dependency versions identical.
