### ISSUE TITLE
Relative links incorrectly pathing

### ISSUE THREAD

**Issue by bgree052** [facebook/docusaurus#5250] opened 2021-07-29 17:07 UTC
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io **(the issue happens randomly, I could test for hours and not come across it so making another repo wouldn't work/help)**
- [x] I have read the console error message carefully **(not applicable)**

### Description

Relative links will inconsistently create incorrect paths to the desired pages. 
A normal refresh on the page the link is located on will fix the issue temporarily, so I doubt it is a cache issue. 

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Steps to reproduce

As this is inconsistent it is not something I can tell you how to reproduce with guaranteed success; it happens randomly to users. When I hear about instances of this occurring, going to the page the link is on myself the link will work fine. 
It does happen to me as well though, and a refresh of the page the link was on does always fix the problem for that instance.

## Expected behavior

I expect the links that are all correct as they pass github actions and work after a refresh to work consistently. 

## Actual behavior

Links will randomly go to the wrong path, seemingly by either not going far enough back up the hierarchy and then trying to go from a folder shouldn't be in the path. 

E.g. A relative link such as `(../../nextPage)` from a page at say `folder1/folder2/currentPage`
Will randomly create a path of `docs/folder1/nextPage` rather than the correct url of `docs/nextPage`

## Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

Public source code: Not available publicly
Public site url: https://docs.lunalabs.io/
Docusaurus version used: 2.0.0-beta.4
Environment name and version: Chrome 92.0.4515.107, Babel 7.12.16, Node 14.15.0
Operating system and version: Windows 10 Pro, Version 21H1

## Reproducible demo

You can try links on our docs at https://docs.lunalabs.io/ but as I have stated this issue happens inconsistently and randomly.

**Comment by slorber** [comment] 2021-07-30 10:21
> E.g. A relative link such as (../../nextPage) from a page at say folder1/folder2/currentPage
> Will randomly create a path of docs/folder1/nextPage rather than the correct url of docs/nextPage

We don't "process" relative links in Docusaurus, and they are rendered "as is" in the final HTML page. Thus if those pages are broken, it is actually your fault :D 

However it's a common issue, and we provided some tools to help you figure things out more easily. See https://github.com/facebook/docusaurus/issues/3372

If you have a link such as `(my/page)` and you are clicking from:
- `/source`, the link will lead to `/my/page`
- `/source/`, the link will lead to `/source/my/page`

It is also the same when using `../..`

This is not an issue of Docusaurus, it's how relative links have ever worked. The presence of a trailing slash or not might break your relative links.

Some static hosting providers might unexpectedly add a trailing slash for you and break your links.

This issue is very commonly reported in all static site generators. I've created a repo to help figure things out: https://github.com/slorber/trailing-slash-guide

We have a new `trailingSlash` config that you should fine-tune according to your static hosting provider, and also your static hosting provider might have options you can play with.

To avoid such issues, I also added this in our doc recently: https://docusaurus.io/docs/docs-markdown-features#referencing-other-documents

![image](https://user-images.githubusercontent.com/749374/127638762-cc7d9cd8-149c-4cff-a580-5f77586f7b88.png)


---

I'm going to close for now as I think it's just a missing `trailingSlash` config. 

If you can't solve it, I will need more details, including your static hosting solution, its current configuration, and screenshots displaying the problem end-2-end (displaying the URL bad, HTML markup of the link, md content used to create the link etc...). I can't help you without all those important information unfortunately.

If you look at this page: https://docs.lunalabs.io/docs/playable/common-issues/builds and refresh the page, you will see that for some reason the slash is added to the url bad and then removed. I suspect someone already tried to fix the problem on your site and even added some JS code to "automatically" remove it, but it may fail in some cases, leading to your issues.

**Comment by bgree052** [comment] 2021-08-02 11:32
If I understand one of your solutions correctly, I need to change my links to file paths by including the file extension on the end (e.g. folder/myPage -> folder/myPage.md)?
If that is indeed the case it seems that it will mean on localhost the links will take me to unformatted pages, though I can see that on the live version the extension is removed.
Is there a workaround for fixing this behaviour on local?

**Comment by slorber** [comment] 2021-08-02 13:24
> If that is indeed the case it seems that it will mean on localhost the links will take me to unformatted pages, though I can see that on the live version the extension is removed.
> Is there a workaround for fixing this behaviour on local?

Links should be the same in prod and dev.

If you link to `[myDoc](../../myDoc.md)` and that doc as `slug: /a/b/c`, then the final link should be in both cases `/docs/a/b/c`. If that's not the case please open a bug report with a small repro, but that seems suspicious to me because this linking feature is a widely used feature. 

Note someone reported recently a bug on Windows when the site path contains a space, maybe it's affecting you locally but not on CI?: https://github.com/facebook/docusaurus/discussions/4610#discussioncomment-1108983

**Comment by bgree052** [comment] 2021-08-02 13:53
There are no console warnings, also the link that I changed to include the file extension just produced the same issue as before on local (an incorrect path). There are also no spaces in the path.

**Comment by slorber** [comment] 2021-08-02 14:09
If you can produce a small repro, I can try to run it locally and see if this happens for me too. If I can reproduce, I'll be easier to get it fixed, otherwise it will be hard because I have no idea why you have this issue which seems to only happen to you. First we should figure out if it's a bug affecting all computers or if it's related to your own local computer setup.

**Comment by bgree052** [comment] 2021-08-02 15:43
On trying a fresh build I am indeed getting a warning in the same style as that one you mentioned (Docs markdown link couldn't be resolved). 
I can also now see that there was indeed a folder (that the docs wouldnt be parsing through on live, only locally) that has a space which would be causing that on local. 
Thanks for the help there, that linked issue solution has seemd to have solved the unformatted page problem. 
I will make the links in my repo into file paths and report back if the problem persists.

**Comment by slorber** [comment] 2021-08-02 16:05
Thanks

Just fixed the bug about folders with space (https://github.com/facebook/docusaurus/pull/5270), please try the canary and let me know if it works for you: https://docusaurus.io/community/canary

Closing this issue for now but let me know if you still have a problem with relative file path links

**Closed by slorber** 2021-08-02 16:05 UTC
Labels: bug, needs triage
