### ISSUE TITLE
Hope the website title can be translated

### ISSUE THREAD

**Issue by TuiTianXia** [facebook/docusaurus#7506] opened 2022-05-26 16:47 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Good for user experience and SEO

`title: ,
tagline: ,`
+
Add keywords field

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

**Comment by slorber** [comment] 2022-05-26 17:14
duplicate of https://github.com/facebook/docusaurus/issues/4542

**Closed by slorber** 2022-05-26 17:14 UTC
Labels: closed: duplicate, feature
