### ISSUE TITLE
dark mode scrollbar

### ISSUE THREAD

**Issue by KristianRykkje** [facebook/docusaurus#5143] opened 2021-07-10 09:03 UTC
### Current state (windows)
![image](https://user-images.githubusercontent.com/59834135/125157974-44b07800-e16e-11eb-88fd-4740605a0fc8.png)
### Suggested state
![image](https://user-images.githubusercontent.com/59834135/125158012-7295bc80-e16e-11eb-8581-d7080be1e684.png)

**A dark mode scrollbar**

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Has this been requested on [Canny](https://docusaurus.io/feedback)?

No

## Motivation

I know how to implement a dark mode scrollbar, but I flop on running the project local

## Have you tried building it?

I tried cloning the repo, but got this:
![image](https://user-images.githubusercontent.com/59834135/125157900-de2b5a00-e16d-11eb-84b4-cca5a1ec2cba.png)

I use dark mode with dark mode scrollbars on every project I do and professionally I created it (dark mode and scrollbars that is) for www.fotmob.com

**Comment by Josh-Cena** [comment] 2021-07-10 12:22
https://github.com/facebook/docusaurus/pull/5120

Already addressed recently

**Comment by slorber** [comment] 2021-07-12 17:55
Yes, will be in beta.4 with infima update https://github.com/facebookincubator/infima/pull/147

duplicate of https://github.com/facebook/docusaurus/issues/3023

**Closed by slorber** 2021-07-12 17:55 UTC
Labels: feature, needs triage
