### ISSUE TITLE
Losing all the styling on using Bootstrap or SemanticUI or any other CSS-framework/CDN

### ISSUE THREAD

**Issue by KulkiratSingh** [facebook/docusaurus#4662] opened 2021-04-22 03:26 UTC
I am looking to use bootstrap/semantic-ui components in my Docusaurus generated website. But when I use either bootstrap or any other framework/CDN then all the styling is changed. I tried using it using [stylesheet](https://docusaurus.io/docs/docusaurus.config.js#stylesheets) method as well in `docusaurus.config.js` file as given in the document like this: 

`module.exports = {`
`....`
`  stylesheets: [
    {
      href:
        "https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css",
      type: "text/css",
    },
  ], ` 
  `}`
  
 but it had the some issues. Is there a way we can use bootstrap or any other CDN by not getting the built-in styling changed on using bootstrap/semantic-UI ?

**Comment by slorber** [comment] 2021-04-22 07:59
this is a question, not a bug report, so closing in favor of the duplicate discussion: https://github.com/facebook/docusaurus/discussions/4664

**Closed by slorber** 2021-04-22 07:59 UTC
Labels: needs triage, questions
