### ISSUE TITLE
"docusaurus write-heading-ids" generates unsupported ids when titles contain accentuated characters

### ISSUE THREAD

**Issue by domeav** [facebook/docusaurus#7720] opened 2022-07-04 09:37 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

French is the main language of my docusaurus doc project.

After I use the "write-heading-ids" command, titles containing accents are all messed up when I build the website: see demo, screenshot or public link below.

### Reproducible demo

https://stackblitz.com/edit/github-dzapan-b7pzge?file=docs/intro.md

### Steps to reproduce

1. Have a title with an accent in a doc markdown page ("## Développement local")
2. Use "yarn write-heading-ids . docs" (Id is generated properly: "## Développement local {#développement-local}")
3. Use "yarn build" (or yarn start)

=> the title is not displayed properly as the whole line is handled as a title (see screenshot or intro.md page in demo).

### Expected behavior

Two possibilities: either docusaurus should be able to handle title ids containing accents or the "write-heading-ids" command  should replace accentuated characters.

First option would be more consistent, since accentuated characters seem to be supported in slugs.

### Actual behavior

![Screenshot from 2022-07-04 11-31-08](https://user-images.githubusercontent.com/47646/177126790-0b0bca60-b89f-4b5e-977e-ea045c794c21.png)

See also output from our CI setup: https://doc.bluemind.net/chore/BMD-40/Premiers_pas_avec_BlueMind/Debuter_avec_le_webmail

### Your environment

- Public site URL: https://doc.bluemind.net/chore/BMD-40/Premiers_pas_avec_BlueMind/Debuter_avec_le_webmail
- Docusaurus version used: 2.0.0-beta.21
- Environment name and version: Chrome 103, Node.js 17.9
- Operating system and version: Debian Sid, Ubuntu 22.04

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-07-04 10:37
Hi, this is a bug in our title parsing algo—duplicate of #7603. It will be fixed in the next release (expect one this week).

**Closed by Josh-Cena** 2022-07-04 10:37 UTC
Labels: bug, status: needs triage
