### ISSUE TITLE
Netlify deploy using Webpack@5 OOMs

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#4843] opened 2021-05-25 10:14 UTC
## 🐛 Bug Report

After https://github.com/facebook/jest/pull/11266 the website no longer deployed successfully, see e.g. https://app.netlify.com/sites/jestjs/deploys/60acb00d26f4ce00073f7557.

After reverting in https://github.com/facebook/jest/commit/a832dc385cdbeefc255770d90f3bc1ed3617a820 it deployed successfully: https://app.netlify.com/sites/jestjs/deploys/60acbc3315bb2e0008c47fba

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## To Reproduce

Not sure, probably try to build Jest's website using `beta.0`?

## Expected behavior

It should not OOM

## Actual Behavior

The build OOMs

## Your Environment

- Public source code: https://github.com/facebook/jest/tree/master/website
- Public site url: https://jestjs.io/
- Docusaurus version used: `2.0.0-beta.0`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): N/A
- Operating system and version (desktop or mobile): N/A

## Reproducible Demo

See linked Netlify logs

**Comment by lex111** [comment] 2021-05-25 16:43
Unfortunately, this is a fairly common problem for large projects using webpack. At the moment (more as a workaround than a solution), I would suggest increasing the memory limit, something like this:

```
node --max_old_space_size=16000 node_modules/@docusaurus/core/bin/docusaurus build
```

Perhaps you want replace `babel-loader` with `esbuild`, as was done on the Docusaurus website (see https://github.com/facebook/docusaurus/pull/4766 for more details).

**Comment by slorber** [comment] 2021-06-03 11:17
Not a bug, just a memory allocation issue.

It's normal for large sites to require more nodejs memory, particularly as webpack 5 does more things than webpack 4 (like the new caching system etc)

Will be fixed in https://github.com/facebook/jest/pull/11516

**Closed by slorber** 2021-06-03 11:17 UTC
Labels: bug, needs triage
