### ISSUE TITLE
Strange error presented

### ISSUE THREAD

**Issue by RDIL** [facebook/docusaurus#4186] opened 2021-02-07 03:04 UTC
## 🐛 Bug Report

Hey all,

I just created a new docusaurus site as part of a brand new tutorial series I'm filming about it, and... I got the strangest error.

I tried reinstalling with yarn, clearing my cache, etc, but nothing worked.

Error:

```javascript
C:\Users\Reece\IdeaProjects\docusaurus-project\example>yarn start
yarn run v1.23.0-20200615.1913
$ docusaurus start
C:\Users\Reece\IdeaProjects\docusaurus-project\example\node_modules\lodash.some\index.js:107
var freeModule = freeExports && typeof module == 'object' && module && !m


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Reece\IdeaProjects\docusaurus-project\example\node_modules\cheerio\lib\api\attributes.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Reece\IdeaProjects\docusaurus-project\example\node_modules\cheerio\lib\cheerio.js:19:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Create new docusaurus site
1. yarn start

## Your Environment

- Public source code: literally the classic template
- Public site url:
- Docusaurus version used: I tried on Canary *and* alpha.70, both were broken
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 14.15.4
- Operating system and version (desktop or mobile): Windows 10 20H2

## Reproducible Demo

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Paste the link to an example repo, including a `docusaurus.config.js`, and exact instructions to reproduce the issue.)

**Comment by lex111** [comment] 2021-02-07 09:33
Couldn't reproduce this using Windows machine with Node version 14.15.4.

Are you sure you are creating new project with the `npx@docusaurus/init@latest init my-website classic` command?
In any case, we need the reproducible repo.

**Comment by RDIL** [comment] 2021-02-07 16:16
> Couldn't reproduce this using Windows machine with Node version 14.15.4.
> 
> Are you sure you are creating new project with the `npx @docusaurus/init@latest init my-website classic` command?
> In any case, we need the reproducible repo.

I used @canary

**Comment by slorber** [comment] 2021-02-08 14:58
```
npx @docusaurus/init@canary init my-website classic
cd my-website
yarn start
yarn build
```

Couldn't reproduce with canary either

**Comment by RDIL** [comment] 2021-02-08 15:05
Thats not good!  When I get home I'll upload the repro to a repository with node_modules included

**Comment by lex111** [comment] 2021-03-01 01:03
@RDIL it looks like this is already staled issue, so I will close it right now, but if the problem is still present, feel free to reopen it.

**Closed by lex111** 2021-03-01 01:03 UTC
Labels: bug, needs triage
