### ISSUE TITLE
Add "@satisfies" JSDoc tag to every "@type" JSDoc tag throughout the repository

### ISSUE THREAD

**Issue by Zamiell** [facebook/docusaurus#8639] opened 2023-02-06 21:27 UTC
[edit - Original issue was about specifying bogus fields in my "docusaurus.config.js" file and it not throwing any errors.]

### Description

- The Docusaurus config file is called "docusaurus.config.js".
- One of the fields in the config file is "algolia".
- From what I can tell, this field is defined here: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-search-algolia/src/theme-search-algolia.d.ts#L11

This is nice, because it allows for auto-complete and in-editor validation when adding entries to your configuration file.
However, this interface is not strict insofar that you can add bogus entries to the Algolia config without getting an error from the TypeScript compiler. This is a mistake, as we surely want to alert users with a red squiggly line in their editor (e.g. VSCode) the moment that they make a typo here (or insert a non-valid entry).

## Motivation

I wasted months troubleshooting issues with Algolia due to Docusaurus essentially lying to me about what were valid configuration entries: https://github.com/algolia/docsearch/issues/1658#issuecomment-1419764650

**Comment by Josh-Cena** [comment] 2023-02-06 21:48
By "not strict", do you mean we mark things as optional? Or do you mean you can add properties that do not match the declared type?

**Comment by Zamiell** [comment] 2023-02-06 22:07
I mean that end-users can add properties that do not match the declared type.

**Comment by Zamiell** [comment] 2023-02-06 22:09
e.g. When working in my Docusaurus config, I, and I expect most other people, will expect an error like this:
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIBucANgK4QCMAXMiGQLYBG0A3PkaRQEy33NtcAX1y4E6EAGcwyGJloYsAXhwdi5KrUrcAzABo1XCL2QAWAKwA2AwXUUdtAOwAOAJwGRQA

**Comment by Josh-Cena** [comment] 2023-02-06 22:10
Do you have a repro? When you hover over the `algolia` key and go to definition, what do you see?

**Comment by Zamiell** [comment] 2023-02-06 22:23
> When you hover over the algolia key and go to definition, what do you see?

When I hit F12 on the `algolia` key, it just takes me to `theme-search-algolia.d.ts` file, which looks like this:

```ts
  export type ThemeConfig = {
    algolia: {
      contextualSearch: boolean;
      externalUrlRegex?: string;
      appId: string;
      apiKey: string;
      indexName: string;
      searchParameters: {[key: string]: unknown};
      searchPagePath: string | false | null;
      replaceSearchResultPathname?: {
        from: string;
        to: string;
      };
    };
  };
```

The corresponds to this file, which I already included in the OP: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-search-algolia/src/theme-search-algolia.d.ts#L11

> Do you have a repro?

Does the bug not happen for you? If you want, you can clone my repository and see for yourself: https://github.com/IsaacScript/isaacscript

**Comment by Josh-Cena** [comment] 2023-02-08 05:58
This is working as intended. We are using `/** @type {import('@docusaurus/preset-classic').ThemeConfig} */` to type the `themeConfig` property, which is not the same as a type annotation. In fact, `@type` is closer to an `as` assertion. TypeScript's excess property check is very limited and only works in very certain cases where it's sure that "something can't be accessible". Here's a dumbed-down case:

[Playground](https://www.typescriptlang.org/play?ts=4.9.5&filetype=js#code/PQKhAIAEBcE8AcCmATRAzcBvTAoc4A3AQwBsBXRARgC5wA7MgWwCNEAnAbj0NIoCZaDFuy4BfUeABiAe2ngQwHDgDG0ugGdo4NLPABeLN3htp8WqAgwEiLDOkSF4ABS58+YuSq0+AGm7veRAFwSj83Hk8AZlpIsPBRAEocUS4gA)

```js
/** @typedef {{
  value1: number;
  value2: number;
}} Foo */

const foo = {
  prop: /** @type {Foo} */ ({
    value1: 2,
    value2: 1,
    value3: 3,
  })
};
```

This will be fixed in TS 5.0 by using the `@satisifies` annotation, but before that, there's little we can do.

**Comment by Zamiell** [comment] 2023-02-08 06:12
Ah, I see.

Well then maybe we can turn this into an issue for tracking the adding @satisfies everywhere once TypeScript 5.0 releases. (Unless there's another one for it?)

Another good option is to have the config file be generated in TypeScript from the get-go, at least when the --typescript flag is used to bootstrap the website. I see that that is being tracked in #7911, so I'll eagerly await both of these upgrades.

**Comment by Josh-Cena** [comment] 2023-02-08 06:19
Yes, we'll probably close this by changing to `@satisfies`. And yes, before #7911, we can't support TS configs, so using `@satifies` is our best mitigation.

**Comment by Josh-Cena** [comment] 2024-07-19 21:37
We now have TS configs so if you want strict type validations you should use that. Closing this as resolved!

**Closed by Josh-Cena** 2024-07-19 21:37 UTC
Labels: better engineering, domain: dx
