### ISSUE TITLE
Markdown html comment parsing error if there is a trailing space

### ISSUE THREAD

**Issue by darwintree** [facebook/docusaurus#8670] opened 2023-02-16 09:59 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Html comment in markdown files raises a syntax error  if there is a trailing space. For example, the markdown code:
`<!-- ![blabla.png](/img/blabla.png)--> ` raises an error but `<!-- ![blabla.png](/img/blabla.png)-->` doesn't.

### Reproducible demo

https://github.com/Conflux-Chain/conflux-documentation/tree/l10n_translation-pipeline

### Steps to reproduce

The error could be reproduced by using the demo in Github codespace. You can simply run `yarn zh`. Or:

1. open a project with a existed markdown file
2. add the following content to the tail of any markdown file
```
<!-- ![blabla.png](/img/blabla.png)-->
<!-- ![blabla.png](/img/blabla.png)--> 
<!-- ![blabla.png](/img/blabla.png)-->
```
Note: there is a trailing space ` ` for the second line
3. run the project, then the error should be like:
![image](https://user-images.githubusercontent.com/17946284/219324013-3edffc14-893e-4516-b1c4-8bb9a5546d6f.png)
Noting that the first and third line will be successfully parsed
4. remove the trailing space of the second line
5. the error disappears

### Expected behavior

1. The html comment with a trailing space is expected to be parsed successfully.
2. If this is hard to accomplish, at least the right error should be raised but not an "unexpected token" error

### Actual behavior

I am integrating my project with Crowdin to the i18n. The default strategy of Crowdin would convert the trailing `\n` to a space in certain circumstances. So this is the [source doc](https://github.com/Conflux-Chain/conflux-documentation/blob/acf4700b12f468a8a6d86db6a7895d6d6e53f913/docs/core/learn/getting-started/funding-your-account.md) and [here](https://github.com/Conflux-Chain/conflux-documentation/blob/acf4700b12f468a8a6d86db6a7895d6d6e53f913/i18n/zh/docusaurus-plugin-content-docs/current/core/learn/getting-started/funding-your-account.md) is an auto-generated untranslated file by Crowdin.

The command `yarn start --locale zh-Hans` but the compilation fails. Although Crowdin slightly changes the structure of the original file, I think it is acceptable because other tools, like vs code, won't raise an error. As far as I am concerned, this might be a bug of docusaurus or its markdown parsing engine.
(This is not the actual error, but is exactly same except for line number)
![image](https://user-images.githubusercontent.com/17946284/219332268-39495806-b0dc-40bd-97c4-4371495b9b4d.png)

### Your environment

- Public source code:https://github.com/Conflux-Chain/conflux-documentation/tree/l10n_translation-pipeline
- Public site URL:
- Docusaurus version used:2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): node.js v16.16.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.6

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2023-02-16 14:01
Apparently, this is a bug in MDX 1, reproducible in the MDX 1 playground: https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground/
MDX 1 is not updated anymore.

We'll upgrade soon to MDX 2 (Docusaurus v3, breaking change) but it does not use html comments by default so you'll have to use JSX comments instead.

Closing because we can't really act on it apart upgrading to MDX 2

**Closed by slorber** 2023-02-16 14:01 UTC
Labels: bug
