### ISSUE TITLE
auto generated side bar missing markdown files

### ISSUE THREAD

**Issue by cm226** [facebook/docusaurus#6703] opened 2022-02-17 09:10 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When a folder contains a markdown file with the same name as the folder, the markdown file doesn't appear in the sidebar. This worked on previous versions.

### Steps to reproduce

Sandbox link: https://codesandbox.io/s/vibrant-boyd-e34iti?file=/docs/same/same.md

1. Create a folder named X in docs
2. create a file named X.md in folder X

### Expected behavior

X appears in the sidebar

### Actual behavior

X is missing from the side bar

### Your environment

- Docusaurus version used: 2.0.0 beta-15

### Reproducible demo

https://codesandbox.io/s/vibrant-boyd-e34iti?file=/docs/same/same.md

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-02-17 09:16
Hi, this is a duplicate of #6301 and fixed in #6495.

**Closed by Josh-Cena** 2022-02-17 09:16 UTC
Labels: bug, closed: duplicate
