### ISSUE TITLE
v3 site has hydration issues on Ubuntu

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#9379] opened 2023-10-07 08:27 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

MIgrating my blog over to docusaurus v3 I noticed `"Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."` in the console.  

Translated, this error means: `Hydration failed because the initial UI does not match what was rendered on the server.`

You can see it on the Docusaurus site as well as on my own.

You can see a repro of the error at either of the URLs below; simply pop open the devtools console and navigate there:
- https://thankful-sky-0bfc7e803-712.westeurope.1.azurestaticapps.net/azure-open-ai-generate-article-metadata-with-typescript
- https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3
 
### Steps to reproduce

See description

### Expected behavior

No errors in console

### Actual behavior

Errors in console 
![image](https://github.com/facebook/docusaurus/assets/1010525/ff224b91-a8ca-4744-acaf-99d4225597d2)

The same error appears present on the docusaurus site itself:

![image](https://github.com/facebook/docusaurus/assets/1010525/0cfa9dfc-b20b-43c7-b74a-8b5054fef9ef)

I run lighthouse in github actions on my blog - it shows up there too:

![image](https://github.com/facebook/docusaurus/assets/1010525/0f817c1c-0784-4f87-bea3-6e12eac5c536)

https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1696186829813-4063.report.html

### Your environment

- Public source code: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/712
- Public site URL: johnnyreilly.com
- Docusaurus version used: 3.0.0-beta.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version - for my machine Ubuntu 22 LTS.  For LightHouse / GitHub Actions Ubuntu also

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2023-10-08 17:00
I don't see any of those hydration errors on my side


<img width="1504" alt="CleanShot 2023-10-08 at 18 57 35@2x" src="https://github.com/facebook/docusaurus/assets/749374/d93e5f8c-39ed-49e4-8052-78caa72b1686">


<img width="1909" alt="CleanShot 2023-10-08 at 18 56 22@2x" src="https://github.com/facebook/docusaurus/assets/749374/05bf6de2-1acf-4ad9-bc23-ee2dd0594604">

Tried on Chrome, Firefox, Safari, no issue found.

Maybe it's related to a local browser extension or something on your computer? I'm surprised Lighthouse reports it though.

**Comment by johnnyreilly** [comment] 2023-10-08 17:59
Lighthouse isn't running on my machine - it's on GitHub actions. So it's not a "my machine" only issue. It was actually the lighthouse report that I first noticed - then I thought I'd have a look on my own machine and found it there too.

I run Ubuntu locally - but I assume the OS isn't necessarily relevant?

**Comment by johnnyreilly** [comment] 2023-10-08 18:01
BTW when testing, are you opening devtools before navigating? I didn't see them locally until I opened devtools prior to entering the URL in the browser. Also, it only seems to be the blog section that's affected

**Comment by johnnyreilly** [comment] 2023-10-08 18:22
Interesting - cracked open my work computer (Mac OS) and there's no issue there:

<img width="1791" alt="image" src="https://github.com/facebook/docusaurus/assets/1010525/73105afb-aad0-461d-9b05-7ed4e19ff9dd">

Also I took a look at the Lighthouse GitHub Action; it runs on Ubuntu also: https://github.com/treosh/lighthouse-ci-action/blob/7f5e1fde07d17cbb1c47873c81441f53c0f72fcf/.github/workflows/main.yml#L5

It looks like this might be an Ubuntu specific issue.  (I haven't tested on Windows - don't know if it surfaces there)

**Comment by slorber** [comment] 2023-10-09 11:14
I don't know but that seems hard to reproduce currently 😅 

If you are able to reproduce it in any way locally, that would be interesting to compare the DOM html you get with/without JS, and see how they differ.

**Comment by johnnyreilly** [comment] 2023-10-09 11:44
I can reproduce locally super easily on my home Ubuntu machine. My guess is any Ubuntu machine would do the job.

So you'd like the originally served HTML and what the DOM html looks like after it starts?

Is there a best way to surface the DOM html? Devtools and copy outerhtml?

**Comment by johnnyreilly** [comment] 2023-10-09 12:04
As a first test, I tried comparing the supposedly working hydration and found that non-hydrated and hydrated already look pretty different.  How did you manage to fix the existing hydration issues @slorber?  Doesn't look like there's much to go on looking at https://github.com/facebook/react/issues/26224

**Comment by johnnyreilly** [comment] 2023-10-09 12:17
By the looks of it, there's 2 parameters sent to `onRecoverableError`:

https://github.com/facebook/react/blob/dddfe688206dafa5646550d351eb9a8e9c53654a/packages/react-reconciler/src/ReactInternalTypes.js#L270-L273

I wonder if we could expose that extra information here:

https://github.com/facebook/docusaurus/blob/35441b38e44959c30fd2ed269ed9839c31e99200/packages/docusaurus/src/client/clientEntry.tsx#L40-L42

So we've got more to go on?

**Comment by johnnyreilly** [comment] 2023-10-09 12:32
I've raised a mini PR to add the `errorInfo` paramater to what is logged here: https://github.com/facebook/docusaurus/pull/9387

**Comment by slorber** [comment] 2023-10-09 13:11
> I can reproduce locally super easily on my home Ubuntu machine. My guess is any Ubuntu machine would do the job.

Unfortunately I don't have one 😅 

Afaik our github actions use ubuntu. I was thinking of upgrading my Argos/Playwright visual tests to also ensure there's no console error on all pages of the site and catch such errors, will see how to do that. 
 
> So you'd like the originally served HTML and what the DOM html looks like after it starts?
> 
> Is there a best way to surface the DOM html? Devtools and copy outerhtml?

I guess you can use the browser with/without JS enabled, and use innerHTML or outerHTML after applying a html formatter/normalizer like Prettier (otherwise it would be hard to compare.



> As a first test, I tried comparing the supposedly working hydration on my Mac (no errors) and found that non-hydrated and hydrated already look pretty different. But that's appears to be fine.

Not surprised, differences are expected because we do some updates just after hydrating. What would be interesting to check is if there are blog-specific changes.

> How did you manage to fix the existing hydration issues @slorber? Doesn't look like there's much to go on looking at [facebook/react#26224](https://github.com/facebook/react/issues/26224)

Oh sorry, totally forgot about this but I actually added a `yarn docusaurus build --dev` option that permits to get better hydration error messages 😄 (see https://github.com/facebook/docusaurus/pull/8961)

**Comment by johnnyreilly** [comment] 2023-10-09 16:36
![image](https://github.com/facebook/docusaurus/assets/1010525/4a66ab04-2416-415d-affc-cccb3f6a4655)

I'm seeing the issue above - this is the stack trace:

```
react-dom.development.js:86 Warning: Prop `className` did not match. Server: "null" Client: ""
    at li
    at HtmlNavbarItem (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/NavbarItem/HtmlNavbarItem.js:17:27)
    at NavbarItem (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/NavbarItem/index.js:81:11)
    at ul
    at div
    at DropdownNavbarItemDesktop (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/NavbarItem/DropdownNavbarItem.js:123:11)
    at DropdownNavbarItem (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/NavbarItem/DropdownNavbarItem.js:277:11)
    at DocsVersionDropdownNavbarItem (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/NavbarItem/DocsVersionDropdownNavbarItem.js:110:11)
    at NavbarItem (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/NavbarItem/index.js:81:11)
    at ErrorCauseBoundary (webpack-internal:///../packages/docusaurus-theme-common/lib/utils/errorBoundaryUtils.js:143:5)
    at NavbarItems (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/Navbar/Content/index.js:67:24)
    at div
    at div
    at NavbarContentLayout (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/Navbar/Content/index.js:87:32)
    at NavbarContent (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/Navbar/Content/index.js:115:117)
    at nav
    at NavbarLayout (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/Navbar/Layout/index.js:91:25)
    at Navbar
    at NavbarSecondaryMenuDisplayProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/navbarSecondaryMenu/display.js:89:64)
    at NavbarMobileSidebarProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/navbarMobileSidebar.js:70:40)
    at NavbarSecondaryMenuContentProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/navbarSecondaryMenu/content.js:20:64)
    at NavbarProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/utils/navbarUtils.js:40:31)
    at HtmlClassNameProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/utils/metadataUtils.js:108:49)
    at PluginHtmlClassNameProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/utils/metadataUtils.js:141:44)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/docsPreferredVersion.js:177:54)
    at DocsPreferredVersionContextProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/docsPreferredVersion.js:191:52)
    at ScrollControllerProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/utils/scrollUtils.js:40:37)
    at AnnouncementBarProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/announcementBar.js:76:36)
    at ColorModeProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/colorMode.js:144:30)
    at eval (webpack-internal:///../packages/docusaurus-theme-common/lib/utils/reactUtils.js:93:15)
    at LayoutProvider (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/Layout/Provider/index.js:32:27)
    at Layout (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/Layout/index.js:68:13)
    at LayoutWrapper
    at BlogLayout (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/BlogLayout/index.js:101:13)
    at BlogPostPageContent (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/BlogPostPage/index.js:34:32)
    at HtmlClassNameProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/utils/metadataUtils.js:108:49)
    at BlogPostProvider (webpack-internal:///../packages/docusaurus-theme-common/lib/contexts/blogPost.js:38:33)
    at BlogPostPage (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/BlogPostPage/index.js:74:35)
    at RouteContextProvider (webpack-internal:///../packages/docusaurus/lib/client/routeContext.js:62:33)
    at LoadableComponent (webpack-internal:///../node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///../node_modules/react-router/esm/react-router.js:648:29)
    at Switch (webpack-internal:///../node_modules/react-router/esm/react-router.js:850:29)
    at Route (webpack-internal:///../node_modules/react-router/esm/react-router.js:648:29)
    at ClientLifecyclesDispatcher (webpack-internal:///../packages/docusaurus/lib/client/ClientLifecyclesDispatcher.js:48:39)
    at PendingNavigation (webpack-internal:///../packages/docusaurus/lib/client/PendingNavigation.js:83:9)
    at Root (webpack-internal:///../packages/docusaurus/lib/client/theme-fallback/Root/index.js:22:17)
    at BrowserContextProvider (webpack-internal:///../packages/docusaurus/lib/client/browserContext.js:24:35)
    at DocusaurusContextProvider (webpack-internal:///../packages/docusaurus/lib/client/docusaurusContext.js:36:38)
    at ErrorBoundary (webpack-internal:///../packages/docusaurus/lib/client/exports/ErrorBoundary.js:80:9)
    at App (webpack-internal:///../packages/docusaurus/lib/client/App.js:47:85)
    at Router (webpack-internal:///../node_modules/react-router/esm/react-router.js:267:30)
    at BrowserRouter (webpack-internal:///../node_modules/react-router-dom/esm/react-router-dom.js:58:35)
    at r (webpack-internal:///../node_modules/react-helmet-async/lib/index.module.js:17:7350)
```

**Comment by slorber** [comment] 2023-10-09 16:40
Yes I also have it in dev mode, on all pages. As I said after inspecting the code I'm unable to troubleshoot this navbar item error that only happens in dev, and not in prod.

I'm not sure it is related to your problem.
If you want to be sure, remove all navbar items and see if it fixes your prod problem.

**Comment by johnnyreilly** [comment] 2023-10-09 18:56
> If you want to be sure, remove all navbar items and see if it fixes your prod problem on blog pages:

![image](https://github.com/facebook/docusaurus/assets/1010525/6d8f057f-a5e4-4052-9fea-c2f3d2da69bb)

removing navbar items has revealed a similar issue in the blog section!

**Comment by johnnyreilly** [comment] 2023-10-10 06:05
With the new `onRecoverableError` logging in place I got this:

![image](https://github.com/facebook/docusaurus/assets/1010525/e1d57fb6-e580-4cfa-9e22-078e918e1617)

```
main.78700692.js:2 Docusaurus React Root onRecoverableError: Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ls (main.78700692.js:2:109705)
    at Oc (main.78700692.js:2:182751)
    at xd (main.78700692.js:2:170225)
    at vd (main.78700692.js:2:170197)
    at sd (main.78700692.js:2:165247)
    at w (main.78700692.js:2:232540)
    at MessagePort.T (main.78700692.js:2:233072) {componentStack: '\n    at div\n    at G (http://localhost:3000/assets…calhost:3000/assets/js/main.78700692.js:2:199606)', digest: null}
n @ main.78700692.js:2
(anonymous) @ main.78700692.js:2
wd @ main.78700692.js:2
sd @ main.78700692.js:2
w @ main.78700692.js:2
T @ main.78700692.js:2
main.78700692.js:2 Docusaurus React Root onRecoverableError: Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ls (main.78700692.js:2:109705)
    at Oc (main.78700692.js:2:182751)
    at xd (main.78700692.js:2:170225)
    at vd (main.78700692.js:2:170197)
    at sd (main.78700692.js:2:165247)
    at w (main.78700692.js:2:232540)
    at MessagePort.T (main.78700692.js:2:233072) {componentStack: '\n    at div\n    at q (http://localhost:3000/assets…calhost:3000/assets/js/main.78700692.js:2:199606)', digest: null}
n @ main.78700692.js:2
(anonymous) @ main.78700692.js:2
wd @ main.78700692.js:2
sd @ main.78700692.js:2
w @ main.78700692.js:2
T @ main.78700692.js:2
main.78700692.js:2 Docusaurus React Root onRecoverableError: Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ls (main.78700692.js:2:109705)
    at Oc (main.78700692.js:2:182751)
    at xd (main.78700692.js:2:170225)
    at vd (main.78700692.js:2:170197)
    at sd (main.78700692.js:2:165247)
    at w (main.78700692.js:2:232540)
    at MessagePort.T (main.78700692.js:2:233072) {componentStack: '\n    at footer\n    at kn (http://localhost:3000/as…calhost:3000/assets/js/main.78700692.js:2:199606)', digest: null}
n @ main.78700692.js:2
(anonymous) @ main.78700692.js:2
wd @ main.78700692.js:2
sd @ main.78700692.js:2
w @ main.78700692.js:2
T @ main.78700692.js:2
main.78700692.js:2 Docusaurus React Root onRecoverableError: Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Oc (main.78700692.js:2:182437)
    at xd (main.78700692.js:2:170225)
    at yd (main.78700692.js:2:170153)
    at hd (main.78700692.js:2:170016)
    at id (main.78700692.js:2:166823)
    at sd (main.78700692.js:2:165375)
    at w (main.78700692.js:2:232540)
    at MessagePort.T (main.78700692.js:2:233072) {componentStack: '', digest: null}
```

Not actually that helpful.

**Comment by slorber** [comment] 2023-10-10 11:07
> The issue here is coming from a common pattern in the codebase; something passing className to clsx; and it looks like className is the string "null" on the server and "" on the client:

As far as I remember, I tried to debug those during the React 18 update and still got errors in dev even after hardcoding a static value for the className. I concluded it might be a React bug.

Are you seeing a mismatch in practice, or is this only your supposition that there must be one? If you see a mismatch, please give me your exact navbar item definition, and what's the JSX/className on server vs client.

In any case it's surprising if we all get different behaviors, and even more surprising if some hydration errors are logged in `--dev` for me, but not in regular build mode. 

---

We also had this clsx edge case, not sure it's related but in case: https://github.com/facebook/docusaurus/issues/9098

**Comment by slorber** [comment] 2023-10-10 11:25
I just tried again locally on the `HtmlNavbarItem`.

Using the current code, I couldn't see anything that produces a mismatch (nothing reads from browser APIs), and by logging the className I didn't see any mismatch at runtime either.

---

This produces an hydration error, but only in dev: `Warning: Prop `className` did not match. Server: "null" Client: ""`

```js
<Comp className="" dangerouslySetInnerHTML={{__html: ''}} />
```

This doesn't produce an hydration error, in both dev/prod

```js
<Comp className="some-class" dangerouslySetInnerHTML={{__html: ''}} />
```

This really looks like a React bug to me 😅

**Comment by johnnyreilly** [comment] 2023-10-10 11:49
> Are you seeing a mismatch in practice, or is this only your supposition that there must be one? If you see a mismatch, please give me your exact navbar item definition, and what's the JSX/className on server vs client.

I'm not sure - I'm doing a `yarn build` and trying to `console.log` stuff - but the fancy updating console means I can't see output. How do you deactivate that?  I can have another try tonight.

**Comment by johnnyreilly** [comment] 2023-10-10 11:50
the frusting thing is that the issue in the blogs section is still there when I do a standard `yarn build` but even with the extra logging I dont'  get enough information to diagnose.

**Comment by slorber** [comment] 2023-10-12 09:21
> > Are you seeing a mismatch in practice, or is this only your supposition that there must be one? If you see a mismatch, please give me your exact navbar item definition, and what's the JSX/className on server vs client.
> 
> I'm not sure - I'm doing a `yarn build` and trying to `console.log` stuff - but the fancy updating console means I can't see output. How do you deactivate that? I can have another try tonight.

For me console logs are still displayed correctly 🤔  but you can try to disable locally the `new WebpackBar()` Webpack plugins.  

> the frusting thing is that the issue in the blogs section is still there when I do a standard `yarn build` but even with the extra logging I dont' get enough information to diagnose.

Yes, this is frustrating and I still have no idea how to fix that, or if it's even a bug in Docusaurus in the first place. I also wonder if others see those errors or if it's just you.

**Comment by johnnyreilly** [comment] 2023-10-12 09:25
> Yes, this is frustrating and I still have no idea how to fix that, or if it's even a bug in Docusaurus in the first place. I also wonder if others see those errors or if it's just you

So because it shows up in the lighthouse GitHub action results that don't run on my machine I'm pretty sure it's not just me. My guess is that anyone who uses Docusaurus v3 and had lighthouse set up would probably see this

**Comment by johnnyreilly** [comment] 2023-10-12 09:39
I've raised https://github.com/facebook/docusaurus/pull/9393 which points lighthouse to the Docusaurus blog - if my theory is correct, the issue should show up in the lighthouse report on that PR for the `/blogs` URL.

**Comment by johnnyreilly** [comment] 2023-10-12 10:08
@slorber I'm not seeing the addition of the /blogs endpoint show up on my linked PR for some reason - does the PR need to be merged for us to be able to see `/blog` results show up or something (because I'm coming from a fork)?

<img width="1789" alt="image" src="https://github.com/facebook/docusaurus/assets/1010525/240ba7d8-ea05-4431-95cb-31db5a250570">

**Comment by johnnyreilly** [comment] 2023-10-12 12:16
Thanks for merging the related PR @slorber - I've just triggered a whitespace PR to see if the changes are applied https://github.com/facebook/docusaurus/pull/9395

**Comment by slorber** [comment] 2023-10-12 12:43
😅 annoying, I don't know how I'm going to solve that. I'll have to try various things and rely on CI to know if it improves maybe.

**Comment by slorber** [comment] 2023-10-12 13:10
In https://github.com/facebook/docusaurus/pull/9395#issuecomment-1759495361 it looks like it's not just the blog but actually any Docusaurus page has errors, do you also see that locally? Particularly on docs?

**Comment by lebalz** [comment] 2023-10-12 14:17
Yes, this pops up here aswell:
<img width="1199" alt="image" src="https://github.com/facebook/docusaurus/assets/22354689/90d7aa32-d48b-4c34-8213-6d1a8bb555b7">

**Comment by johnnyreilly** [comment] 2023-10-12 20:36
yup seems to be a general issue - this is what I get at https://docusaurus.io/

![image](https://github.com/facebook/docusaurus/assets/1010525/ec054f77-a8b1-423e-b22d-e4c92a2ac386)

**Comment by slorber** [comment] 2023-10-24 16:05
@lebalz are you using Ubuntu as well?
Do we agree that this only happens in Ubuntu?

I will need your help here because I'm using BrowserStack to test this and so far I couldn't reproduce using various combinations of OS/browsers.

---

Can you try various browsers in incognito mode on Ubuntu and report the exact OS/Browser versions that can reproduce these hydration errors? And check multiple pages (home, docs, blog?)

A clear report like this would help me a lot:

```md

# Ubuntu v22.04

## Firefox v119

- [/](https://docusaurus.io/): ✅
- [/docs](https://docusaurus.io/docs): ❌ (React error 418)
- [/blog](https://docusaurus.io/blog): ❌ (React error 418)

## Chrome v118

- [/](https://docusaurus.io/): ✅
- [/docs](https://docusaurus.io/docs): ❌ (React error 418)
- [/blog](https://docusaurus.io/blog): ❌ (React error 418)

**Comment by lebalz** [comment] 2023-10-24 21:27
ok, could it be somehow content-related? I can reproduce it only on the following blog post, but consistently on each browser in win 11

# Windows 11 (22H2, Build Version 22621.2428)

## Firefox v119.0
- [/blog/releases/2.4](https://docusaurus.io/blog/releases/2.4) ❌ (React error 418)

## Edge v118.0
- [/blog/releases/2.4](https://docusaurus.io/blog/releases/2.4) ❌ (React error 418)

## Edge v118.0 (Guest Mode)
- [/blog/releases/2.4](https://docusaurus.io/blog/releases/2.4) ❌ (React error 418)

## Chrome v118.0
- [/blog/releases/2.4](https://docusaurus.io/blog/releases/2.4) ❌ (React error 418)

## Brave v1.59.120 (Chromium: 118.0.5993.88)
- [/blog/releases/2.4](https://docusaurus.io/blog/releases/2.4) ❌ (React error 418)

**Comment by slorber** [comment] 2023-10-25 08:19
Thanks for the into !

@lebalz yes https://docusaurus.io/blog/releases/2.4 definitively has an hydration problem, it's a quite specific case due to using an embedded iframe with a query-string. I can reproduce it and will see how to fix it.

Do you have any problem on other posts that do not contain an iframe? For example this one?
https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3

---

@johnnyreilly are you using guest mode on Chrome and still getting errors?
Do you have any extension enabled that could produce it?
Do you have google chrome autotranslate or something similar in action? That can lead to hydration issues.

**Comment by slorber** [comment] 2023-10-25 11:15
@johnnyreilly to be honest I'm not sure how I will be able to fix this issue 😅 

This Docusaurus page that just prints "Hello" is still producing a lighthouse console error 🤷‍♂️  so I guess you get it too

https://deploy-preview-9446--docusaurus-2.netlify.app/

![CleanShot 2023-10-25 at 13 14 56](https://github.com/facebook/docusaurus/assets/749374/d94e0c72-fdc1-4399-a80e-4d230f86a54b)


I'll try to see if there's something in Docusaurus core, but this quite surprising 😅 

And the `--dev` errors do not even report it so 🤷‍♂️

**Comment by johnnyreilly** [comment] 2023-10-25 11:21
> @johnnyreilly are you using guest mode on Chrome and still getting errors?

Yes.  And it shows up in Lighthouse.

> This Docusaurus page that just prints "Hello" is still producing a lighthouse console error 🤷‍♂️ so I guess you get it too
>
> https://deploy-preview-9446--docusaurus-2.netlify.app/

Nope - looks fine

<img width="1384" alt="image" src="https://github.com/facebook/docusaurus/assets/1010525/6ba2d6e4-19f9-4556-b4eb-d63930498b8d">

**Comment by johnnyreilly** [comment] 2023-10-25 11:27
Did you see my comments on https://github.com/facebook/docusaurus/pull/9447 ?  I'm happy to help you get Docusaurus running on Azure Static Web Apps and plug in Lighthouse there.

**Comment by slorber** [comment] 2023-10-25 15:56
Damn, I spent the day on this to figure out the problem is not Ubuntu but mobile viewport.

If you hydrate a page on small device (like Lighthouse does) you get the error.

This should be fixed now: https://deploy-preview-9446--docusaurus-2.netlify.app/

**Closed** 2023-10-25 16:18 UTC
Labels: bug

**Comment by johnnyreilly** [comment] 2023-10-25 16:28
Good work on the mobile viewport stuff! I'll test on my home machine when I get a moment. The one thing that's in the back of my mind is that I have seen this on Ubuntu in desktop view - will let you know what I find

**Comment by johnnyreilly** [comment] 2023-10-25 16:40
It might be good to run lighthouse in desktop and mobile view regardless. There's tips here on how to do it

https://github.com/treosh/lighthouse-ci-action/issues/79#issuecomment-804938524

**Comment by slorber** [comment] 2023-10-25 17:19
Thanks, I'm not satisfied with our current setup, noted to also test on desktop here: https://github.com/facebook/docusaurus/issues/9449

**Comment by lebalz** [comment] 2023-10-25 17:29
Good catch and thanks for the big effort 💪

**Comment by johnnyreilly** [comment] 2023-10-25 18:12
I still see the error on the mobile view @slorber - is the change live? Browsing at https://docusaurus.io/ and I've done a hard refresh

![image](https://github.com/facebook/docusaurus/assets/1010525/9da78a7c-2ac9-41f5-9b92-bdddc5027c8e)

**Comment by slorber** [comment] 2023-10-26 08:20
Not live yet, deploy failed like often due to our weird i18n setup

If it's ok in the deploy preview it should be soon in prod

**Comment by FZambia** [comment] 2023-11-04 16:38
@slorber hello, I just updated Centrifugo doc site to Docusaurus v3 and getting similar console errors in production build. I am using v3.0.0 - here is a branch with update, https://github.com/centrifugal/centrifugal.dev/pull/45 . Looking at discussion it seems to be fixed in v3.0.0 - but still sth causes all these errors.

For now I rolled back to using v2.

**Comment by slorber** [comment] 2023-11-06 20:50
@FZambia those errors are likely due to your own site code. 

Remove your React code, third party plugins, and if error persist then it's our fault, but I doubt it it.

Or you can provide a minimal repro.

Those errors are not a big deal. With React 18 we only log them while they were there but kind of hidden before in v2. It's likely that your v2 site already has hydration issues, that are simply unreported

**Comment by duanbaosheng** [comment] 2023-12-31 09:44
i  meet the same error,   i run
```
npx create-docusaurus@latest my-website classic --typescript
cd my-website
npm run build
```
i start a koa server 
then, i copy the files in the build dir to the static dir
then  reproduce the error.
i  do not know how  to fix it.

but i  run 
```
npm run build
npm run serve
```
there is  no error

**Comment by FZambia** [comment] 2023-12-31 10:03
> Remove your React code, third party plugins, and if error persist then it's our fault, but I doubt it it.

This advice helped me, thanks! In my case this was due to the following plugin in `docusaurus.config.js`:

```javascript
  plugins: [
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        hashed: true,
      },
    ],
```

Removing it fixed all the errors.

**Comment by ismaelga** [comment] 2024-03-05 16:06
I was facing this issue serving static build with Caddy.

My issue was that I was always serving index.html which wouldn't match what React would render for each other page on the client, obviously!

Just writing this to give a tip on how to debug this:
- Get the html from what's being rendered (DOM)
- Get the source served
- Format both with any formatter and do a diff using any diffing tool to see what's different.
- That diff should give you good hints on where your issues come from. 

Maybe this obvious for some, but might be a good hint for others 🍻

**Comment by slorber** [comment] 2024-03-05 16:28
> My issue was that I was always serving index.html 

That's a common issue with hosts that do not serve static deployments correctly by default. 

You can also use devtools to throttle the network (or even block JS execution) and see that it first renders your homepage, and then it gets "fixed" by the local JS.
