### ISSUE TITLE
Left nav sometime can't scroll on Safari

### ISSUE THREAD

**Issue by chenglou** [facebook/docusaurus#877] opened 2018-07-30 11:20 UTC
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open Safari, make sure browser is vertically small
1. Go to https://docusaurus.io/docs/en/installation
1. Scroll the main area til the bottom
1. Try to scroll sidebar

## Expected behavior

Sidebar scrolls

## Actual Behavior

Main area scrolls instead (most of the time). This is a relatively known problem with Safari. I believe immutable.js used to have this problem. They've since switched to a static side bar (which funnily was what docusaurus used a while ago).

## Reproducible Demo

See above.

**Comment by JoelMarcey** [comment] 2018-08-22 14:44
Claimed by @sbansal3096

**Comment by JoelMarcey** [comment] 2018-09-05 15:43
@sbansal3096 does not have a Mac (and thus Safari) to do this work.

**Comment by lensbart** [comment] 2018-11-23 09:16
Right sidebar too, see: https://github.com/facebook/jest/issues/7296#issuecomment-441169441

**Comment by leeyspaul** [comment] 2020-10-07 22:44
Hi! Is this stale? I tried to replicate this and I could not reproduce. @JoelMarcey @endiliey

**Comment by lensbart** [comment] 2020-10-08 07:17
I can’t reproduce this either.

If memory serves me well, this used to be a Safari bug, because I think I encountered this on other (non-Docusaurus) web pages as well.

So yes, I think you can close this issue!

**Comment by leeyspaul** [comment] 2020-10-08 13:31
@lensbart awesome! I guess we'll leave that to the folks who can do it. :]

**Comment by slorber** [comment] 2020-10-08 16:53
Let's close it until someone else find this bug again.

Note: it's v1 so must be looked for in v1 websites :)

**Closed by slorber** 2020-10-08 16:53 UTC
Labels: bug, good first issue, help wanted, platform-inconsistency, v1
