### ISSUE TITLE
[v2] Code block fails to render when using escaped HTML characters

### ISSUE THREAD

**Issue by akrantz01** [facebook/docusaurus#3246] opened 2020-08-09 00:35 UTC
## 🐛 Bug Report

In a table, using `<code>` tags with any HTML entities (I think that's the right term) does not render the text as code. However, when the there is only an HTML entity in the code block and nothing else, it works as expected.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Create a table with at least 1 column
1. Insert `<code>test escape &amp;</code>` into a row
1. The inline code does not render properly

## Expected behavior

I expected it to render the block as code with the HTML entities replaced with their representations.

## Actual Behavior

It rendered without formatting the text as code, but still replaced the HTML entities.

For example, with the markdown: `<code>test &amp;</code>` in a table's cell, it renders **_test &amp;_** (bold and italics for separation from the rest of the text).

## Your Environment

- Docusaurus version used: v2.0.0-alpha61
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile): desktop

## Reproducible Demo

I hope a gist is ok, the repo itself is private.

https://gist.github.com/akrantz01/05a917f9dea75fb73d9991beddc58c84

Also, an interesting note: GitHub ends up rendering it correctly.

**Comment by slorber** [comment] 2020-08-11 13:44
Sorry but reading this issue it's really hard to scan where exactly is the repro case (your link has a table with a lot of examples, not sure which one you feel is actually broken because it looks like the expected behavior to me, for all of them)

Is it even related to markdown tables at all?

We use MDX (and unlikely to change) that compiles markdown to JSX. 

It may be worth checking if your example compiles to JSX in the correct form: https://mdxjs.com/playground
If it's not the case, report the bug to MDX directly.

I'm closing but could reopen if convince me

**Closed by slorber** 2020-08-11 13:44 UTC
Labels: bug, needs triage

**Comment by akrantz01** [comment] 2020-08-11 18:22
Oh, sorry if it wasn't clear. I've updated the [gist](https://gist.github.com/akrantz01/05a917f9dea75fb73d9991beddc58c84) with images of the expected and actual results. I think it is related to markdown tables since I can't seem to get it to reproduce when its not in a table.

Is it the expected result to have the 6th example not render with the code tag around it? Here's the images from the gist when its rendering in Docusaurus:

Expected result:
![expected](https://i.imgur.com/8XhWSfZ.png)

Actual result:
![actual](https://i.imgur.com/Aixjqd0.png)

Also, it seems as though it may be a bug in MDX since when I try the table in the playground, I get an error when the last line is included: `TypeError: e.trim is not a function`. I'll file a bug report with them.

**Comment by slorber** [comment] 2020-08-12 10:02
I don't know all the specifics of MDX, maybe it's a bad usage of this syntax, as MDX is not 100% compatible with CommonMark. MDX v2 may also improve this.
