### ISSUE TITLE
Cannot provide siteDir to external commands

### ISSUE THREAD

**Issue by ouadie-lahdioui** [facebook/docusaurus#9029] opened 2023-05-31 17:57 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hi All,

All internal Docusaurus commands accept the `siteDir` parameter in addition to other options:

```
yar docusaurus serve [options] [siteDir]
yar docusaurus clear [options] [siteDir]
...
```

That provides the possibility to execute internal commands from another directory. For example, considering the following project organization:

```
my-app/
|-- package.json
|-- docs/
│  |-- docusaurus.config.js
```

Internal commands can be executed directly from `my-app`, for example: `yarn docusaurus serve -p 8081 docs`

**Whats wrong?**

I cannot execute external command docs:version directly from `my-app `
```
yarn docusaurus docs:version 1  --> ❌ Not working
yarn docusaurus docs:version 1 docs --> ❌ Not working
yarn docusaurus docs:version docs 1 --> ❌ Not working
yarn docusaurus docs:version 1 --config docs/docusaurus.config.js  --> ❌ Not working
```

### Steps to reproduce

1. yarn install
2. yarn docusaurus docs:version 1

### Expected behavior

[SUCCESS] [docs]: version 1 created!

### Actual behavior

[ERROR] No config file found.
[INFO] Expected one of:
- docusaurus.config.js
- docusaurus.config.cjs
You can provide a custom config path with the `--config` option.
/my-app/node_modules/@docusaurus/core/lib/server/config.js:25
        throw new Error();
              ^

### Your environment

- Docusaurus version used: 2.3.1
- Environment name and version: Node v18
- Operating system and version: MacOS Montery 12.3

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-05-31 18:16
Duplicate of https://github.com/facebook/docusaurus/issues/8903

**Closed by Josh-Cena** 2023-05-31 18:16 UTC
Labels: bug, status: needs triage
