### ISSUE TITLE
Scrollbar is still white in dark mode

### ISSUE THREAD

**Issue by danielzgtg** [facebook/docusaurus#3023] opened 2020-07-05 03:04 UTC
## 🐛 Bug Report

Dark mode doesn't apply to the scrollbar. This hurts my eyes.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Open https://v2.docusaurus.io/docs/
2. Make sure the toggle is set to dark mode
3. Look at the scrollbar at the very right

## Expected behavior

The scrollbar is grey or black.

Something like:

![image](https://user-images.githubusercontent.com/25646384/86524575-34bed380-be4a-11ea-8733-7f5f8fcd26da.png)

## Actual Behavior

The scrollbar is still the browser default white.

![image](https://user-images.githubusercontent.com/25646384/86524558-0e009d00-be4a-11ea-88b6-a5707ed49622.png)

## Your Environment

- Docusaurus version used: None
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Chrome 83.0.4103.116, Node.js None
- Operating system and version (desktop or mobile): Desktop Ubuntu 20.04

## Reproducible Demo

Possibly https://github.com/facebook/docusaurus/tree/master/website

I've only checked by going to https://v2.docusaurus.io/docs/

**Comment by slorber** [comment] 2020-07-06 10:04
@danielzgtg that's not a bug to me, and highly subjective. I personnaly prefer the native scrollbar than your dark scrollbar. There are plenty of sites with dark mode yet the native browser scrollbar, and afaik there's no way to tell a scrollbar to be dark, you have to apply styling to it (which might not work well across all browsers), which is then quite subjective.

We could accept a PR with an option to style the style bar for dark mode, but this is likely not something we'd apply by default to all D2 websites. 

Also note that people that want a dark scrollbar can provide their own stylesheet.

Feel free to open a PR with a proposal implementation if you feel this should be an option.

**Comment by vitaly-zdanevich** [comment] 2021-07-02 18:39
> afaik there's no way to tell a scrollbar to be dark

For Firefox you can use [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color):
```
:root {
    scrollbar-color: #333 #000;
}
```

**Comment by slorber** [comment] 2021-07-07 18:01
Re-opening because the new `color-scheme` CSS property can help tell the browser to use a native dark scrollbar, this seems the way to go even

https://dev.to/okikio/psa-add-dark-mode-to-your-sites-or-at-least-let-the-browsers-do-it-for-you-18hi

**Comment by lex111** [comment] 2021-08-24 09:34
Fixed in #5193.

**Closed by lex111** 2021-08-24 09:34 UTC
Labels: bug, needs triage
