### ISSUE TITLE
TOC is missing when content imported via mdx

### ISSUE THREAD

**Issue by msteller-connyun** [facebook/docusaurus#4414] opened 2021-03-12 15:02 UTC
## 🐛 Bug Report

When an mdx file is imported into an other mdx file, the imported content is ignored by the TOC.

## To Reproduce

1. Create a mdx file with some headlines (#, ##)
2. Import the mdx file into an other one and call the mdx file as a jsx component

main.mdx:
```
import Demo from './demo.mdx‘;

<Demo></Demo>
```

## Expected behavior

The headers from demo.mdx should be visible in the TOC of main.mdx 

## Actual Behavior

TOC ignores demo.mdx, when imported.

## Your Environment
  "@docusaurus/core": "2.0.0-alpha.71",
  "@docusaurus/preset-classic": "2.0.0-alpha.71",

**Comment by slorber** [comment] 2021-03-12 16:51
Yes, this is a known issue I'd really like to get solved, but it does not seem easy to solve :'(

Duplicate of https://github.com/facebook/docusaurus/issues/3915

**Closed by slorber** 2021-03-12 16:51 UTC
Labels: bug, needs triage
