### ISSUE TITLE
Error retrieving content from Next and Previous Buttons in multi-language docs

### ISSUE THREAD

**Issue by nguyenquyynh** [facebook/docusaurus#10753] opened 2024-12-10 03:08 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

There are some problems in getting languages ​​in a multilingual Docusaurus. My page has 2 languages: vi-VN and en-US. I configured the sidebar to automatically generate and use _category_.json and It looks like this : 
![{02317CAD-BE3F-46AE-9F5B-7AEB1BE12689}](https://github.com/user-attachments/assets/7f29703f-4d68-41e2-a0e1-dbfae42fe06b)

This is the directory structure : 
![image](https://github.com/user-attachments/assets/9eb2578d-7477-4f38-a6e1-d63d95ee7b50)

However, when running the project, I noticed that the next and previous suction in the vi-VN language version took the label of the _category_.json file of the original language (en-US), this is the image
It seems that the Docusaurus docs site also has this problem

![{3EAD1B96-BBB4-4B6C-8ABD-FE88EC1EB882}](https://github.com/user-attachments/assets/17bcd805-8e00-406e-9916-08a85e16c534)

![{91A8C392-7361-49D3-8A83-0F1090BCE90F}](https://github.com/user-attachments/assets/5bc58677-cc59-4d06-922c-83f70e56a53b)

### Reproducible demo

https://docusaurus.io/zh-CN/docs/i18n/git

### Steps to reproduce

Regarding the error pattern, I think you can see it clearly as long as you visit the official docusaurus page.

### Expected behavior

I would expect that the male page content displayed in the next and back buttons would display the correct content in the current language instead of just the original language.

### Actual behavior

![{2828C2E6-3BEE-4530-AAF7-1386B1D78FEF}](https://github.com/user-attachments/assets/450f4ecb-2edc-4167-b4ab-740c0a9fc814)

![{CCF180FD-AFD8-4CF3-9BDC-8ED4527E6F6A}](https://github.com/user-attachments/assets/bede11ec-6e2c-47c5-b6d3-9882d9504b18)

I tried changing the content of the _category_.json file of the original language and it's confusing that the Content displayed at the 2 buttons is according to the original language (This happens when using category.json to set up the sidebar automatically and the next or previous page is the summary of the category )

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-12-10 10:02
Duplicate of https://github.com/facebook/docusaurus/issues/8996

Unfortunately we don't have support for localizing category.json files. 


However it remains possible to handle through our `write-translations` CLI.

Example: https://docusaurus.io/ko/docs/configuration

![CleanShot 2024-12-10 at 11 01 53](https://github.com/user-attachments/assets/a497ae78-b0ec-41f1-a1c6-e9c0a70ec220)

**Closed by slorber** 2024-12-10 10:02 UTC
Labels: bug, status: needs triage
