### ISSUE TITLE
Tailwind Error in running Docusaurus in already exisiting project

### ISSUE THREAD

**Issue by temtechie** [facebook/docusaurus#8607] opened 2023-01-31 20:22 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

When i tried running docusaurus in my already existing nodejs project it gave series of error. until i found out that tailwind needs to be installed and that solved the bug. it was never mentioned anywhere in the documentation. this happened while running Docusaurus in an already exisiting project , call it a monorepo 
using this command npx create-docusaurus

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment] 2023-01-31 21:38
Duplicate of https://github.com/facebook/docusaurus/issues/6631?

**Closed** 2023-02-01 21:27 UTC
Labels: documentation, status: needs triage
