### ISSUE TITLE
crowdin-cli fails but docusaurus still deploy

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#1188] opened 2019-01-16 17:11 UTC
## 🐛 Bug Report

After merging a change in MD that fixed the link from GitHub's standpoint, the deployed website lost most translations from crowdin. See https://github.com/facebook/jest/pull/7638/files

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Mess up link in MD
1. Deploy app with translations
1. Watch in horror as most translations are deleted from `gh-pages`

## Expected behavior

That, if an issue with a link arose, the new website would not be published

## Actual Behavior

Even though the CI build failed, but it still pushed `gh-pages`.

## Reproducible Demo

See https://github.com/facebook/jest/issues/7639 and the CI runs.

Failed build which still pushed a broken website: https://circleci.com/gh/facebook/jest/44116

Successful deploy after revert: https://circleci.com/gh/facebook/jest/44129

**Comment by JoelMarcey** [comment] 2019-01-23 22:32
@SimenB Hi! Have you tried to reproduce this more than once? Just wanted to make sure this wasn't something flaky.

**Comment by SimenB** [comment] 2019-01-23 22:47
No, afraid to test again as it was 45 minutes of downtime even after the revert...

**Comment by JoelMarcey** [comment] 2019-01-24 00:59
I am trying to figure out a way if this is a one-off or if we need to contact Crowdin about this. Because, I assume, you have made updates to docs like this in the past with no issues with the translations, right?

**Comment by SimenB** [comment] 2019-01-24 06:41
Yes, we've added and removed links without issue

**Comment by endiliey** [comment] 2019-03-28 12:52
I just investigated this today (was away for quite a while). It turns out that this is happening because crowdin-cli fails to download that enormous amount of docs at some point (well, API sometimes fail)

And after that step, Docusaurus run `publish-gh-pages`. And as the behavior suggest, we don't check if there is any missing translated docs (because that's supposed to be provided by crowdin) and the deploy somehow still proceed. This is a very tricky bug because even the CI log at https://circleci.com/gh/facebook/jest/44116 is incomplete and stops at this particular step

```bash
  yarn crowdin-upload
  yarn crowdin-download
```

Reference:
https://github.com/facebook/jest/blob/e08be020e9ddcab5b89cd871a2cbd72f006cda7b/.circleci/website.sh#L23-L24

---

Is this still happening recently @SimenB ?

I am particularly quite confident that this is not recently happening anymore to Jest since the number of versions at Jest has decreased a lot (https://jestjs.io/en/versions)

**Comment by SimenB** [comment] 2019-03-28 14:46
We have not seen this again, AFAIK

**Comment by endiliey** [comment] 2019-03-28 15:57
Hmm.. I'm not going to close this issue up. But fixing this "bug" can be very tricky as it seems to be quite non-deterministic and a little bit hard to reproduce. But of course we should do a better job catching these.

I believe this is the reason why jest had lot of i18n 404 in the past. Thank you for the information @SimenB

**Comment by endiliey** [comment] 2019-07-26 16:14
I dont think this issue still persist. at least nobody has reported it so far. 

Feel free to re-open :)

**Closed by endiliey** 2019-07-26 16:14 UTC
Labels: better engineering, bug
