### ISSUE TITLE
CSS Minimizer: Call retries were exceeded

### ISSUE THREAD

**Issue by lewisjkl** [facebook/docusaurus#8147] opened 2022-09-29 17:29 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Truthfully, I am not positive if this issue exists due to something that needs to be changed in this repo or in https://github.com/webpack-contrib/css-minimizer-webpack-plugin.

It seems that ever since `css-minimizer-webpack-plugin` version 4.2.0 was released (about 2 hours ago), I have been getting the following error when running `yarn build`:

```
assets/css/styles.45f640f6.css from Css Minimizer plugin
Error: Call retries were exceeded
assets/css/styles.8ef29f8a.css from Css Minimizer plugin
Error: Call retries were exceeded
```

Reproduction:

```console
> git clone https://github.com/facebook/docusaurus.git
> cd docusaurus/examples/classic
> yarn install
> yarn build
```

### Steps to reproduce

```console
> git clone https://github.com/facebook/docusaurus.git
> cd docusaurus/examples/classic
> yarn install
> yarn build
```

### Expected behavior

No error should be output when running `yarn build`

### Actual behavior

Error was output.

### Your environment

- Public source code: Docusuarus github repo
- Public site URL: Docusuarus github repo
- Docusaurus version used: Latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): (Node.js 16.17.0), (yarn 1.22.19)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 12.5.1, also reproduced in CI on Ubuntu

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-09-29 17:33
If it's upgrading their version between minor versions that breaks, it's very likely their bug. Let's wait for a few days to see what follows.

**Comment by orsenthil** [comment] 2022-09-29 23:58
I hit this problem too. What will be a workaround?  I see the doc always recommends using the latest 

```
 npx create-docusaurus@latest my-website classic
```

**Comment by ericpassmore** [comment] 2022-09-30 00:38
Doesn't appear to be a Docusaurus issue, workaround is to downgrade css-minimizer-webpack-plugin. That worked for me.
```
npm install css-minimizer-webpack-plugin@4.1.0
```
I encountered the same error with 
- docusaurus@2.1.0 typescript
- node@16.17.1
- css-minimizer-webpack-plugin@4.2.0
- running `npm run build`

**Comment by Josh-Cena** [comment] 2022-09-30 00:51
Closing in favor of https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/198. Whatever the root cause is, seems to be an upstream issue. Thanks for reporting!

**Closed by Josh-Cena** 2022-09-30 00:51 UTC
Labels: bug, status: needs more information, external
