### ISSUE TITLE
Broken Link when class defined in `index.ts` file

### ISSUE THREAD

**Issue by rbala19** [facebook/docusaurus#8665] opened 2023-02-13 22:58 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Currently running into the following build failure when defining a class in an index file. 
The entrypoint provided to the config is to the `src` directory of this package, in which this index file lives. 

```
Exhaustive list of all broken links found:

- On source page path = /code/@app/example-library/modules/:
   -> linking to ../classes/.TestDocusaurusFailure (resolved as: /code/@app/example-library/classes/.TestDocusaurusFailure)
```

A class is defined in an index file in the examples library. This produces a broken link where the index module in this library builds a malformed link to this class in the form of `.{className}`. 

### Reproducible demo

https://github.com/rbala19/docusarus-reprod

### Steps to reproduce

Steps are outlined in example repo. 

### Expected behavior

Expected link to be formed to `{index}.{className}`

### Actual behavior

Link was formed to `.{className}`

### Your environment

- Public source code: https://github.com/rbala19/docusarus-reprod
- Public site URL:
- Docusaurus version used: 2.3.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.18.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): OS X 13.1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-02-13 23:02
Is this a duplicate of, or at least closely related to, https://github.com/facebook/docusaurus/issues/8644?

**Comment by rbala19** [comment] 2023-02-13 23:22
Yes, that ticket can be closed - this ticket contains a reproducible demo as well as a more focused error log.

**Comment by slorber** [comment] 2023-02-15 18:42
Your repro is quite large and you did not really explain which files we are supposed to look at 😅 

Reading your issue, I also have no idea what you mean by "class". Apparently, it's not CSS (no, it was not obvious) because I was able to find this: `export class TestDocusaurusFailure {}`.

Your repro contains a lot of things that are outside the scope of Docusaurus. Apparently you are using "typedoc-plugin-markdown" among other things. Are you sure the bug is a Docusaurus bug and not a bug in another part of your system?

Docusaurus is only responsible for rendering static Markdown files, and is not involved in any TS/JS/class to Markdown transformation. For this reason, I'm closing this issue because I believe it is not a Docusaurus bug.

If you still think it's a Docusaurus bug, we can re-open it. Please create a smaller repro that doesn't involve so many dependencies, use static Markdown files, and only official Docusaurus packages. We are not responsible for bugs in third-party packages so using them in bug repros is not a good idea.

**Closed by slorber** 2023-02-15 18:42 UTC
Labels: bug, status: needs more information
