### ISSUE TITLE
[Fresh Install] Outdated NPX Template, Broken Links, "Edit This Page" Does Not Work

### ISSUE THREAD

**Issue by Rubix982** [facebook/docusaurus#5243] opened 2021-07-29 11:41 UTC
## 🐛 Bug Report

The "Edit This Page" text that is generated for each page in the `npx` tutorial does not work. With each article given in the starting code generated by the template example, nothing works, and all the links are breaking.

### Prerequisites

- [X] I'm using the latest version of Docusaurus - **Docusaurus 2**
- [X] I have tried the `npm run clear` or `yarn clear` command - **Not Related**
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages - **Not Related**
- [X] I have tried creating a repro with https://new.docusaurus.io - **This is also broken and not up to date**
- [X] I have read the console error message carefully (if applicable) - **Not applicable**

### Description

Investigating this issue, I found that the template is quite old and hasn't been updated as much as the documentation itself present in this repository,

1. The content is extremely old
2. Some links are broken
3. The [`docs/`](https://github.com/facebook/docusaurus/tree/master/website/docs) looks very different than the `docs/` generated by the `npx` template (`npx @docusaurus/init@latest init my-website classic`)

This issue is a list, and the way they can be solved for each of the files mentioned,

Further instructions assume you have firstly finished the `prerequisites` in this issue.

The list of issues relate to the `docs/` folder entirely. They are, and can be fixed in the following ways,

- [ ] FILE `intro.md` should be renamed to `introduction.md`
- [ ] FILE `intro.md` should be updated with latest changes from 
- [ ] DIRECTORY `tutorial-basics` should be renamed `guides`
- [ ] Basically the entire `docs/` folder needs to be updated this way

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes - this is quite a big issue since the resultant template is out of date for the documentation, so maybe this isn't `One issue, one bug` per se.

## Steps to reproduce

```bash
npx @docusaurus/init@latest init my-website classic

cd my-website
npx docusaurus start
```

This will generate the following structure,

```bash
❯ tree -L 1.
├── babel.config.js
├── blog
├── build
├── docs
├── docusaurus.config.js
├── node_modules
├── package.json
├── README.md
├── sidebars.js
├── src
├── static
└── yarn.lock

6 directories, 6 files
```

Inside the `docs/` folder, the following structure exists which is very different from the [`docs/`](https://github.com/facebook/docusaurus/tree/master/website/docs) in this repository,

```bash
❯ tree
.
├── intro.md
├── tutorial-basics
│   ├── _category_.json
│   ├── congratulations.md
│   ├── create-a-blog-post.md
│   ├── create-a-document.md
│   ├── create-a-page.md
│   ├── deploy-your-site.md
│   └── markdown-features.mdx
└── tutorial-extras
    ├── _category_.json
    ├── manage-docs-versions.md
    └── translate-your-site.md

2 directories, 11 files
```

## Expected behavior

The documentation that I should have retrieved with the `npx` example should be the latest one. The problem with this is that the `npx` template was not being pushed the latest changes inside of the `docs/` folder, and has to be updated every single time there is any change to the `docs/`. A good solution would be a process that updates the `docs/` under `npx @docusaurus/init@latest init my-website classic` if any changes occur within the `docs/` of this repository.

## Actual behavior

An outdated documentation with broken links is built.

## Your environment

- Public source code: `npx @docusaurus/init@latest init my-website classic`
- Public site URL: NA
- Docusaurus version used: 2
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Google Chrome 92.0.4515.107 , NodeJS v12.41.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): `Linux saif-kubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

## Reproducible demo

The forked `CodeSandbox` reproducible is at this [link](https://codesandbox.io/s/silly-dawn-9o61m). Navigating to `tutorials` -> `next page` -> `create a page`, and then navigating to the hosted `documentation` at [Docusaurus - Creating Pages](https://docusaurus.io/docs/creating-pages), we can see both of them are dissimilar.

**Comment by Rubix982** [comment] 2021-07-29 11:52
# Update

So I just tired out changing the command a bit from `npx @docusaurus/init@latest init my-website classic`. I changed `classic` to `bootstrap`, and the result is very broken. It doesn't look finished.

![image](https://user-images.githubusercontent.com/41635766/127487170-9a0b8af4-44b9-4809-b601-c3308c9f675a.png)

Changing it to `facebook` gives me somewhat better template, but the UI screen size is broken with overflow.

**Comment by Josh-Cena** [comment] 2021-07-29 12:48
I can help to answer several of your confusions 🙋

1. The init template is by no means a copy of the website itself. It used to be only some placeholder docs, but was later improved to contain **some** tutorial docs to help you get started. Still, the chief purpose is to provide a scaffolding. If you need up-to-date docs, check the website (docusaurus.io) instead. (The templates are located under `packages/docusaurus-init/templates` btw)
2. Broken links are certainly an issue. Probably something's broken that prevents links referencing `.md` files to be resolved correctly.
3. `bootstrap` is a WIP and is very raw. No one's maintaining it ATM and you are not expected to use it. `facebook` is well-developed because this is the template for Facebook projects which have more unified demands and toolchains.
4. You are expected to update the `editUrl` to your own repo. Everything you get from the init template are just examples.

So only the second issue is a bug...

**Comment by slorber** [comment] 2021-07-29 15:51
> The content is extremely old
> The docs/ looks very different than the docs/ generated by the npx template (npx @docusaurus/init@latest init my-website classic)

That seems to be the same problem right?

As @Josh-Cena said, the init template is not supposed to be a copy of the existing official docs. It is a very lightweight tutorial that you can do locally before browsing the official doc which is a lot more exhaustive. We don't want the template to contain as much content as it would be overwhelming. This template is not meant to serve as the documentation that you should read, it's just a way to get started. We could also have provided you with a docs folder that contains a single md file.

=> https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-init/templates/classic/docs

---

> Some links are broken

Please be very specific and list them here in an exhaustive way.

> The "Edit This Page" text that is generated for each page in the npx tutorial does not work.

![image](https://user-images.githubusercontent.com/749374/127523382-c06fb9cc-7eee-44cf-8c56-b247bd67876e.png)

> // Please change this to your repo.
> editUrl: 'https://github.com/facebook/docusaurus/edit/master/website/',

The links are not broken, it's just you didn't configure them. Read the doc and learn how to configure them. Docusaurus has no way to guess where your doc is hosted if you don't tell it.

--- 

> With each article given in the starting code generated by the template example, nothing works, and all the links are breaking.

What doesn't work exactly? Please be very specific. "nothing" does not mean anything to me and so far all the issues you mention in a specific way are not issues, it's more a misunderstanding of what our init template it. You likely encounter the intended behavior.

---

In general, please try to clarify your issue. It is quite messy, and very hard to understand for me. I'm going to close it because I think we addressed all the reported "bugs" but if you still think there is a bug, please focus on that single bug or at least create a dedicated section/paragraph per bug with the expected/actual behavior, and we'll figure out if each case is a bug or not.

**Closed by slorber** 2021-07-29 15:51 UTC
Labels: bug, needs triage

**Comment by Rubix982** [comment] 2021-07-29 16:24
Thank you, @slorber. I apologize for the issue for not being detailed/comprehensive enough. It's fault on my part. 

I'll go through the material you have provided. Much thanks.

**Comment by Josh-Cena** [comment] 2021-07-29 23:53
@slorber I think the "broken links" is the same issue as reported here: https://github.com/facebook/docusaurus/discussions/4610#discussioncomment-1044171

**Comment by slorber** [comment] 2021-07-30 09:14
yes it might be but we can't be sure as @Rubix982 didn't report which links are broken exactly 😅
