### ISSUE TITLE
Light/Dark theme selector alt-text shows wrong default mode upon first access / refresh of Docusaurus

### ISSUE THREAD

**Issue by Nirusu** [facebook/docusaurus#8024] opened 2022-08-30 13:55 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

(this is reproducible on https://docusaurus.io/, so no need for these debugging steps and there is no console error message except some cookie SameSite stuff).

### Description

When using system theme dark mode (in my case from Ubuntu 22.04 / GNOME) and hovering over the "Moon" icon to switch between light/dark mode, the alt text when first loading Docusaurus says that I am currently in light mode, despite being in dark mode:
![image](https://user-images.githubusercontent.com/26608194/187454575-7503dee6-a261-496a-9ae6-7374661d8785.png)

This issue disappears when browsing around in the docs (clicking links), but reappears when refreshing or reloading the page.

### Steps to reproduce

1. Use Ubuntu 22.04 with default Firefox (Snap)
2. Enable "Dark" style in system settings
3. Visit https://docusaurus.io/
4. Right on the starting page without clicking anywhere, hover over the "Moon" icon in the header. It will say you are currently using light mode, despite using dark mode.
5. Click on some link, like "Docs" in the header bar
6. Hover over the moon icon, it will say you are currently using dark mode.
7. Refresh the page in Firefox
8. Hover over the moon icon, it will say you are currently using light mode.

### Expected behavior

It should say it is using dark mode all the time.

### Actual behavior

It switches between _saying_ it is using light mode and using dark mode despite always actually using dark mode.

### Your environment

- Public source code: https://github.com/facebook/docusaurus
- Public site URL: https://docusaurus.io
- Docusaurus version used: 2.0.1 & Canary
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 104.0 (Snap), dunno whatever the original page uses (but reproducible on a local setup with Node.js 16.17.0)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 22.04 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-08-30 14:10
Duplicate of https://github.com/facebook/docusaurus/issues/7986

**Comment by Josh-Cena** [comment] 2022-08-30 14:11
Thanks for the demonstration of an actual issue of #7986! This is caused by the hydration mismatch.

**Closed by Josh-Cena** 2022-08-30 14:11 UTC
Labels: bug, status: needs triage
