### ISSUE TITLE
Archived version docs links are broken

### ISSUE THREAD

**Issue by fflaten** [facebook/docusaurus#9314] opened 2023-09-16 08:48 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Description

Netlify-links to archived version docs are dead:
https://github.com/facebook/docusaurus/blob/main/website/versionsArchived.json

With v3 coming in, time to remove old 2.0 prereleases from the json?

### Self-service

- [X] I'd be willing to address this documentation request myself.

**Comment by slorber** [comment] 2023-09-18 17:10
Thanks, it's a known issue and I'm waiting for an answer from someone at Meta to see how we decide to archive older versions for Meta open-source sites. I was not able to get an answer yet?.

The archiving process options are described here: https://github.com/facebook/react-native-website/issues/3819

Duplicate of https://github.com/facebook/docusaurus/issues/8634

**Closed by slorber** 2023-09-18 17:10 UTC
Labels: documentation, status: needs triage
