### ISSUE TITLE
:::admonition [`code-formatted-link`](path.md) ::: color themes have incorrect contrast

### ISSUE THREAD

**Issue by Steviebaa** [facebook/docusaurus#3923] opened 2020-12-15 00:24 UTC
## 🐛 Bug Report

Consider this:
```
:::admonition 
<a><code></code></a>
:::
```

or 

```
:::admonition 
[`code-formatted-link`](path.md) 
:::
```

When you toggle dark theme, it appears dark text on a dark code block.
![Screen Shot 2020-12-15 at 10 50 32 am](https://user-images.githubusercontent.com/16717394/102150449-b4a29c80-3ec4-11eb-8491-9d487087ee49.png)

When you toggle light theme, it appears dark text on a light code block. Which you can't see at all on a `note` admonition
![Screen Shot 2020-12-15 at 11 02 18 am](https://user-images.githubusercontent.com/16717394/102150595-106d2580-3ec5-11eb-9b6a-fce000d48456.png)

## To Reproduce

1. Put the above code in an mdx and run

## Expected behavior

Better contrast, not black on black etc.

## Actual Behavior

black on black etc.

## Your Environment

```	
"dependencies": {
	"@docusaurus/core": "2.0.0-alpha.69",
	"@docusaurus/preset-classic": "2.0.0-alpha.69",
	"@mdx-js/react": "^1.6.21",
	"clsx": "^1.1.1",
	"react": "^16.8.4",
	"react-dom": "^16.8.4"
},
```
```
>node -v                                                                                                                                                                    (master)api-docs
v15.3.0
```
Brave, Safari, Chrome - all the same

MacBook Pro (16-inch, 2019)
MacOS Big Sur v11.0.1

## Reproducible Demo

See the admonition at the top. Note these admonitions display red in Brave browser but correctly in others. Will save that for another issue.
https://steviebaa.github.io/api-v3-docs/docs/s3d-model/

**Comment by tomchen** [comment] 2020-12-22 19:03
I was about to open a same issue that I've just found:

(`info` can be any [admonition](https://v2.docusaurus.io/docs/markdown-features/#calloutsadmonitions) other than `note`)

```md
:::info
[`hello`](#hello).
:::

:::note
[`hello`](#hello).
:::
```

Normal light mode:

![2020-12-22_195934](https://user-images.githubusercontent.com/529949/102923578-447db300-4490-11eb-9b8a-a21651d99a9f.png)

Dark mode:

![2020-12-22_195943](https://user-images.githubusercontent.com/529949/102923605-4d6e8480-4490-11eb-8567-a614dbc8fa28.png)

`note` is OK in light mode. In other three scenarios, `<a><code></code></a>` becomes unreadable.

**Comment by Steviebaa** [comment] 2020-12-22 21:54
> `note` is OK in light mode. In other three scenarios, `<a><code></code></a>` becomes unreadable.

This is just because the codeblock has the same background-color as the admonition. I think this one should also be fixed to show a different shading.

**Comment by tomchen** [comment] 2020-12-23 11:45
> > `note` is OK in light mode. In other three scenarios, `<a><code></code></a>` becomes unreadable.
> 
> This is just because the codeblock has the same background-color as the admonition. I think this one should also be fixed to show a different shading.
Yeah, maybe a darker gray as the background color for `<code>` in that case

**Comment by slorber** [comment] 2020-12-29 14:28
This issue is duplicate of https://github.com/facebook/docusaurus/issues/2930 and has been moved to Infima repo => https://github.com/facebookincubator/infima/issues/55

**Closed by slorber** 2020-12-29 14:28 UTC
Labels: bug, needs triage
