### ISSUE TITLE
page next, prev locale label not work(only doc)

### ISSUE THREAD

**Issue by kijung-iM** [facebook/docusaurus#10141] opened 2024-05-16 07:01 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Hello,
pagenavigator locale not work on Docusaurus v.3.3.2 

only doc is not work

<img width="888" alt="image" src="https://github.com/facebook/docusaurus/assets/126956257/525edc8b-62e6-405b-bcdd-7ddfd99dc3d3">

```
"sidebar.javaSidebar.doc.지원 환경": {
  "message": "サポート環境",
  "description": "The label for the doc item 지원 환경 in sidebar javaSidebar, linking to the doc java/supported-spec"
},
```

but category is work

<img width="897" alt="image" src="https://github.com/facebook/docusaurus/assets/126956257/18e3fa3c-198d-464e-a5fe-c04361a54922">

```
"sidebar.javaSidebar.category.JAVA 모니터링": {
  "message": "JAVAモニタリング",
  "description": "The label for category JAVA 모니터링 in sidebar javaSidebar"
},
```
  

### Reproducible demo

Our repository is https://github.com/whatap/whatap-docs 
Our site: https://docs.whatap.io

### Steps to reproduce

This problem occurs when `yarn start` and `yarn build` in version v3.3.2.

### Expected behavior

Hopefully the page links (prev, next) at the bottom of the screen will apply the correct locale.

### Actual behavior

Only when `type` is `doc` will you not be able to get the translated value in current.json .

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-05-16 10:46
Yes it's a bug, duplicate of:
- https://github.com/facebook/docusaurus/issues/8118
- https://github.com/facebook/docusaurus/pull/8123

**Closed by slorber** 2024-05-16 10:46 UTC
Labels: bug, status: needs triage
