### ISSUE TITLE
Change default language 

### ISSUE THREAD

**Issue by guigaoliveira** [facebook/Docusaurus#938] opened 2018-09-03 12:52 UTC
Is possible to change the default language (from English to Portuguese for example)? I wanted to make English as the second translation option, not the main one.

**Comment by JoelMarcey** [comment] 2018-09-05 16:01
@guigaoliveira At this point, English is the default shown language. But you are correct that we should have an option to set what the default language is.

We actually have this as a feature request in https://github.com/facebook/Docusaurus/issues/586 - @endiliey is this something we should still target before v2?

Of course, the if you don't have translations on, you can just write your docs in Portuguese -- but that isn't the best user experience, obviously if you want multiple languages.

**Comment by JoelMarcey** [comment] 2018-09-05 16:01
I am going to close this as a duplicate of #586  - but feel free to comment there as well.

**Closed by JoelMarcey** 2018-09-05 16:01 UTC
Labels: duplicate

**Comment by endiliey** [comment] 2018-09-05 16:05
@JoelMarcey I'm targeting that on v2 to not hardcode english as default language. 

One thing to note is that in current version, all pages are located in `pages/en/*.js`, it should be `pages/**.js` in v2
