### ISSUE TITLE
Default mobile theme has a 1px gap on some mobile devices

### ISSUE THREAD

**Issue by markerikson** [facebook/Docusaurus#1152] opened 2018-12-09 01:09 UTC
## 🐛 Bug Report

Some site users have reported a 1px gap between the header sections on mobile devices, especially iPhones with iOS 12 and Safari / Chrome.  

This gap appears on multiple sites, including https://react-redux.js.org, https://docusaurus.io/en/ , and https://facebook.github.io/create-react-app/docs , so it appears to be something about the default Docusaurus mobile theme.

> Note: I have not observed this myself - I'm filing this for other users who have.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Browse to a Docusaurus mobile site on an iOS 12 device.  Scroll down.

## Expected behavior

There's no gap in the header.

## Actual Behavior

There is a 1px horizontal gap in the header, and the main page is visible scrolling past that.

Sample screenshots:

![ds pixel gap - redux](https://user-images.githubusercontent.com/1128784/49692291-f6095000-fb24-11e8-9dd2-bfa6c0d438c2.png)

![ds pixel gap - docusaurus chrome](https://user-images.githubusercontent.com/1128784/49692297-06212f80-fb25-11e8-90f6-43461c57847d.png)

![ds pixel gap - docusaurus safari](https://user-images.githubusercontent.com/1128784/49692300-0f120100-fb25-11e8-9df1-956c69570a62.png)

![ds pixel gap - cra](https://user-images.githubusercontent.com/1128784/49692302-133e1e80-fb25-11e8-9110-8d696b736e16.png)

## Reproducible Demo

Browse straight to the Docusaurus site on an iOS 12 device, apparently.

**Comment by sveinpg** [comment] 2018-12-09 10:35
I think this can be fixed by disabling scaling on the website. 
For instance by adding this meta-tag: `<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, width=device-width">`

If disabling scaling is not desirable, a background colour might do the trick.

**Comment by endiliey** [comment] 2018-12-10 10:20
Duplicate of #820 but will leave this issue open since it might get more attention

**Closed** 2018-12-17 02:04 UTC
Labels: bug, difficulty: starter, good first issue, help wanted
