### ISSUE TITLE
[v2] Couldn't link to static assets with Chinese characters under sub-dir

### ISSUE THREAD

**Issue by niheaven** [facebook/docusaurus#3471] opened 2020-09-22 06:45 UTC
## 🐛 Bug Report

When linking to static assets (pdf or xlsx, etc.) directly from markdown files, and if the file is under some co-locate subdir and has Chinese characters in its path name (filename or dirname), then the parsing engine will give some error as following:

```
./docs/doc2.md
Module not found: Can't resolve './0202测试.pdf' in 'xxx\docusaurus\docs'./docs/doc2.md
Module not found: Can't resolve './test测试.pdf' in 'xxx\docusaurus\docs'./docs/doc2.md
Module not found: Can't resolve './测试 est.pdf' in 'xxx\docusaurus\docs'
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## To Reproduce

1. Create some dummy files and dirs under docs, e.g., `测试/test.pdf`, `test/测试.pdf`, `0202/测试.pdf`
1. Link to these files in md file under docs, e.g., `doc2.md`, using markdown's syntax (`Link to [subdir with Chinese path name 1](test/测试.pdf)`) (Webpack's works well `<a ... require('./0202/测试.pdf').default ... /a>`)
1. Save `doc2.md` 

## Expected behavior

No error, move these files to `assests` and create clickable links

## Actual Behavior

```
× Client
  Compiled with some errors in 83.04ms



./docs/doc2.md
Module not found: Can't resolve './0202测试.pdf' in 'xxx\docusaurus\docs'./docs/doc2.md
Module not found: Can't resolve './test测试.pdf' in 'xxx\docusaurus\docs'./docs/doc2.md
Module not found: Can't resolve './测试 est.pdf' in 'xxx\docusaurus\docs'
```

Oh, line breaks got wrong, too...

## Your Environment

- Docusaurus version used: 2.0.0-alpha.64
- Environment name and version: Edge 85.0.564.51, Node.js 12.18.4
- Operating system and version: Windows 10 19042.487 64bit

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

Just add some Chinese named files and dirs...

**Comment by slorber** [comment] 2020-09-29 10:15
Hi,

I'm sorry but I'm unable to reproduce this issue.

![image](https://user-images.githubusercontent.com/749374/94545867-667ae700-024d-11eb-8809-d756bf65c9b4.png)

![image](https://user-images.githubusercontent.com/749374/94545843-5ebb4280-024d-11eb-8713-f78018e678c9.png)

![image](https://user-images.githubusercontent.com/749374/94545893-6e3a8b80-024d-11eb-9ee6-9a2e0c128e29.png)


I would need a full repro to be able to debug this and be sure it's not an error on your side.

**Comment by slorber** [comment] 2020-10-08 16:49
no answer so closing

**Comment by niheaven** [comment] 2020-10-09 05:13
Sorry, on vacation...

Please check https://github.com/niheaven/docusaurus-debug, and output on my machine likes:

![image](https://user-images.githubusercontent.com/5832170/95545680-2c6dca00-0a31-11eb-8aa2-f6eced5df993.png)

`init commit` runs well.

**Comment by slorber** [comment] 2020-10-09 07:23
Thanks, let's reopen.

I don't have windows to test the repro, unfortunately, but people have reported that using other shells (like PowerShell) could solve problem. Can you try some other Windows shell if possible?

**Comment by niheaven** [comment] 2020-10-09 09:07
What I use is PowerShell 7, and I also tried PowerShell 5.1, CMD and nu shell. Unfortunately, the same error...

`npm run start` cannot work, too.

It seems like parsing engine treat `./assets/测试.pdf` as `./assets\测试.pdf` in Windows and the backslash is used as an escape character.

**Comment by hotlong** [comment] 2021-01-05 03:36
The same error.

Failed to compile
../docs/help/deploy/deploy_ubuntu.md
SyntaxError: unknown: Bad character escape sequence (118:192)

```
  116 | <p parentName="blockquote">{`只需执行一次`}</p>
  117 | </blockquote>
> 118 | <p><img alt={"暂存修改"} src={require("!url-loader?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!C:\Users\steedos\Documents\GitHub\steedos-website\website\static\assets\ubuntu\git暂存修改.png").default}  /></p>
      |                                                                                                                                                                                                 ^
  119 | <p>{`其次写说明并提交更改：`}</p>
  120 | <p><img alt={"提交更改"} src={require("!url-loader?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!C:\Users\steedos\Documents\GitHub\steedos-website\website\static\assets\ubuntu\git提交更改.png").default}  /></p>
  121 | <p>{`如果没有 git 客户端可选择取消打开 git 客户端，并在 vscode 中登陆 git 账号：`}</p>
```

**Comment by slorber** [comment] 2021-05-06 14:52
Should be fixed by https://github.com/facebook/docusaurus/pull/4736

Please let me know if you still have an issue

**Closed by slorber** 2021-05-06 14:52 UTC
Labels: bug, needs more information
