### ISSUE TITLE
[v2] Toggle theme component not reacting on change system theme

### ISSUE THREAD

**Issue by popuguytheparrot** [facebook/docusaurus#2295] opened 2020-02-18 14:24 UTC
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. start new project
2. go to system settings
3. change system theme
4. Toggle not change on current theme

## Expected behavior

Toggle will display the current theme

## Actual Behavior

Site theme changed but Toggle icons not reacting on changes.

(Write what happened. Add screenshots, if applicable.)
![image](https://user-images.githubusercontent.com/19804652/74744529-7a03af80-5273-11ea-9ea8-4ce9c6969ac2.png)

alpha.43

**Comment by popuguytheparrot** [comment] 2020-02-18 14:25
https://v2.docusaurus.io/ has same problem

**Comment by yangshun** [comment] 2020-02-18 15:29
I'm not able to reproduce this. Once you toggle it manually, we write the value to `localStorage` and the system value no longer affects it. Please try on incognito mode and see if the same thing happens.

**Comment by popuguytheparrot** [comment] 2020-02-18 15:40
@yangshun i change system theme and Toggle not reacting on this

**Comment by yangshun** [comment] 2020-02-18 15:47
> i change system theme and a Toggle not reacting on this

Did you try incognito mode? Could you clear your `localStorage` and try again?

Is it just the toggle? Does the rest of the website respond to the change in the theme? A video recording would be helpful.

> Sorry. I did it on Windows 10

Unfortunately I don't have Windows and can't really debug there. If you have time I recommend you try debugging it. It's not very complicated. The relevant code can be found in `docusaurus/packages/docusaurus-theme-classic/src/index.js`

**Comment by lex111** [comment] 2020-02-18 18:03
@popuguytheparrot good catch, I see this bug, it will be fixed in the next release!

**Closed** 2020-02-27 02:14 UTC
Labels: bug
