### ISSUE TITLE
Doc page contributors

### ISSUE THREAD

**Issue by osamajandali** [facebook/docusaurus#7959] opened 2022-08-16 17:20 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

Similar to `last updated by` in the Doc footer where it states the dev who last update a file, there should be an option for listing all the contributors for that specific page.
Here is an imagined UI design for it:
![image](https://user-images.githubusercontent.com/13832392/184939866-fe0b7f06-218c-4a48-9c59-8b1eed467b54.png)

I found that this feature is discussed [here](https://github.com/facebook/docusaurus/discussions/6194)  

### Motivation

Some docs involved many people not necessarily the core team only, e.g. non-profit organisation where people voluntarily contribute to certain doc and those people need to be mentioned not only the last one.

### API design

So this is github based so no need for the users to add any components by themselves.
I think it should be enabled/disabled via the config file 

### Have you tried building it?

I tried to follow the same approach of `last updated by` by ejecting the doc footer component but that went without luck as I saw it uses useDoc hook so I feel that I couldn’t edit it.

### Self-service

- [X] I'd be willing to contribute this feature to Docusaurus myself.

**Comment by Josh-Cena** [comment] 2022-08-16 17:31
Duplicate of #6218

**Comment by Josh-Cena** [comment] 2022-08-16 17:32
Your mocked UI looks great btw, feel free to re-post under #6218

**Closed** 2022-08-16 17:32 UTC
Labels: closed: duplicate, feature

**Comment by lukedukeus** [comment] 2022-09-03 16:52
@osamajandali Can you post the code you used to get this result? 

Thanks
