### ISSUE TITLE
Sidebar item type docsSidebar throws error when featured as item in sidebar type dropdown 

### ISSUE THREAD

**Issue by mongodben** [facebook/docusaurus#6634] opened 2022-02-07 22:11 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When creating the site's top navigation i want to create a drop down menu where the items are of navitem type `docSidebar`. however, when i try to include these, the site throws the error:  
```
[ERROR] ValidationError: Bad navbar item type docSidebar
```

### Steps to reproduce

1. create sidebars in sidebars.js file
2. in the docusaurus.config.js file, add a `navbar.items` entry with `type: "dropdown"`. 
3. run `npm start` in local dev
4. view error

here is an example sidebar config that'd throw this error: 

```js

({
      navbar: {
        title: "MongoDB Realm Docs",
        logo: {
          alt: "Realm Logo",
          src: "img/realm-logo.png",
        },
        items: [
          {
            type: "dropdown",
            label: "SDKs",
            position: "left",
            items: [
              {
                type: "docSidebar",
                position: "left",
                sidebarId: "flutter",
                label: "Alpha",
              },
              {
                type: "docSidebar",
                position: "left",
                sidebarId: "flutter2",
                label: "Beta",
              },
            ],
          },

          {
            href: "https://github.com/mongodben/flutter-sdk-docs",
            label: "GitHub",
            position: "right",
          },
        ],
      },
     // ... more config
})
```

### Expected behavior

no error thrown

### Actual behavior

throws errors: 

```
[ERROR] A validation error occurred.
[INFO] The validation system was added recently to Docusaurus as an attempt to avoid user configuration errors.
We may have made some mistakes.
If you think your configuration is valid and should keep working, please open a bug report.
[ERROR] ValidationError: Bad navbar item type docSidebar
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-02-08 01:12
Duplicate of #6597 and fixed in #6599

**Closed by Josh-Cena** 2022-02-08 01:12 UTC
Labels: bug, closed: duplicate
