### ISSUE TITLE
Failed to start Docusaurus server

### ISSUE THREAD

**Issue by felipewmartins** [facebook/docusaurus#3215] opened 2020-08-05 14:58 UTC
## 🐛 Bug Report

Fail to start docusaurus-server
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. run npx docusaurus-init
1. yarn start
1. Step 3...

## Expected behavior

Starts normally

(Write what you thought would happen.)

## Actual Behavior

Actual is: Failed to start Docusaurus server: SyntaxError: Unexpected token (37:15)

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Docusaurus version used: 1.14.5
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node v12.15.0
- Operating system and version (desktop or mobile): Fedora 31

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by slorber** [comment] 2020-08-05 14:59
Duplicate of https://github.com/facebook/docusaurus/issues/3199

Already fixed, going to release right now

**Closed by slorber** 2020-08-05 15:00 UTC
Labels: bug, needs triage

**Comment by slorber** [comment] 2020-08-05 15:16
Release 1.14.6, seems to work now
