### ISSUE TITLE
Sidebar not scrolling to open page

### ISSUE THREAD

**Issue by ArthurFlag** [facebook/docusaurus#10615] opened 2024-10-25 11:39 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When going on a docusaurus website via a link to a given page, the sidebar doesn't scroll to the open page, leaving the user to scroll appropriately to locate the page they are on. 

### Steps to reproduce

1. Go a page in a large sidebar, for example [this page](https://aiven.io/docs/products/mysql/howto/connect-from-cli).
2. Notice the sidebar remains at the top.

### Expected behavior

I would like for the sidebar to scroll down to where I landed, to show me the context in the table of contents/sidebar.

### Actual behavior

The user sees the top of the sidebar pane.

### Your environment

- Public source code: [github](https://github.com/aiven/aiven-docs)
- Docusaurus version used: 3.5.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 130

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2024-10-25 17:47
Duplicate of https://github.com/facebook/docusaurus/issues/7980

**Closed by slorber** 2024-10-25 17:47 UTC
Labels: bug, closed: duplicate
