### ISSUE TITLE
Titles are not handled properly anymore

### ISSUE THREAD

**Issue by Sotty75** [facebook/docusaurus#4665] opened 2021-04-22 07:09 UTC
## 🐛 Bug Report
The article titles are behaving differently than before and in not consistent ways.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. I have a site where an article has the following front-matter section:
```
---
id: azuread_setup
title: Azure AD Configuration Setup
hide_title: true
hide_table_of_contents: false
sidebar_label: Azure AD Configuration Setup
description: Azure AD Configuration Setup
keywords:
  - Application
  - Web Server
  - Requirements
---
```

followed by a header 1 title
`# My Header`

## Expected behavior
I expect the front-matter Title to be hidden and the string **My Header** to be displayed as a title

## Actual Behavior
**My Header** title is hidden as well.
Also if i have instead of `# My Header` a second level header immediately after the front-matter section, i see the ID displayed as a title.

**Comment by slorber** [comment] 2021-04-22 16:11
@Sotty75 can you show me a screenshot of how it was before, how it is now, so that we can more easily understand and compare?

I'm assuming the minimal md doc to reproduce looks like this (I'm not certain because your sample only contains frontmatter):

```md
---
title: Azure AD Configuration Setup
---

# My Header

Lorem Ipsum
```

Some questions:
- What is your motivation to have BOTH a title in frontmatter AND in the markdown doc? 
- What is your expectation when this happens?
- Which title should be used where exactly in such a case?

> I expect the front-matter Title to be hidden and the string My Header to be displayed as a title

Why?

If 2 titles are declared on the doc, there is an ambiguity and Docusaurus has to pick one of the 2.
This choice Docusaurus makes is not really specified, you should not rely on it, and you should avoid creating this ambiguity in the first place.


> Also if I have instead of # My Header a second-level header immediately after the front-matter section, i see the ID displayed as a title.

Already fixed with https://github.com/facebook/docusaurus/pull/4641), you can use `@canary` until we release it (soon).

**Comment by slorber** [comment] 2021-04-22 16:41
With this doc:

```md
---
title: Azure AD Configuration Setup
---

# My Header

Lorem Ipsum

## My Header 2

Lorem Ipsum 2

```


The behavior before (tested on alpha.71):

![image](https://user-images.githubusercontent.com/749374/115751654-acd69580-a399-11eb-92a8-aba1eeb4ebab.png)

The behavior after (master, using Docusaurus 2 website to test):

![image](https://user-images.githubusercontent.com/749374/115751965-f32bf480-a399-11eb-92d9-c12b79de26e0.png)

The correct behavior is the behavior after the change.

Having a double-h1 heading at the top of a markdown doc is not something semantically correct and you should simply not do that.

If you really want to, you will have to update your docs to put 2 headings in the markdown:

```
---
title: Azure AD Configuration Setup
---

# Azure AD Configuration Setup

# My Header

Lorem Ipsum

## My Header 2

Lorem Ipsum 2
```

![image](https://user-images.githubusercontent.com/749374/115752275-39815380-a39a-11eb-9c6a-3468f9d79661.png)


If you absolutely want to restore the behavior before, you can write a remark plugin that would extract your frontmatter title and put it at the top of the markdown content, but again I'd advise against this.

**Comment by Sotty75** [comment] 2021-04-22 18:00
There was really not a good reason to have the title in the frontmatter and in the markdown.

 It was like that as i migrated a set of existing Docs to docusaurus and then added the frontmatter by cut and paste on all of them, without understanding what i was doing. 

I cleared the ambiguity as suggested, removing the title from the frontmatter.  Thanks a lot for fixing the other problem.

**Comment by slorber** [comment] 2021-04-23 18:09
Actually I'll re-open because while testing newest Docusaurus site on a few existing sites I noticed this pattern was sometimes used.

Frontmatter title can control page meta title, and markdown title can control page heading. I think it makes sense to make it possible to have a page heading different from the page meta title

**Closed** 2021-04-27 13:44 UTC
Labels: bug, needs triage

**Comment by baur** [comment] 2023-10-25 05:52
Docusaurus v3.rc0

Doc plugin
---
hide_title: true
breadcrumbs: false
---
not affects
