### ISSUE TITLE
Inconsistent behavior when slug contains a space

### ISSUE THREAD

**Issue by kayx23** [facebook/docusaurus#8843] opened 2023-03-28 11:57 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

This issue was discovered when someone accidentally added spaces in slug in the markdown front matter, which brings up a few discussion points:
* when slug contains space, such as `blahblah/blah blah`, Docusaurus compiles without error (not sure if intended)
* the page can still be accessed by `blahblah/blah%20blah`
* however, left navbar and some other components disappeared

For example, say the page normally looks like this:
![Screenshot at Mar 28 19-16-06](https://user-images.githubusercontent.com/39619599/228226818-866cb9d6-0b8a-4451-bf42-04976ae37a38.png)

If I add a space into the slug, the page can still be accessed (not the URL), but it now looks like this (I masked certain info, but the idea is the two areas I highlighted in the previous pic disappeared):
![Screenshot at Mar 28 19-16-35](https://user-images.githubusercontent.com/39619599/228226854-1a1dc9d3-68d0-4079-b414-867659cc1912.png)

Certain components just evaporated. 

### Steps to reproduce

1. Update the slug in the front matter of a document markdown file to contain a space 
2. Access the page by replacing space with `%20`
3. Note that the left navbar and other component is gone

### Expected behavior

I expect Docusaurus to either 
1. not allow spaces in slug; or
2. support spaces but renders with consistent behaviours, without differences in component rendering

### Actual behavior

1. Docusaurus compiles without warning/error when slug contains a space
2. missing components when accessing this page with spaces in URL

### Your environment

- Docusaurus version: `v2.3.1`

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by jttimko5** [comment] 2023-03-28 17:40
I would like to work on this task, can you please assign it to me?

**Comment by slorber** [comment] 2023-04-06 17:45
Can't reproduce, can you provide a repro please?

Can you verify on v2.4 too?

**Comment by kayx23** [comment] 2023-04-07 00:19
hm, I tried to reproduce it on stackblitz just now and realized the issue is related to my team's project's left navbar wasn't' automatically generated by Docusaurus. Components that disappeared were likely customized and added on. 

As it is not an issue with Docusaurus, I'm closing the issue @slorber

**Closed** 2023-04-07 00:24 UTC
Labels: bug, status: needs more information
