### ISSUE TITLE
BrowserOnly hydration issuse

### ISSUE THREAD

**Issue by drcmda** [facebook/docusaurus#4934] opened 2021-06-09 07:18 UTC
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.

### Description

BrowserOnly seems to have a hydration issue. It

- removes the first parent node of the would-be content
- and then picks the next sibling of the page and ... wrap the rest that is left in it

Say you have:

```jsx
<BrowserOnly>
  () => ..............
    <div class="a">
      <div class="b">hello</div>
    </div>
</BrowserOnly>
<div class="c">...</div>
```

In production (not in dev) Docusaurus will transform it to:

```jsx
<div class="c">
  <div class="b">hello</div>
</div>
<div class="c">...</div>
```

Here is a real world example:

<img width="923" alt="Screenshot 2021-06-09 at 09 12 35" src="https://user-images.githubusercontent.com/2223602/121310522-bdb87780-c903-11eb-9fcf-ce5597b83dbd.png">

Docusaurus will start to mix that code in very strange ways:

<img width="954" alt="Screenshot 2021-06-09 at 09 15 59" src="https://user-images.githubusercontent.com/2223602/121310143-55699600-c903-11eb-830a-126c4ae32c69.png">

And this is how it looks in dev:

<img width="1066" alt="Screenshot 2021-06-09 at 09 17 18" src="https://user-images.githubusercontent.com/2223602/121310304-85189e00-c903-11eb-832f-241e27c6714f.png">

A workaround is to wrap BrowserOnly into the the first element of the would-be content. Why this works is even stranger, i can't see a pattern in that. 

<img width="876" alt="Screenshot 2021-06-09 at 09 26 43" src="https://user-images.githubusercontent.com/2223602/121311584-d5dcc680-c904-11eb-904e-9c526e9c425b.png">

**Comment by slorber** [comment] 2021-06-09 09:42
Thanks, I think we should hydrate with the exact same markup and use `useLayoutEffect` to render the client JSX a bit later.

This is probably related to https://www.joshwcomeau.com/react/the-perils-of-rehydration/

**Comment by lex111** [comment] 2021-06-09 10:02
Oops, sorry, it is my mistake, will be fixed in #4935.

**Closed** 2021-06-09 11:41 UTC
Labels: bug, needs triage

**Comment by slorber** [comment] 2021-06-09 12:54
@drcmda it should be fixed now.

Please try to use the `@canary` dist tag on your repro case and let us know if it is fixed (2.0.0-beta.d81d43c24 for example)

**Comment by drcmda** [comment] 2021-06-14 07:04
@slorber @lex111 for some reason the canary gives me this now:

```jsx
index.js?1ef8:1 Warning: React has detected a change in the order of Hooks called by BrowserOnly. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. undefined                  useRef
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at BrowserOnly (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/BrowserOnly.js:12:26)
    at div
    at div
    at nav
    at Navbar (webpack-internal:///./src/theme/Navbar.js:28:423)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal://
```

there seems to be nothing unusual in the file that im loading inside browseronly.

**Comment by lex111** [comment] 2021-06-14 07:23
@drcmda sorry, will be fixed in #4960.

**Comment by slorber** [comment] 2021-06-14 16:46
@drcmda surprised because it looks fine to me.

Are you calling hooks in the children of BrowserOnly? 

The children prop is executed as a plain function, not a React component so the following wouldn't work:

```js
<BrowserOnly>
  {() => {
    const value = useContextValue();
    return <div/>
  }}
```

Is this a dev/browser or prod/nodejs warning? 

Are you adding a browser only component to the navbar?

Can you try `yarn docusaurus clear` and run again?

**Comment by drcmda** [comment] 2021-06-14 21:43
Navbar.js

```jsx
        <div className="navbar__items navbar__items--right">
          <BrowserOnly fallback={null}>
            {() => {
              const MenuItems = require('../components/MenuItems').default
              return <MenuItems />
            }}
          </BrowserOnly>
```

MenuItems.js

```jsx
export default function MenuItems({ targetItem = 'navbar__item', targetLink = 'navbar__link' }) {
  const [visibleSignIn, setVisibleSignIn] = useState(false)
  const [visibleSignUp, setVisibleSignUp] = useState(false)
  const isSignedIn = useBackend((b) => b.user.isSignedIn)

  return (
    <>
      {isSignedIn && (
        <Link to={routes.profile} className={`${targetItem} ${targetLink}`}>
          <UserOutlined />
        </Link>
      )}
      {!isSignedIn && (
        <Popover style={{ background: 'white' }}>
          <Popover.Button as="div">
            <a href="#" className={`${targetItem} ${targetLink}`}>
              Sign in
            </a>
          </Popover.Button>
          <Popover.Panel className="popover-panel">
            <SignIn modal />
          </Popover.Panel>
        </Popover>
      )}
```

The menu items are tied to firebase and auth, signin, signup, they do use hooks. without browseronly it wouldn't work because it starts to complain. the context hook doesn't seem to come from us, i think that's from browseronly internals.

**Comment by slorber** [comment] 2021-06-15 11:00
``` 
   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. undefined                  useRef
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@drcmda I double-checked and I don't see any place in our codebase where we would use useContext + useRef and where the ref is called conditionnally (we don't use a lot of refs so it's fast to check)

I suspect this is one of your integration that is calling the `useRef` hook inside BrowserOnly callback. As far as I understand you have multiple `BrowserOnly` so it may be worth to check them all, and try to replace them one by one with a placeholder until the problem is resolved?

If you still have the issue after removing all your `BrowserOnly` usage, that would be surprising because we don't have this issue on our own website, deployed with fwk code from master (and we do use BrowserOnly for the json debug view here: https://docusaurus.io/__docusaurus/debug)
