### ISSUE TITLE
(v2) Version label is now mandatory or on by default after upgrading to alpha.62

### ISSUE THREAD

**Issue by adrianmcli** [facebook/docusaurus#3362] opened 2020-08-29 09:04 UTC
## 🐛 Bug Report

Versioning is now imposed on the user since upgrading to alpha.62 (from alpha.61).

As a project that does not want to use versioning in their docs at all, it's weird to have a version label at the top of each page imposed upon us. There's also no clear way to disable this without swizzling.

I would hope that at the very least, there should be an easy way to disable it. But I think it should be off by default.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Upgrade to alpha.62
2. Notice that every page now has a `Version` label at the time

## Expected behavior

Nothing should change.

## Actual Behavior

Unwanted version label on top of each page.

<img width="299" alt="Screen Shot 2020-08-29 at 2 01 12 AM" src="https://user-images.githubusercontent.com/943555/91633278-f6124900-e9b4-11ea-95d1-12ab9f70d3e6.png">

**Comment by slorber** [comment] 2020-08-29 13:41
This is likely a little regression from my big docs plugin refractor. Will be fixed in the next release, in the meantime you can swizzle the comp temporarily

**Comment by MateuszDabrowski** [comment] 2020-08-30 11:24
The same problem might also impact the custom sidebars approach for doc only page: https://github.com/facebook/docusaurus/issues/3366

**Comment by adrianmcli** [comment] 2020-08-30 20:24
I think I'll stay on alpha.61 for now, but it might be a good idea to have a test case for this. I think not having versioning is much more common than having it.

**Comment by slorber** [comment] 2020-08-31 07:40
@adrianmcli this thing is theme-specific. One theme might choose to show the label while another might not, and you can implement your own theme too :) 

Historically the classic theme has no UI test, so it would be odd that I just add one for this particular case when there are so many more tests to write (and I need to make progress on i18n), but yeah that would be great to have more tests here.

**Comment by slorber** [comment] 2020-08-31 17:05
Will be fixed in https://github.com/facebook/docusaurus/pull/3376

**Comment by adrianmcli** [comment] 2020-08-31 19:11
Thanks @slorber!

**Closed** 2020-09-01 14:31 UTC
Labels: bug, needs triage

**Comment by nabeelio** [comment] 2020-09-02 18:26
I get this error when trying to use `disableVersioning: true` to try to hide the label too:

> Error: Docs: using disableVersioning=true option on a non-versioned site does not make sense

I'm not sure that error makes sense - I _want_ to disable versioning when my site isn't versioned. Is this related? Didn't want to open something new if it is.

**Comment by slorber** [comment] 2020-09-02 19:39
AFAIK apart swizzling there is no way to disable it in alpha 62, but will release alpha 63 soon.

The error means it's not possible to disable versioning if your site is not versioned. Versioning is indeed already disabled.

**Comment by nabeelio** [comment] 2020-09-02 19:47
Yeah I'll wait for an update. And thanks for clarifying, makes sense, I guess I was confused by the version stuff showing up.

**Comment by slorber** [comment] 2020-09-03 17:26
Released in alpha 63 🎊  please spread the word 🙏 and tell me if this works fine for you
https://twitter.com/docusaurus/status/1301562737693138944
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.63

**Comment by nabeelio** [comment] 2020-09-03 17:27
Awesome! I will try it out later tonight and let you know if there are issues!

**Comment by nabeelio** [comment] 2020-09-03 18:50
Ok, looks like it's gone now. Had to remove my `node_modules` directory first and rerun it and seems like the label is gone. Thanks!
