### ISSUE TITLE
[Proposal] Make local search plugin officially supported

### ISSUE THREAD

**Issue by gabrielcsapo** [facebook/docusaurus#5201] opened 2021-07-20 22:29 UTC
## 💥 Proposal

First off thanks so much for all the work you have done! 

I have been using docusaurus for a bunch of projects lately and am always reaching for https://github.com/easyops-cn/docusaurus-search-local. It would be great to make local search an officially supported feature without needing to Algolia as that isn't an option for my projects. 

So just as there is an option for `@docusaurus/theme-search-algolia` it would be great to have an official theme for local search called `@docusaurus/theme-search-local`.

**Comment by slorber** [comment] 2021-07-21 13:41
Duplicate of https://github.com/facebook/docusaurus/issues/776

**Closed by slorber** 2021-07-21 13:41 UTC
Labels: needs triage, proposal

**Comment by slorber** [comment] 2021-07-21 13:44
I'm trying to get from FB a docusaurus-community repo, on which such plugins could live and receive more maintainance

We only add plugins that we use in the Docusaurus site itself in this repo
