### ISSUE TITLE
Publish-gh-pages script fails -- error: git clone failed

### ISSUE THREAD

**Issue by jartuso** [facebook/docusaurus#2258] opened 2020-01-31 00:02 UTC
## 🐛 Bug Report

When trying to publish changes to our github pages hosted site, the npm run publish-gh-pages step fails with the following error code (full output from powershell attached)

generate.js triggered...
feed.js triggered...
feed.js triggered...
sitemap.js triggered...
Site built successfully. Generated files in 'build' folder.
7ce717117293691c87678f7b3cc7fbe015e946de
fatal: Too many arguments.
Error: git clone failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ publish-gh-pages: `docusaurus-publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ publish-gh-pages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\artus\AppData\Roaming\npm-cache\_logs\2020-01-30T23_49_07_563Z-debug.log

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce
Windows 10
node (12.14.1)
npm (6.13.4)
yarn (1.21.1)

1. clone documentation repo locally
2. make edits in visual studio code
3. run command: cmd /C "set GIT_USER=[myuser] && set CURRENT_BRANCH=master && npm run publish-gh-pages"
4. fails :(

Note -- also fails in the same way when using yarn run publish-gh-pages

## Expected behavior

My 1st time trying to push changes to our docusaurus site. I expected it to work without any errors. 

## Actual Behavior

npm run publish-gh-pages failed

## Reproducible Demo

Repo that I'm trying to push changes for
https://github.com/OpenBCI/Documentation/tree/master

[docusaurus-errortxt.txt](https://github.com/facebook/docusaurus/files/4136846/docusaurus-errortxt.txt)

**Comment by LogicEveryWhere** [comment] 2020-02-04 07:41
same issue with identical environment

**Comment by LogicEveryWhere** [comment] 2020-02-04 21:43
Temporary solution!!
file ```website/node_modules/docusaurus/lib/publish-gh-pages.js```
line 20: ```const GIT_USER = process.env.GIT_USER.trim();```

just trim git user

**Comment by prma85** [comment] 2020-02-07 17:17
This is what I have been using in azure and works just fine
```
git config --global user.email "$(GH_USER)@users.noreply.github.com"
git config --global user.name "$(GH_USER)"
GIT_USER=$(GH_USER) npm run publish-gh-pages
```

Running it directly from my machine (windows 10) also worked without errors.

I hope it helps :)

**Comment by OndrejNepozitek** [comment] 2020-02-11 12:09
The problem is caused by a whiteline that is appended to the GIT_USER env variable on windows 10 when you run the `cmd /C "set GIT_USER=<GITHUB_USERNAME> && yarn deploy"` command. It can be fixed by running `cmd /C "set GIT_USER=<GITHUB_USERNAME>&& yarn deploy"`  instead (note the missing space between <GITHUB_USERNAME> and &&).

It's quite unfortunate that the command is included in the official docs so probably a lot of windows users will encounter this problem.

**Comment by yangshun** [comment] 2020-02-11 12:14
Could you help to submit a PR for Windows? That would be much appreciated!

**Closed** 2020-02-21 01:46 UTC
Labels: bug, needs triage, v1

**Comment by Turkyden** [comment] 2020-09-20 07:33
> The problem is caused by a whiteline that is appended to the GIT_USER env variable on windows 10 when you run the `cmd /C "set GIT_USER=<GITHUB_USERNAME> && yarn deploy"` command. It can be fixed by running `cmd /C "set GIT_USER=<GITHUB_USERNAME>&& yarn deploy"` instead (note the missing space between <GITHUB_USERNAME> and &&).
> 
> It's quite unfortunate that the command is included in the official docs so probably a lot of windows users will encounter this problem.

Nice, it work ! Thank you sir.

**Comment by AlFalahTaieb** [comment] 2020-11-27 15:50
I'm having this problem and i'm not even on Windows

**Comment by akshaymalik75** [comment] 2022-08-27 14:30
Cloning into 'D:\Practice\React\Restaurant App\restaurantapp\node_modules\.cache\gh-pages\https!akshaymalik75.github.io!React_forms'...
fatal: repository 'https://akshaymalik75.github.io/React_forms/' not found

I am getting this error even I have changed the repo name please help.
