### ISSUE TITLE
RFC: better swizzle cli

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#2984] opened 2020-06-23 12:55 UTC
## 🚀 Feature

The swizzle cli experience works, but is a but rough and could be improved

## Pitch

Here I'm using `yarn workspace docusaurus-2-website swizzle ...` in the screeshots (as I'm using D2 website for testing), but replace in your mind with `yarn swizzle ...`

Here are some suggestions

---

Display all the installed theme names with `yarn swizzle`, instead of:

![image](https://user-images.githubusercontent.com/749374/85405400-a6e90b80-b560-11ea-9c15-39217a2aa670.png)

---

On theme name typo, better error with theme name suggestions:

![image](https://user-images.githubusercontent.com/749374/85405610-f7f8ff80-b560-11ea-872d-419e10fc1f78.png)

---

Do not swizzle the whole theme files with `yarn swizzle @docusaurus/theme-classic`, insead display available names to swizzle. (breaking change)

![image](https://user-images.githubusercontent.com/749374/85405802-37bfe700-b561-11ea-993d-47bf26e27e17.png)

---

Typo on swizzle component name: same as theme, suggest valid names instead o:

![image](https://user-images.githubusercontent.com/749374/85405900-558d4c00-b561-11ea-9159-fc11cf8c7df5.png)

--- 

Allow swizzling the whole theme files with an `--all` option: `yarn swizzle @docusaurus/theme-classic --all`

**Comment by fanny** [comment] 2020-06-23 14:59
To facilitate the use of the users, when a user pass a command that don't exist in the CLI, we could output a help, showing the current options. Loved the idea.

**Comment by anshulrgoyal** [comment] 2020-06-24 08:14
@slorber I will be interested if the issue is available.

**Comment by slorber** [comment] 2020-06-24 15:51
thanks

You can probably start a poc, but there's ongoing work by @SamChou19815 that we should probably merge first here: https://github.com/facebook/docusaurus/pull/2671

**Comment by anshulrgoyal** [comment] 2020-07-01 06:20
@slorber I working on this issue

**Comment by anshulrgoyal** [comment] 2020-07-01 15:59
@slorber I was trying to get package name for themes but due to the use of `require.resolve` I am getting the path of the module instead. Do you know any method get package names?

**Comment by slorber** [comment] 2020-07-03 08:41
hey @anshulrgoyal , maybe from the module path you could read the package.json in it, to get the name attribute?

**Comment by anshulrgoyal** [comment] 2020-07-03 09:20
> hey @anshulrgoyal , maybe from the module path you could read the package.json in it, to get the name attribute?

Did same in my pr.

**Comment by anshulrgoyal** [comment] 2020-08-12 14:16
@slorber  we should close this

**Closed** 2020-08-13 23:05 UTC
Labels: mlh, proposal, v2
