### ISSUE TITLE
A line break inside a markdown link will break url rendering

### ISSUE THREAD

**Issue by chromy96** [facebook/docusaurus#9523] opened 2023-11-09 15:04 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Two URLs containing a file path to the same document will be rendered differently depending on if the link text contains a line break or not.

Properly rendered url (points to `website`/docs/example)
```markdown
[A link example](example.md)
```

Badly rendered url (points to `website`/example.md)
```markdown
[A link
example](example.md)
```

Docusaurus version: 3.0.0

### Steps to reproduce

1. Create a link with a line break in it 
2. Check how the URL is rendered

### Expected behavior

Expected a URL to be rendered the same way as without the line break.

### Actual behavior

A link points to `website`/example.md instead of `website`/docs/example

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.0.0
- Environment name and version (e.g. Chrome 89, Node.js 18.2): Chrome 119, Node.js 18.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2023-11-09 15:38
This is currently working as intended because we only process links line-by-line. We can investigate making it multiline but I wonder if it would be as trivial as the other Markdown link bugs. We'll soon use an actual Markdown parser for this.

**Comment by slorber** [comment] 2023-11-10 11:28
Closing as duplicate of https://github.com/facebook/docusaurus/issues/9048

This bug is only there because we don't use MDX/Remark/micromark to resolve links using filename extensions.

**Closed by slorber** 2023-11-10 11:28 UTC
Labels: bug, domain: markdown
