### ISSUE TITLE
Scrolling problem with right sidebar in Linux

### ISSUE THREAD

**Issue by djipco** [facebook/docusaurus#6669] opened 2022-02-13 17:46 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When using the right sidebar navigation, there is a scrolling issue. It is detailed here: 
https://github.com/djipco/webmidi/issues/236

As stated in the above issue, both website using v2.0.0-beta.15 have this issue while older ones do not. It might be a coincidence but it might also be a hint...

### Steps to reproduce

Create a page docs page with right-side navigation. Try to scroll.

### Expected behavior

Should scroll normally.

### Actual behavior

Does not fully scroll the page.

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-02-14 01:57
Please see if #6587 is a duplicate of this issue. i.e. if the original post had "Experimental web platform features" turned on.

**Closed by Josh-Cena** 2022-02-14 01:57 UTC
Labels: bug, closed: duplicate
