### ISSUE TITLE
Development server broken on fresh install

### ISSUE THREAD

**Issue by davidvarela-us** [facebook/docusaurus#7571] opened 2022-06-05 23:25 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

`npm run start` is not serving files on a fresh install

### Steps to reproduce

1. `npx create-docusaurus@latest my-website classic --typescript`
2. `cd my-website`
3. `npm run start`

### Expected behavior

I expect to see some ouptut at `localhost:3000`.

### Actual behavior

 Navigating to `localhost:3000` complains with "This site can’t be reached".

Must be some problem with the development stack itself: `npm run build` + `npm run serve` works as expected.

### Your environment

- node version: v18.3.0
- npm version: 8.5.5
- OS: archlinux

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by davidvarela-us** [comment] 2022-06-05 23:42
Failing for both typescript and js versions

**Comment by Josh-Cena** [comment] 2022-06-06 01:56
Interesting that build + serve works: that's a pretty critical piece of information. I still strongly suspect there's something going on with the system setup, but I don't know how to debug this. Leaving this open until someone can chime in.

Have you tried running `start` with `--host 0.0.0.0` or `--port 8888`, etc.?

**Comment by davidvarela-us** [comment] 2022-06-06 02:39
The dev server seems to be running/watching at least:
```
✔ Client
  Compiled successfully in 1.20s

client (webpack 5.73.0) compiled successfully

✔ Client
  Compiled successfully in 1.03s

client (webpack 5.73.0) compiled successfully

✔ Client
  Compiled successfully in 514.34ms

client (webpack 5.73.0) compiled successfully`
```

**Comment by Josh-Cena** [comment] 2022-06-06 02:44
Yeah, that part is an FS watcher that doesn't go over the wires. So somewhere between the dev server and the browser things stopped working. You mentioned on Discord that running CRA/Next.js worked, which is even weirder, because AFAIK we use a dev server setup quite similar to CRA.

You can try messing with `node_modules/@docusaurus/core/lib/commands/start.js` and see if changing any config fixes it.

**Comment by davidvarela-us** [comment] 2022-06-06 02:46
Working for now with `--host 0.0.0.0`. Thanks a bunch

**Comment by slorber** [comment] 2022-06-08 22:22
afaik it may happen in case you messed up things in `/etc/hosts` and other similar files

**Comment by Josh-Cena** [comment] 2022-06-16 06:15
Hey—I suspect this is a websocket error. I don't have the infrastructure needed to reproduce this, so I'm going to close this for the same reason as https://github.com/facebook/docusaurus/issues/3652. It doesn't mean we 100% dismiss this as not our issue, but this is unactionable unless someone can step in and narrow it down to a specific place in our code. Meanwhile developing on `0.0.0.0` should be good enough.

**Closed by Josh-Cena** 2022-06-16 06:15 UTC
Labels: bug, status: needs more information
