### ISSUE TITLE
Navigation Pane flickering, and weird animation

### ISSUE THREAD

**Issue by acoates-ms** [facebook/docusaurus#1746] opened 2019-08-06 18:13 UTC
## 🐛 Bug Report

When navigating between two pages in the same group, the entire nav pane flickers blank.  And the chevron in the group header of the two pages flashed back to the closed position and reanimates open.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## To Reproduce

1. Goto https://facebook.github.io/react-native/docs/getting-started
1. Navigate between two pages in the `The Basics` group

## Expected behavior

Navigation wouldn't flicker and group wouldn't animate unnecessarily. 

## Actual Behavior

Navigation pane goes blank for some frames during navigation.
The chevron animates when it should remain consistently in the open position.

![Image](https://i.imgur.com/v8yDFf8.gif)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by yangshun** [comment] 2019-08-06 19:55
This is because pages in Docusaurus 1 are server-side rendered and the expand/collapse logic only runs after the page loads. There's a script which finds the category that contains the current page and toggle that part to expand.

This bug is annoying but doesn't affect the site's functionality. One potential way to solve it would be to determine if a category should be expanded during SSR phase and render the expanded HTML. It can be quite complicated and might not be worth fixing. Help in fixing would be appreciated!

FWIF this problem does not exist in Docusaurus 2 because it's a single-page app.

**Comment by endiliey** [comment] 2019-08-07 02:51
Another solution is to use something like pjax that can loads pages using AJAX and updates the browser's current URL using pushState() without reloading page's layout or any resources (JS, CSS), giving a fast page load.

https://github.com/MoOx/pjax/blob/master/README.md#pjax

> It allows you to completely transform the user experience of standard websites (server-side generated or static ones) to make users feel like they are browsing an app, especially for those with low bandwidth connections.

**Comment by yangshun** [comment] 2020-06-05 09:11
This is a duplicate of #1235. We'll address this in v2.

**Closed by yangshun** 2020-06-05 09:11 UTC
Labels: difficulty: intermediate, help wanted, v1, wontfix
