### ISSUE TITLE
mdx or other imgage reload Error

### ISSUE THREAD

**Issue by checkwoodson** [facebook/docusaurus#6211] opened 2021-12-28 14:29 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Initialize the project, the image is introduced with an error.
![image](https://user-images.githubusercontent.com/33786022/147576272-1887c209-9ef8-4e7a-938b-22172affbd0e.png)
 maybe Catalogs Chinese? 

### Steps to reproduce

npx programs

### Expected behavior

安装完后运行就这样了。。。。

### Actual behavior

这是一个必显问题。

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2021-12-28 14:30
Yes, this is a problem related to path escaping. Duplicate of #6180 and fixed by #6190. You can use the canary release if you need the fix

**Closed by Josh-Cena** 2021-12-28 14:30 UTC
Labels: bug, status: needs triage

**Comment by checkwoodson** [comment] 2021-12-29 14:29
> Yes, this is a problem related to path escaping. Duplicate of #6180 and fixed by #6190. You can use the canary release if you need the fix

No problem ，I change fileName so ok.
Why does fanhyi always report git errors, because I have China git blocked? I am open proxy. Hey, it's too hard.
git no ssl or other problem...

**Comment by Josh-Cena** [comment] 2021-12-29 14:31
> Why does fanhyi always report git errors, because I have China git blocked?

No idea what you meant, don't know what "fanhyi" is and git works well for me with / without proxy.
