### ISSUE TITLE
Docusaurus build fails with "No Docusaurus route context found" for manually created sidebar with many items

### ISSUE THREAD

**Issue by DonaldKellett** [facebook/docusaurus#10718] opened 2024-11-23 03:48 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

This is a duplicate of #10709 which was closed due to lacking a reproducible example. So here's a reproducible example: https://github.com/DonaldKellett/docusaurus-10709-repro

Building our production Technical KB written in Docusaurus with `npm run build` recently failed consistently with the error message below.

```text
[cause]: Error: Unexpected: no Docusaurus route context found
```

The problem is reproducible in that the error appears 100% of the time when we try to add just 1 more item to our manually created sidebar \(maybe our sidebar is too large?\) regardless of what the item is or where it is placed within the sidebar, but our Docusaurus site contains sensitive and confidential information so we can't share the source code here. Nevertheless, we'll try to include as much relevant information as possible to help reproduce the issue without divulging too many details.

### Reproducible demo

https://github.com/DonaldKellett/docusaurus-10709-repro

### Steps to reproduce

Without divulging too many details, we're using Docusaurus v3.6.1 with the `@docusaurus/faster` plugin enabled though we found that the issue persists regardless of whether the experimental plugin is enabled or disabled.

Our `package.json` and `package-lock.json` files are as attached. In particular, the version of [`p-map`](https://github.com/sindresorhus/p-map) used as seen in `package-lock.json` is `4.0.0` which is important as we will see later:

- [package-lock.json](https://github.com/user-attachments/files/17856679/package-lock.json)
- [package.json](https://github.com/user-attachments/files/17856680/package.json)

The issue is consistently triggered when we try to add 1 more item anywhere within our manually created sidebar in `sidebars.js`. Here's an overview of what it looks like:

```javascript
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: "category",
      label: "GitLab",
      link: {
        type: "generated-index",
        title: "GitLab",
        description: "Articles related to GitLab",
      },
      items: [
        {
          type: "category",
          label: "Administrator Guide",
          link: {
            type: "generated-index",
            title: "Administrator Guide",
            description: "Administrator Guide for GitLab Helm Chart",
          },
          items: [
            "gitlab/install-gitlab-with-helm",
            "gitlab/enable-git-over-ssh-for-gitlab",
            "gitlab/enable-ad-login-for-gitlab",
            "gitlab/gitlab-properly-signed-tls",
            "gitlab/enable-gitlab-managed-terraform-backend",
            "gitlab/provide-custom-ca-gitlab-ci-jobs",
            "gitlab/cron-backup-gitlab-ee-16.x",
            "gitlab/gitlab-runner-https-certificate-error",
          ],
        },
        ...
      ]
    },
    ...
  ]
};

module.exports = sidebars;
```

For reference, here's what our `docusaurus.config.js` looks like \(portions omitted due to containing sensitive information\):

```javascript
// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require("prism-react-renderer").themes.github;
const darkCodeTheme = require("prism-react-renderer").themes.dracula;

/** @type {import('@docusaurus/types').Config} */
const config = {
  future: {
    experimental_faster: true,
  },
  title: "Technical KB",
  tagline: "Internal technical knowledge base for Enfinity",
  favicon: "img/favicon.ico",

  // Set the production url of your site here
  url: "https://enfinity-solutions.pages.internal.enfinity.com.hk/",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/internal/technical-kb/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "facebook", // Usually your GitHub org/user name.
  projectName: "docusaurus", // Usually your repo name.

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
          editUrl:
            "https://gitlab.internal.enfinity.com.hk/enfinity-solutions/internal/technical-kb/-/tree/main/",
        },
        blog: false,
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: "img/docusaurus-social-card.jpg",
      navbar: {
        title: "Technical KB",
        logo: {
          alt: "My Site Logo",
          src: "img/logo.svg",
        },
        items: [
          { to: "/docs/category/gitlab", label: "GitLab", position: "left" },
          { to: "/docs/category/cloud", label: "Cloud", position: "left" },
          ...,
          {
            href: "https://gitlab.internal.enfinity.com.hk/enfinity-solutions/internal/technical-kb",
            label: "GitLab",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Docs",
            items: [
              {
                label: "GitLab",
                to: "/docs/category/gitlab",
              },
              {
                label: "Cloud",
                to: "/docs/category/cloud",
              },
              ...
            ],
          },
          {
            title: "More",
            items: [
              {
                label: "GitLab",
                href: "https://gitlab.internal.enfinity.com.hk/enfinity-solutions/internal/technical-kb",
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Enfinity Solutions Limited. Built with Docusaurus.`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
```

### Expected behavior

Building the site with `npm run build` finishes without issues. The site loads and displays correctly with `npm run serve`.

### Actual behavior

Docusaurus static site generation failed for 306 paths:

```text
> website@0.0.0 build
> docusaurus build
[INFO] [en] Creating an optimized production build...
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/builds/enfinity-solutions/internal/technical-kb/node_modules/@docusaurus/core/lib/commands/build/build.js:78:15)
    at async /builds/enfinity-solutions/internal/technical-kb/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
    at async mapAsyncSequential (/builds/enfinity-solutions/internal/technical-kb/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/builds/enfinity-solutions/internal/technical-kb/node_modules/@docusaurus/core/lib/commands/build/build.js:33:5) {
  [cause]: Error: Docusaurus static site generation failed for 306 paths:
...
```

The detailed error for each failure is "Error: Unexpected: no Docusaurus route context found" which can be traced down to `p-map/index.js:57:22` and is identical for each failure.

```text
Error: Can't render static file for pathname "/internal/technical-kb/docs/aiml/install-pyenv"
            at generateStaticFile (/builds/enfinity-solutions/internal/technical-kb/node_modules/@docusaurus/core/lib/ssg/ssg.js:167:15)
            at processTicksAndRejections (node:internal/process/task_queues:105:5)
            at runNextTicks (node:internal/process/task_queues:69:3)
            at process.processImmediate (node:internal/timers:459:9)
            at async /builds/enfinity-solutions/internal/technical-kb/node_modules/p-map/index.js:57:22 {
          [cause]: Error: Unexpected: no Docusaurus route context found
              at mergeContexts (server.bundle.js:10977:19)
              at server.bundle.js:10995:16
              at Object.Ic [as useMemo] (server.bundle.js:3227:240)
              at __webpack_modules__.72408.exports.useMemo (server.bundle.js:4808:208)
              at RouteContextProvider (server.bundle.js:10994:69)
              at Uc (server.bundle.js:3234:44)
              at Xc (server.bundle.js:3236:253)
              at Z (server.bundle.js:3242:89)
              at Vc (server.bundle.js:3234:473)
              at Xc (server.bundle.js:3236:210)
        },
```

The offending line in version `4.0.0` of `p-map` is: https://github.com/sindresorhus/p-map/blob/a4b4dec459544d98880bc53a580e53691aff9fa9/index.js#L57

```javascript
result[index] = await mapper(element, index);
```

Screenshots containing the error messages in our failing GitLab CI builds are attached below.

![2024-11-22 12_15_40-Window](https://github.com/user-attachments/assets/3aa1fa0f-4604-494b-95df-6746dba0d09c)
![2024-11-22 12_15_11-Window](https://github.com/user-attachments/assets/c4882ede-0f03-4e4e-824b-e6bae1a896f1)

### Your environment

- Public source code: https://github.com/DonaldKellett/docusaurus-10709-repro
- Public site URL: https://github.com/DonaldKellett/docusaurus-10709-repro
- Docusaurus version used: v3.6.2
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js `v22.11.0`
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 24.04 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by DonaldKellett** [comment] 2024-11-23 03:58
Here's the commit that triggers the bug causing the build to fail: https://github.com/DonaldKellett/docusaurus-10709-repro/commit/2c4431b741c1b30008f45af64fa6057e173ce3ef As can be seen from the commit, adding just a single item to the sidebar anywhere triggers this cryptic build error.

The failing job and build logs in CI: https://github.com/DonaldKellett/docusaurus-10709-repro/actions/runs/11983861175/job/33413927236

**Comment by DonaldKellett** [comment] 2024-11-24 02:16
Just discovered that the build error disappears when duplicate sub-category names are renamed to become unique, e.g. these 2:

1. "Kubernetes > Storage": https://github.com/DonaldKellett/docusaurus-10709-repro/blob/main/sidebars.js#L233-L248
1. "OpenShift > Storage": https://github.com/DonaldKellett/docusaurus-10709-repro/blob/main/sidebars.js#L488-L502

Nevertheless, I insist this is a bug in Docusaurus since the build process should catch duplicated sub-category names in the sidebar if it is not a supported use-case and exit with a human-readable error message instead of exhibiting unspecified behavior and randomly failing builds with a cryptic error message when a certain number of sidebar items is reached.

**Comment by slorber** [comment] 2024-11-25 09:33
Sorry for closing your initial issue too eagerly, I didn't know you planned to provide a runnable repro. We usually re-open the issue once a repro is provided. 

Thanks for the repro, this definitively looks like a bug / DX problem.

I suspect both of your categories have the same final URL, and this leads to conflicts/ name collision later in JS modules emitted by Docusaurus.

I'll investigate at the end of the week. 

Until then I'm curious, what is the pathname you access both of these generated index categories? I suspect it's the same pathname, something like:

`/docs/category/storage`

And you could use the `slug` attribute to see if it improves things:

```json
        {
          type: "category",
          label: "Storage",
          link: {
            type: "generated-index",
            title: "Storage",
            description: "Articles related to storage on Kubernetes",
            slug: "my-kuternete-storage-slug",
          },
```

I'll still consider it a bug though, because we should prevent these collisions in the first place or at least fail-fast on this case and emit a clear actionable error message for the user.

**Comment by comp615** [comment] 2024-11-25 15:37
Again, maybe not helpful, but we are also experiencing a similar issue where 3.6+ versions are throwing lots of missing context errors in custom sidebars during prod compilation (I think dev works? And I think 3.6.3 was triggering it for us; or some pseudo randomness?). I have not debugged our setup or checked for collisions like mentioned above, but wanted to add that I think this is a more broad current pain point potentially.

**Comment by DonaldKellett** [comment] 2024-11-25 16:23
> Sorry for closing your initial issue too eagerly, I didn't know you planned to provide a runnable repro. We usually re-open the issue once a repro is provided.
> 
> Thanks for the repro, this definitively looks like a bug / DX problem.
> 
> I suspect both of your categories have the same final URL, and this leads to conflicts/ name collision later in JS modules emitted by Docusaurus.
> 
> I'll investigate at the end of the week.
> 
> Until then I'm curious, what is the pathname you access both of these generated index categories? I suspect it's the same pathname, something like:
> 
> `/docs/category/storage`
> 
> And you could use the `slug` attribute to see if it improves things:
> 
> ```js
>         {
>           type: "category",
>           label: "Storage",
>           link: {
>             type: "generated-index",
>             title: "Storage",
>             description: "Articles related to storage on Kubernetes",
>             slug: "my-kuternete-storage-slug",
>           },
> }
> ```
> 
> I'll still consider it a bug though, because we should prevent these collisions in the first place or at least fail-fast on this case and emit a clear actionable error message for the user.

Thanks! I believe the generated pathname for both subcategories is indeed `/docs/category/storage` as you suggested.

While our team fixed the build by re-assigning unique names, e.g. "Kubernetes Storage" vs. "OpenShift Storage", may I ask what the optional `slug` field does in this context? Does it override the auto-generated category pathname, e.g. changing `/docs/category/storage` to `/docs/category/my-kubernetes-storage-slug`?

**Comment by slorber** [comment] 2024-11-25 16:41
`slug` permits to choose a custom pathname / url suffix for that category: https://docusaurus.io/docs/sidebar/items#generated-index-page

---

> Again, maybe not helpful, but we are also experiencing a similar issue where 3.6+ versions are throwing lots of missing context errors in custom sidebars during prod compilation (I think dev works? And I think 3.6.3 was triggering it for us; or some pseudo randomness?). I have not debugged our setup or checked for collisions like mentioned above, but wanted to add that I think this is a more broad current pain point potentially.

I don't see any recent change that could lead to that kind of error (apart the opt-in Docusaurus Faster flags). Please try to be sure. Because we can't do much with a vague comment like that 😅. We need runnable bug repros and a precise bug description with exact version numbers.

**Comment by slorber** [comment] 2024-11-29 11:36
Damn, this was not easy to troubleshoot. Many little things could "fix" the problem but it wasn't clear why, and what's the best fix for it.

This is really bad luck, you had 1/1000 chance for encountering a hash collision in our route chunks codename generation. 

2 route definitions with the same path lead to the exact same hash:



```bash
CONFLICT /internal/technical-kb/docs-456 {
  plugin: { name: 'docusaurus-plugin-content-docs', id: 'default' },
  path: '/internal/technical-kb/docs',
  exact: false,
  component: '@theme/DocsRoot',
  routes: [
    {
      path: '/internal/technical-kb/docs',
      exact: false,
      component: '@theme/DocVersionRoot',
      routes: [Array],
      props: undefined,
      priority: -1,
      modules: [Object]
    }
  ],
  context: {
    plugin: '@generated/docusaurus-plugin-content-docs/default/__plugin.json'
  },
  modules: {},
  props: undefined
}

CONFLICT /internal/technical-kb/docs-456 {
  path: '/internal/technical-kb/docs',
  exact: false,
  component: '@theme/DocVersionRoot',
  routes: [
    {
      path: '/internal/technical-kb/docs',
      exact: false,
      component: '@theme/DocRoot',
      routes: [Array],
      modules: {},
      props: undefined
    }
  ],
  props: undefined,
  priority: -1,
  modules: {
    __props: '@generated/docusaurus-plugin-content-docs/default/p/internal-technical-kb-docs-462.json'
  }
}
```


This leads `routeChunkNames` to look like this:

```
/internal/technical-kb/docs-456
{__comp: '__comp---theme-doc-version-roota-7-b-5de', __props: '__props---internal-technical-kb-docsce-3-cb8'}

/internal/technical-kb/docs-994
{__comp: '__comp---theme-doc-roota-94-67a'}
```


Instead of this:


```
/internal/technical-kb/docs-8a8
{__comp: '__comp---theme-doc-version-roota-7-b-5de', __props: '__props---internal-technical-kb-docs-661-be4'}

/internal/technical-kb/docs-331
{__comp: '__comp---theme-doc-roota-94-67a'}

/internal/technical-kb/docs-431
{__comp: '__comp---theme-docs-root-5-e-9-0b6', __context: {plugin: 'plugin---internal-technical-kb-docsaba-b8a'}}
```

---

Note that 2 routes with the same path are normal/expected, it's how we handle the docs routing tree:

```js
{
 path: "/docs",
 component: "@theme/DocsRoot",
 children: [
   {
     path: "/docs",
     component: "@theme/DocVersionRoot
     children: []
   }  
 ]
}
```

Here what happens in practice is that the parent route has the exact same hash as its child 😅 and this leads to a hash collision because we generate unique keys using `${route.path- hash(route)}`

**Comment by slorber** [comment] 2024-11-29 14:30
Will be fixed in the next release with https://github.com/facebook/docusaurus/pull/10727

Note that in your case, the issue is only temporary. Editing many things on your site will trigger new hashes to be computed, and the collision will not be there anymore. Just editing any sidebar item or category label fixes the collision for example.

**Closed as completed** 2024-11-29 14:36 UTC
Labels: bug

**Comment by karl-cardenas-coding** [comment] 2025-01-16 00:07
For anyone that may stumble upon this issue. We too got this error but the error output looked a bit differently, like so:

```shell
 Error: Can't render static file for pathname "/architecture/"
            at generateStaticFile (/home/ubuntu/actions-runner/_work/librarium/librarium/node_modules/@docusaurus/core/lib/ssg/ssg.js:167:15)
            at processTicksAndRejections (node:internal/process/task_queues:95:5)
            at runNextTicks (node:internal/process/task_queues:64:3)
            at process.processImmediate (node:internal/timers:454:9)
            at async /home/ubuntu/actions-runner/_work/librarium/librarium/node_modules/p-map/index.js:57:22 {
          [cause]: ReactContextError
              at useDocsSidebar (server.bundle.js:1993213:132)
              at useSidebarBreadcrumbs (server.bundle.js:1993267:119)
              at DocBreadcrumbs (server.bundle.js:1993687:501)
              at Uc (server.bundle.js:2417254:44)
              at Xc (server.bundle.js:2417256:253)
              at Z (server.bundle.js:2417262:89)
              at Yc (server.bundle.js:2417265:98)
              at $c (server.bundle.js:2417264:140)
              at Z (server.bundle.js:2417262:345)
              at Yc (server.bundle.js:2417265:98) {
            message: 'Hook useDocsSidebar is called outside the <DocsSidebarProvider>. '
          }
```

We are generating a ton of files before build that are add to the sidebar. Unfortunately for us, the build failed but return an exit code of `2`. This caused us to have a production outage. So we have some lessons learned on our end. But yeah, keep an eye on any Docusaurus version pre 3.7.0 that relates to `async /home/ubuntu/actions-runner/_work/librarium/librarium/node_modules/p-map/index.js:57:22 `

We resolved it by upgrading to Docusaurus version 3.7.1 😄

**Comment by slorber** [comment] 2025-01-16 09:35
> Hook useDocsSidebar is called outside the <DocsSidebarProvider>.

This kind of error is likely due to duplicate package versions. Not relate to p-map nor conflicts.

Upgrading likely helped your package manager deduplicate the packages.

**Comment by karl-cardenas-coding** [comment] 2025-01-16 11:58
@slorber apologies if this is a silly question. What do you mean when you say duplicate package? You lost me there.

**Comment by slorber** [comment] 2025-01-16 12:05
It means that you might have 2 versions of the same package in `node_modules`. Context errors happen often when you use 2 versions of React.

Examples:

- `./node_modules/react`
- `./packages/my-pkg1/node_modules/react`
- `./packages/my-pkg2/node_modules/react`
- `./node_modules/@docusaurus/theme-common/node_modules/react`

Try running `npm/yarn why react`

**Comment by karl-cardenas-coding** [comment] 2025-01-16 19:49
Thank you so much @slorber. We're pretty sure we found the culprit. `jest-config-docusaurus`. It was an old dev dependency we really don't need and was bringing in React 16 vs the expected React 18.
