### ISSUE TITLE
[V2] Links are broken

### ISSUE THREAD

**Issue by zkochan** [facebook/docusaurus#4419] opened 2021-03-12 22:25 UTC
## 🐛 Bug Report

Links are broken, when opening a doc page directly, when navigating to the page from home page, links work.

related issue https://github.com/pnpm/pnpm.github.io/issues/94

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Open this page: https://pnpm.js.org/installation/#upgrading
2. click on the link in the tip

(or on [this page](https://pnpm.js.org/cli/add#install-from-the-workspace) click on the workspace link)

## Expected behavior

This page is opened: https://pnpm.js.org/continuous-integration

## Actual Behavior

A non-existen page is opened: https://pnpm.js.org/installation/continuous-integration

## Your Environment

- Public source code: https://github.com/pnpm/pnpm.github.io/edit/source/versioned_docs/version-5.x/installation.md
- Public site url:
- Docusaurus version used: v2
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 
- Operating system and version (desktop or mobile):

**Comment by slorber** [comment] 2021-03-13 08:24
Hi

This is a known issue due to using relative links and having your host provider adding a trailing slash

You can use absolute paths, relative paths to file (including md extension) or configure your host. 

What is your host? 

Duplicate of https://github.com/facebook/docusaurus/issues/3372

**Closed by slorber** 2021-03-13 08:24 UTC
Labels: bug, needs triage

**Comment by zkochan** [comment] 2021-03-13 10:08
GitHub pages is our host
