### ISSUE TITLE
Why index title had repeat ?

### ISSUE THREAD

**Issue by lkzwc** [facebook/docusaurus#7389] opened 2022-05-10 16:13 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

![image](https://user-images.githubusercontent.com/84896877/167673895-ae8416be-9aaa-4c22-9519-0de80f39763a.png)
![image](https://user-images.githubusercontent.com/84896877/167674111-6c816f95-5862-4a9c-b234-36671de155e8.png)

the environment is 
 "@docusaurus/core": "2.0.0-beta.18",
    "@docusaurus/plugin-sitemap": "^2.0.0-beta.20",
    "@docusaurus/preset-classic": "2.0.0-beta.18",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "prism-react-renderer": "^1.3.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"

### Steps to reproduce

no

### Expected behavior

expect one title

### Actual behavior

actual show title  and title by '|'

### Your environment

url: https://lkthblog.vercel.app/
 "@docusaurus/core": "2.0.0-beta.18",
    "@docusaurus/plugin-sitemap": "^2.0.0-beta.20",
    "@docusaurus/preset-classic": "2.0.0-beta.18",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "prism-react-renderer": "^1.3.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment] 2022-05-10 16:16
Duplicate of #5878

**Comment by Josh-Cena** [comment] 2022-05-10 16:17
It's like that because we never got around to implement heuristics of when to show only the site title. You can ignore the `title` prop entirely to not show duplicated title. Just use `<Layout description="你的描述" />`

**Closed by Josh-Cena** 2022-05-10 16:17 UTC
Labels: closed: duplicate

**Comment by lkzwc** [comment] 2022-05-10 16:50
> <Layout description="你的描述"></Layout>

if i delete title of layout ,the index title is none ?? it will be show description
![image](https://user-images.githubusercontent.com/84896877/167681462-835e4fcb-44e0-410f-a162-dc73ca7ab443.png)

**Comment by lkzwc** [comment] 2022-05-10 16:51
> It's like that because we never got around to implement heuristics of when to show only the site title. You can ignore the `title` prop entirely to not show duplicated title. Just use `<Layout description="你的描述"></Layout>`

if i delete title of layout ,the index title is none ?? it will be show description
image

**Comment by lkzwc** [comment] 2022-05-10 17:08
@Josh-Cena

**Comment by lkzwc** [comment] 2022-05-10 17:54
![image](https://user-images.githubusercontent.com/84896877/167691813-ead41a18-c91e-498f-b166-79770e404323.png)
源码当中这个逻辑整错了吧

**Comment by Josh-Cena** [comment] 2022-05-11 01:39
这是另外一个 bug，会在 #7362 中修复。
