### ISSUE TITLE
@docusaurus/mdx-loader can not parse hr tag

### ISSUE THREAD

**Issue by imbsky** [facebook/docusaurus#2025] opened 2019-11-21 11:54 UTC

**Comment by imbsky** [comment] 2019-11-21 11:54
```
./docs/01-linters.md
Module build failed (from ./node_modules/@docusaurus/mdx-loader/src/index.js):
SyntaxError: unknown: Unterminated JSX contents (701:16)
```

**Comment by endiliey** [comment] 2019-11-21 15:20
It looks like you just deleted our lovely crafted [issue template](https://github.com/facebook/docusaurus/issues/new/choose). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue. 

You need to provide reproducible markdown or repo.
But to answer your question, it's most likely our parser https://github.com/mdx-js/mdx since html tag is considered as JSX. Report there instead

**Closed by endiliey** 2019-11-21 15:20 UTC
Labels: bug, needs triage

**Comment by yangshun** [comment] 2019-11-21 16:31
Use `<hr/>` not `<hr>`

**Comment by imbsky** [comment] 2019-11-21 20:39
I'm sorry to delete the template, for example, if you are migrating existing doc to the docusaurus version 2, a certain number of special tags "<hr>" may be used. Also, the error is little unkind. Unless you solve them, the migration can be little difficult.

**Comment by imbsky** [comment] 2019-11-21 20:40
and you can use `---` instead of `<hr />` in Markdown!

**Comment by yangshun** [comment] 2019-11-21 20:47
We did mention this specific problem in our migration docs - https://v2.docusaurus.io/docs/migrating-from-v1-to-v2#update-markdown-syntax-to-be-mdx-compatible

**Comment by imbsky** [comment] 2019-11-21 20:48
I didn't even know there was a v2 document... Thank you!

**Comment by yangshun** [comment] 2019-11-21 20:52
No problem. It was in the migration task: https://github.com/facebook/docusaurus/issues/1834

> Follow the v1 to v2 migration guide here

**Comment by imbsky** [comment] 2019-11-21 20:59
By the way, the issue of Infer had been inactive for a long time, so I migrated yesterday. In that case, I want to open a PR, but I don't know the person who manages the website of the Infer. Do you know who I should mention to? Please allow me to understand that you are on a different team. and I already create a preview site. https://github.com/facebook/infer/issues/1171
