### ISSUE TITLE
useDoc hook does not work on generated-index pages in DocBreadcrumb swizzled components

### ISSUE THREAD

**Issue by lanegoolsby** [facebook/docusaurus#7999] opened 2022-08-24 16:19 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I am working on a custom plugin where I have swizzled the DocBreadcrumb component in order to inject a custom component. 

In that component I am using the useDoc hook in order to access the page's front matter tags. This works fine for 'normal' markdown pages. However, as soon as I navigate to a page with the generated index ([for example](https://github.com/facebook/docusaurus/blob/c2ce8a02e726fec68c06be56cb6f6a305df25bc0/examples/classic/docs/tutorial-extras/_category_.json#L5)) I get the following error:

![image](https://user-images.githubusercontent.com/10758510/186467303-540ef0b2-e311-44df-b632-6ea924563970.png)

### Reproducible demo

https://stackblitz.com/edit/github-c3lcrm?file=src/theme/DocBreadcrumbs/example.js

### Steps to reproduce

1. Click on Tutorial
2. Click on any of the pages with a hyphen in the name

### Expected behavior

No error thrown

### Actual behavior

Error thrown

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [x] I'd be willing to fix this bug myself.

**Comment by slorber** [comment] 2022-09-01 09:43
`useDoc()` is meant to be used only on document pages. 

A sidebar category with a `generated-index` link is not a document page

It doesn't make sense to use `useDoc()` on such a page because it can't return any of the data that is generally available to a doc

`'metadata' | 'frontMatter' | 'toc' | 'assets' | 'contentTitle'` => none of these attributes exist for a generated index. At most the hook would return null for everything. I'd rather fail fast and make it clear by throwing.

> I am working on a custom plugin where I have swizzled the DocBreadcrumb component in order to inject a custom component.

It's not clear to me without seeing the code (please share more code):
- do you use `useDoc()` for the whole breadcrumb?  => that can't work for the reasons explained above
- do you use `useDoc()` for each breadcrumb item? => that's not how it's supposed to work, all the docs data are on all the pages)


At best, I suggest you could do something like the following:


```jsx
export default function DocBreadcrumb() {
  const {pathname} = useLocation();
  const isCategoryIndex = pathname.startsWith("/docs/category"); // A bit hacky, we could find a better way
  if ( isCategoryIndex ) {
    return <DocBreadcrumbCategoryIndex />
  } else {
    return <NormalDocBreadcrumb />
}

function DocBreadcrumbCategoryIndex() {
  // not possible to call useDoc() here
  return <div>Render what you want here</div>
}

function NormalDocBreadcrumb() {
  const doc = useDoc(); // This is allowed here
  return <div>{doc.frontMatter.something}</div>
}
```

Closing because it works as intended, but open to continue the discussion

**Closed by slorber** 2022-09-01 09:43 UTC
Labels: bug, status: needs triage

**Comment by lanegoolsby** [comment] 2022-09-02 16:40
Perhaps I can choose a different component to swizzle?

Long story short, we're adding an integration to our corporate StackExchange instance. We have a bunch of technical docs that are housed in a DS site. Each doc has front matter tags for that particular topic. We're using those tags to query our StackExchanage via REST to help engineers who may have a question about a particular page/topic. 

I am using the `useDoc` hook to get the list of tags for the current page.

We want our integration to show up below the bookmark/above the doc contents.

For example:
Initial page load
![image](https://user-images.githubusercontent.com/10758510/188199247-1a4752c1-adc6-4ff6-b327-62825e8e1f50.png)

After clicking the Show button
![image](https://user-images.githubusercontent.com/10758510/188199323-c7bf67b8-e70c-4bae-a4cb-0902979e8c4e.png)

**Comment by slorber** [comment] 2022-09-07 10:23
`<DocBreadcrumb>` is used on both doc page and generated index pages, so it's not a good fit in your case. Also your feature is not really related to breadcrumbs in the first place, so it doesn't look right to swizzle this component.

I'd suggest swizzle --eject DocItem/Layout instead. It's larger to maintain, but gives you more flexibility to plug your own component in the global doc page layout. Also think about the mobile story where there's a collapsible TOC.

<img width="682" alt="CleanShot 2022-09-07 at 12 19 12@2x" src="https://user-images.githubusercontent.com/749374/188855087-52a13039-56bf-44bb-8a26-92e4f039fafe.png">

You could also swizzle --wrap DocItem/Content and display the StackExchange widget just above the content, if this placement is what you want it would make it easier to maintain, at the cost of greater flexibility
